### ISSUE TITLE
learning material weblinks require "http://" prefix

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#1013]
if the user does not provide the `http://` prefix to a web address, adding the learning material weblink will fail. This is an onerous action to put on the user.

Solution: if possible, we should provide the `http://` as the default value on focus of the cursor in the address form field; if that seems too complex and hoop-jumpery, we should simply allow un-validated web addresses to be added.

**Comment by jrjohnson** [comment]
What about https://?  We could probably prepend http in any case where there was nothing.  its a little weird to modify user input without asking, but I think in this case it should fly.

**Comment by saschaben** [comment]
I agree on all counts. I was thinking more along the lines not of modifying user input per se, but posting a preset value into the field before they even start typing. But that doesn't deal with https (or ftp/s for that matter), and a user could always just delete the prefilled text --- like I often do with forms that do the same thing.

I think it will be best just to open up the API to allow whatever crap address gets plugged in.
