### ISSUE TITLE
Course Title First Line Indented by One Character (Courses and Sessions)

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#102]
![indent](https://cloud.githubusercontent.com/assets/7493331/6157999/06570cf8-b1fb-11e4-8a81-7e7724287a76.JPG)

See the screen shot - it looks like the first line is indented but the second line is not.

**Comment by dartajax** [comment]
This occurs also in the grid view as shown below so it must be related -- see below
![ingrid](https://cloud.githubusercontent.com/assets/7493331/6158799/f23058a8-b202-11e4-9629-d1542e0d7c41.JPG)

**Comment by dartajax** [comment]
This occurs in Objectives as well - see below ...
![indentobj](https://cloud.githubusercontent.com/assets/7493331/6158871/ba57b2e0-b203-11e4-895a-22d0e73a6f4d.JPG)

**Comment by jrjohnson** [comment]
Fixed
