### ISSUE TITLE
Publish All Needs to Take the User Back to the Course Screen

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1022]
After clicking a button like the following ....

![image](https://cloud.githubusercontent.com/assets/7493331/10948151/ef9a19ee-82e0-11e5-8a9c-f3b0e1305aa4.png)

.... the application should return the user to the Course and Sessions page (on the same Course that was just processed for changes).

**Comment by saschaben** [comment]
@jrjohnson Looks like this is now being handled? can we close?
