### ISSUE TITLE
Counts are Wrong on the Summary Action button (Publish # Sessions)

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1023]
![image](https://cloud.githubusercontent.com/assets/7493331/10948667/926a49b2-82e3-11e5-9009-51390e35bc72.png)

![image](https://cloud.githubusercontent.com/assets/7493331/10948689/acf401f6-82e3-11e5-977f-054676f72b7f.png)

2 + 79 + 36 = 117 (the total number of sessions for this course)

The button to take action (at the bottom of the screen) does not accurately represent what is happening here.

![image](https://cloud.githubusercontent.com/assets/7493331/10948737/f62b74a8-82e3-11e5-905e-c6131122ba75.png)

115 + 79 + 0 = 194 (?) = incorrect on many levels.  In this case, I had selected "Publish As-Is" for all of the 36 Sessions requiring review so Publish 115 is correct.  Schedule 79 is incorrect - it should be schedule 0 (zero).  Ignore 0 (zero) should be Ignore 2 (the ones that are missing the offerings and cannot be published at all.

**Comment by saschaben** [comment]
fixed in #1025
