### ISSUE TITLE
Parent Objectives Should Conform with the Current Objective Collapsing Model

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1026]
![image](https://cloud.githubusercontent.com/assets/7493331/10952821/8f890204-82f9-11e5-94f5-ca7cf2eb3f4e.png)

The description of the Objective is truncated with the clickable information icon to expand and retrieve the rest of the Objective's description.  Notice that the Parent Objective is much longer than three lines in length but does not have the expansion capability.

**Comment by dartajax** [comment]
So the idea with this one is that the Parent Objective field have the same formatting as the Description field.

**Comment by jrjohnson** [comment]
I'm closing this because feedback said that we want to ensure that all parent objectives are displayed and the actual solution is to have a collapsing objectives box.
