### ISSUE TITLE
Implement a Way to Review Uploaded Learning Materials

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1027]
Currently, when a Learning Material file is uploaded, there is no way to review to make sure you (as a user) have uploaded the correct file.

We should have a mechanism for the user to download (or open) the file to verify its veracity.

Where is the file to open for review?

![image](https://cloud.githubusercontent.com/assets/7493331/10955296/a9667cd4-8307-11e5-86ce-50eadac391ea.png)

**Comment by saschaben** [comment]
Yes. For LM files we are missing the "filename" value ("mywordfile.docx") which should be a download link.

This should be the same as how we are displaying URLs for weblinks.
