### ISSUE TITLE
Course Should Be Included Info on Calendar Mouse Over

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1030]
![image](https://cloud.githubusercontent.com/assets/7493331/10956272/2bbd98b4-830f-11e5-8701-a68407cea32e.png)

It would be much more informative if the Course Title was included in the information displayed by the mouse-over on the Dashboard Calendar above where it says (in this example) Room 281.

**Comment by jrjohnson** [comment]
This is actually pretty hard to do as it would require passing more information into the calenda than we currently have in an event. So I'm going to put it on the backburner for now.

**Comment by saschaben** [comment]
closed with 3.3
