### ISSUE TITLE
Froala Should be Used in Upload of Learning Materials >> Citation (Citation Field)

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1032]
The Froala text box was not used in the upload Learning Material >> Citation functionality.

It should be used for ease of use and for consistency's sake.

See the screenshot below for reference.

![image](https://github-cloud.s3.amazonaws.com/assets%2F7493331%2F10956759%2F0ecb92b6-8313-11e5-8e2d-cff6d69c0a5e.png)

**Comment by saschaben** [comment]
Closed in favor of #2214.
