### ISSUE TITLE
PM Switches Back to AM When End Time Hour Picker is Used >> Add Offering

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1034]
The AM/PM picker switches back to AM when the End Time Hour is Updated.  Obviously, if it already AM, there is no problem but if PM, it messes up the offering's start and end time.

This session goes from 11:00 AM - 1:00 PM so first I will change the start time.
![image](https://github-cloud.s3.amazonaws.com/assets%2F7493331%2F10957111%2F358449c2-8316-11e5-9cb7-d2f13b5d9884.png)

Now change the end time AM/PM to PM.
![image](https://github-cloud.s3.amazonaws.com/assets%2F7493331%2F10957118%2F49a1cfc4-8316-11e5-877a-42c5532a015b.png)

Now change the end time hour to 1 and notice that without doing anything, the PM switched to AM.
![image](https://github-cloud.s3.amazonaws.com/assets%2F7493331%2F10957127%2F664e325c-8316-11e5-8804-55faa8ba4b5c.png)

NOTE:  This only happens when the end time hour is changed to a different end time hour than it was previously.

**Comment by saschaben** [comment]
see also #938
