### ISSUE TITLE
Edit Menu Item On Session Does Not Do Anything

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1035]
Actually an error is now returned that there is no action handler for the edit menu item.

`there is 1 error <ilios@component:ilios-sessions-list::ember35704> had no action handler for: edit`

This functionality needs to be implemented.

**Comment by saschaben** [comment]
N.B. we should implement edit / delete functionality here with the icons in use elsewhere for the initial release, and remove the action controller until we find a better widget.
