### ISSUE TITLE
Test validations in course overview

### ISSUE THREAD

**Issue by djvoa12** [ilios/frontend#1042]
`validations work properly` test in `tests/acceptance/course/overview-test.js` need to pass in PhantomJS, which is tied to Travis. It passes in Chrome (`ember t -s`).

Difficulty Level: 9000

**Comment by jrjohnson** [comment]
New validations are much more testable need to uncomment and update https://github.com/ilios/frontend/blob/master/tests/acceptance/course/overview-test.js#L492
