### ISSUE TITLE
More Font Size and Color Options Needed in Froala Text Boxes

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1047]
It has been suggested that there should be more options for text formatting in the Froala editor -- especially regarding font size and color.

When pasting in from Word, the font sizes and color customizations are removed.  The current version of Ilios allows this to some degree.

**Comment by saschaben** [comment]
Additional formatting may be a nice to have, but it also creates junk in reporting, which we are trying to keep at a minimum. if there is a particular formatting desire, we should get user input on specifically where and how it is to be used, and why it is necessary in this particular context. For now, no additions are lined up.
