### ISSUE TITLE
Caption on Screen Doesn't Change to Admin when Admin Menu Item Is Clicked

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1048]
![image](https://cloud.githubusercontent.com/assets/7493331/10986023/1cf28156-83db-11e5-93b3-76956ca476e5.png)

**Comment by dartajax** [comment]
In the screen shot above, I had selected Admin but the Label remained "Instructor Groups".

**Comment by saschaben** [comment]
@dartajax, was this on demo or local or netlify? and as what user?
