### ISSUE TITLE
Mark As Scheduled Should Not Appear If There Are No Offerings

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1059]
There is no reason to have “Mark as Scheduled” anywhere in drop-down menus where there is no session offering yet.  There is nothing to schedule (or publish of course) without an event - unless we don't care about this.

![image](https://cloud.githubusercontent.com/assets/7493331/11012417/81c29bd4-84a8-11e5-8d27-7e75562c24a1.png)

**Comment by saschaben** [comment]
We should get further feedback from users, but I would guess that in real use having the "scheduled" option disappear or appear rather than being a constant option may be more confusing in the end. Let's backlog this and see what they say after launch.

**Comment by jrjohnson** [comment]
We decided to keep this in the menu since it is valid even though it is weird.
