### ISSUE TITLE
calendar week view events bleed across days column lines

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#1066]
when there are overlapping events for a given time period, in week view the events fartherst to the right of the day colunm area bleed over into the next day column (see image below).

**Comment by saschaben** [comment]
![bleed](https://cloud.githubusercontent.com/assets/1753431/11022354/6f907b1a-8611-11e5-8ba3-4a449a4202a2.png)

**Comment by dartajax** [comment]
It seems that the widths of the calendar offerings being displayed are twice as wide as they should be and are tiled incorrectly. 

Here is another screen shot.

![calendar_overlap](https://cloud.githubusercontent.com/assets/7493331/11905757/f228e6fe-a57c-11e5-853d-144396e1a244.jpg)

**Comment by saschaben** [comment]
the simplest solution to this is to add an `overflow: overlay`value to the css entry for either week-day or event-column, and alter the calculated offset of overlapping events from 50% of available space to just 30% of available space, and determine z-index by start time of the event ascending -- -so the latest event in time for a day should be the top displayed overlay.
