### ISSUE TITLE
Learning Material toggles not firing when clicked

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#1075]
when the toggles are set to "on", clicking and saving will update the record to make not required and/or hide notes from students, but the toggles do not visibly fire when clicked. Clicking them to "on" state from "off" state works just dandy. It's just turning them off that isn't firing.

**Comment by djvoa12** [comment]
@saschaben I couldn't recreate this. Can you maybe write down steps to get there with demo3 as proxy?

**Comment by saschaben** [comment]
huh. I can't recreate now either, although it was pretty consistent yesterday. It may be an ajax-y latency issue: if you log in as demo_faculty4, and go to http://localhost:4200/courses/791/sessions/23063, and clickety-click a bunch on the LM toggles, you should see that there is some sticky latency in the firing off (but not on) of the toggles -- especially if you've toggled one off/on and then go to the next one and try to fire it. But  as you note, this is not a regularly reproducible bug as I thought earlier. closing this with a 'won't fix', and adding a different issue regarding the latency on toggles generally.
