### ISSUE TITLE
Need to Display HTML Properly in Calendar Detail

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1077]
![image](https://cloud.githubusercontent.com/assets/7493331/11049794/bf711c68-86f5-11e5-80f0-d8aad9a3c08b.png)

This should look more like ...

![image](https://cloud.githubusercontent.com/assets/7493331/11049808/da0b0b42-86f5-11e5-899f-1d8354362c74.png)

... as it does within the application.

**Comment by djvoa12** [comment]
@dartajax @saschaben I need steps to re-create this on demo3 proxy.

**Comment by saschaben** [comment]
login as demofaculty4. go to:

http://localhost:4200/events/S0120151113O62551 : look at learning materials
http://localhost:4200/events/S0120151115O58353 : course objectives
http://localhost:4200/events/S0120151111O64499 : session description block

some (like objectives) are worse than others: lots of MSWord cut'n'paste cruft xml garbage. Others just have simple HTML markup (like the description example.) In all cases, we should be wrapping this text to render as HTML (which should make the cruft vanish, and render whatever valid tags are being passed in.).
