### ISSUE TITLE
Froala Validation Error on Save

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1078]
This occurs in Session Objective and Session Description ...

![image](https://cloud.githubusercontent.com/assets/7493331/11050237/0c819ba6-86f9-11e5-841f-4e18bed4930a.png)

Click the Description above to edit it.

![image](https://cloud.githubusercontent.com/assets/7493331/11050263/2cf73224-86f9-11e5-9a42-0b76a59ba1ad.png)

Click Done without editing any information in the field.

It removes whatever was there.

![image](https://cloud.githubusercontent.com/assets/7493331/11050277/4c5e8b8a-86f9-11e5-97c6-de70f1da70f3.png)

Click to edit.

It's gone.

![image](https://cloud.githubusercontent.com/assets/7493331/11050290/68c97956-86f9-11e5-9dce-6ec95a2f37a8.png)

I had the Inspect Element running but did not pick anything up in Console or Network.

**Comment by dartajax** [comment]
I got this error when trying to navigate back to dashboard.

![image](https://cloud.githubusercontent.com/assets/7493331/11050427/9a456002-86fa-11e5-8e30-ce65672715ce.png)

**Comment by saschaben** [comment]
Session description is sending the following:

`Remote Address:64.54.247.108:443`
`Request URL:https://ilios-stage.ucsf.edu/api/v1/sessiondescriptions/10386`
`Request Method:DELETE`
`Status Code:204 No Content`

looks like if there is data in the title field and no change is made, a save action actually fires a delete action instead.
