### ISSUE TITLE
Objective Description Needs the Ellipsis or Continuation Indicator

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#108]
See below ...

Full Objective Description text 
<TEXT>
Have a basic understanding of the normal anatomy, development, physiology, and radiological features of the human nervous system, and current concepts regarding consciousness, perception, emotion and other aspects of the mind
</TEXT>
Screen shot below -- pre-edit 
![objext1](https://cloud.githubusercontent.com/assets/7493331/6158952/8d5edbd2-b204-11e4-9786-b2162e73864e.JPG)

**Comment by thecoolestguy** [comment]
Modify the live edit component (editable-textarea) to add a character count and class for the elipsis.

**Comment by jenzweben** [comment]
![screen shot 2015-02-23 at 12 11 45 pm](https://cloud.githubusercontent.com/assets/5023894/6336109/2af529c4-bb55-11e4-9fe9-08fffdf5b220.png)
