### ISSUE TITLE
Learner Groups Not Available For Selection After Adding Instructor

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1082]
How is this possible?  I know I did the following things ..

* selected an instructor for an existing session offering / event 
* attempted to at the same time to remove an instructor group -- that was impossible since I was doing the add of the instructor at the same time 
* clicked Done 
* noticed that the Learner Group got removed from the offering
* tried to fix it and noticed that the learner groups were not loading up for me to select one to fix this situation
* noticed the session below still had learner groups available for selection 

![image](https://cloud.githubusercontent.com/assets/7493331/11051329/18f65e1c-8703-11e5-9569-77c4b1f8d0bc.png)

Reloading the page did not help the situation. 

This may not be the best description of this scenario but I have some more for tomorrow on this topic as well.

**Comment by saschaben** [comment]
OK. it looks like this is more general: learner groups do not currently load into the group selector for existing offerings.
