### ISSUE TITLE
Fix Sort Order in Courses and Sessions

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1091]
I was trying to assign a Cohort to a newly-created course and I noticed the cohort list unsorted as shown below.

![image](https://cloud.githubusercontent.com/assets/7493331/11077872/1cf522dc-87b7-11e5-99fc-ffce0351a313.png)

I assume they should be sorted with most recent at the top of the sort.

**Comment by dartajax** [comment]
I will put the steps in and retest after the Standup meeting.

**Comment by dartajax** [comment]
![image](https://cloud.githubusercontent.com/assets/7493331/11135342/0a2f9756-8959-11e5-83ee-7a83d155f769.png)

![image](https://cloud.githubusercontent.com/assets/7493331/11135348/1e9cce5c-8959-11e5-97c5-8f2e5ad63714.png)

![image](https://cloud.githubusercontent.com/assets/7493331/11135364/336eeb58-8959-11e5-9632-ede0f071c92e.png)

![image](https://cloud.githubusercontent.com/assets/7493331/11135376/44546e98-8959-11e5-9b71-2046e533d581.png)

![image](https://cloud.githubusercontent.com/assets/7493331/11135378/54f35e3a-8959-11e5-9e32-19e827eb991c.png)

![image](https://cloud.githubusercontent.com/assets/7493331/11135393/77470fb8-8959-11e5-955c-d86c28034329.png)

I think this has been fixed.  At least on stage, you can see the correct sort order now displaying.  Oh well, the steps above are for reference in case we need to re-test.  See the proper sort order below.

![image](https://cloud.githubusercontent.com/assets/7493331/11135407/954f5ace-8959-11e5-8a20-37a8f93f0767.png)

**Comment by dartajax** [comment]
:+1:

**Comment by djvoa12** [comment]
@saschaben @dartajax seems like this is no longer issue. Should we close this one?
