### ISSUE TITLE
Learner Groups End Up Getting Duplicated When Editing Small Group Offerings

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1094]
See the scenario below in full color screen shots.

![image](https://cloud.githubusercontent.com/assets/7493331/11079175/54f7dffa-87bf-11e5-9004-85be51b0131f.png)

![image](https://cloud.githubusercontent.com/assets/7493331/11079186/66755118-87bf-11e5-96c8-c5a8c37b3d99.png)

![image](https://cloud.githubusercontent.com/assets/7493331/11079203/898c2b2c-87bf-11e5-9672-bed57c40b007.png)

![image](https://cloud.githubusercontent.com/assets/7493331/11079224/b3aa6892-87bf-11e5-8924-d344a186498a.png)

![image](https://cloud.githubusercontent.com/assets/7493331/11079249/ddd175c0-87bf-11e5-8316-d18dad6878ab.png)

![image](https://cloud.githubusercontent.com/assets/7493331/11079266/f23596d6-87bf-11e5-996d-38e7abaa184c.png)

After cancelling and then reopening the offering to edit / review it, the learner group keeps getting duplicated on the screen.

![image](https://cloud.githubusercontent.com/assets/7493331/11079323/503c1188-87c0-11e5-9364-4cacc4c20d89.png)

**Comment by djvoa12** [comment]
@jrjohnson @saschaben I believe PR #1097 fixes this dup issue. Can you verify?

**Comment by dartajax** [comment]
I just went through all of the steps above and the issue appears to have been resolved as far as I can tell.

:+1:
