### ISSUE TITLE
Delete Failing On Session

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1096]
I created some sessions that I wanted to delete in order to report a different issue; but the system is not allowing me to delete my sessions.

![image](https://cloud.githubusercontent.com/assets/7493331/11079804/aedc8454-87c3-11e5-8d79-6013e2720a49.png)

This message is not correct either.  Shouldn't it warn me of the offerings that are attached to learner groups that I am about to drop?

![image](https://cloud.githubusercontent.com/assets/7493331/11079837/dfd6eee6-87c3-11e5-8f9f-3d60430c19b1.png)

![image](https://cloud.githubusercontent.com/assets/7493331/11079859/17a08f08-87c4-11e5-9fd8-2227612760b5.png)

![image](https://cloud.githubusercontent.com/assets/7493331/11079870/24015f52-87c4-11e5-80b3-a882358ec4d9.png)

**Comment by jrjohnson** [comment]
Some people don't have permission to delete sessions, we should hid the icon from them.

**Comment by stopfstedt** [comment]
@dartajax - what environment are you using, and what user login are you using? thnaks.

**Comment by jrjohnson** [comment]
Created a new ticket to address this globally #1181
