### ISSUE TITLE
Save Failing On Offerings When Changed From Small Groups To Single Offering

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1099]
see the shots below ...

![image](https://cloud.githubusercontent.com/assets/7493331/11080153/3e1ed55c-87c6-11e5-83c8-10b6df3a111e.png)

Add an offering ...

![image](https://cloud.githubusercontent.com/assets/7493331/11080166/56e1038a-87c6-11e5-97d1-d3ffa2eb4959.png)

![image](https://cloud.githubusercontent.com/assets/7493331/11080189/8849b4a8-87c6-11e5-912c-64085e3cb368.png)

Switch it to Offering (rather than the Small Group default)

![image](https://cloud.githubusercontent.com/assets/7493331/11080197/a122445e-87c6-11e5-861a-a11fcdb08347.png)

Add two instructors and a room.

Press Done

![image](https://cloud.githubusercontent.com/assets/7493331/11080218/de46e59c-87c6-11e5-9550-98a274a21a46.png)

Results ....

![image](https://cloud.githubusercontent.com/assets/7493331/11080238/fa016c4e-87c6-11e5-833f-890747732772.png)

Or ...

![image](https://cloud.githubusercontent.com/assets/7493331/11080253/0e63bfb6-87c7-11e5-86a2-6028c559ff4b.png)

**Comment by djvoa12** [comment]
@jrjohnson I believe @stopfstedt is working on fixing this one.

**Comment by stopfstedt** [comment]
should be fixed with #1080, please check if this issue persists after that PR has been merged and deployed.

**Comment by jrjohnson** [comment]
Confirmed that I can't duplicate this and think it is fixed.
