### ISSUE TITLE
funky results with offering create/edit with instructors/instructor-groups

### ISSUE THREAD

**Issue by djvoa12** [ilios/frontend#1100]
A lot of bugs arising from creating and editing offerings with instructor or instructor-groups. The code for saving or displaying instructor or instructor-groups need revision.

- Creating a new offering blows up.
<img width="893" alt="screen shot 2015-11-10 at 4 18 22 pm" src="https://cloud.githubusercontent.com/assets/7553764/11080296/498d21d6-87c7-11e5-9ae0-efed0fbd8f9a.png">

- Sometimes, instructors added in edit mode doesn't persist (many times after adding more than 1 instructor).

**Comment by dartajax** [comment]
This is related to #1099 and #1094 probably as well.  Funky results = true.

**Comment by stopfstedt** [comment]
see #1080 as well.

**Comment by saschaben** [comment]
dupe. replaced by #1311.
