### ISSUE TITLE
Course ID Not Displayed Anywhere On Course Detail

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#111]
![coursewid](https://cloud.githubusercontent.com/assets/7493331/6159257/f3cee288-b207-11e4-9cf1-135264405228.JPG)
![coursenoid](https://cloud.githubusercontent.com/assets/7493331/6159259/f7c4288a-b207-11e4-9ce7-95ad020b6b52.JPG)

**Comment by jrjohnson** [comment]
It displays as external ID in the overview section.
