### ISSUE TITLE
Long learning material titles break the alignment of the row

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#1118]
When a learning material title breaks into two lines the row becomes miss-aligned.  We should probably vertically center everything so it doesn't look wonky.
![lmlongtitle](https://cloud.githubusercontent.com/assets/349624/11164435/e8f2013a-8aa4-11e5-823e-830d99dfe9a6.png)

**Comment by dartajax** [comment]
This is still an issue.  Low hanging fruit gets the bees.

![image](https://cloud.githubusercontent.com/assets/7493331/23278360/16567f16-f9c6-11e6-9f71-25c8e6f29a1d.png)

**Comment by stopfstedt** [comment]
turns out this already got fixed.
