### ISSUE TITLE
Delete (Remove) Course Fails -- 500

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1141]
I was trying to remove "Jason's Test Course" and received this message.  I was logged in as Nicholas Gutierrez (demo_dev1) so I should have had the authority to do this, no?

![image](https://cloud.githubusercontent.com/assets/7493331/11307277/ee16532a-8f6b-11e5-869c-7d54a547abba.png)

**Comment by saschaben** [comment]
permissions issue
