### ISSUE TITLE
Learner Groups Page Needs Dropdown Highlighting Indicating The Selected Value

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1145]
See screen shot below for more information.  This first field is the Cohort drop-down.  Class of 2018 should be highlighted to indicated that that is the value currently selected in the drop-down.

![image](https://cloud.githubusercontent.com/assets/7493331/11307772/1fbd024a-8f6f-11e5-8a96-016cdf7db11a.png)

The same is true for Program ...

![image](https://cloud.githubusercontent.com/assets/7493331/11307798/43a3e00c-8f6f-11e5-9c41-05c4bcc5d2ff.png)

The same is also true for School ...

![image](https://cloud.githubusercontent.com/assets/7493331/11307817/594170b4-8f6f-11e5-9280-017745463ad5.png)

The user should have an indication that what is contained in the top of the box is actually a selected value from the list.

**Comment by jrjohnson** [comment]
This is fixed now that we are using regular select lists.  Which is an AWESOME reason to use regular select lists.
