### ISSUE TITLE
MyReports needs a report-close button

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#1150]
currently we have no way to close a report once opened and return to the report list.

We should add our usual X - close icon in the upper right corner for the opened report display

**Comment by jrjohnson** [comment]
The plus sign turns into an "All Reports" button.  So it isn't possible to add a report when one is being viewed.  Should we keep that and also do a red x?

**Comment by saschaben** [comment]
Ah. Ok. I totally missed the 'All Reports' button. Maybe we should just change it to "Close Report" and that will be more clear. no need for a red X.

**Comment by jrjohnson** [comment]
Ok - should I make it red as well?

**Comment by saschaben** [comment]
Nah. Button blue should be fine.
