### ISSUE TITLE
MyReports - courses should list in reports with academic year

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#1151]
in returning a list of courses, the printed value should be `[academic year] - [course title]`,  as we do in My Courses. 

Currently we only print course title on screen.

**Comment by jrjohnson** [comment]
Sort them by course title or by year?

**Comment by saschaben** [comment]
we currently sort by title then date so courses are grouped together in date order. we may want to alter that moving forward but let's replicate it for this release.

**Comment by saschaben** [comment]
fixed in PR #1198
