### ISSUE TITLE
Acceptance tests regarding members' true count need to be fixed

### ISSUE THREAD

**Issue by djvoa12** [ilios/frontend#1157]
This [PR](https://github.com/ilios/frontend/pull/1114) fixes the counts, but the associations in the four acceptance tests (four assertions total) need to be straightened out as the counts don't add up in the tests.

#### In demo3 proxy (works fine):
- `http://localhost:4200/learnergroups?program=1&programYear=27`
<img width="554" alt="screen shot 2015-11-25 at 12 47 05 pm" src="https://cloud.githubusercontent.com/assets/7553764/11409193/011a7b1c-9373-11e5-80ad-a52ede2fc751.png">

- `http://localhost:4200/learnergroups/2771`
<img width="341" alt="screen shot 2015-11-25 at 12 47 20 pm" src="https://cloud.githubusercontent.com/assets/7553764/11409203/1a693e46-9373-11e5-8217-c5ce4029919a.png">

#### Four acceptance tests (commented out):
<img width="829" alt="screen shot 2015-11-25 at 12 51 08 pm" src="https://cloud.githubusercontent.com/assets/7553764/11409231/47a8c156-9373-11e5-984f-e3340866b02a.png">
<img width="553" alt="screen shot 2015-11-25 at 12 51 24 pm" src="https://cloud.githubusercontent.com/assets/7553764/11409234/4c8e79b8-9373-11e5-9170-d3fd1fec6627.png">

**Comment by saschaben** [comment]
is this still an issue? If not, please close, thanks.
