### ISSUE TITLE
userSyncIgnore property in the user model does not keep state in the server

### ISSUE THREAD

**Issue by djvoa12** [ilios/frontend#1169]
1) Go to `/users` route.

2) Select first user.
<img width="984" alt="screen shot 2015-11-30 at 1 36 59 pm" src="https://cloud.githubusercontent.com/assets/7553764/11485339/969da252-9767-11e5-93cd-7561f0ababe3.png">

3) Check `Exclude From Sync`
<img width="254" alt="screen shot 2015-11-30 at 1 38 27 pm" src="https://cloud.githubusercontent.com/assets/7553764/11485358/b0fc288a-9767-11e5-84d0-50d65f02f9cb.png">

4) See that it sends a `PUT` request to the server.
<img width="390" alt="screen shot 2015-11-30 at 1 39 39 pm" src="https://cloud.githubusercontent.com/assets/7553764/11485399/d6a08144-9767-11e5-83a6-2d9f0ab35307.png">

5) Refresh the page and found that the checkmark is gone. `userSyncIgnore` property in the user model returns `undefined`.

**Comment by jrjohnson** [comment]
Fixes in API.
