### ISSUE TITLE
inline editing "save" icon does not function properly

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#117]
the inline edit "save" check icon does not close form fields on click. if you click it, and then click the "x" to close the form field, updates are saved. (this appears to be a regression, @thecoolestguy I think you are aware of the problem and a solution --- it may have got overwritten in our latest sprint.)

**Comment by thecoolestguy** [comment]
This was resolved in a previous commit by jrjohnson, but it is still a little buggy, so Its mixin needs review... Changed title to reflect the the bugginess

**Comment by saschaben** [comment]
Inconsistently throws error and fails ---
![ilios 2015-02-23 12-57-31](https://cloud.githubusercontent.com/assets/1753431/6336999/97fa30c2-bb5b-11e4-8d29-3ed93c6b6231.png)
Cannot replicate with any consistency -- but once occurring, throws error for all controls on the page.

Otherwise, the return rendering to non-edit state is painfully slow: the API call show a network time for about 1 second for the put; the lag to re-rendering the control is about five seconds.

Testing with master branch on chrome.

**Comment by jrjohnson** [comment]
resolved earlier
