### ISSUE TITLE
500 server error during user model update

### ISSUE THREAD

**Issue by djvoa12** [ilios/frontend#1170]
1) Go to `/users` route.

2) Select the last user on the first page.
<img width="871" alt="screen shot 2015-11-30 at 1 43 38 pm" src="https://cloud.githubusercontent.com/assets/7553764/11485508/6d432aca-9768-11e5-8c3a-3d541f6e0e01.png">

3) Check `Disable User` or `Exclude From Sync` and wait for a moment.

4) Error message should pop up.
<img width="391" alt="screen shot 2015-11-30 at 1 46 25 pm" src="https://cloud.githubusercontent.com/assets/7553764/11485593/f1589c0a-9768-11e5-9620-9f86f59e5f55.png">

**Comment by jrjohnson** [comment]
API Issue, resolved there.
