### ISSUE TITLE
Review Missing Items Doesn't Work At the Course Level

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1175]
I was using stage when I noticed this.  The course I am trying to publish is called "Advanced Health Policy".  Apparently there are 3 things missing but the functionality to review them is not happening.  I am not capturing anything in the Inspect Element / Console panel.

Here is a screen shot hopefully ...

![image](https://cloud.githubusercontent.com/assets/7493331/11489856/e0d5f142-9787-11e5-8539-53dbceb8aa94.png)

Selecting "Review 3 Missing Items" does not do anything.

**Comment by jrjohnson** [comment]
@dartajax I'm unable to duplicate this.  Seems to work fine.  Can you confirm?  Maybe this was a temporary issue?

**Comment by dartajax** [comment]
Fair enough.  I just retested and it seems to work fine for me now too.
