### ISSUE TITLE
Unable to delete program year

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#1177]
We currently don't cascade all of a program year delete in the database.  It seems to be possible to remove a new program year (even if it is copied from the previous data) but not one with courses attached.

I think this is probably the correct behavior from the API.  We just need to reflect to the user which program years they can and can not delete.

**Comment by saschaben** [comment]
I agree, but this is not the behavior I am seeing. I am unable to delete a year with no attachments; create a new program year, add nothing to it, and still it throws an error.

This is more a housekeeping thing than anything else, but still let's be sure to investigate and correct it, to make sure there aren't any associated gotchas.
