### ISSUE TITLE
Delete Permission Review

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#1182]
I think we're currently allowing delete option to anyone and that should change.  @saschaben can you review who should be able to delete a course, session, or offering?  Any instructor currently has access to those options.

**Comment by saschaben** [comment]
From @dartajax and Valentina's feedback, I think we want to allow delete (at least at this point) only to superuser types: valentinas and possibly course directors. So:

* Deleting a Program: only School superuser (developer+course director?)
* Deleting a Course: Only a course director for that course, or a school superuser developer type.
* Deleting a Session: Only a course director for that session's course, or a developer type (ie staff).
* Deleting an Offering: Only an instructor attached to that offering, or a course director for that offering's course, or a developer type (ie staff).

For questions like this, we can start to refer back to the now ancient permissions grid which is pinned to the cubicle walls and is also kept here: https://www.dropbox.com/s/7cerjnm5qbfion5/permissions%20matrix%20-%20app.%20B.docx?dl=0

This should provide initial guidance.
