### ISSUE TITLE
Review Missing Details At Course Level Should Send The User to The Review Location

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1188]
This occurs when the details of a course are being shown and the user selects "Review X Missing Items" where X is obviously the number of missing items.

It performs as it should but does not route take the user to the location on the screen where the missing details are located.  This is not an issue when the details of a course are being hidden.

![image](https://cloud.githubusercontent.com/assets/7493331/11574670/dfd5b99e-99c1-11e5-988c-fbac2ce134bd.png)

After clicking in this case "Review 2 Missing Items", the screen looks like ...

![image](https://cloud.githubusercontent.com/assets/7493331/11574686/f52e80fa-99c1-11e5-89e4-89409ac172d6.png)

It doesn't change at all.  If the user has the wherewithal to know that if he or she scrolls to the bottom of the screen, they would find, ...

![image](https://cloud.githubusercontent.com/assets/7493331/11574718/19d68952-99c2-11e5-8410-7b73d6f9a3bf.png)

We can't depend on users to have that knowledge (without any visible screen changes whatsoever) that they should scroll to the bottom of the screen to see the information requested.

**Comment by saschaben** [comment]
This speaks to a possible need to refactor how we present this information in the page generally. Let's discuss after we make more progress on permissions.

**Comment by dartajax** [comment]
Steps to Reproduce ...

* Pull up a Course 
https://ilios3-demo.ucsf.edu/courses/1505

* Create a New Session titled anything you want 
* Scroll down to the Offerings Editor and ...
![image](https://user-images.githubusercontent.com/7493331/56913710-3da65f00-6a67-11e9-8c37-49d6f1c37003.png)

![image](https://user-images.githubusercontent.com/7493331/56913901-a1308c80-6a67-11e9-9ec6-9066d32d7b57.png)

* Select a Learner Group for the Offering 
![image](https://user-images.githubusercontent.com/7493331/56913947-befdf180-6a67-11e9-8be1-20e756012242.png)

* Click Done 
![image](https://user-images.githubusercontent.com/7493331/56914073-008e9c80-6a68-11e9-8632-a09abadc7730.png)

* Now when `Review [x] Missing Items` is selected, the user should be taken to the location where they can review the missing items - the bottom of the screen.

**Comment by stopfstedt** [comment]
the obvious solution is to scroll the review section into view.
