### ISSUE TITLE
Make MeSH Results Box Wider and Possibly Taller

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1189]
![image](https://cloud.githubusercontent.com/assets/7493331/11575252/dcd14f94-99c4-11e5-92c1-731e4be3471c.png)

In this example I was really only able to review one result for the search of "Heart".  It would be hard to determine if there is a better result down below.

**Comment by dartajax** [comment]
What is the "Show more" button / label / tab thing supposed to do?  I would imagine it would expand the box or something to make it easier for the user to see more results or a bigger, more detailed view of the current results.

**Comment by jrjohnson** [comment]
No, it adds more results to the bottom of the list.  There are 20 there now, and if you click there will be 80.  We probably need to update the UX on this because I agree it may be confusing.   Any thoughts on improvements?

**Comment by dartajax** [comment]
Maybe we could add more to the results and expand the box when someone clicks "Show more"?
