### ISSUE TITLE
Search Results (Global) Do Not Return Correct Data

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1190]
What this means is ...

When you log in to Ilios and immediately go to Admin and then do a search for an entity that you are confident exists -- in this case, I searched for myself.

See the screen shot below. It orders by Last Name, First Name asc so I am showing the place where Leonard, David should exist.

![image](https://cloud.githubusercontent.com/assets/7493331/11575850/1b858478-99c8-11e5-87a9-a0e3c750ff71.png)

The other search available from ....

![image](https://cloud.githubusercontent.com/assets/7493331/11575871/3ae16076-99c8-11e5-8700-bed891af0de1.png)

... seems to work.

![image](https://cloud.githubusercontent.com/assets/7493331/11575906/549aeb0e-99c8-11e5-8683-6221321cfd79.png)

Now if I go back to the Global Search by clicking Admin as shown, 

![image](https://cloud.githubusercontent.com/assets/7493331/11575939/7d2b039c-99c8-11e5-81cb-6a1dc0d54119.png)

I am still getting the bad data ...

![image](https://cloud.githubusercontent.com/assets/7493331/11575968/a1a14b82-99c8-11e5-8995-377f9e1270f5.png)

But ...

Eventually it works.  I obtained the correct results by futzing with the search parameter (using Leona, Leon, Leo, Leonar) various thngs like that and eventually the results matched what was returned in the other "Manage Users" search.

**Comment by dartajax** [comment]
![image](https://cloud.githubusercontent.com/assets/7493331/11576018/fa46ec38-99c8-11e5-9ed4-57e5a20de764.png)

**Comment by dartajax** [comment]
This is really inconsistent.  When you erase the contents of the search box completely, the old bad results are still there.  And then again sometimes, they are not.

**Comment by dartajax** [comment]
Try this ....

1.  Bad
![image](https://cloud.githubusercontent.com/assets/7493331/11576352/de35ce40-99ca-11e5-8768-5b961e3404d4.png)

2. Good
![image](https://cloud.githubusercontent.com/assets/7493331/11576361/f3a3e6e0-99ca-11e5-9cbd-d98b1a1e40da.png)

3. Bad
![image](https://cloud.githubusercontent.com/assets/7493331/11576371/07ed99e8-99cb-11e5-920b-ff64cdd79022.png)

**Comment by dartajax** [comment]
Clear the entire search string out and ....

Bad
![image](https://cloud.githubusercontent.com/assets/7493331/11576390/3176d6f8-99cb-11e5-85b7-ac5ff48af3eb.png)

This is not even mentioning the fact that there should be no search results if no search string is entered (well now it is).

**Comment by djvoa12** [comment]
Client-side has been refactored. If there are inconsistent search results, it might be a back-end issue.
