### ISSUE TITLE
Change Caption For MeSH Search

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1193]
Since MeSH is the only search area that requires the user to press the enter key on their keyboard to run the search, we should provide this information in the caption.

Instead of saying "Search MeSH" as shown below, can we change it to something like "Press Enter to Search"?  or maybe something even more descriptive.  

![image](https://cloud.githubusercontent.com/assets/7493331/11576700/7fd8842a-99cd-11e5-8aee-cd3fc2347655.png)

Or in a small caption like this.

![image](https://cloud.githubusercontent.com/assets/7493331/11576833/61f50dba-99ce-11e5-82f9-e90fb1487f41.png)

Instead of saying "can't be blank", it could say "enter search criteria and press enter" -- something like that.

**Comment by stopfstedt** [comment]
change nothinhg here. instead, provide more concise info on how to use this search component in the user guide.

**Comment by dartajax** [comment]
The image pasted below is from the User Guide.  

![image](https://cloud.githubusercontent.com/assets/7493331/19787947/86057f84-9c5a-11e6-9a18-ce15f8560eeb.png)
