### ISSUE TITLE
Adjust topic tag display section to accommodate new vocabulary model

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1220]
If you select a long topic name such as  "Clinical and Translational Research" or "Complimentary/Alternative Healthcare" the topic name will split between two columns making it appear that each topic is multiple topics.

![image](https://cloud.githubusercontent.com/assets/7493331/11644870/85071cba-9d04-11e5-8b5c-1a3f5a2db366.png)

**Comment by dartajax** [comment]
![topicstuff](https://cloud.githubusercontent.com/assets/7493331/11645025/cad4df1a-9d05-11e5-8bc2-bc866007d6da.JPG)

**Comment by dartajax** [comment]
Maybe it should be badged somehow to help determine topic wrapping.

**Comment by jrjohnson** [comment]
Sorry I'm not understanding. 1. - shows two topics.  What should it show?

**Comment by dartajax** [comment]
![image](https://cloud.githubusercontent.com/assets/7493331/11645185/23dc77c0-9d07-11e5-930d-3b8e3c459d41.png)

![image](https://cloud.githubusercontent.com/assets/7493331/11645189/38fd1ace-9d07-11e5-9183-dad322988db7.png)

**Comment by dartajax** [comment]
1. was confusing because there is a huge gap and instead of 2 topics, it looks like 4.

"Clinical and Translational"
"Research"
"Complimentary/Alternative"
"Healthcare"

**Comment by jrjohnson** [comment]
Ah ok - I see now.  Wow, yea that is a bad display.  Looked like none to me with column headers.  Ok.

**Comment by jrjohnson** [comment]
I can't repeat this anywhere.  What course were you working with?

**Comment by saschaben** [comment]
Create a test course --- or delete all topics from a course or session. This only occurs with the shown "long name" topics, and only when two or less are selected. The grid evens them out when you have three or more columns in the grid....

**Comment by jrjohnson** [comment]
AHHHH... I understand the issue now.  Ok, if I can fix this in 1 few minutes I will otherwise this seems pretty low priority.

**Comment by jrjohnson** [comment]
Tried adjusting css word-wrap or display values, but nothing seemed to be a good fix.  Setting a height on the list item caused the values to wrap, but blew up the alignment on the list.
Some other options:
1.  A better CSS solution
2. Strip spaces from the topic names and preset them with &nbsp; instead.
3. When there are less than 3 items don't use a column list just put them in a regular list.

**Comment by saschaben** [comment]
Let's address this one in conjunction with the taxonomies work.

**Comment by saschaben** [comment]
changing this to address not only the wrapping, but the implied additional issues we will have with larger, longer-named, and more complex tags generally once the vocabulary terms start being shown. We will need to rethink the way we are presenting this information in the grid...
