### ISSUE TITLE
Inline Save on Learning Materials is Confusing

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1229]
See below ...

![image](https://cloud.githubusercontent.com/assets/7493331/11673567/d67f7f5e-9dce-11e5-9108-f79544a6cff8.png)

![image](https://cloud.githubusercontent.com/assets/7493331/11673577/f6292cec-9dce-11e5-88f2-2a3f94eede50.png)

![image](https://cloud.githubusercontent.com/assets/7493331/11673589/03328262-9dcf-11e5-9a24-a55db921fca4.png)

Inline Save of Other Field data does not save either.

**Comment by saschaben** [comment]
controls in the manager should be open rather than closed when the manager opens

**Comment by jrjohnson** [comment]
Fixed in #3235
