### ISSUE TITLE
Multi Edit of Learner Groups Only Moves the First Record (Wrong Record Even)

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1235]
See my screenshot "narrative" for details.

This group and its sub-groups don't contain any members yet.  My task is to fix that. I click on "ABG Small Group" to some editing.

![image](https://cloud.githubusercontent.com/assets/7493331/11695955/de7a92e6-9e66-11e5-9927-9424b4d684e9.png)

As can be seen below, there are no members of the higher level "ABG Small Groups" learner group and all of the sub-groups below have no members yet either.  My goal is to add 5 people to the "ABG Small Group 1" group.  I will select these five students from the Cohort.  First, I will select the sub group as shown below.

![image](https://cloud.githubusercontent.com/assets/7493331/11696024/18026c5a-9e67-11e5-9657-c379d310604c.png)

Now the screen appears as follows ...

I am going to turn on the Multi-Edit functionality as shown below.

![image](https://cloud.githubusercontent.com/assets/7493331/11696122/99815782-9e67-11e5-80ae-9c830cecfd4b.png)

Now that Multi-Edit is on the screen appears as shown below.  I have selected the five students I would like to have included in "ABG Small Group 1".

Now by accessing the "Select" drop-down, I will assign them to the correct group as shown in Figure 1.2.45 below.

Figure 1.2.45

![image](https://cloud.githubusercontent.com/assets/7493331/11696208/07656b94-9e68-11e5-9fa1-6427b84798e6.png)

and more ...

![image](https://cloud.githubusercontent.com/assets/7493331/11696228/202aa9f0-9e68-11e5-9090-7172d88ee3a7.png)

After clicking the Green save icon ...

The splash screen appears and then ...

Someone who I did not even select went into the group.  What the?

![image](https://cloud.githubusercontent.com/assets/7493331/11696262/54026394-9e68-11e5-8ef7-e607245b1fe9.png)

**Comment by jrjohnson** [comment]
This will be addressed in #1246
