### ISSUE TITLE
any MyReports request with Mesh fails

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#1236]
any "all mesh for X" request throws a 500 error; "All X for Mesh Y" throws `t[n] is not a function`

**Comment by jrjohnson** [comment]
I can't duplicate this.  Can you give me a specific setup on ilios-stage?  I tried running courses and sessions with mesh and mesh with courses and sessions and they all came back fine.

**Comment by saschaben** [comment]
this appears to have been due to duplicate logins, somehow. closing.
