### ISSUE TITLE
MyReports has some issues

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#1238]
- [x] "__All session types for instructor [X]__" returns `_this[mapper] is not a function`
- [x] "__All session types for Competency [X]__" returns `t[n] is not a function`
- [ ] "__All sessions for course [X]__"  returns `500: Error: Adapter operation failed ` when attempting to retrieve list of courses
- [x] For reports requiring a predicate selection (like "all courses associated to topic which is [X]"), the select list of predicates does not allow for selection of the default selected display value (topic: acute  care, for instance) -- only an active select action will allow a save.
- [x] "__All session types associated to__"....association list is incorrect. should be: 
 - COURSE 
 - PROGRAM YEAR 
 - PROGRAM 
 - INSTRUCTOR 
 - INSTRUCTOR GROUP 
 - LEARNING MATERIAL 
 - COMPETENCY 
 - MESH TERM 
 - TOPIC 
- Currently list includes 
 - SESSION 
 - INSTRUCTOR 
 - INSTRUCTOR GROUP 
 - COMPETENCY 
 - MESH TERM

**Comment by jrjohnson** [comment]
Created #1374 to add program year to session type list.  It is a harder problem than fixing these bugs.

**Comment by jrjohnson** [comment]
Created https://github.com/ilios/ilios/issues/1312 to handle loading courses blowing up.  Also modified the query to scope the course list by school so that will help with this most of the time until that is resolved.
