### ISSUE TITLE
change "My calendar" label

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#1241]
at this point, it makes little sense: we've got the "my calendar" header label for the default agenda view, the "calendar on/off" toggle to actually show the calendar, the "my schedule" toggle to show the user schedule in the calendar grid.....

My Calendar should be more appropriately named.

Maybe "upcoming activities"
Or Events List
Or Agenda
Or "What's Happenin'!"

Or something.

**Comment by jrjohnson** [comment]
This got fixed... at some point.
