### ISSUE TITLE
learner group listings in user management display should be ordered

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#1249]
currently looks like they are sorting by id; should be sorted by alpha AND should identify nesting. So "Anatomy Lab" should somehow be identified as the parent for "Anatomy Lab 21",, yah?
![ilios 2015-12-14 12-57-07](https://cloud.githubusercontent.com/assets/1753431/11793761/3e64aa8a-a262-11e5-8b5b-7cad3665bf1e.png)

**Comment by jrjohnson** [comment]
This entire section has been updated many times, at some point we fixed this issue.
