### ISSUE TITLE
Formatting Issue For Session Type (Not Enough Room)

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1251]
Refer to the screenshot below.  We need 4 or 5 more spaces to allow the longer Types of Sessions to be displayed.  Suggestion:  Maybe we could stack the first offering ...

Date of Offering
Time of Offering 

ILMs ...

ILM Due By
Date ILM Due By

![image](https://cloud.githubusercontent.com/assets/7493331/11799031/2b6b222e-a285-11e5-8bda-c80bad5ecea7.png)

**Comment by jrjohnson** [comment]
Fixed in #3578 as the table now flows more naturally. Probably need to address this entire layout area, but I'm closing this one item as fixed.
