### ISSUE TITLE
User Search does not refresh

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#1256]
If you run a search on users, the search results are sticky....***very*** sticky. requires a hard refresh to clear results and get back to an unfiltered list.

- Go to admin.
- click "manage users".
- enter the search string "Chandl".
-    > you will have two results.
- Now navigate to course list. 
- Now click the Admin link to navigate back to users.
- Click "manage users".
- Your search results are still there.

We need a "clear search results" button.

**Comment by jrjohnson** [comment]
I am adding this to #2026 as I already fixed it while working on that.
