### ISSUE TITLE
Incorrect Field Mapping or Label in Learning Materials

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1257]
![image](https://cloud.githubusercontent.com/assets/7493331/11903709/0ac9a372-a570-11e5-8e29-e63a99d540eb.png)

The "Owner" of this learning material file is "Dana Rohde" according to the Session level Learning Materials screen.  After clicking (see dotted line) on the Learning Material hyperlink to get more details / download the file, the screen appears as shown below ...

![image](https://cloud.githubusercontent.com/assets/7493331/11903778/5dfc5062-a570-11e5-8079-f8bd1fc4ab87.png)

The "Owner" is now Michelle X Liu not Dana Rohde.  These fields and values need to be straightened out.

**Comment by saschaben** [comment]
Addressed with #1324. Closing.
