### ISSUE TITLE
Locked Courses Need To Have An Indication Of That Fact

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1266]
Since we have not gotten to locking, archiving, and rolling over courses, there is currently no indication that a course is locked.  The user will an error when they try and access that course but the course should either be in read-only mode or at a minimum, contain a visual indicator that the course is locked.

**Comment by saschaben** [comment]
we should add the fa-lock icon at 2x in the header like this:

![fa-lock](https://cloud.githubusercontent.com/assets/1753431/11965731/6ea8ba70-a8ab-11e5-9e99-776294ea9a52.png)


and the items that should be set as inactive on the course page are:

- [ ] course title
- [ ] Publish button
- [ ] external ID
- [ ] Start Date
- [ ] End Date
- [ ] Clerkship Type
- [ ] Level
- [ ] Directors / Director search
- [ ] Add Objective
- [ ] Objective Description
- [ ] Parent Objective 
- [ ] Objective MeSH Term
- [ ] Objective 
- [ ] Objective Delete Action (replace with static fa-lock icon)
- [ ] Add learning material / search learning material
- [ ] Manage Topics
- [ ] Manage MeSH
- [ ] Manage Cohort
- [ ] Add Session
- [ ] Publish all session button
- [ ] Session action icons (replace with static fa-lock icon)
- [ ] Session edit via session title link.

We will need to have a follow on at some point to do the same lock down for individual sessions, and then modify the session title link back to active.

**Comment by saschaben** [comment]
If the above solution is not possible in the short term, then plan B:

in the COURSE LIST page, make the titles of locked courses inactive as links, and replace the action icons with the fa-lock icon.
