### ISSUE TITLE
Allow User to Be Able to Set Priority (Sort Order) For Learning Materials

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1269]
It has been requested that we allow users to be able to set Learning Materials up for a Course or Session with a Priority value that could serve as a sort order.  The materials with the lowest value would appear first when students are reviewing a Course or Session and they would understand that this particular Learning Material (and the other ordered ones) are of a higher priority.

**Comment by saschaben** [comment]
High priority for both UCSF and UCI.

**Comment by jrjohnson** [comment]
> The materials with the lowest value would appear first 

Should that read **highest value first**?

**Comment by saschaben** [comment]
Here's how this goes:

1) allow for learning material list to be column sorted, _à la_ sessions;
2) default sort is: most recently added (top of list) to least recently added;
3) add the sort order value attribute to API and schema and frontend list;
4) sort order goes from 1 (top of display list in event detail) to _n_, where _n_ = the total number of LMs in the list.
