### ISSUE TITLE
Hard Refresh Should Not Be Needed After Offering Date/Time Change

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1276]
It has been reported and we have successfully repeated that when you change a date or time of an offering, the date/time of the offering does not refresh to reflect the change in the session list.

**Comment by dartajax** [comment]
It still contains the previous value until the screen is refreshed / reloaded.

**Comment by dartajax** [comment]
![image](https://cloud.githubusercontent.com/assets/7493331/11968823/2a99134c-a8c5-11e5-8499-63a5a303017e.png)

I changed it to 6/9/2015 same time and then came back to the session list and found ...


![image](https://cloud.githubusercontent.com/assets/7493331/11968841/76092e0c-a8c5-11e5-93f2-e6ad5e649a38.png)

but in the offering detail ...

![image](https://cloud.githubusercontent.com/assets/7493331/11968852/88398bda-a8c5-11e5-8e6e-f37ce0c4e5a6.png)

**Comment by saschaben** [comment]
this one is starting to get troublesome for the users.
