### ISSUE TITLE
Teaching Reminder Emails Are Off Because of the UTC Time Zone Issue

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1277]
Here is the reminder I rcvd ..
__________________________________________
Dear David Leonard:

This message is a reminder for your upcoming Lecture in this School of Medicine course.

Course:   test -FOR TRACKING ONLY DO NOT USE
Session:  Test Session for the 28th
Date:     Tue Dec 29, 2015
Time:     01:00 am - 05:00 am
Location: board room

The learner groups participating in this session are:

The learners participating in this session are:

The learning objectives listed for this session are:

The learning objectives listed for this course are:
- this is an objective

For a complete review of the session details and its associated learning materials, visit the session details on your Ilios Calendar at https://curriculum.ucsf.edu/courses/855.

If you would like to edit the details of this session and do not have editing rights in Ilios for this course please contact the School of Medicine's Curriculum Coordinator at irocket@ucsf.edu.

A description of most classrooms, including maps, can be found at: http://edtech.ucsf.edu/classroom-services/scheduling/classroom-features
_____________________________________________________

This would be fine except for the fact that the session offering I was supposed to be reminded to teach actually occurs at 5pm on the previous day - 8 hours earlier (UTC - current time zone).

![image](https://cloud.githubusercontent.com/assets/7493331/11968894/6a7f89c2-a8c6-11e5-9f78-6b9a263ea93d.png)

**Comment by stopfstedt** [comment]
totally not a frontend issue. please move this into the backend queue. thanks!

**Comment by dartajax** [comment]
okay
