### ISSUE TITLE
iCal feed is broken

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#1278]
generates an error when atteempting to import it into gcal; downloading the ics file and parsing it shows the following at the end of the file:

```
CATEGORIES:laboratory
DTSTAMP:20151223T002809Z
END:VEVENT
END:VCALENDAR<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <title>An Error Occurred: Internal Server Error</title>
    </head>
    <body>
        <h1>Oops! An Error Occurred</h1>
        <h2>The server returned a "500 Internal Server Error".</h2>

        <div>
            Something is broken. Please let us know what you were doing when this error occurred.
            We will fix it as soon as possible. Sorry for any inconvenience caused.
        </div>
    </body>
</html>
```

**Comment by dartajax** [comment]
The ILM's don't show up correctly.

See screen shots.

![image](https://cloud.githubusercontent.com/assets/7493331/11969605/d0c442d6-a8d0-11e5-9909-78e4c074afa4.png)

![image](https://cloud.githubusercontent.com/assets/7493331/11969606/e00a1572-a8d0-11e5-969b-1999f1db1ec0.png)

**Comment by stopfstedt** [comment]
@dartajax two separate issues. please break this out into two tickets. thanks!
