### ISSUE TITLE
Adding Learner Group to ILM Sessions Raises Error For SOP User

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1281]
The save does get completed upon refreshing the screen however.

I did not have the same issue.

The user has user_role values of 1,2,3 and did not have any entries in the "permission" table.

**Comment by dartajax** [comment]
If the save itself succeeded then we will need to look for the front-end error in the API logs.  It is probably a coding issue there as opposed to a permissions issue on the API.  I'm guessing an attempt to double save when permissions only allow most users to save on one side of the relationship.

**Comment by saschaben** [comment]
I believe this has been resolved with the work done by @stopfstedt  on the voters. Closing.
