### ISSUE TITLE
Learner Group Management Displays Inactive Accounts

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1282]
![image](https://cloud.githubusercontent.com/assets/7493331/11983665/f80e2f0c-a969-11e5-93b7-4071d6bc468d.png)

![image](https://cloud.githubusercontent.com/assets/7493331/11983675/131671ba-a96a-11e5-873c-d1dd6c7d375d.png)

In this case, it is clear which one is the correct one since there are bogus email accounts for the two wrong accounts but they also are disabled if you look them up in the user table.

**Comment by dartajax** [comment]
The inactive accounts should show up greyed out.

**Comment by dartajax** [comment]
It also wouldn't hurt if there were more information available in the Learner Group Management so the user could see email addr - stuff like that.

**Comment by saschaben** [comment]
Hover should provide email/campus id. That was existing functionality.

**Comment by dartajax** [comment]
That would probably do it - not working though.  Another issue?

**Comment by saschaben** [comment]
@dartajax please create another ticket for that.
