### ISSUE TITLE
not all calendar events displaying in month view for FF 42+

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#1286]
the scroll for the daily box in month view is not allowing full viewing of the list of events for a given day in FF 42 and above.

we currently address this with a `padding-bottom` value for the class in css;
```
ilios-calendar .ilios-calendar-month .el-calendar .day .events {
    height: 7rem;
    overflow-y: auto;
    padding-bottom: 4rem;
```
 this still works fine for chrome and safari.

**Comment by saschaben** [comment]
This looks like something FF is doing with rendering that might be a flexbox thing, but: it can be corrected by adding paragrf tags and non-breaking space at the close of the div. I'm guessing that FF now is ignoring the padding-bottom tag if it causes the  inner/outer containers to  have mismatched size values (as with the calendar days in the month grid).

**Comment by saschaben** [comment]
This appears to be related to the way we are nesting  / setting the `height` value for this entity; chrome reads the height assignment differently than FF. To test: open a month view in both browsers, find a day with a significant overflow stack of events (eg April 12, 2016), and see the difference in rendering when the height is set to 7rem, 3rem, or 12rem.

**Comment by jrjohnson** [comment]
@saschaben  Microsoft outlook handles this by only showing events that fit and then putting a down triangle which when clicked goes to the day view.  Any interest in going that route?
<img width="141" alt="screen shot 2016-03-23 at 11 05 12 pm" src="https://cloud.githubusercontent.com/assets/349624/14009701/db7811c6-f14b-11e5-8778-e95fe7b50102.png">

**Comment by saschaben** [comment]
Instead of default scroll? I'm fine with this, but I'm not clear on how it resolves the display bug.

**Comment by jrjohnson** [comment]
There would no longer be a scroll.  Instead just the first couple of events would show up and then if there were more there would be an arrow to indicate that and clicking the error would take you to the day view.

**Comment by jrjohnson** [comment]
Decision: Display as many events as will fit and show the down arrow indicator if there are more.  This is going to need to be fixed in the calendar or maybe the addon so moved this to ilios/calendar#47
