### ISSUE TITLE
publish is broken

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#1287]
- [ ] Course publish is totally borked
- [ ] Individual Session publish is totally borked 
- [ ] Publish All session publish is partially borked.

1.  when course publish is activated, we post to publish_event incorrectly, setting a table_name value of “new” rather than “course” and a table_row_id of ‘0’. In turn, the publish event id does NOT get set into the course table, and the course, while not erroring during the process, silently fails and gives a false success response.

This, btw, is not affecting processing of the `publish_as_tbd` flag.
 
2. The same issue is occurring with individual session publish actions. 

3. On Publish All actions, sessions do get published, and the `publish_event_id` is getting set on the session table row, BUT the values are entered into the publish_event table as `table_name = "new"` , `table_row_id = 0`. So it's only partially busted, and the broken bits are not immediately visible to users (but will throw the data consistency all to hell if anyone unpublishes anything, ever).

**Comment by jrjohnson** [comment]
Fixed in #1288
