### ISSUE TITLE
Add update alert icon to calendar events that have recently been updated

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#1299]
this was existing functionality in 2.4; for any event with changes logged in the prior _n_ days (_n_ being configurable, default = 5), the alert icon will appear in the calendar (upper corner for month/day/week views). We should add it as well to the event view (on the items/categories updated), as well as to the event list view.

icon:  `fa-exclamation` or `fa-exclamation-circle`; color=red

Items which trigger the alert:

- change to start time
- change to end time
- change to location
- change to instructor
- change to objectives 
- change to learning materials 
- change to description

**Comment by jrjohnson** [comment]
We're passing a last update time stamp with the user and school events.  So this should be a simple calculation to see if that timestamp is in the last 5 days.  Where is this configurable?  For the school or for the user?  Is that a requirement or an additional feature?

**Comment by saschaben** [comment]
Previously this was part of the ilios.config at the school level. if we can't do that easily, let's just burn it in at five days, an worry about flexibility later.

**Comment by jrjohnson** [comment]
We have a method for passing config to the client, but it really needs to be wrapped in a better implementation.  That can happen as part of this ticket, or separately, I just wanted to make the requirements clear.

**Comment by saschaben** [comment]
we need something to indicate for "not published" status as well.
