### ISSUE TITLE
Handle missing data in scheduled events for students

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#1300]
As of ilios/ilios#1243 students will not see offering or ilmSession details in scheduled events.  This needs to be accounted for in the frontend.

**Comment by stopfstedt** [comment]
i thought we handled this one already. can this be closed?

**Comment by stopfstedt** [comment]
^ @saschaben @jrjohnson

**Comment by jrjohnson** [comment]
Yes, fixed in #1313
