### ISSUE TITLE
Calendar blocks/mouseover popups do not display enough info

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#1301]
right now we are only displaying time, session title and location:

![ilios 2016-01-06 14-25-58](https://cloud.githubusercontent.com/assets/1753431/12156701/72c69cda-b481-11e5-9fa8-92978cb0d6ee.png)

In order for viewers to have more context, we should also be displaying instructor and course:

![ilios 2016-01-06 14-25-58](https://cloud.githubusercontent.com/assets/1753431/12156918/ac7dcfd8-b482-11e5-8f56-eb8a5267aab5.png)

This should be replicated in the tooltip popup

**Comment by stopfstedt** [comment]
needs to be fixed in ilios-calendar project. working on it.

**Comment by stopfstedt** [comment]
per an earlier conversation - we have to limit the number of instructors shown.

solution: truncate instructor lists after two elements and suffix it "et. al."
