### ISSUE TITLE
Calendar filters do not reflect full user school associations

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#1305]
The calendar filters, when set to "My calendar", show only the options for a user's primary school. This means that they can't actually use them for their schedule if they are associated with events from other schools. fer instance, if I am taking SOM and SOP courses, but am a SOM primary student, then my filters will only show courses from SOM, and cohorts from SOM, etc. No way to filter my SOP events. I have to turn on "all events" and work backwards from the full curriculum.

The filters should be cognizant of a users affiliations, and provide full contexts for each category according to those affiliations. Or we need to provide a school switcher all the time.

**Comment by jrjohnson** [comment]
Fixed in #3725
