### ISSUE TITLE
Offerings group selector is buggy

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#1311]
When selecting groups for offering assignment:

- the "groups available for selection" list does not visually match the "groups already selected" list.
   - group trees given as name values on the "available" list are the complete (correct) trees, those on the left ("selected") are not, as they are missing their parent tree name values:

![item1](https://cloud.githubusercontent.com/assets/1753431/12245713/1911a234-b85f-11e5-8fe9-21562a2bc1df.png)

- On initial load of the page, the "groups available" list does not exclude the groups already selected and  displayed in the selected list, making for both user confusion and an inability to de-select groups for edit.

![ilios 2016-01-11 12-23-01](https://cloud.githubusercontent.com/assets/1753431/12245622/9145c20e-b85e-11e5-8b7d-6dc25c87383e.png)

....but after a single click in the right side "available" list, the view corrects itself, and editing is possible:

![afterclick](https://cloud.githubusercontent.com/assets/1753431/12245670/d687b926-b85e-11e5-8116-3b9dccb830ba.png)

**Comment by saschaben** [comment]
one option is to replace this pattern with that in the ILM:

![ilm-lg](https://cloud.githubusercontent.com/assets/1753431/14619031/64f7f740-056a-11e6-889b-f7fc115ffdbe.png)

But here as well, we are missing the top level cohort identification info on our badges: this is noted in #1611 and should be addressed along with this ticket.

**Comment by jrjohnson** [comment]
Needs #1775 first to make it easier to cleanup display.

**Comment by saschaben** [comment]
refs also #866
