### ISSUE TITLE
truncate session list to improve load time

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#1317]
instead of loading all sessions for a course, limit initial load to 50 sessions, and provide a "load more sessions" button at the bottom of the list to load the remainder. Button should be labeled "Show XX More Sessions"

And now that we have column sorting, initial sort on load should be date ascending if at all possible.

![sessionlist](https://cloud.githubusercontent.com/assets/1753431/12282016/c10c1a82-b94f-11e5-846e-1c9bff2d4a13.png)

**Comment by jrjohnson** [comment]
While some filtering against the server is possible we will loose sorting on sessionType, firstOffering, and offering count.  These are too complex to handle in the query to the API.  We can either 
1) sort only on sessions already loaded or 
2) force the whole list to load before we allow any sorting.

@saschaben I think we decided on an approach to this in person, but I didn't write it down, do you recall the solution?

**Comment by saschaben** [comment]
@jrjohnson blurg. I'm not sure we settled on one or the other. sorting on only loaded sessions could lead to mistakes not realizing other sessions are extant -- duplication replication, angry calls to support of "where'd my session go?"; forcing the whole list means that we will get the "I can't sort any more" calls.

I think forcing the load in the end is the better choice: we can call the load action with both the "load more sessions" action as well as with the firing of any of the sort requests.

Does that make sense?

**Comment by jrjohnson** [comment]
Next problem.  We cannot get a count of all of the sessions in a course without loading them.  We present this count in two places - as Sessions(42) and also in the publish all button.  An easy solution is to remove those counts a more difficult path is to change the API to send the length of the sessions as metadata with any course request.

@saschaben / @stopfstedt thoughts?

**Comment by saschaben** [comment]
Easy solution === very bad solution. If we are going to not display all sessions on load then it is even more critical that we correctly and swiftly load the count for the users.
