### ISSUE TITLE
Add Taxonomies to extend topic tags

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#1318]
See Ilios/Ilios#1257.

Extend the current topic manager to provide for additional complex taxonomies of tagging.

**Comment by saschaben** [comment]
DUE BY 4 MARCH 2016

**Comment by stopfstedt** [comment]
regarding: **linking taxonomies across schools.** 

in Ilios2, the scope for selectable topics was set by the _currently set school_ (via the "school switcher") in the user's session. 
That concept of current school has gone away in Ilios3.
We need an alternative means of determining which taxonomies are eligible for assignment to courses/sessions in Ilios3.

Here is what I remember from previous conversations.

1. taxonomies belonging to the course's owning school will _always_ be available.
2. if a cohort from another school has been linked to the given course, all taxonomies from that cohort's owning school will become available for selection as well.

Example:

1. Course A is owned by School of Medicine. All taxonomies (vocabs/terms) owned by School of Medicine are eligible for assignment to this course.
2. Course B is owned by School of Medicine, and has Cohorts from School of Pharmacy and School of Dentistry assigned to it. Therefore, all taxonomies owned by these three schools can be assigned to this course.

@saschaben please confirm/debunk/correct my assumptions stated above. Thank you.

**Comment by saschaben** [comment]
@stopfstedt please see my notes above.

**Comment by stopfstedt** [comment]
thanks for the feedback. exposure of taxonomies to students via calendar events is a different, but related can of worms, good to have some of the access permissions penned down here.
