### ISSUE TITLE
ILMs do not display enough info on calendar

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#1320]
see also #1301.

Along with the additional info (course, instructor) from #1301, ILMs should be identified with some flag (icon?) to show that regardless of session type assigned, they are an independent learning activity.

**Comment by jrjohnson** [comment]
They are currently prefixed with `ILM:`

**Comment by stopfstedt** [comment]
ideas for visually setting them apart from offerings-based events:

- different border styles (perhaps thicker)
- different background color that is not in-use by 'regular' events
- said image/icon indicator

**Comment by saschaben** [comment]
@stopfstedt bg color is not an option, as ILMs should carry the color of whatever session type gets assigned to them (none/independent learning = white, lecture = green, etc); border styles/icons I think are the right approach.

**Comment by saschaben** [comment]
@jrjohnson this is primarily about the calendar grid display, where we currently do not provide a marker for session type or ILM (other than color). we do prefix ILM for the event detail page, so that is not really in question for the moment.

**Comment by jrjohnson** [comment]
Oh - I thought we prefixed ILM on the calendar grid as well.

**Comment by stopfstedt** [comment]
in any case, we'll need to be able to set a class on the event's container div that carries the information that this is an ILM, e.g. `is-ilm`, so we can hang styles off of that.
