### ISSUE TITLE
Multiple Sets of Small Groups Only Display One Set In Week and Month Calendar View - Day View is OK

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1329]
https://ilios-stage.ucsf.edu/courses/789/sessions/22783

Check out the session above on March 4, 2016.  Check the Day View and notice there are two groups of small groups.

Week view 

![image](https://cloud.githubusercontent.com/assets/7493331/12369715/87d9d43e-bbb1-11e5-95c0-c93c995068f8.png)

Day view 

![image](https://cloud.githubusercontent.com/assets/7493331/12369723/9fdf000e-bbb1-11e5-8211-823769e46ba9.png)

Month view 

![image](https://cloud.githubusercontent.com/assets/7493331/12369728/b7133c54-bbb1-11e5-896f-45e8838ab459.png)

Courses and Sessions view 

![image](https://cloud.githubusercontent.com/assets/7493331/12369739/eda91090-bbb1-11e5-862a-09d6e4969515.png)

Note that there were 20 offerings initially.  One of the 10-12 ones was deleted for testing purposes to see if the changes would force both to be displayed.  Also, whichever one of the two sets that is updated most recently will be the one that shows up on the Calendar.

**Comment by stopfstedt** [comment]
_only_ occurs on school events, not user events.

**Comment by stopfstedt** [comment]
found the problem. in school-view, we only render one event per session in week/month view.

see `dashboard-calendar.js` ,`ourEvents()` function. working on it ...
