### ISSUE TITLE
navigation from page has significant delays

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#1331]
When navigating away from certain pages, there is a major delay in action. In order of slowness:

1. from the dashboard to anywhere when calendar filters are OPEN.
2. From Session to anywhere when Offering edit is OPEN.
3. From Session to anywhere.
4. From course when course details are fully expanded.

Items 3 & 4 are not significantly ugly in normal use, but items 1 & 2 are. These may be one of the primary causes of current difficulties with performance.

**Comment by jrjohnson** [comment]
It looks to me like the complexity of the courses page with a session open is the primary cause of the delay navigating away from it.  We may be able to code our way out of some of this by restructuring the page substantially, but it will be a lot of work.  I think getting up to a current version of ember will give us more performance gain than anything else.  Browsers are also working on this internally and will likely show ongoing improvements.

I think the best bet to make navigating away from sessions fast is probably #425 - should we start working on that?
