### ISSUE TITLE
Event Detail Page Needs Loading indicator(s)

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#1338]
This should be dealt with in conjunction with #877. With both issues unaddressed, usability is a major issue. With only one or the other addressed, the problem of users not  knowing when the load of the page is complete is a problem.

Needs to be replicated in ilios/calendar as well.

**Comment by jrjohnson** [comment]
This should be addressed entirely in ilios/calendar.  It is already expecting promises for these values so we just need an indication of loading.
