### ISSUE TITLE
Draft Status Learning Materials Are Not Being Hidden From Learners

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1342]
1.

See the second learning material has been saved as Draft -- Logged in as me.
![image](https://cloud.githubusercontent.com/assets/7493331/12437236/f8e1b756-bed0-11e5-9e5d-256b070388a1.png)

2.

Spoofing a student ...

![image](https://cloud.githubusercontent.com/assets/7493331/12437221/dab9be54-bed0-11e5-8971-abc816197b28.png)

**Comment by dartajax** [comment]
In situation two, the Winter 2016 Pulmonary Syllabus should not be showing up since it is in Draft status.

**Comment by jrjohnson** [comment]
@stopfstedt I assigned this to you as I think it probably needs a combination of API voters and frontend changes.
