### ISSUE TITLE
improve calendar navigation

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#1345]
replace the current `fa-angle-left` and `fa-angle-right` icons used to navigate the calendar with `fa-backward` and `fa-forward`. This will provide a much better user experience. example:

![backforth](https://cloud.githubusercontent.com/assets/1753431/12457603/46511a70-bf5a-11e5-8f54-3e8b056030cf.png)

**Comment by stopfstedt** [comment]
wrong project. this needs to be filed in ilios/calendar.

moving it...

**Comment by stopfstedt** [comment]
duplicated by ilios/calendar#24
