### ISSUE TITLE
Add "DRAFT" marker to events in unpublished state on the calendar

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#1347]
Provide a draft icon on the calendar to allow faculty to differentiate publish status. I suggest the `fa-files-o` set at top of box:

![icon1](https://cloud.githubusercontent.com/assets/1753431/12494188/b1785d02-c03d-11e5-85e8-3637d65f404b.png)
![icon2](https://cloud.githubusercontent.com/assets/1753431/12494193/b369bd22-c03d-11e5-9e6b-4d8b91378288.png)

This is in conjunction with #1299.

**Comment by stopfstedt** [comment]
wrong issue queue. closed in favour of ilios/calendar#1347
