### ISSUE TITLE
Janky course topic function

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#135]
Rapid adding and removing of topics causes the topics list to unload and an error to be thrown which causes further navigation or page action to fail. See also #134, #133, #129.

**Comment by saschaben** [comment]
OK -- updates to  #133 and #134 and #129 clear the issue of further navigation / page action failure: yay!

But the basic janky issue with the topics selection and list display remains: boo! same error gets thrown: 
![ilios 2015-02-17 12-46-08](https://cloud.githubusercontent.com/assets/1753431/6236855/f9ed7694-b6a2-11e4-8460-6e6712f49964.png)

**Comment by jrjohnson** [comment]
Fix: Handle saves when they happen repeatedly and asynchronously.
