### ISSUE TITLE
replace JSLint with ESLint

### ISSUE THREAD

**Issue by stopfstedt** [ilios/frontend#1363]
http://www.sitepoint.com/comparison-javascript-linting-tools/
https://github.com/eslint/eslint
http://eslint.org/docs/

**Comment by stopfstedt** [comment]
this would allow us to set more fine-grained rules re: indentation 

http://eslint.org/docs/rules/indent

**Comment by jrjohnson** [comment]
If we are going to do a cleanup I think we should add https://github.com/dockyard/ember-suave it takes care of lots of standardization stuff outside of simple linting.

**Comment by stopfstedt** [comment]
closed and rejected in favour of eslint.

**Comment by Trott** [comment]
What needs to happen next on this?
