### ISSUE TITLE
<P></P> Tags are Showing Up In Select Parent Objective

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1367]
This is not a super priority I would imagine but it is something we should fix I believe.  See below.

![image](https://cloud.githubusercontent.com/assets/7493331/12685888/98778f82-c67b-11e5-9748-549914b83ea3.png)

![image](https://cloud.githubusercontent.com/assets/7493331/12685915/b218ce10-c67b-11e5-81f4-311d510ad9e5.png)

![image](https://cloud.githubusercontent.com/assets/7493331/12685922/c258e88c-c67b-11e5-841b-5b1ec7b49d2b.png)

![image](https://cloud.githubusercontent.com/assets/7493331/12685942/da6ab270-c67b-11e5-9151-ec1ace6924a4.png)

I added this parent objective to our test cohort Class of 2010.

**Comment by jrjohnson** [comment]
fixed already.
