### ISSUE TITLE
clean up session listing controls

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#1370]
here's what we have:

![as-is](https://cloud.githubusercontent.com/assets/1753431/12733124/ea40427c-c8ed-11e5-9711-8cf719f4cf6d.png)

here' what would look a little better, adding 0.75em padding to the `clickable is-clickable` element:
![to-be](https://cloud.githubusercontent.com/assets/1753431/12733126/f2668d4e-c8ed-11e5-8abb-e943a9d933cb.png)

**Comment by jrjohnson** [comment]
Looks good - in case someone else gets to this make sure to add a custom class to these arrows and add padding to that.  Changing 'clickable is-clickable' would break a lot of other content.
