### ISSUE TITLE
allow for timed release of learning materials

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#1376]
this would allow items to be displayed or not to students on a strict time basis:

![newlmtime](https://cloud.githubusercontent.com/assets/1753431/26743095/69bbcf54-4795-11e7-8348-ceb8bf4381ec.png)

Note that this is immplemented on the LM association to a course/session; not on the parent file itself.

This enhancement would require modification to the schema; modification to the API, modification to the LM management panel, and modification to the calendar event detail view. Sibling tickets should be entered in https://github.com/ilios/ilios and https://github.com/ilios/calendar to address.

**Comment by dartajax** [comment]
I moved it over to Ready since we were discussing this today.

**Comment by saschaben** [comment]
As a priority for Vanderbilt (and other schools), we should move this forward.

**Comment by saschaben** [comment]
Q: need to determine how this will look in event detail pages, material lists, etc. Is an unreleased file invisible? Visible but without link? Shown as "File for timed release ([start date/time])"?.....

**Comment by saschaben** [comment]
Proposed display for timed release:

In all locations, and for all users, the following display value
- LM Display Name (eg "Title")
- Release Date
- Release Time

If end time is NOT set for LM (this is the default)

**_Example file: Short Sheet_** _(Timed Release: Available after **[Date] [Time]**)_ 

-for Materials listing, once release time is reached, links would be active and other descriptive info (description/notes) would be shown.

If and END time is set for LM

**_Example file: Short Sheet_** _(Timed Release: Available **[Date] [Time]** - **[Date] [Time]**  only)_ 

-for Materials listing, if end time is set, once release time is reached, links would be active and other descriptive info (description/notes) would be shown, but view would revert to the above in ALL locations after end time.

**Comment by saschaben** [comment]
companion ticket to  https://github.com/ilios/ilios/issues/1908

**Comment by saschaben** [comment]
completed in 3.38
