### ISSUE TITLE
Default display sort order of Learning Materials is incorrect

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#1377]
Right now, on the calendar detail view page, learning materials are ordered by id only. The correct sort order here should be `ORDER BY is_required, title`. 

This is actually a 2.4 regression.

**Comment by stopfstedt** [comment]
@saschaben i take it you want required LMs to be shown before not-required ones? please confirm, thanks.

**Comment by saschaben** [comment]
@stopfstedt yes: first required, then not required. sorted by title A-Z rather than id.

**Comment by stopfstedt** [comment]
closed via ilios/calendar#39.
