### ISSUE TITLE
User Suggested Changes to Event Detail

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1378]
See the screen shot for details - I think the ideas were good ones.

![session_detail](https://cloud.githubusercontent.com/assets/7493331/12797642/c9dedace-ca79-11e5-9696-ae74354f2bd5.jpg)

**Comment by jrjohnson** [comment]
I'm 99% certain that we arrived at this display on purpose.  Maybe @saschaben recalls why?  It would be easier to display this page in the way @dartajax has suggested and remove some awkward translation stuff.  If we can remove 'Taught by '  as well that would be great.

**Comment by saschaben** [comment]
Once upon a time, this was driven by user and student feedback. I think that with 6 years passage, we can look at making these modifications in light of new user input.

**Comment by jrjohnson** [comment]
Group discussion - we're going to go ahead with these changes as is.
