### ISSUE TITLE
Add quick copy functionality for LM file links

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#1379]
once a learning material is saved, we should provide the permalink that is generated so that faculty can plug it in as a link in the CLE, etc.

![perma](https://cloud.githubusercontent.com/assets/1753431/12806229/e921617e-cab8-11e5-9905-8aecc70dda85.png)

**Comment by jrjohnson** [comment]
This mock doesn't really make sense as it is the form for saving a learning material.  The link should probably go where [file] is in the table.  Or else on the edit page when clicking on a saved learning material.

**Comment by jrjohnson** [comment]
Actually the link already appears on the edit page, do we want it somewhere else?:
<img width="376" alt="screen shot 2016-02-03 at 8 47 27 pm" src="https://cloud.githubusercontent.com/assets/349624/12806051/5161710e-cab7-11e5-8127-8bff80f7e90c.png">

**Comment by saschaben** [comment]
@jrjohnson right on the first count: I grabbed the wrong screenshot to present the permalink. On the second: right again! but we don't make it at all clear to users that they can use this link outside of the application (in earlier versions, they could not). So prolly what we need is just an explicit "copy permalink" button added next to the link shown -- like we do for the calendar URL -- and add some instruction to the guides.

**Comment by saschaben** [comment]
![perma](https://cloud.githubusercontent.com/assets/1753431/12806229/e921617e-cab8-11e5-9905-8aecc70dda85.png)
