### ISSUE TITLE
Add objective mesh picker to course details

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#138]
We need a generic mesh attachment component that will work for course objective and for other areas where this relationship is created.  It should be based on the course objective manager.

Implement it initially when you click 'Add New' under Mesh Terms on course objectives.

@jenzweben - can you provide the mock for this?  Please work with @saschaben to identify any rules for associating mesh terms to a course objectives (many, just one) and how they might be different for session objectives or program objectives.

**Comment by jenzweben** [comment]
@saschaben this is what I'm thinking - if a user clicks on "Add New" in the MeSH column for an existing Objective, we would expand down and display the MeSH picker...

If you like it, please assign to JJ if not, let's discuss.  

![course-detail-add-mesh-objective](https://cloud.githubusercontent.com/assets/5023894/6273727/813a2410-b826-11e4-8968-0e3afcf67158.png)

**Comment by saschaben** [comment]
works for me. I'm a big fan of an accordion expansion below the active content for this sort of action.

Make it so.

**Comment by jrjohnson** [comment]
How can you tell what objective you are adding that term to?  What does it look like when there are already 2-3 terms selected?  How would I remove a term I had already selected.
