### ISSUE TITLE
add title attributes to all icons in use

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#1389]
for clarity and accessibility conformance, all icons should get a title attribute:

calendar alert icon: `title="recently updated"`

> FR: `récemment mis à jour`

calendar draft icon: `title="draft"`

> FR: `avant-projet`

big blue plus sign: `title="add new"`

> FR: `Ajouté Neuf`

edit icon: `'title="edit"`

> FR: `modifier`

trash can: `title="delete"`

> FR: `supprimer`

session list eyeball: `title="quick view"`

> FR: `aperçu rapide`

Learning materials notes eyeball: `title="show to students"`

> FR: `Affichage aux étudiants`

objective collapser: `title="expand/collapse"`

> FR: `agrandir / réduire`

**Comment by jrjohnson** [comment]
If @dartajax and @saschaben add translations to this issue it will simplify the implementation a lot.

**Comment by stopfstedt** [comment]
https://github.com/martndemus/ember-cli-font-awesome#title-attribute

**Comment by jrjohnson** [comment]
should be done like `{{fa-icon title=(t 'general.title')}}`
