### ISSUE TITLE
Title Should Appear In Add MeSH for Session Objective

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1392]
See the screen shots ....

![image](https://cloud.githubusercontent.com/assets/7493331/12900590/0846f990-ce6c-11e5-8acc-538fe0b9e330.png)

see below - - which of the session objectives is it that the MeSH term is being added to -- we should have the objective title here 

![image](https://cloud.githubusercontent.com/assets/7493331/12900646/3ff66768-ce6c-11e5-9e0f-592877653ffa.png)

**Comment by stopfstedt** [comment]
objectives are problematic. 

1. they don't have a title, only a description. they tend to run long, so appending them to the mesh picker dialog title will break layout in many cases.

2. that description can contain markup, so injecting _that_ into a headline tag will blow layout up as well.
stripping tags from the objective descriptions may have undesired effects as well (e.g list items will be rolled up into nonsense).

in sum - we're better off without that IMO.
