### ISSUE TITLE
yes/no buttons get "stuck"

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1394]
Click as shown below on the Right Side of the Toggle switch.

![image](https://cloud.githubusercontent.com/assets/7493331/12903024/800d30b8-ce79-11e5-9d58-14cd8f224964.png)

It works as it should usually.  Sometimes the first click fails but in general, clicking on the right side of the toggle does function.  The screen changes as shown below.

![image](https://cloud.githubusercontent.com/assets/7493331/12903082/d7b36706-ce79-11e5-8329-16ed07641a99.png)

Now click on the Left Side of the Toggle switch as shown below and verify that nothing happens.

![image](https://cloud.githubusercontent.com/assets/7493331/12903134/31ccc71e-ce7a-11e5-9134-aaa6278a92d2.png)

**Comment by stopfstedt** [comment]
i verified that clicking the yes/no toggle _always_ fires the underlying action. however, the display only gets updated inconsistently.

**Comment by stopfstedt** [comment]
click click clickity click CLICK. seems to get randomly stuck in the current position. moving the mouse and clicking elsewhere in the control knocks it lose again, most of the time.
verified in latest FF and Chrome.

**Comment by stopfstedt** [comment]
since the JS/event handling seems to work reliably, i'm starting to think that this may be an issue with the CSS transitions. will take a stab at it and see if taking these out will fix the problem.
