### ISSUE TITLE
Course title only editable when edit pane is open

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#140]
Fix:  Enforce isEditing boolean on the course-header component.

Right now the title is editable all over the place.  Basically any time it is on the screen.  I don't think it would make visual sense to have to open the View All / Edit expander to edit it on the course page.  However I think we should turn off editing any time it is on another page (like manager objectives, or session details).

@jenzweben - Does that make sense?  Or should we make it only editable when the collapsed edit pane is open?  Or always editable like it is now?

**Comment by jenzweben** [comment]
I think it makes sense for the title to be editable only when edit pane is open.

**Comment by jrjohnson** [comment]
@saschaben  decided when the edit pane is open you can edit things.  Then End.
