### ISSUE TITLE
Froala Editor Is Removing Blank Spaces Strangely

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1421]
see the screen shots for reference 

This is a Session Objective ...

https://curriculum.ucsf.edu/courses/941/sessions/26953?sessionObjectiveDetails=true

![image](https://cloud.githubusercontent.com/assets/7493331/13190777/228a7e16-d714-11e5-9336-c7c2801335f3.png)

![image](https://cloud.githubusercontent.com/assets/7493331/13190787/3b9d6954-d714-11e5-811e-cdc78579656b.png)

Click Cancel and then it is back to normal with the space between "Understand" and "one" returned.

**Comment by saschaben** [comment]
I suspect this is due to how it is handling the difference between
"Understand one..."
and 
"`Understand&nbsp;one...`"

**Comment by jrjohnson** [comment]
Yea or `understand\x\0one...`

**Comment by stopfstedt** [comment]
backend issue. create another migration for massaging objectives. replace all remaining non-regular spaces (see comments above) with standard blank spaces.
ticket to come...

**Comment by dartajax** [comment]
This has been fixed.
