### ISSUE TITLE
Activate add new learning material action

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#143]
What happens when a user clicks add new on a course learning material?

@jenzweben please provide your mock for this action.

**Comment by jenzweben** [comment]
![learning-materials-upload-file-v3](https://cloud.githubusercontent.com/assets/5023894/6235570/470aa060-b698-11e4-8704-bca45a3bac35.png)

**Comment by jenzweben** [comment]
![learning-materials-upload-file-v2](https://cloud.githubusercontent.com/assets/5023894/6235592/6dfb4260-b698-11e4-8e74-8f799f507924.png)

**Comment by jenzweben** [comment]
Step 1

**Comment by jenzweben** [comment]
Step 1 
![learning-materials-upload-file-v3](https://cloud.githubusercontent.com/assets/5023894/6235668/f4a00e90-b698-11e4-926d-a0360b5486c2.png)

**Comment by jenzweben** [comment]
Step 2
![learning-materials-details-upload-v3](https://cloud.githubusercontent.com/assets/5023894/6235678/00d465bc-b699-11e4-9c10-67c484fdcb26.png)
