### ISSUE TITLE
Default Location and Instructors Not Working Properly

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1435]
The first thing I am doing here is setting the Learner Group to have a default instructor and default location.

![image](https://cloud.githubusercontent.com/assets/7493331/13294734/37f58524-dada-11e5-9744-3fbddeba2b12.png)

Then I went and added this Learner Group to a Session Offering.  There is no problem here.  The correct default Instructor and Location were picked up from the Session Offering.

https://ilios-stage.ucsf.edu/courses/802/sessions/23602

![image](https://cloud.githubusercontent.com/assets/7493331/13294813/a8e36a12-dada-11e5-9bd2-c3ccb26748a0.png)

So, I deleted the default Instructor and Location and created a new Session Offering with Anatomy Lab 1 only attached and got the following ...

![image](https://cloud.githubusercontent.com/assets/7493331/13295073/effcf39a-dadb-11e5-84c5-6e8617891a29.png)

Shouldn't it pick up the default Location and Instructors from the Learner Group assignment that I showed at the top of the ticket?  I don't think this is the exact bug that was reported but I wanted to point it out anyway as I try and root out to see if this is the same issue.

**Comment by saschaben** [comment]
Issue: Default instructor / location values work for Small Group generation, but not for "offering" generation.

Offering should create a single offering for all groups selected, and list the default(s) for the top-level of each groupset selected.

**Comment by jrjohnson** [comment]
@dartajax can you confirm if this bug still exists using the new offering form added in #1869?

**Comment by dartajax** [comment]
I will check out that branch and test it out.

**Comment by jrjohnson** [comment]
It is merged.  So you can test in master.  It just isn't released yet.

**Comment by dartajax** [comment]
OK.  Thanks.  I will use master.

**Comment by saschaben** [comment]
the bug still exists, but @dartajax if you can identify its parameters better in the new offering tool that would be incredibly useful. I think it is actually more extensive now.

**Comment by dartajax** [comment]
@saschaben and I discussed this earlier today.  He made some valid points about why the defaults are not automatically entered when choosing "offering" rather than "small groups".  We may want to put a label in there to let the user know that the defaults will not be added.  They can go enter the location of the offering after the save event takes place.

**Comment by saschaben** [comment]
CURRENT BEHAVIOR:
regardless of situation, default instructor and default location values do not load for newly generated offerings.

DESIRED BEHAVIOR:
for SMALL GROUP GENERATION -- for each group generating an offering, if values are set for default instructor or location, those values should be set as the instructor(s) and location for the specific offering.

for OFFERING GENERATION -- for each offering generated, provide a label by the form fields for location and instructor which says "Default [instructor] | [location] will not be loaded: please enter desired value."

A future enhancement can be investigated which will allow the granular selection and insertion of default values for offering.

**Comment by saschaben** [comment]
@dartajax please add something about the above described behavior to the documentation; @jrjohnson please review offering management functionality to address and meet desired behavior.

**Comment by dartajax** [comment]
I had a thought about something that I doubt you guys are going to like but I am going to mention it anyway.  Regarding the label that @saschaben points out that is going to appear during the generation of an Offering (not Small Group), would it be possible or logical to only have the label appear when there actually is something in the database regarding default instructor or default location.  If there is no default, the label wouldn't really apply anyway and could cause some confusion.

**Comment by saschaben** [comment]
@dartajax possibly logical, probably not possible. also, that would require them to display after a selection of a group, which then gets into the whole issue we have already discussed of knowing what selection (or not) will happen before it does.

**Comment by dartajax** [comment]
I just wanted to throw it out there.  And then I started thinking about it again and realized that it is probably not advisable.  What if someone chooses a second group that does have defaults, then this label appears out of nowhere.  We have to check the whole group of groups for default and if any of them have defaults, then show the label?  Nah.

**Comment by dartajax** [comment]
I have updated the user documentation with the fact that defaults will not be applied for Location or Instructor for individual Offerings as opposed to Small Groups where they will be applied.  I took @jrjohnson off the ticket so I can create the translations for these labels.

**Comment by dartajax** [comment]
It seems that the assignment of default location and default instructor(s) is not working on small groups.  I had thought that it was working previously.  I do have a pull request to submit for the labels on the single offering in any case.

**Comment by saschaben** [comment]
@dartajax that is correct -- the continued existience of the actual issue is noted above https://github.com/ilios/frontend/issues/1435#issuecomment-236074130
