### ISSUE TITLE
Session Description Allows Saving of Blank Space and Empty Strings

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1438]
There is some strange behavior with editing session description.

Opening this one in favor of #841 which I will be closing.

If a session description has been saved, it is not possible to delete everything and save that.  See below.

Session has description -- Click on it to edit

![image](https://cloud.githubusercontent.com/assets/7493331/13304449/87fe7560-db09-11e5-9c23-4fe5d512f356.png)

![image](https://cloud.githubusercontent.com/assets/7493331/13304465/a2c35b40-db09-11e5-8392-5a23aa54806b.png)

Delete the session description and click Done.

![image](https://cloud.githubusercontent.com/assets/7493331/13304591/705dc84c-db0a-11e5-97fe-055d9da8af7e.png)

What happens is ...

Old title still there

![image](https://cloud.githubusercontent.com/assets/7493331/13304510/d4ae787e-db09-11e5-8c20-a7ff0a841cdc.png)

The bogus workaround -- put a blank space in there using the keyboard space bar.

![image](https://cloud.githubusercontent.com/assets/7493331/13304524/f25e8d96-db09-11e5-9dcf-998544e93110.png)

click done and 

..

![image](https://cloud.githubusercontent.com/assets/7493331/13304535/0338bfba-db0a-11e5-864f-279d97f5ff1f.png)

It's gone but at least with 3.x, it is possible to click to edit even though the blank space is there.  We should allow the save to revert the value of the field back to NULL.  This should have happened above where the description was deleted and the Done button was clicked.

**Comment by saschaben** [comment]
This is a menace! Allowing empty strings to be saved via the editor causes editing to become inaccessible -- since froala saves empty markup tags, which then register as data when we test for a `null` value, but cannot be displayed as an active link (cuz they have no content).

**Comment by saschaben** [comment]
See also #2072. This is definitely an issue with our implementation of Froala, which does not detect "empty" strings. In WYSIWYG mode, it is generating blank strings and `&nbsp;` nonbreaking spaces, which get read as valid, and in code mode it doesn't appear to be validating at all.
