### ISSUE TITLE
Fix adding mesh to course

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#144]
Needs:
1. Correct Translation for the search prompt
2. Fix search box style it is a little blown up
3. Add searchTerm to the mesh API like we have for users.
~~4. Style the returned results appropriatly.~~ (moved to #214)

@jenzweben please attach your mock for the add mesh on the course detail page.

**Comment by jenzweben** [comment]
![course-detail-page-editmode-publish-missing-v13](https://cloud.githubusercontent.com/assets/5023894/6235850/66b2d318-b69a-11e4-8ad3-e56b7fb1ee89.png)

**Comment by saschaben** [comment]
Search: PASS. appears to work as desired.
Cancel search: FAIL. cancel clears the search box, but does not clear/close the results box. 

Let me know if you want to merge this as is and add a bug report for cancel function, or if the cancel code is part of this PR
