### ISSUE TITLE
Close cohort picker on course details?

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#146]
Once a user clicks the add new button for course cohorts the picker will be open forever.  Do we want to provide a close option?  

We could:
a. Change the button when the picker is open - 'Close New' or whatever
b. Add a big x next to it to close it.

@jenzweben - your choice.  I can add the control and you can handle any style.

**Comment by saschaben** [comment]
"x" to close.

**Comment by jenzweben** [comment]
I like the way it behaves currently (picker closes once a user makes a selection...

**Comment by jrjohnson** [comment]
@jenzweben please work with @saschaben to mock up this again.  We need to consider closing the pane with no selection as well as the placement of the pane (above/below the list of selected cohorts)

**Comment by jenzweben** [comment]
![screen shot 2015-02-19 at 3 17 48 pm](https://cloud.githubusercontent.com/assets/5023894/6278267/82df21e8-b84a-11e4-9ac0-e2809beb9f3e.png)

**Comment by saschaben** [comment]
I think we can use a more generic message, like "Please add at least one cohort of learners" -- not sure we actually need to send them to the button so explicitly. But in any case I do like this solution: message when vacant, click to open, select to add (and auto close on add); hit close to close without adding.

**Comment by jenzweben** [comment]
Updated mock with Sascha's notes.

![screen shot 2015-02-23 at 12 39 49 pm](https://cloud.githubusercontent.com/assets/5023894/6336675/1cd1dd20-bb59-11e4-8607-f11caa5c979b.png)

**Comment by jenzweben** [comment]
![screen shot 2015-02-23 at 12 40 28 pm](https://cloud.githubusercontent.com/assets/5023894/6336680/2c92af64-bb59-11e4-8d1f-265c2ac7e897.png)

**Comment by jenzweben** [comment]
![screen shot 2015-02-23 at 12 40 57 pm](https://cloud.githubusercontent.com/assets/5023894/6336690/3eadd8ea-bb59-11e4-99ef-4f953be9e947.png)

**Comment by jrjohnson** [comment]
Went with the manager pattern from the other sections in #365
