### ISSUE TITLE
Need Validation Message If Author Is Missing Data During LM Upload

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1469]
See the screen shot below.  Clicking the Done button does nothing since Author is missing the req'd 2 char min data entry.  We need to have the message appear underneath the field as it does when the user actually gives the focus to the Author box.  Then, it works properly.  We need this validation to occur during the event that occurs when the Done button is pressed.

![image](https://cloud.githubusercontent.com/assets/7493331/13544154/cc0fdd64-e227-11e5-9eb4-8c88ac8b8e39.png)

**Comment by jrjohnson** [comment]
fixed already.
