### ISSUE TITLE
Active add new session action on course detail page

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#147]
What happens when a use clicks add new in the sessions section?

@jenzweben please provide the mock for this.  I think we should use the slide down form we are going to use on the courses list.

**Comment by jenzweben** [comment]
![session-add](https://cloud.githubusercontent.com/assets/5023894/6236788/5f5ae7e2-b6a2-11e4-9035-6c91e99904e5.png)

**Comment by jrjohnson** [comment]
@saschaben take a look at this mockup.  Which fields are *required*?  Anything not required needs to go elsewhere.  The required fields need to either:
a. have a default option
b. ask "Pick a Value..." and then not allow save with no choice.

**Comment by saschaben** [comment]
REQUIRED Fields for a session to be saved:
1. TITLE (no default value, should provide a "please type something" prompt.
2. SESSION TYPE (sigh. Default to "Lecture".) _BUT_: what happens to the default if a school changes the session type list and does not use "lecture"....?
