### ISSUE TITLE
Admin Console Total Record Count Does Not Get Updated

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1475]
See the screen shot below ...

It should be Showing 1 - 158 of 158 and not Showing 1 - 162 of 158, which is not possible mathematically.  The "162" count did not refresh.

![image](https://cloud.githubusercontent.com/assets/7493331/13617620/7d18b590-e534-11e5-9968-bf579510b5dc.png)

**Comment by saschaben** [comment]
In both these cases, the dispaly for total number of records and  values of `n of nx records` are not updating correctly after an action is complete on one or more accounts/names.
