### ISSUE TITLE
Admin Console Inconsistency - Inaccurate Limit Count

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1476]
Here is the URL

https://curriculum.ucsf.edu/admin/userupdates?limit=200&school=3

Limit = 200 

However the screen appears to be limited to 10 records but it is not.  It is showing all 53 records.

![image](https://cloud.githubusercontent.com/assets/7493331/13618564/a5f382ec-e539-11e5-9765-13f2f354d627.png)

**Comment by jrjohnson** [comment]
Mucking with the URL does cause the number of results to change but doesn't change the dropdown.  This isn't really a bug more like something that happens.
