### ISSUE TITLE
Dividing Line Missing on Course Terms

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1479]
See the screenshots.  The dividing line is initially not being displayed until you press to reveal the Terms.

![dividinglinemissing](https://cloud.githubusercontent.com/assets/7493331/13645387/a9049cc2-e5df-11e5-8076-92b94f2f99bc.jpg)

![dividinglinemissing2](https://cloud.githubusercontent.com/assets/7493331/13645395/b364c6ce-e5df-11e5-827f-e50cd093add0.jpg)

Click on Terms and ...

![image](https://cloud.githubusercontent.com/assets/7493331/13645350/76e1afbe-e5df-11e5-8f72-2a91666f6d22.png)

... it appears ...

![image](https://cloud.githubusercontent.com/assets/7493331/13645372/9396ce28-e5df-11e5-897e-b5db07dc5510.png)

... where it should have been all along.

**Comment by stopfstedt** [comment]
just checked, the line shows up on initial load (now).
