### ISSUE TITLE
Calendar Filter Settings Need to Be Retained

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1481]
I know this is part of a bigger discussion on calendar filters but I wanted to throw this in now as a reminder.

See screen shots below ...

Apply filter as shown ..
![image](https://cloud.githubusercontent.com/assets/7493331/13686568/3413330a-e6cb-11e5-8417-cdca7e83ec80.png)

Click on Calendar event to review / see details ...

![image](https://cloud.githubusercontent.com/assets/7493331/13686583/47534400-e6cb-11e5-937d-21a3edd38211.png)

Click the back button on the browser and notice the filters have been removed.

No filters anymore ...

![image](https://cloud.githubusercontent.com/assets/7493331/13686604/62cca4e2-e6cb-11e5-9541-a1170e6a3c5f.png)

**Comment by jrjohnson** [comment]
This is working, but I have no idea when it was resolved. Going to mark as closed anyway.

**Comment by dartajax** [comment]
This has not been fixed. Steps 
* Filter for All Events >> "Pathogens ..." 
* Click on a Calendared Event to go to Event Detail
* Click the Back button

Notice that the filter set in the first step has been removed.

**Comment by dartajax** [comment]
I re-tested today. It seems to be fixed. I am ready to close this ticket again.
