### ISSUE TITLE
MyReports is returning errors / incorrect results

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#1486]
When requesting courses, sessions, lms, etc. for an instructor (or vice versa)-- we need to ask for instructedCourses, instructedSessions, instructedLearningMaterials, in order to retrieve the correct outputs. right now we don't.

right now: Get all instructors for course X will fail with a 500 error.

**Comment by stopfstedt** [comment]
backend failure on user controller.
trying to filter on course bombs out.

example:
`/api/v1/users?limit=1000&filters[courses]=134`
