### ISSUE TITLE
Style for live search

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#149]
@jenzweben please look at the director search on the course detail page and recommend improvements.  Re-style to include enough space for name and email (and maybe more in the future).

Also look at the styling of searching... no results... keep typing... and see if you hate them.

**Comment by jenzweben** [comment]
@thecoolestguy or @jrjohnson can one of you add a class to the name and another to the email address so I can style them? Please re-assign this to me when you're done.  Also I think I broke the remove function (for selected Directors) by adding a class to the remove "x" icon...sorry

**Comment by thecoolestguy** [comment]
This depends on the completion of #166, will reassign when finished.

**Comment by thecoolestguy** [comment]
Was completed in #265, 
search results username wrapped in div with class 'livesearch-user-name' 
and email address wrapped in div with class 'livesearch-user-email'
