### ISSUE TITLE
Session Details Doesn't Provide Room Information For The Session Offering

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1496]
See the screenshots below -- you can see the Room # for a session from the Calendar during mouse-over hover and directly by viewing the Calendar.  This is shown by the black arrows in the screen shot below.

![image](https://cloud.githubusercontent.com/assets/7493331/13832460/8ec09dec-eb99-11e5-89d0-2f808388af76.png)

However, when the Calendar Event is clicked, the following appears ...

This is just the top part; but this is where the Room # (Location) should appear ...

![image](https://cloud.githubusercontent.com/assets/7493331/13832488/d54fb72a-eb99-11e5-9b0f-18cd8c482f48.png)

**Comment by jrjohnson** [comment]
I'm thinking it would go on the second line as:
`In: HSW 301`

Will that work in translation?  Or should we just have the room number with no preface?

**Comment by saschaben** [comment]
No prefix needed. 2nd line, right beneath date / time.

While we're at  it, date time didn't really need a prefix either...

**Comment by saschaben** [comment]
![updated](https://cloud.githubusercontent.com/assets/1753431/13852577/f4d7a388-ec1f-11e5-8c6b-a9601a6487dc.png)

**Comment by jrjohnson** [comment]
Requires ilios/calendar#46
