### ISSUE TITLE
Session Detail Page

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#150]
Finish session detail page.

@jenzweben please add your mock for session details.

**Comment by jrjohnson** [comment]
![sessions-detail-page-v9](https://cloud.githubusercontent.com/assets/349624/6283131/a8b73a5a-b894-11e4-925a-29b6dfff700a.png)

**Comment by jrjohnson** [comment]
@dartajax can you make sure your notes from our meeting yesterday find their way into this ticket?

**Comment by dartajax** [comment]
The notes I have are the following ...

The link to go back to the main course page should be one of the following  ...
* Back to Main Course Page
* Back to Course Details

Session summary needs to show associated groups.

Independent Learning Modules need to be addressed.

Parent Objectives -- need to have a count not detail with a link to the Objective inspector.

**Comment by dartajax** [comment]
What Valentina really wants is to have the page like the one above but also have the other sessions available -- in other words "View All / Edit " refers to sessions -- above and below "The Abdonimal Physical Exam Revisited" would be (in collapsed mode) the previous and / or following sessions (depending on how the screen has been sorted).  This would be huge for her if this could be possible.  She is aware the screen could be really long.
