### ISSUE TITLE
Functionality Needed For Session Copy Into Same Or Different Course

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1509]
We need to make it possible to copy a session (with or without the offerings) into (by default) the same course or into a different course of the user's choosing.

It would copy all of the attributes of the original session (MeSH, Vocabulary, etc.).  If copied into the same course, a "(2)" would be appended to the session title.  It would then be up to the user to update all of the details of the cloned session.

**Comment by saschaben** [comment]
I believe that cloning of offering data from course to course could be problematic, as it opens up more issues with dates and times than it solves by capturing instructor and group data. For instance, if you clone a session from winter term into a course the next fall,where you are not actually processing a rollover, you could wind up with all sorts of challenges that would require manual cleanup and review above and beyond the effort required to re-add the necessary offerings.

**Comment by saschaben** [comment]
I believe that cloning of offering data from course to course could be problematic, as it opens up more issues with dates and times than it solves by capturing instructor and group data. For instance, if you clone a session from winter term into a course the next fall,where you are not actually processing a rollover, you could wind up with all sorts of challenges that would require manual cleanup and review above and beyond the effort required to re-add the necessary offerings. 

to handle this effectively would require a rollover model for single session offering sets -- I'm not sure we want to go there at this stage.

**Comment by saschaben** [comment]
For the UI, we can provide a copy icon in the listing when appropriate:
![clone1](https://cloud.githubusercontent.com/assets/1753431/16882087/0e0bb884-4a72-11e6-8afc-3c44fd1e03b7.png)

which would open up a panel similar to rollover:
![clone2](https://cloud.githubusercontent.com/assets/1753431/16882101/1b089f48-4a72-11e6-839d-f4f8206f8357.png)

Cloning in the first iteration at least will copy a session structure and metadata, but NOT the offering data -- no dates times locations groups or instructors.

**Comment by jrjohnson** [comment]
Should we put the icon in the session overview after opening the session instead of the list like we have the icon for rollover in the overview?

**Comment by saschaben** [comment]
like this?

![clone3](https://cloud.githubusercontent.com/assets/1753431/16883035/dd417752-4a76-11e6-89f7-6fded81cb495.png)

possibly. Let's discuss.

**Comment by jrjohnson** [comment]
Yes.  Somewhere in there.   Just for consistency with course rollover.

**Comment by saschaben** [comment]
Let's get the functional bits taken care of, and run it by the primary admins to see what they think about placement (in the list vs. in the session). then we can just plop the icon link in.
