### ISSUE TITLE
Add Unique Course ID to Course Details

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#1519]
In the past, we provided a unique-ish ID to allow for specific courses to be identified both internally and in the UI: 
![course manager 2016-03-29 09-23-33](https://cloud.githubusercontent.com/assets/1753431/14115492/12c4834c-f590-11e5-955b-ededc7e62b9f.png)

In order to expedite course identification between years and terms, and for tracking ability, we should do the same now. A similar hash pattern and location and presentation. And even better if we make it a searchable field....

**Comment by stopfstedt** [comment]
this may require backend changes in order to make courses searchable by this attribute.

**Comment by jrjohnson** [comment]
I thought that ID was just a helpful tag for the user if we exapand this I think we can do some very interesting stuff here for clarity:
1) Completely separate this conceptually from the external ID which is what it is tied to now.
2) Standardize this for all courses and make it never overridable
3) Don't store this in the DB - instead it should be determined in a pattern way from the course id and year.

I would vote we call this Universal Course Identifier.  Or something else Title Casey that makes it feel Official and serious.  

Or alternatively we can just put the current ID of the course on the screen and not just in the URL so users would know that it was important.

**Comment by saschaben** [comment]
Agreed on all 3 points. I'd prefer to use some sort of pattern above and beyond course_id so that it can be not only used as an internal identifier, but potentially used externally as well in ancillary systems (like all of our wacky msaccess tools). I nix Universal Course Identifier because "UCI". Maybe Global Course ID? @stopfstedt the searchability is a nice to have only. not a req.

**Comment by saschaben** [comment]
OK. we are going to go with a simple "ILIOS[course_id]" value. Label will be: <strike>"Big Kahuna ID"</strike> Universal Locator.  Location will be either under  end date (in the same grid row as "level"). And while we should _refer_ to this as the <strike>"Big Kahuna ID"</strike> Universal Locator, I don't think we need to print a label on the UI: just the grey-text ID as before in 2.
