### ISSUE TITLE
Represent educational year as an academic year

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#152]
1. Add academicYear computed value to educationYear model.  It should be YYYY - YYYY+1
2. Use this property on courses list filter.

**Comment by saschaben** [comment]
Let's make sure we all use the same language to describe the same things when it comes to the nefariously confusing academic year/educational year/calendar year confluence. Please see https://www.dropbox.com/s/jqql3gh63q65uj1/Managing%20the%20Academic%20Year%20in%20Ilios.docx?dl=0 for definitions and details.
