### ISSUE TITLE
MyReports requires filter for academic year

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#1520]
Right now we return results for all of time, leaving you with lots of results from 2009-10 etc. user should be able to filter a report by academic year.

**Comment by stopfstedt** [comment]
any report variations on courses can use this. possibly others.

**Comment by jrjohnson** [comment]
@saschaben - is this critical path?  Seems like an enhancement for sure, but less valuable than many others.

**Comment by saschaben** [comment]
see also #1637

**Comment by jrjohnson** [comment]
Some example reports:
Get me all the sessions associated with a term in a given year
Get me all the mesh terms associated with a school in a given year
