### ISSUE TITLE
MyReports is returning incorrect results

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#1526]
We are not returning correct datasets in MyReports. Example:

run a report for "all instructors for session type "Lecture" in Medicine. The result set is:

Chandler M.
David R.
Douglas S.
Sascha C.
Tracy F.

Now run the following SQL:

```
SELECT course.title, session.title, ofx.user_id, user.last_name,user.first_name FROM session 
JOIN course ON session.course_id = course.course_id 
JOIN offering ON session.session_id = offering.session_id 
JOIN offering_x_instructor ofx ON offering.offering_id = ofx.offering_id 
JOIN user ON ofx.user_id = user.user_id 
WHERE course.school_id = 1 AND session_type_id = 25 AND course.year = '2016';
```

This would presumable return a **subset* of the report above, but actually returns the correct list of 56 records of lectures and their associated instructors in the 2016 MD program.

And there is no overlap.

I have not done data verification with other report matrices, but instructor to session type is wrong for all schools and all queries.

**Comment by stopfstedt** [comment]
closed via #1533
