### ISSUE TITLE
UX mods for school level competency management

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#1527]
the label "there are _n_ competencies" should read "there are _n_ competency subdomains"
![subdomain](https://cloud.githubusercontent.com/assets/1753431/14151658/cb2c2cb8-f663-11e5-830b-83ea8d1a7760.png)

the parenthetical number reference currently counts total links into any program year objectives. 
![linked](https://cloud.githubusercontent.com/assets/1753431/14151737/47e78d42-f664-11e5-91ee-9142c6c7f38b.png)

This should be modified to count number of courses (or at the least number of course objectives) to which a competency maps. Until we can investigate doing so with Ember Data 2.5, this label should be non-numeric, and simply read "(Linked - In Use)"

![linked](https://cloud.githubusercontent.com/assets/1753431/14151853/d31c361a-f664-11e5-8ca7-6f6acc5291e2.png)

**Comment by dartajax** [comment]
As I have been using the Competency Manager utility, I have noticed that it would nice if the text box (both for adding new and edit existing) were bigger -- as in twice as wide.  Maybe use two of three columns rather than one.  Cool?

**Comment by dartajax** [comment]
Still an issue - reviewed as team
