### ISSUE TITLE
Loading indicator jumps around

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#155]
The pre-render loading indicator is flush left, but once the app loads the indicator moves into the center.

The best place to see this is on courses on a monitor large enough to have vertical white bars on the left and right of the application..  Just hit refresh and watch it jump.

**Comment by saschaben** [comment]
The jump occurs after the slide out menu generates on the page, and the loader jumps to make room for its div. Technically, it's still left aligned in its own div, its just that the left margin of the div moves.
