### ISSUE TITLE
Edit users secondary cohort

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#1556]
On the user profile screen it should be possible to add / remove secondary cohorts for a user.

UI: 
Put an edit pencil next to the secondary cohorts list.
Present the cohort picker from the course page when it is clicked
Exclude the users primary cohort from the list so it can't be removed accidentally or changed at all.

Discussion:
@saschaben what restrictions should be placed on removing a secondary cohort?  Do we:
1) not allow removal if student is in learner groups?
2) remove student from all learner groups when they are removed from a secondary cohort?
3) remove students from secondary cohort and not worry about learner groups at all?

Refs #684

**Comment by saschaben** [comment]
#3 is the goal: historical data of groups/assignments would remain intact, but the user would no longer be available in that cohort for further assignment.
