### ISSUE TITLE
provide Masquerading as user functionality

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#1569]
provide a mechanism to spoof another specific user, and log in as them, for admin users.
- [ ] allow selection of a specific student or instructor as spoof account
- [ ] constrain spoof to only accounts in schools where user has admin rights

Q: how do we audit this action?
Q: how do we limit the amount of damage a spoofing user can do?
Q: should we provide a "consent" key that is only available to the student, which needs to be granted to the admin before access is provided?

**Comment by dartajax** [comment]
For the second question, I believe it should be a read-only thing just mostly to see what is on the student's calendar (providing you're spoofing a student) -- or not so there's no chance of stuff getting messed up. The consent key is a good idea too.

**Comment by saschaben** [comment]
This ticket replaces and updates #587

**Comment by saschaben** [comment]
something like this pattern might be workable:
provide a "spoof" link and prefiltered user search on the profile page:
![spoofer1](https://cloud.githubusercontent.com/assets/1753431/17374057/beac9bbc-595f-11e6-9514-f412a0842a6f.png)

select and activate user:
![spoofer2](https://cloud.githubusercontent.com/assets/1753431/17374062/c4f60742-595f-11e6-9b79-633079b4af46.png)


![spoofer3](https://cloud.githubusercontent.com/assets/1753431/17374067/cc9db562-595f-11e6-9d29-b57da9a4ec9e.png)

Provide a static banner with "undo spoof" link
![spoofer4](https://cloud.githubusercontent.com/assets/1753431/17374072/d1b6c20a-595f-11e6-8fd2-83d6116e1ab3.png)

I don't think a consent is necessary --- it needs to be implicit as part of the use contract generally.

**Comment by thecoolestguy** [comment]
In Drupal, this is referred to as 'Masquerading as a user', which I think is a better name for the functionality.

**Comment by dartajax** [comment]
I believe the admin console >> view calendar on a student's profile action has made this obsolete.
