### ISSUE TITLE
Learning Materials Need More Detail

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1572]
We need to expose as much information as possible regarding Learning Materials when being attached to Sessions and Courses.

Here is a sample search with results.

![image](https://cloud.githubusercontent.com/assets/7493331/14445861/63723742-0005-11e6-9ae8-8227931fa482.png)

Notice that there is not information about when the file was uploaded or saved, who the author of the document is,  In fact, the second and third audio file would appear identical to the user.  We should provide all of the information that we can to make this easier to know which document to select.

**Comment by saschaben** [comment]
So, proposal is to add the following metadata points to search results (and make them searchable?):

- Author
- Owner (ie "uploaded by")
- Upload Date
![63723742-0005-11e6-9ae8-8227931fa482](https://cloud.githubusercontent.com/assets/1753431/14474141/52ad3afa-00b0-11e6-9bfb-159f61136650.png)
