### ISSUE TITLE
Confusion bout red cancel x in editable fields

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#159]
A note for discussion.  We've had a few conversations about this in meetings and after the quick demo last week.  The red x we are using to cancel editing on a field seems to be confusing to some people.  They think it might be a delete indicator.  Maybe [undo](http://fortawesome.github.io/Font-Awesome/icon/undo/) would be a better indicator?

**Comment by saschaben** [comment]
Why don't we try the fa-undo in red for the initial release on inline edit fields. We can discuss how the "x" should be used as we move along.

**Comment by jenzweben** [comment]
sounds good to me.
