### ISSUE TITLE
Add Another User Button Needs to Be Placed In Admin Console

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1593]
This button should only appear after a user has been selected and added.  This is useful because frequently a series of Instructors needs to be added and it would make this process smoother and easier to accomplish.

See the ugly mock below ...
\
![add_another_user](https://cloud.githubusercontent.com/assets/7493331/14539170/2081761a-0234-11e6-89d9-4dc5a3d0d83d.jpg)

**Comment by dartajax** [comment]
The user would then be taken back to this screen.

![image](https://cloud.githubusercontent.com/assets/7493331/14539225/5cd1c8fe-0234-11e6-8991-d20737598b9e.png)

**Comment by saschaben** [comment]
This is actually fairly tricky technically. Recognizing that this is a time saver for admins, I would want more info on how frequently this would be used before we commit to its development and the revision of the user admin interface to accommodate it.

**Comment by dartajax** [comment]
resolved
