### ISSUE TITLE
Hide Session Objective Column Headers When There Is No Data To Display

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1602]
See the screen shot ...

![image](https://cloud.githubusercontent.com/assets/7493331/14577419/acd683c2-0328-11e6-91bf-d7ffebaa289f.png)

**Comment by dartajax** [comment]
This screen shot is from Program Years where the situation is similar.

![image](https://cloud.githubusercontent.com/assets/7493331/18455305/03f46048-78fe-11e6-9a8d-d1060332c56b.png)

**Comment by stopfstedt** [comment]
closed via #2347
