### ISSUE TITLE
School Switcher Missing In Programs

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1609]
It appears there is a label instead of a drop-down on Programs.  

![image](https://cloud.githubusercontent.com/assets/7493331/14618410/5796d7fe-0567-11e6-906e-7dada9bad124.png)

It should be more like it is on Courses and Sessions where the user can switch schools.  This was reported by a technically savvy Pharmacy Admin user who figured out how to access Programs >> Pharmacy by using the URL https://curriculum.ucsf.edu/programs/7 .

![image](https://cloud.githubusercontent.com/assets/7493331/14618453/7ed5ce88-0567-11e6-8aef-f72f200e10fc.png)

**Comment by saschaben** [comment]
yes.

The Programs page currently default to only medicine, and does not have a school selector.

fix this.

also, if at all possible, default to users primary school.

**Comment by jrjohnson** [comment]
Looks like a one line change may fix this;
https://github.com/ilios/frontend/blob/master/app/controllers/programs.js#L36

should by `hasMoreThanOneSchool: gt('model.length', 1),`

But probably there is some more to do.

**Comment by saschaben** [comment]
@jrjohnson am assigning you 'cuz you built it. ha ha.
