### ISSUE TITLE
Allow for password management in Admin GUI for systems using form-based authentication

### ISSUE THREAD

**Issue by thecoolestguy** [ilios/frontend#1612]
For system's running form-based (non-LDAP/SSO) user authentication, the ability to add/update passwords needs to be added to the administrators' user management interface. (see also ilios/ilios#1382)

**Comment by jrjohnson** [comment]
Couple of clarifiers for the group (@saschaben @stopfstedt @dartajax )
- Do we need to provide for auto-generation of replacement password?
- Can the administrator simply enter a new phrase?  
- Do we want to validate password strength?
- Should be use a 'password' type input to hide the users typing or just plain text?

**Comment by saschaben** [comment]
(@thecoolestguy @jrjohnson @stopfstedt @dartajax )

• Do we need to provide for auto-generation of replacement password?
-- no, but it would be a nice to have.
• Can the administrator simply enter a new phrase?
-- it's the lowest hanging fruit, not sure it's such a bad thing, at least to start.
• Do we want to validate password strength?
-- sure, but we don't want to ​*disallow*​ weak passwords.
• Should be use a 'password' type input to hide the users typing or just plain text?
-- should be `password` type input. very much not a fan of plain text password inputs.

**Comment by saschaben** [comment]
see also #1613

**Comment by jrjohnson** [comment]
Mostly done.
