### ISSUE TITLE
Delete Button Not Needed In My Courses - Delete Fails Anyway

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1621]
See the screen shot.

There is no reason anybody should be able to delete a Course to which they are explicitly attached.  

See below.  Plus it bombs out when you try.

![image](https://cloud.githubusercontent.com/assets/7493331/14657635/f88d931e-0643-11e6-9752-7afd9e349cf4.png)

![image](https://cloud.githubusercontent.com/assets/7493331/14657651/0878a584-0644-11e6-9565-b258a4c12cd2.png)

![image](https://cloud.githubusercontent.com/assets/7493331/14657662/15563bf4-0644-11e6-9e41-10dc91123a0b.png)

**Comment by stopfstedt** [comment]
superseded by #1627
