### ISSUE TITLE
improve message in course deletion confirmation dialog.

### ISSUE THREAD

**Issue by stopfstedt** [ilios/frontend#1628]
![selection_152](https://cloud.githubusercontent.com/assets/1410427/14723364/8543a6e0-07c5-11e6-92cf-99198d3405b9.png)
1. yank "with published offerings", which is wrong in multiple ways.
2. add a count of sessions and offerings to the message. 

Proposal:  
"ACHTUNG! This action will also remove all sessions (X) and offerings (Y) for this course, and cannot be undone. Are you sure you want to proceed?"

**Comment by stopfstedt** [comment]
@saschaben @jrjohnson thoughts?

**Comment by saschaben** [comment]
I concur. wording:  "You are about to permanently delete this course. This action will also remove all sessions (X) and offerings (Y) for this course, and cannot be undone. Are you sure you want to proceed?"
