### ISSUE TITLE
Learning Materials now display with border

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#1635]
![lmbord](https://cloud.githubusercontent.com/assets/1753431/14748904/295edd5c-0871-11e6-9220-1c1283dda35e.png)

**Comment by jrjohnson** [comment]
@saschaben I'm not really sure what to do with this ticket.  Do you want to remove the borders?  I have no recollection if we added this on purpose or not.

**Comment by saschaben** [comment]
yah. weird, huh? I actually think it's a css bleedover accident/error, but it sort of works for me. I am thinking maybe we label it as an enhancement and call it "completed".

**Comment by jrjohnson** [comment]
💯
