### ISSUE TITLE
Add Calendar Filter for Vocabularies

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#1636]
Since we no longer have a static "topics" list to filter against, we need to add in the ability to filter against any tag from any vocabulary instead:

this filter should be
- [ ] multi-select to allow display of any accessible vocabulary 
- [ ] tags should display in nested list
- [ ] filtered by school (like session type)

![filters](https://cloud.githubusercontent.com/assets/1753431/14750962/671e5fb8-087c-11e6-82e4-f2f02bb07738.png)

**Comment by jrjohnson** [comment]
@saschaben I'm pretty sure this is solved and should have been closed. Can you verify and let me know if we're missing anything?
