### ISSUE TITLE
user profile component too big

### ISSUE THREAD

**Issue by stopfstedt** [ilios/frontend#1645]
Babel is complaining on application startup.
```
[BABEL] Note: The code generator has deoptimised the styling of "ilios/templates/components/user-profile.js" as it exceeds the max of "100KB".
```

Let's [smash it up](https://www.youtube.com/watch?v=-FFx68qSAuY) into smaller pieces.

_Lowest of low priorities._

**Comment by jrjohnson** [comment]
This will be addressed with Ember 2.9.
