### ISSUE TITLE
Need to Have the Independent Learning Check Box on Session Edit / Add plus Due Date Field

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#165]
In looking at the mockups, I am not seeing where the check box to indicate whether a session is an independent learning session type (Independent Learning Module).  Also missing - the due date - is this a formatted text field or date picker of some sort?

**Comment by jenzweben** [comment]
![session-add](https://cloud.githubusercontent.com/assets/5023894/6337045/01f1456a-bb5c-11e4-948f-7d3ee8b0df57.png)
