### ISSUE TITLE
Published Sessions Appearing In "Sessions Incomplete: cannot publish"

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1658]
The session shown below is already published.

![image](https://cloud.githubusercontent.com/assets/7493331/14899042/0ee80534-0d3f-11e6-8bf8-507e16feba18.png)

![image](https://cloud.githubusercontent.com/assets/7493331/14899059/2f38da7a-0d3f-11e6-88da-f916990365e0.png)

![image](https://cloud.githubusercontent.com/assets/7493331/14899071/3f3fb51a-0d3f-11e6-8c6f-1a258d241827.png)

**Comment by saschaben** [comment]
am guessing that this is ILM-related, rather than a generalized bug. let's verify we are testing publish for ILMs and ordinary sessions here

**Comment by dartajax** [comment]
I think you are right @saschaben
