### ISSUE TITLE
Published Sessions Appearing In "Sessions Complete: ready to publish"

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1659]
This is similar to what is occurring in #1658.

![image](https://cloud.githubusercontent.com/assets/7493331/14899198/da531dda-0d3f-11e6-8792-f2ac6007290f.png)

![image](https://cloud.githubusercontent.com/assets/7493331/14899223/eb10a674-0d3f-11e6-91f8-70d9aa938c9d.png)

**Comment by saschaben** [comment]
not sure this is a bug: I think we are just not bothering to test for "isPublished" when we collect the sessions and session count: any currently published session will show up in the list --- since we are literally publishing "all" -- not "all not-yet-published" -- sessions.

**Comment by dartajax** [comment]
I agree.  Maybe we should have a bucket for Published Sessions too and call the whole thing "Course Review" or something.

**Comment by dartajax** [comment]
Yeah I guess Publish All just means Publish All though, doesn't it?  Maybe we can close this one up.  I thought maybe it was related to the other things I reported, even though #1658 may only apply to ILM's.
