### ISSUE TITLE
Check Boxes Don't Work (Are Reversed) in Sessions Requiring Review

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1660]
Clicking "Publish As-Is"

![image](https://cloud.githubusercontent.com/assets/7493331/14899287/341eb39c-0d40-11e6-8341-658041158b0c.png)

... Does this.

![image](https://cloud.githubusercontent.com/assets/7493331/14899322/50d4ae2e-0d40-11e6-9446-5afa0df77a72.png)

This now leaves both check boxes unchecked. Now clicking either of them will cause the other one to be selected.  It appears the actions are reversed.

**Comment by saschaben** [comment]
I'm not seeing this behavior.

make sure you have a fresh session...and what browser are you in when you see this behavior?

**Comment by saschaben** [comment]
It appears that one of our recent updates has munged our radio / checkbox controls, and that we now essentially have our wires crossed here.

Seek. Destroy. Repair.
