### ISSUE TITLE
Provide a consolidated view of all LMs for a given course

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#1665]
In order to expedite student study experience, provide a display similar to (or perhaps a version of) the course summary view, which displays all learning materials for a course, organized by session / date descending.

**Comment by saschaben** [comment]
One way of tackling this would be to provide some visibility for the students in the dashboard:

1) we could create a link via the MyCourses list to a course-specific listing of LM links and descriptions, sorted by session / date. This would provide course - level organization and access in a permanent manner.

2) we could allow for a weekly type view of current resources as a parallel to our Agenda view in the dashboard -- instead of events, it would list the current and upcoming list of LMs associated with the activities in the Agenda list, sorted by week/due date.

![lm_options](https://cloud.githubusercontent.com/assets/1753431/17902841/d0d865e6-691d-11e6-9472-6bcf316c9f28.png)

**Comment by saschaben** [comment]
still needed: a mockup for a new list of LM links by course --- determine sorting and grouping, and relationship to the print summary view.

**Comment by saschaben** [comment]
Initial wireframe for a course-specific LM page:

![printview-course](https://cloud.githubusercontent.com/assets/1753431/18222426/668f37e6-714c-11e6-9c64-2946df2193de.png)

**Comment by jrjohnson** [comment]
Since this is for students who are only in a single offering we should sort the LMs by the date of the offering they are in (as opposed to first offering date for the session).  Or put a different way we should lookup a sorted list of all student offerings for a course and then display learning materials sorted by that date for each session.  There *might* be a case where duplication occurs, but we can figure out how to best deal with that.

**Comment by saschaben** [comment]
@jrjohnson good insight. With the new curricula there are actually more opportunities for a student to be in more than one offering per session regardless of the session type, but that doesn't change the model: sort by first offering date for a given learner in any session.

**Comment by jrjohnson** [comment]
@saschaben is this just a learner view of this data?  Or so I need to create it to show both LMs assigned to a learner as well as all LMs in a course for an administrator to see?

**Comment by saschaben** [comment]
see also #2230

**Comment by saschaben** [comment]
on the question of how a user accesses this LM - Course summary view....

1) a link should be added to the calendar event page, just like print summary.
2) a link should be added to the course management page, just like print summary.
2) For students, we need to add the MyCourses block on the dashboard and provide this as a direct route as described above.

**Comment by saschaben** [comment]
For item #1 above: add link as noted, using `fa-archive`, with mouseover tooltip as shown -- 

![ilios 2016-10-18 11-00-54](https://cloud.githubusercontent.com/assets/1753431/19483593/e8cc92f4-9522-11e6-986c-56d2f76a9a00.png)

For item #2 above: add link as noted, using `fa-archive`, with tooltip "Learning Materials Summary" --

![course1](https://cloud.githubusercontent.com/assets/1753431/19484135/9274e490-9524-11e6-98fd-306df9ecaa7e.png)

**Comment by saschaben** [comment]
...and a consolidated header for the LM list view: should have session and if possible total LM counts, publish status; does not require directors.

![header](https://cloud.githubusercontent.com/assets/1753431/19488035/30e7ca26-9533-11e6-8573-0c3544c96d39.png)
