### ISSUE TITLE
Attach Program Level Competencies to Courses 

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#167]
I am not seeing in the mockup or in my version of Ilios 3.0 how a user would add a Program Level competency to any given Course.  I may not have the latest commits though so maybe this has changed.  I am seeing on my local ember Ilios 3.0  ...

![competencies](https://cloud.githubusercontent.com/assets/7493331/6259955/5f3b4860-b78d-11e4-9340-591d9697c3aa.JPG)

... with no way to go select the competencies.

**Comment by saschaben** [comment]
Competencies are displayed once a parent objective is selected for an objective. Since the competency relationship is only available thru inheritance, it only shows up once that relationship is made. the latest code has active links to add parent objectives for course objectives.

**Comment by dartajax** [comment]
That sounds good to me.  I can close this if it is unnecessary.
