### ISSUE TITLE
Recurring Event Day Of Week Boxes Should Be Read-Only (Controlled By Start Date Picker)

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1670]
Since 05/04/2016 is a Wednesday, there is no reason for the other days of the week to be selected.  The day of the week selected depends on what is chosen in the Start Date control.

![image](https://cloud.githubusercontent.com/assets/7493331/15025484/453de1c2-11ee-11e6-9096-fc156f31618f.png)

**Comment by stopfstedt** [comment]
i don't agree. 
you can chose to start on  a wednesday, but then have even on tuesday and fri in the following X weeks.
