### ISSUE TITLE
Hide Grid Header If No Data Associated - Learning Materials

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#168]
The headers should probably be hidden if there is no data to display, no?  And across the board, this would seem like a good idea.

![lm](https://cloud.githubusercontent.com/assets/7493331/6260006/ca179cb0-b78d-11e4-8bc9-d272777f5087.JPG)

**Comment by thecoolestguy** [comment]
We decided to have no header if there are no learning materials.

**Comment by thecoolestguy** [comment]
Fixed in #205
