### ISSUE TITLE
Cannot link to or select single-level competency

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#1696]
If a competency has no sub-domains (ie if it is only single level, not 2-level), it is inaccessible from the selector for program year competency:
![comp1](https://cloud.githubusercontent.com/assets/1753431/15256206/3a16555a-18f5-11e6-8e39-9adc4fffec1a.png)
Similarly, if a competency has subdomains, the top-level domain is unselectable for linking -- even if it is added to a program year stripped of sub-domains:
![comp2](https://cloud.githubusercontent.com/assets/1753431/15256270/ae3e2ebc-18f5-11e6-920a-458df618babe.png)

![comp3](https://cloud.githubusercontent.com/assets/1753431/15256271/b2c5f3a2-18f5-11e6-967a-4eed5fcf3a9a.png)

Since the bridges curriculum does not have competency subdomains, in order to map correctly this will need to be addressed.

**Comment by jrjohnson** [comment]
@saschaben For adding competencies to a program year should we use the new UI from ILM Learner Groups or stick with this tree?  How do we allow user to pick a domain, but not the children?
Also - 
1 - Can a domain be linked to a program year only if it has no competencies as children?
2 - Same question but for course objectives

**Comment by saschaben** [comment]
I think we stick with the tree: in this data domain, the hierarchy is actually substantially more important to track and understand than it is in groups. 

To pick a domain, but not the children, a user would have to select the domain and then de-select the children (this is the pattern we had in 2). As a somewhat edge case, I don't have a problem with forcing the extra clicks.

1& 2: let's discuss. this is an interesting edge case for usability.

**Comment by jrjohnson** [comment]
2 - Domains can only be linked to program year objectives if they have no children which have been attached to the program year.

**Comment by jrjohnson** [comment]
1 - User clicks whole domain then clicks each competency to remove it, but the domain remains.  This sometimes happens now which may be a bug - but should be the real behavior with tests.

**Comment by saschaben** [comment]
This is now a priority for Bridges, as there is a 2ndary system with a dependency on the linkages from course objective > program objective > competency, and the bridges competencies do not have children.

**Comment by saschaben** [comment]
Additionally, if a program objective does not have a parent competency, then it is un-selectable as a parent for a course objective. This essentially breaks the entire mapping model. This is an outgrowth of the primary issue here, but is getting its own ticket:
