### ISSUE TITLE
Check Box For Select All / Select None in Learner Groups Not Working Correctly

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1722]
See below, nobody has been selected.

![image](https://cloud.githubusercontent.com/assets/7493331/15514990/aa4cfee2-21a0-11e6-9fc3-2722354b9814.png)

Now when I select one or more people from the list, it appears "Check All" has been selected above.

![image](https://cloud.githubusercontent.com/assets/7493331/15515027/da936262-21a0-11e6-9a20-10f96367b20c.png)

It is confusing as a user.

**Comment by jrjohnson** [comment]
What should happen to that box when 
- some users are selected
- all users are selected
- no users are selected

**Comment by dartajax** [comment]
Let me take a crack at answering that.

* some users are selected 
... provided they were selected manually and the check all / none box was never used, the check all / none box should not be selected 

* all users are selected
... if all users are selected because of using that check box, the check box should stay selected.

Here is the tricky part ... what happens when all are selected using the check box and then some are removed manually.  I believe the check all box should stay selected since that is the action that got us to this point.

* no users are selected 
It should not be checked.  If users start getting selected manually, it should stay unselected.

**Comment by dartajax** [comment]
Maybe we could do a horizontal line or something.   This is from Yahoo Mail for reference.

originally...

![image](https://cloud.githubusercontent.com/assets/7493331/15585283/6d38baa2-2333-11e6-9202-008609cfb390.png)

After selecting one or more of my messages, the select all / none changes to this ..

![image](https://cloud.githubusercontent.com/assets/7493331/15585367/c2cdc03e-2333-11e6-8c5c-2458278dd64e.png)

Maybe this will help ..

https://css-tricks.com/indeterminate-checkboxes/
