### ISSUE TITLE
Breadcrumbs Get Broken When Navigating to Sub Sub Groups

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1723]
I made a secondary level sub group called "Prologue Mid Sub 1". Nobody is in it yet.  The breadcrumbs should be as follows ...

Learner Groups > Prologue Entire Class > Prologue Midpoint Feedback > Prologue Mid Sub 1 

... and not as shown in the screen shot below.
![image](https://cloud.githubusercontent.com/assets/7493331/15515127/6ac2d566-21a1-11e6-8021-fbf89b181456.png)

Prologue Entire Class is a higher level group than Prologue Midpoint Feedback.  It navigates correctly but as a user you don't know where you are when you assume you are moving one level up the tree, you end up two levels up.

**Comment by dartajax** [comment]
:+1:

**Comment by jrjohnson** [comment]
@dartajax was your thumbs up supposed to be on the pull request?
