### ISSUE TITLE
Fix edit-in-place model binding

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#173]
Current the edit in place mixin dynamically binds the property value, but doesn't account for the model changing.  This is especially problematic when the model is set after the component render.  We need to move the bindings off of the DOM insert and into something else.  

Probably bind the properties every time the model changes and un-bind them when it goes away.

**Comment by saschaben** [comment]
is this still an issue to be addressed? if not please close.

**Comment by jrjohnson** [comment]
Yes. We haven't quite transitioned away from this yet. Will investigate.

**Comment by jrjohnson** [comment]
Will be resolved with the removal inplace in #2212
