### ISSUE TITLE
Save Of New Instructor Group Not Adding New Group To The List

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1764]
See the steps below ...

![image](https://cloud.githubusercontent.com/assets/7493331/15945156/d97832f2-2e45-11e6-8732-e06018b80816.png)

![image](https://cloud.githubusercontent.com/assets/7493331/15945192/05e2b39e-2e46-11e6-9748-5ebd9ac23e09.png)

This new group should appear at the top of the list.  It does not appear anywhere.

![image](https://cloud.githubusercontent.com/assets/7493331/15945214/22486ad8-2e46-11e6-8a86-149b1f742839.png)

You can even click on the provided link and then return to the Instructor Group listing and it is still missing.  However a good complete screen refresh (F5) brings it to the list as shown below.

![image](https://cloud.githubusercontent.com/assets/7493331/15945257/57e21568-2e46-11e6-9ba8-b9ace59d3ea7.png)

**Comment by jrjohnson** [comment]
This was fixed at some point and works now.
