### ISSUE TITLE
Location of Search Box in Learner Groups for ILM's Too High / Confusing

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1780]
See the screen shot below.

When there are no Learner Groups yet attached to an ILM, the location of the the search box is confusing.  Even if there are Learner Groups attached, it appears too high on the screen.  See the screen shot for reference.  It is less confusing once Learner Groups have been attached but it is still too high.

![image](https://cloud.githubusercontent.com/assets/7493331/16024423/95943b4c-3176-11e6-8a74-db1ce56b49fe.png)

**Comment by dartajax** [comment]
That line was placed for reference.  I know it is ugly and possibly confusing.

**Comment by jrjohnson** [comment]
Fixed in #1869 Now it looks like:
<img width="445" alt="screen shot 2017-04-19 at 8 46 38 am" src="https://cloud.githubusercontent.com/assets/349624/25189055/e6df953c-24dc-11e7-8f86-e889892663ff.png">
