### ISSUE TITLE
Window Sizing Causes Flyout Menu to Overlay App

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1781]
It is possible to resize the window so that the flyout menu is activated but covers up portions of the application.  See below.

![image](https://cloud.githubusercontent.com/assets/7493331/16026105/bee14cb0-3180-11e6-8e1c-75a8de224581.png)

**Comment by dartajax** [comment]
This window size ...

![image](https://cloud.githubusercontent.com/assets/7493331/16026166/3b0fa49e-3181-11e6-8588-0b5a69214b3d.png)

**Comment by saschaben** [comment]
The current flyout becomes static "out" at about 1470px width; it should not do so until about 1570px width.
