### ISSUE TITLE
Developer Check Box Should Be Disabled for Logged-In Developer User 

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1788]
I noticed this on stage3 and then it also occurred on ilios3-demo.  

![image](https://cloud.githubusercontent.com/assets/7493331/16098821/de88c00e-3309-11e6-8edf-2c382d4c2a7c.png)

I clicked the Developer check box to de-select it and ...

![image](https://cloud.githubusercontent.com/assets/7493331/16098837/f18f13ec-3309-11e6-994d-08a8783534aa.png)

This issue does not occur with Course Director or Instructor --- only Developer.

**Comment by saschaben** [comment]
if you were logged in as demo_dev1, this would be expected -- I don't think you can undo your own developer role when accessing a page/function that requires a developer role....

**Comment by dartajax** [comment]
You are correct and I will close this.  I was able to undo the developer role for other developers but not for myself.  Maybe we should trap that error better.

**Comment by jrjohnson** [comment]
No longer relevant in the new permissions paradigm.
