### ISSUE TITLE
clicking on white circle of a toggle does not fire action

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#1820]
clicking on the text/color area of any toggle control fires both the css of the toggle and the action event; clicking on the white circle of the toggle fires only the css, but does NOT fire the ember action

![toggle](https://cloud.githubusercontent.com/assets/1753431/16390183/60d94e34-3c56-11e6-8d81-9ae68781c01d.png)

**Comment by jrjohnson** [comment]
This control has mostly been removed except for the yes/no slider in which circle click does work.
