### ISSUE TITLE
Need to provide ability to roll course over into same (current) year

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#1822]
for a course that might be given multiple times in a year, the UI needs to provide the ability to add it to the same year as the parent course.

This can be handled by appending a value to the title, like `(2)` or something similar, or providing the ability to edit the name on rollover.

Note that when a course is rolled over into the same academic year as the parent, it KEEPS all relationships to program year: course objective > program objective links are cloned along with everything else.

**Comment by jrjohnson** [comment]
@saschaben how should this be done in the UI?  I'm thinking we add Title and if it is changed then options would be re-enabled to roll the course into those years.  Also add an option to the year dropdown for this year.

The title could also go under advanced, but I'm not sure we need to hid this option which could be very useful for fixing up titles pre-rollover.

**Comment by jrjohnson** [comment]
Needs https://github.com/ilios/ilios/issues/1487 so we can take a different title
