### ISSUE TITLE
Meaning of academic year in calendar filtering is unclear

### ISSUE THREAD

**Issue by mtb3** [ilios/frontend#1830]
When using the calendar filters, the meaning of the academic year (e.g., '2016 - 2017') in the (unlabeled) drop-down list is not clear. In fact this value appears to have 2 rather different meanings, depending on filtering options selected.

When `COURSE/TYPE` is chosen, the selected year specifies a filter by academic year for courses available to select.

![ilios_year_course_type](https://cloud.githubusercontent.com/assets/3044074/16495409/48d33126-3ebb-11e6-8c67-d15cd74d55fd.png)

When `DETAIL` is chosen, the selected year actually specifies the _matriculation year_ and then allows selecting from program cohorts with that matriculation year.

![ilios_year_detail_cohort](https://cloud.githubusercontent.com/assets/3044074/16495421/5837c294-3ebb-11e6-9a46-8324b9f4c501.png)

I thought this latter behavior was rather surprising (in particular for users of Ilios 2).

**Comment by saschaben** [comment]
some options:
![selector1.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5551233e5601aa8f0097f50b/125516c66e82c728ace21e0d46fb9196268197a69db8fd0fe64de29b234324676b5ee17e25d1ba7ab9462952595f1daf42590c44fcf1d82ef7e53d62964e49bc8f3900299f7744eeaa880dbd01b0218e4c85b4bd8a45c9ea3c24ee99c2.png)
![selector2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5551233e5601aa8f0097f50b/125516c66e82c728ace21e0d46fb9196268197a69dbbfd0fe64de29b234324676b5ee17e25d1ba7ab9462952595f1daf42590c44fcf1d82ef7e53d62964e49bc8f3900299f7744eeaa880dbe06b0218e4c85b4bd8a45c9ea3f24e799c2.png)
