### ISSUE TITLE
add/update PRIMARY COHORT via UI

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#1831]
to allow for more reasonable management of learners. Should be able to:

- Add a primary cohort
- flip a secondary cohort into a primary cohort
- flip a primary cohort to a secondary cohort

**Comment by jrjohnson** [comment]
I'm thinking we add a checkbox next to each secondary cohort in the user profile allowing it to be made primary?  Does that make sense for an experience?

**Comment by saschaben** [comment]
I think a button rather than a checkbox ("make this the primary cohort"), but yes that sounds like the right workflow.

**Comment by saschaben** [comment]
I think this pattern is probably the simplest and most direct:

![secondaytoprimary](https://cloud.githubusercontent.com/assets/1753431/16529869/0f91575c-3f7a-11e6-9950-a61064186802.png)

Only allow the promotion of secondary cohorts to primary; not the demotion of the primary. This way we avoid the potential of orphans.

**Comment by saschaben** [comment]
see also #2026
