### ISSUE TITLE
disallow deletion of program when program year exists

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#1836]
If a program has at least one program year with data, we should not allow deletion. Either remove the delete icon, or provide a message: "you must remove all associated program year data before you can delete this program."

refs. #1177

**Comment by stopfstedt** [comment]
cascading deletes are problematic for programs, see #2237.
for now, i'd yank that delete button if at least one program year exists.

**Comment by dartajax** [comment]
This still raises an ugly message - the delete button should not be visible.

![image](https://user-images.githubusercontent.com/7493331/30670769-7c640dd6-9e18-11e7-9066-4344c922a17c.png)

**Comment by stopfstedt** [comment]
addendum:
this also borks out if the program is uses in CI reporting. add this to the check that determines whether the trashbin gets displayed or not.
