### ISSUE TITLE
Program Year Details has misaligned right border

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#1843]
![rtborder](https://cloud.githubusercontent.com/assets/1753431/16595369/9e0bf574-42a3-11e6-9216-45587185f35e.png)

**Comment by gboushey** [comment]
@saschaben @dartajax  Is this still a bug?  I looked into it this morning and alignment appears to be working properly.

**Comment by saschaben** [comment]
Hmm, yes. this appears to have resolved in the last two updates. would love to know what actually fixed it, but hey -- I'll take it! @dartajax please review and confirm, and if all OK please close.

**Comment by dartajax** [comment]
This is related to the last one I just closed and it also looks good - will do a re-test and close if so.

**Comment by dartajax** [comment]
Low hanging fruit gets the bees - LGTM :1st_place_medal:
