### ISSUE TITLE
ILMs in Agenda View of Dashboard should show "DUE BY"

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#1851]
right now ILMs in the agenda list are not distinguishable from regular activities. 

They should be listed as they are in the detail page, with "Due by [Date/Time]" rather than just the date/time value, and a prefix of "ILM: " on the title of the activity.

**Comment by saschaben** [comment]
![dubye](https://cloud.githubusercontent.com/assets/1753431/17153935/bb7c1800-5333-11e6-93f1-4f6e99dc2620.png)

**Comment by jrjohnson** [comment]
@saschaben the red highlight is probably the hardest part about this because it requires breaking up the link and applying differing styles to the sections.  It's not that difficult, just want to make sure it is necessary as opposed to just adding Due By text to the existing blue.

**Comment by jrjohnson** [comment]
@saschaben ping for advice on my previous question here.

**Comment by saschaben** [comment]
@jrjohnson highlight is not necessary (though it would be nice); Text in same color as surrounding text is fine.
