### ISSUE TITLE
Sample user upload file not found

### ISSUE THREAD

**Issue by mtb3** [ilios/frontend#1860]
I was just trying to take a look at the user upload feature in Admin, and clicked the `Sample File` button. I see an error indicating the file can't be found.

![ilios_no_sample](https://cloud.githubusercontent.com/assets/3044074/16776626/38a2a89a-4834-11e6-8e40-dcae13c67ba6.png)

I first encountered this issue using my own Ilios 3 instance, then reproduced on the Ilios 3 demo site.

**Comment by jrjohnson** [comment]
@mtb3 - this seems to be a larger issue than I originally thought and may take some time to wort out.  In the interim I attached the file to this ticket so you can check it out.

[SampleUserUpload.txt](https://github.com/ilios/frontend/files/359961/SampleUserUpload.txt)

**Comment by mtb3** [comment]
@jrjohnson Okay, thanks. I actually already found the file in the codebase for my own reference, but wanted to report the problem as well.

**Comment by dartajax** [comment]
It was addressed in PR# 3089.

**Comment by dartajax** [comment]
Refer to #3089
