### ISSUE TITLE
Offerings appear 1 hour off in week view starting November 6th 2016

### ISSUE THREAD

**Issue by mtb3** [ilios/frontend#1873]
All offerings for the week of November 6th - 12th 2016 appear 1 hour off in the Week view. The times shown in the event preview/popup are correct, but they are aligned 1 hour off from the times shown on the left side of the screen.

The previous and the next week look correct. Could this have something to do with Daylight Saving Time, which ends Nov. 6, 2016?

I have reproduced this issue on the Ilios 3 demo site, as seen in this screenshot:

![ilios_bad_week_demo_site](https://cloud.githubusercontent.com/assets/3044074/16923297/72835656-4ce7-11e6-950c-2348a2cae407.png)

**Comment by stopfstedt** [comment]
Thanks for reporting this.
We were able to narrow this problem down to an edge-case bug in the week view of the calendar grid. Day-view and month view are unaffected, as well as ICS feeds.
This problem only manifests itself in the week where the time change occurs. 
We're working on it and keep you posted via this ticket thread.

**Comment by mtb3** [comment]
@stopfstedt Thank you for taking a look and narrowing down the problem.
