### ISSUE TITLE
Upload date incorrectly shows current date in Manage Learning Material

### ISSUE THREAD

**Issue by mtb3** [ilios/frontend#1882]
When using `Manage Learning Material` pane to view/edit learning material details, the `Upload date` field is incorrect: it always reflects today's date, instead of the actual upload date.

Note: I was able to see this problem on the Ilios 3 demo site, for example here: https://ilios3-demo.ucsf.edu/courses/913/sessions/26429?details=true

Based on my brief testing of the API, I believe the upload date is being returned correctly from the Ilios backend.

**Comment by saschaben** [comment]
good catch. It is definitely a display rather than a data issue. Thanks for reporting!

**Comment by mtb3** [comment]
Thanks for handling this one.

**Comment by stopfstedt** [comment]
@mtb3 thanks for reporting! please keep 'em coming.
