### ISSUE TITLE
Better clarity for Competency Domain labeling and count in Schools Tab

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#1885]
When handling competency management, the total count value is misleading; we should list the total top-level domains, and the total sub-domains, as separate counts.

**Comment by stopfstedt** [comment]
right now:

![selection_040](https://cloud.githubusercontent.com/assets/1410427/17157295/47da3caa-5343-11e6-85de-1a1ae4a79453.png)


how about:

![selection_040b](https://cloud.githubusercontent.com/assets/1410427/17157314/61273cd0-5343-11e6-9585-964a4c992f14.png)

**Comment by saschaben** [comment]
...or maybe

![newcount](https://cloud.githubusercontent.com/assets/1753431/17157781/a27fd842-5346-11e6-8ed0-e002a601f15e.png)
