### ISSUE TITLE
Update LM copyright attestation

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#1893]
change wording from:

> The file I am attempting to upload is my own or I have express permission to reproduce and/or distribute this item and does not contain any protected health information. My use of this file is in compliance with Government and University policies on copyright and information security and my educational program's guidelines for professional conduct. This file also adheres to the Terms and Conditions for this application.

to:

> The file I am uploading is my own or I have express permission to reproduce and/or distribute this item, or use of it here has been assessed as allowable by the legal doctrine of Fair Use. This file does not contain protected health information, and use of it here is in compliance with Government and University policies on copyright and information security and my institution’s guidelines for professional conduct.

**Comment by stopfstedt** [comment]
machine-translation to spanish

> El archivo que estoy subiendo es mía o tengo permiso expreso para reproducir y / o distribuir este artículo, o el uso de aquí ha sido evaluado como permisible por la doctrina del uso justo. Este archivo no contiene información protegida de la salud, y la utilización de aquí está en conformidad con las políticas del gobierno y de la universidad de derecho de autor y de seguridad de la información y las directrices de mi institución para la conducta profesional.

french:

> Le fichier J'envoie est ma propre ou j'avoir la permission expresse de reproduire et / ou distribuer cet article, ou l'utilisation de celui-ci ici a été jugée admissible par la doctrine juridique de l'utilisation équitable. Ce fichier ne contient pas protégé information sur la santé, et l'utilisation de celui-ci ici est en conformité avec le gouvernement et l'Université des politiques sur le droit d'auteur et à la sécurité de l'information et les directives de mon institution pour la conduite professionnelle.

**Comment by dartajax** [comment]
El archivo que estoy subiendo es mío o tengo permiso expreso para reproducir y / o distribuir este artículo, o su uso aquí ha sido evaluado como permisible por la doctrina del uso justo. Este archivo no contiene ninguna información protegida de la salud, y su utilización aquí está en conformidad con las políticas del gobierno y Universidad sobre derechos de autor y de seguridad de la información y las directrices de mi institución para la conducta profesional.

**Comment by dartajax** [comment]
@saschaben Please verify the French translation is correct.

**Comment by saschaben** [comment]
French is good enough for government work. :+1:
