### ISSUE TITLE
Cannot add parent objective to course objective if the parent program objective is not mapped to a competency

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#1905]
see also #1696.

A program competency should be available for selection as a parent regardless of whether it has been mapped or not to a higher level parent. 

Mapping from one level to the next higher level cannot be dependent on the mapping of other levels.

**Comment by stopfstedt** [comment]
solved by rolling these program objectives without competency into a 'special' group that appears at the end of the nested list of selectable objectives.

![selection_004](https://cloud.githubusercontent.com/assets/1410427/17309953/4bdb9800-57f6-11e6-9f6c-dd7dbbacd810.png)
