### ISSUE TITLE
Draft Mode Icon Showing Up On Calendar for Scheduled Items

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1923]
See the screen shot below.

This was received from a user and it was concerning a different issue; but the Draft icons should not be there.

![image](https://cloud.githubusercontent.com/assets/7493331/17451967/ecbd3888-5b1f-11e6-8b33-521fe79c3ec5.png)

**Comment by jrjohnson** [comment]
@dartajax Why not?  Draft events do not show up on staff calendars, but for students it seems like having an icon is a nice way to indicate that the item is not published.  Is there another icon that would make more sense?

**Comment by saschaben** [comment]
FA-CLOCK
