### ISSUE TITLE
Deleted Course / Bad URL Fails Incessantly

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1935]
While verifying that a course (#800) had been deleted using the following link ...

https://curriculum.ucsf.edu/courses/800

The squiggly line (shown here in snap shot) just goes back and forth on the screen.  It should display an error if the URL passed was bad.

![image](https://cloud.githubusercontent.com/assets/7493331/17496118/b1c64c76-5d70-11e6-9051-a4615820e29e.png)

**Comment by jrjohnson** [comment]
Closed in #2204
