### ISSUE TITLE
Provide calendar feed time window options

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#1942]
While we cannot extend the feed window beyond 6 months without encountering issues, we could allow users to self-select the window they generate. Envisioning a drop-down selector for "total days" and a second for "[x] months back" -- the forward look would auto-generate and display as a label, like we do end date/time for offering.

**Comment by jrjohnson** [comment]
Can't fix, too many ICS consumers with weird rules. "We're giving them everything the internet will allow" - @saschaben
