### ISSUE TITLE
"saved sucessfully" message is misaligned

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#1948]
on program, program year, course, and instructor group, when a new entity is created, the  "[entity] saved successfully" link/message is misaligned to the left:

![save1](https://cloud.githubusercontent.com/assets/1753431/17612885/107a102a-600c-11e6-9125-02042b0dfc70.png)

In these pages we should use the pattern in place for session save:

![save2](https://cloud.githubusercontent.com/assets/1753431/17612910/43e3e5ee-600c-11e6-8722-26f2cf71adcd.png)

**Comment by stopfstedt** [comment]
closed via #2592
