### ISSUE TITLE
Request to Be Able to Go Straight From MyAccess into Ilios without Having to Click the Login Button

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#195]
It has been suggested that the second step of having to click Login be eliminated when accessing Ilios through MyAccess.  Currently, the user logs in to MyAccess, click Ilios, and then has to click a Login button.  It is not required that the user re-enter the credentials though.

**Comment by jrjohnson** [comment]
Agreed, however this issue actually belongs on ilios/ilios.  It seems like a frontend problem, but we're going to handle all the authentication stuff on the backend.  I fact I would take this a step further and say if a users is visiting a link like course/551?detail=true then they should not only be directed to login, but back to the EXACT page.  @dartajax Can you create this issue on that side?
