### ISSUE TITLE
Default Start and End Date Should Be Defaults - Creating Sequence Block - CI

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1979]
Once a Course has been selected, shouldn't the Start and End dates for the Course become the defaults for Start and End date on the Sequence Block.  These values can be easily cleared or fixed if the Course Start and End dates are not correct for the Sequence Block.  It could be a time saving way to start though.

![image](https://cloud.githubusercontent.com/assets/7493331/17746346/8390bc1a-6464-11e6-9e06-902ef759b984.png)

**Comment by stopfstedt** [comment]
not doable. sorry. the date pickers get initialized on rendering time. at that point, no course has been picked, and therefore no default dates can be provided to the pickers.

**Comment by saschaben** [comment]
one means of dealing with this could be to create a new control with a button "add course dates" to the start date/end date/duration component. you open up the date pickers, and click the button, and if there is a course selected we could javascripty-add them to the now-initialized form fields...but this is for future consideration.
