### ISSUE TITLE
Client Side validation

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#198]
We need to display validation errors and prevent form submission as the user enters data:

http://www.teamrarebit.com/blog/2015/02/14/ember-inline-validation-errors

**Comment by jenzweben** [comment]
![screen shot 2015-02-23 at 12 15 32 pm](https://cloud.githubusercontent.com/assets/5023894/6336207/b41a4b58-bb55-11e4-8ef6-cf55386b3768.png)

**Comment by jenzweben** [comment]
I'm good with the example shown in the link - but please add red alert icon (fa-warning) before the text and add more padding around the message than is in the example.

**Comment by jrjohnson** [comment]
When https://github.com/dockyard/ember-easy-form is at 2.0 they should have cli integration and be a nice place to start for validation.  Bumping this for a few versions to see if they make it.

**Comment by jrjohnson** [comment]
@ebryn - hopefully you can give us some direction in validating input.  Is there a good library for this that will ease to process?  Or do we just need to validate in component save actions using plain javascript tests?

**Comment by ebryn** [comment]
I recommend trying out ember-validations: https://github.com/dockyard/ember-validations
