### ISSUE TITLE
box-sizing too small for School & Program selects in CI Report

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1990]
This will provide a little more space on the right side of the drop-downs for School and Program to be selected on the Curriculum Inventory form.

**Comment by saschaben** [comment]
the issue appears to be the style:

```
@media screen and (min-width: 53.75em)
.curriculum-inventory-reports .filter-tools .schoolsfilter select, .curriculum-inventory-reports .filter-tools .programsfilter select {
    width: 90%;
```
where width should instead be set to `initial`.

**Comment by stopfstedt** [comment]
refs #2011

**Comment by stopfstedt** [comment]
i don't understand this request. what's the issue here?
