### ISSUE TITLE
"(In Days)" Missing From Duration Label - New Sequence Block

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1991]
I noticed that when modifying a Sequence Block, the label for Duration includes the (in my opinion, helpful) addition of "days".

![image](https://cloud.githubusercontent.com/assets/7493331/17755033/7b387cb0-648c-11e6-9c4a-a67c61f29ea0.png)

This is missing from the screen when doing a new Sequence Block.

![image](https://cloud.githubusercontent.com/assets/7493331/17755059/a698d15c-648c-11e6-90c8-fffbf81b2545.png)

**Comment by saschaben** [comment]
looks like this just needs a label change in app/templates/components/new-curriculum-inventory-sequence-block.hbs from `general.duration` to `curriculumInventory.durationInDays`.

**Comment by stopfstedt** [comment]
refs #2011

**Comment by stopfstedt** [comment]
closed via #2018
