### ISSUE TITLE
Buttons in header are misaligned on right border

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#1992]
the download and finalize buttons are getting cut off by the right edge of the page container:

![cutoff](https://cloud.githubusercontent.com/assets/1753431/17755984/0aeb292a-6492-11e6-919e-3c029335ca77.png)

**Comment by stopfstedt** [comment]
refs #2011

**Comment by stopfstedt** [comment]
has been addressed already, just checked the demo server and `master` on localhost.
