### ISSUE TITLE
Mouse Pointer Should Indicate Fields Which Can Be Edited - CI Sequence Block

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1993]
This refers to two areas on the form ...

![image](https://cloud.githubusercontent.com/assets/7493331/17756920/2ccc881c-6498-11e6-8025-0a88f9dcb031.png)

**Comment by dartajax** [comment]
The mouse pointer turns into a finger when any of the other form fields are hovered over.  The four areas above do not indicate they can be edited but they can actually be edited.  The same is true for Duration (in Days) but I forgot to put that in my screen shot.

**Comment by stopfstedt** [comment]
refs #2011
