### ISSUE TITLE
Done and Cancel Buttons Objective Mapping Too Far Over to the Right

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1997]
See screen shot ..

![image](https://cloud.githubusercontent.com/assets/7493331/17782794/0aa2327c-652a-11e6-9602-886087d8b756.png)

**Comment by dartajax** [comment]
Related to #1906

**Comment by saschaben** [comment]
This one also looks like it got fixed along the way. @gboushey @dartajax please confirm, and close if obsolete.

**Comment by dartajax** [comment]
I think it's obsolete. LGTM :+1:
