### ISSUE TITLE
Publish buttons on course and session displaying at the same time is confusing

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#202]
@jenzweben please see it there is something we can do about this.
![screen shot 2015-02-26 at 11 46 41 am](https://cloud.githubusercontent.com/assets/349624/6400380/56215118-bdad-11e4-8d01-53f9d72fb5f4.png)

**Comment by jenzweben** [comment]
How about this?  @saschaben please review and assign back to me with comments or assign to @jrjohnson if it's good to go...

![sessions-detail-page-v10](https://cloud.githubusercontent.com/assets/5023894/6403855/2e551948-bdc7-11e4-8d7e-8597750b511a.png)

**Comment by saschaben** [comment]
I like the approach of modifying the session rather than course buttons; considering we still need to provide the multiple publish options in the "dropdown" from the button, we might want to make them a little more button-ish. And while I like the icons, the thumbs-up may be too facebook "like"-ish. thoughts?

**Comment by jenzweben** [comment]
I don't mind the thumbs up / thumbs down because I think it's super obvious but here are 2 other options...

Option 1 - Cloud / Sun

![sessions-detail-page-v11](https://cloud.githubusercontent.com/assets/5023894/6446734/d461a4e4-c0c1-11e4-8267-b940d8ae64de.png)

**Comment by jenzweben** [comment]
Option 2 - Happy face / Meh face

![sessions-detail-page-v11-faces](https://cloud.githubusercontent.com/assets/5023894/6446768/05fedc7e-c0c2-11e4-9f0e-04503249e9c0.png)

**Comment by saschaben** [comment]
Decision on this ticket: for this iteration, style everything with buttons. Course level buttons should say 

UnPublish Course
Publish Course

session level buttons should say 

UnPublish Session
Publish Session

(and can we maybe downsize the buttons for session, if that is a styling issue and not a tweak the controller issue? just a thought)

We will address restyling the buttons for session as icon-paired non-buttonish linky things in a new ticket.

**Comment by jenzweben** [comment]
I can't figure out how to style the publish button... I can only style unpublish.  Please add a class to the publish dropdown so I can style it.  Thanks!
