### ISSUE TITLE
add ability to clone curriculum inventory reports

### ISSUE THREAD

**Issue by stopfstedt** [ilios/frontend#2022]
cloning down to the sequence level.

implement a workflow similar to course cloning.

when cloning a report, the user may specify a different title, description and academic year.

refs #519

**Comment by stopfstedt** [comment]
this requires changes (additions) to the backend.

**Comment by stopfstedt** [comment]
@saschaben i'll need some verbiage here on the report rollover dialog.

![selection_028](https://cloud.githubusercontent.com/assets/1410427/19581748/209b590a-96e4-11e6-9161-ca621e055c4b.png)

Please advise, thanks!

**Comment by saschaben** [comment]
"This action will copy the structure of this report to be used in your target year. It will not copy course information, only the higher level sequence block structure. You will need to add the appropriate course information once you have rolled over the existing report structure."
