### ISSUE TITLE
Updating Name on Course Rollover Causes Cursor to Shoot To End of Text Field

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#2030]
This is similar to the closed issue #1986.

Place the Cursor in the Course Title as Shown below.
\
![image](https://cloud.githubusercontent.com/assets/7493331/17939768/f24b6278-69e0-11e6-958f-fa9a3ebedfe2.png)

I am trying to enter the word "Spring" into the Title field.  The "S" is indicated by the squiggly red arrow and the location of the cursor is indicated by the squiggly blue arrow.  

![image](https://cloud.githubusercontent.com/assets/7493331/17939937/99a325ec-69e1-11e6-8e7f-8e8602d26785.png)

Here is where I was...

https://ilios3-demo.ucsf.edu/courses/1010/rollover

**Comment by jrjohnson** [comment]
Fixes in #2031
