### ISSUE TITLE
Top Border Missing on Container in Learner Group Management

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#2050]
I'm not sure if this happens elsewhere in the application but the top border appears to be missing in Manage Learner Group membership.

Squiggly blue lines have been badly drawn to indicate where I believe the top border should be.  

![image](https://cloud.githubusercontent.com/assets/7493331/18212589/da3e37d6-70f8-11e6-8181-79e6930df622.png)

**Comment by jrjohnson** [comment]
Fixed in #3578 (there is now no border.)
