### ISSUE TITLE
Cascading Delete Needed for Learner Groups

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#2058]
Currently, when you (if you have the permissions) attempt to delete a Learner Group that has Sub Groups, the delete fails in an ugly manner.  Here is an example of the process and the message received once Show Details has been clicked.

![image](https://cloud.githubusercontent.com/assets/7493331/18289961/7057bcac-7436-11e6-94f1-262633f69061.png)

![image](https://cloud.githubusercontent.com/assets/7493331/18289987/86215be2-7436-11e6-97f5-ebbdde6a7636.png)

![image](https://cloud.githubusercontent.com/assets/7493331/18290002/9652d27a-7436-11e6-9d84-7182c1a99805.png)

![image](https://cloud.githubusercontent.com/assets/7493331/18290024/a67a789c-7436-11e6-86ff-d141fab683ab.png)

Cascading the delete down to Sub Groups should be allowed.

**Comment by jrjohnson** [comment]
Moved to API https://github.com/ilios/ilios/issues/1594
