### ISSUE TITLE
A Better Enforcement for File Size of LM's Is Needed

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#2060]
Currently, if a user tries to upload a file that is too large (larger than 110MB), this is what is returned.  

![image](https://cloud.githubusercontent.com/assets/7493331/18293777/d65d4f2c-7449-11e6-8ebb-46534d50bc03.png)

There needs to be a message returned to the user advising about what just happened -- or a message indicating that file chosen is too large and can't be uploaded preventing the upload attempt from even taking place.

**Comment by saschaben** [comment]
see also ilios/ilios#1196
