### ISSUE TITLE
Add calendar to user profile

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#2061]
rather than create an auth-challenging spoofing system in order to see another user's calendar, what about providing the user profile page with a mini calendar display?

Could be either graphical or the agenda view. No filters, no customizations. Just user-specific events display.

Should be considered in conjunction with visualization tools to show progress in curriculum.

**Comment by saschaben** [comment]
N.B. this would have to be deployed after the implementation of granular permissions, in order to provide the appropriate level of  privacy/security to student schedule data.

**Comment by dartajax** [comment]
This is a great idea.
