### ISSUE TITLE
Toggling The Independent Learning Switches Results In An Error

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#2088]
This is true for Sessions which initially are not toggled to Independent Learning.  

See below.

Click the Toggle - Initially set to not Independent Learning.
![image](https://cloud.githubusercontent.com/assets/7493331/18495810/9c1bdb26-79d5-11e6-8fbd-3c1ce90b613c.png)

It seems to have worked OK.

![image](https://cloud.githubusercontent.com/assets/7493331/18495819/b11bf16e-79d5-11e6-845a-9de3d24e7f7b.png)

Now toggle back ...

![image](https://cloud.githubusercontent.com/assets/7493331/18495826/c0736b9c-79d5-11e6-9ed9-342ec04ab34e.png)

You may have to toggle back and forth more than once to get the error shown below ..

![image](https://cloud.githubusercontent.com/assets/7493331/18495844/dbbab32e-79d5-11e6-9e9b-a9b671227d95.png)

I noticed that the toggle itself seemed to try to switch back to the Yes position and then when the click is performed, the error above results.

**Comment by dartajax** [comment]
I managed to get a payload error as well when toggling quickly and shortly after the session loads up 

![image](https://cloud.githubusercontent.com/assets/7493331/18495886/2265b03a-79d6-11e6-9ebe-4795f43ab176.png)

**Comment by stopfstedt** [comment]
convert to be a droppable task to prevent rager-clickers from borking things up.

**Comment by dartajax** [comment]
I rage clicked quite a bit and was unable to reproduce. Gonna close this one.
