### ISSUE TITLE
Missing Translation

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#2095]
![image](https://cloud.githubusercontent.com/assets/7493331/18564564/e878947a-7b40-11e6-9691-7d3c2085a901.png)

When you mouse over the (+) icon, the missing translation error appears.

general.moveToGroup

**Comment by dartajax** [comment]
I am not so sure I am finding this one anymore.

**Comment by saschaben** [comment]
@dartajax yeah..this appears to be fixed now...
