### ISSUE TITLE
Curriculum Inventory Report requires loading indicator on Download

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#2113]
when a user downloads a report, we need either a loading indicator/spinner, or a modal to display on the page to alert the user to activity requiring a wait until the file has been generated and the download window opens.

**Comment by stopfstedt** [comment]
In Ilios2, we [solved this problem](https://github.com/ilios/ilios/blob/2.4.x/web/application/views/curriculum_inventory/js/ilios.cim.view.js#L1025) with a kludgy technique that relies on a cookies. There is no equivalent with the API backend server in Ilios3.

Looking for alternatives - we could throw up flash message that alerts the user that the download has started and that it may take a while.

**Comment by stopfstedt** [comment]
closed via #2203.
