### ISSUE TITLE
Special Equipment and/or Attire Indicators Missing From Detail Page

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#2118]
Currently, there is no way to tell (as a Student) if Special Equipment is needed and/or is Special Attire is needed.  There used to be an icon on the Calendar and a written indication on the Detail Screen.  See several screen shots below for example.

![image](https://cloud.githubusercontent.com/assets/7493331/18650280/18d44494-7e79-11e6-8694-e32a04d4db31.png)

![image](https://cloud.githubusercontent.com/assets/7493331/18650306/44161a06-7e79-11e6-88c1-4dc0666458f3.png)

![image](https://cloud.githubusercontent.com/assets/7493331/18650324/5506e016-7e79-11e6-8fea-6d029791da8b.png)

Nothing available for Special Equipment or Attire available on mouse-over either.

With other details removed, the Detail Screen only indicates as shown below that this Session is a Laboratory.  It doesn't advise here either about whether special Attire or Equipment are needed.

**Comment by dartajax** [comment]
![image](https://cloud.githubusercontent.com/assets/7493331/18650469/0e55fca0-7e7a-11e6-915e-e0c2e73b72fd.png)

**Comment by jrjohnson** [comment]
@dartajax / @saschaben what should this look like?  Should it be an icon or text?  What text and what icon should we use?

**Comment by saschaben** [comment]
On the detail page:
text & icon, directly beneath the session type display:

> This session is "Laboratory"
> Special Equipment is required <fa-flask>
> Special Attire is required [still seeking an icon]

On the calendar event blocks, display icons only, with the above text in the mouseover.

**Comment by stopfstedt** [comment]
special attire http://fontawesome.io/icon/black-tie/
