### ISSUE TITLE
Hide Delete Action Button When Learner Groups Have Attached Offerings

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#2119]
If a Learner Group has Offerings associated with it - in any Published state - the Delete Trash can icon should not appear.

![image](https://cloud.githubusercontent.com/assets/7493331/18651757/278411b4-7e82-11e6-9648-455a92c71db4.png)

If Learner Group "A" in the example above has associated Offerings, the trash can should not be visible.

**Comment by jrjohnson** [comment]
We don't hide it, but we do grey it out and disable it now. I think that's good enough.
