### ISSUE TITLE
Ember Form Validation Not Recognizing Valid User Names in Admin Console

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#2121]
After synching up a user and attempting to save, the error results ...

![image](https://cloud.githubusercontent.com/assets/7493331/18680697/aedb9d3e-7f19-11e6-8392-3d8ef5ac384f.png)

The form is not recognizing the data as correct - probably not seeing it as anything at all - empty string or NULL.

To reproduce,

1. Pull up a user record in the Admin Console
2. Click the sync button.
3. Click the save button.
4. Review and appreciate the resulting error.

The field is in a "disabled" status at UCSF to avoid the insertion of junk data.

**Comment by saschaben** [comment]
FYI, `The field is in a "disabled" status at UCSF to avoid the insertion of junk data` is only an assumption, not a certainty, and needs to be validated by @jrjohnson

**Comment by jrjohnson** [comment]
This is caused by not allowing a dot or @ symbol in this field.
