### ISSUE TITLE
Citation LM's Need to Display The Citation - Print View

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#2139]
The citation itself needs to be displayed in the Summary Print View of a Course.

Currently, this is what shows up.  We will be adding links and reorganizing the screen significantly.  Even so, more information should be visible immediately from the Print View.

![image](https://cloud.githubusercontent.com/assets/7493331/18768650/a6ec21ac-80db-11e6-972f-de69c1e70d44.png)

**Comment by stopfstedt** [comment]
i could use some more feedback here before getting started on this.
exactly where should the citation show up in that table?  a mock-up would be helpful, thanks.
