### ISSUE TITLE
MeSH Breakdown

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#214]
What are all the components of a mesh term that we need to display and how should we organize the API around those components?

**Comment by saschaben** [comment]
Regarding Display: we want to be able to display the data exposed in the current search results: the user-entered search term, the term or descriptor name, the UID (whether a descriptor ID or a descriptor and concept ID), and the annotation or scope notes (truncated at 150 characters) for the term.

Let's talk about approaches on this: mesh is challenging.

**Comment by saschaben** [comment]
Currently the items we want to display that are being returned by the API (per #144):

NAME
ID 
ANNOTATION
(SEARCH TERM)

the other information (qualifiers, concept IDs, etc) are not currently needed for display. At least not in this iteration.

**Comment by jrjohnson** [comment]
Closing in favor of #825
