### ISSUE TITLE
CI Sequence Block start and end dates shown incorrectly in Ilios frontend

### ISSUE THREAD

**Issue by mtb3** [ilios/frontend#2164]
A user reported this issue with the start and end dates of Sequence Blocks being added (or edited) using the Curriculum Inventory tool in Ilios. This is with Ilios 3.19.0.

After the dates are entered and saved in Ilios, if the user then logs out and back in, the dates are being shown one day off (early) in the CI tool.

For example, the following screenshots were taken during this process for an example course.

If the start date is first set to 8/03/2015:

![ilios_cir_edit_date](https://cloud.githubusercontent.com/assets/3044074/18919790/5feab3ea-856d-11e6-8efd-407f24db492e.png)

The CI tool shows the correct date after it is saved:

![ilios_cir_date_before](https://cloud.githubusercontent.com/assets/3044074/18919802/69b4a91c-856d-11e6-8f09-5d17c2dc6d19.png)

But then after logging out of Ilios, logging back in, and returning to this sequence block in the CI tools, the wrong date is reflected (it is one day earlier):

![ilios_cir_date_after](https://cloud.githubusercontent.com/assets/3044074/18919829/7bc03b3a-856d-11e6-91dd-c6ffb4853528.png)

Note that the correct date is stored in the Ilios backend. I have not tested every possible scenario to try to isolate the circumstances where this problem occurs, but I am able to reproduce per the screenshots shown above.

**Comment by saschaben** [comment]
@mtb3 Thanks for reporting this issue. We will get it reviewed asap.

**Comment by saschaben** [comment]
@mtb3 one question - do you what time of day this was identified, and when you tested? I only ask to see if we can pinpoint or rule out that this might be a local time vs. UTC conversion issue.

**Comment by mtb3** [comment]
@saschaben I reproduced the issue right before I reported it this morning (thus around 11:15am EDT today).

Also, as an FYI: this issue (fortunately) isn't urgent for us, as the data is reflected correctly on the backend and in the CI report.
