### ISSUE TITLE
add form validation to login form.

### ISSUE THREAD

**Issue by stopfstedt** [ilios/frontend#2171]
at the very least, the presence of username and password should be ensured before a login request to the backend is issued.

refs #2166

**Comment by stopfstedt** [comment]
currently handled on the server-side, so not a hot issue. nevertheless, this should be added.

**Comment by mhgh22** [comment]
Unclear about the issue. -Michael/Nanci/Stacey

**Comment by stopfstedt** [comment]
confirming that this indeed still an issue. 

![image](https://user-images.githubusercontent.com/1410427/162833824-4630e30a-df7a-4deb-8619-5899ab48b12e.png)

if no username/password are provided, then the application shouldn't even send a login-request to the backend. 

working on it.
