### ISSUE TITLE
Style Objective Manager

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#218]
objectivemanager.scss needs to be fixed, it lost a lot of its defaults in the #189 changeover.  Styles course and session objectives.

**Comment by jenzweben** [comment]
I've styled as much as I can for the moment - there are a few things that we need to fix in the template.  For some reason, the header of the section of a selected item is having the selected item styling applied to it...

Attaching the mock here for reference:
![screen shot 2015-03-02 at 12 45 13 pm](https://cloud.githubusercontent.com/assets/5023894/6450137/9dcb3d3c-c0da-11e4-8c4d-8bd84069a944.png)

Screenshot of header taking on selected item styling:
![screen shot 2015-03-02 at 12 48 34 pm](https://cloud.githubusercontent.com/assets/5023894/6450192/fef3d696-c0da-11e4-8a1b-0d6bd579b843.png)

**Comment by jrjohnson** [comment]
The header picking up selected style is intentional, indicates which competency is selected.
