### ISSUE TITLE
instructor dropdown in Offering needs work

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#2192]
right now the instructor offering pushes the action buttons (and the group listings) far off the bottom of the screen if there are more than just a few values returned in the drop down list. This is sub-optimal. we should replace with a different pattern -- either change the return list to a scrolling box displaying 10 names max, or (less good) make instructor selection a manager component, or move the action buttons, or force the close of the list on every selection and make the user search atomically for each name desired.

**Comment by jrjohnson** [comment]
Fixed in #3578
