### ISSUE TITLE
Validate login errors before displaying them

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#2207]
We are currently trusting the server to return a good translatable error messages, but it is also possible to get the attached:
<img width="469" alt="screen shot 2016-10-09 at 9 10 20 pm" src="https://cloud.githubusercontent.com/assets/349624/19226781/e6cd31f8-8e64-11e6-85f2-99ac4ba0fa32.png">

**Comment by saschaben** [comment]
Ouch!
