### ISSUE TITLE
500 Payload Error Received When Assigning School Permissions in Admin Console

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#2209]
This is another one where I was checking some user permissions and I needed to update a user's account.  On prod and on stage, it processed the request and the Clear Errors functionality seemed to resolve the situation as well.  But, here is the error received.  This error was received when either adding permissions (read/write) or removing permissions (read/write).  When I removed a user's "write" rights only, I received an extra pair of errors.

![image](https://cloud.githubusercontent.com/assets/7493331/19253164/05a07876-8efe-11e6-905c-fd7ac9541813.png)

**Comment by dartajax** [comment]
It does not always fail.  I had success adding just one more school to a user's record with only one school - adding Faculty Dev to a SOM user.  Maybe this is because those two schools are related?

**Comment by jrjohnson** [comment]
Unable to duplicate on demo or ilios3-stage.  @dartajax can you provide specifics about what user was being added to which school?

**Comment by dartajax** [comment]
I couldn't reproduce either but will try again in a bit.
