### ISSUE TITLE
Click Back Button On Admin While Search Is Being Performed Returns the Child Node Missing Error

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#2215]
I was doing a bunch of searches and decided to click back button and received the following error message.  This is similar to the error message received in Course Rollover.

![image](https://cloud.githubusercontent.com/assets/7493331/19287574/09cc0f8c-8fb7-11e6-8d91-f62c43dbe1a4.png)

**Comment by dartajax** [comment]
This was from the "View All" in Admin.

**Comment by stopfstedt** [comment]
i'm not actively working on this right now, so i'm releasing it back into the pool of unassigned tasks.

**Comment by djvoa12** [comment]
I think this squashed itself. I followed these steps:
1) Click "Admin" on the left navigation.
2) Click "View All" link.
3) Enter random values into the user search box at the top.
4) Click browser "Back" button.
5) Observe that no global error occurs.

@dartajax can you confirm?

**Comment by dartajax** [comment]
I can't reproduce. I will self-assign and close.
