### ISSUE TITLE
Apply slide transition to all internal pages

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#222]
**RESPONSE**: Let's determine the correct pattern for each type of transition, and what animation will be used to address it. This will go into our style guide (available on the github wiki) and be the basis for future decision making when coding transition segments.

_**PROBLEM POSED**: The current transition from session list to session detail within a course is the optimal pattern for all transitions from a large object (like course) or list to a more detailed portion of that object (like session). This should be applied as our default desired behavior._

**Comment by saschaben** [comment]
Also: we need to review **_ALL_** transitions to make certain that we are expanding content in the appropriate real estate to ensure no loss of context core the user: this means noting the placement/continuity of header information, associative data, and links.

**Comment by jenzweben** [comment]
Also we need to make sure that all content comes in from the right and goes out to the right...currently parent objectives are coming in from the left and whilst I understand that a parent is a level up, it's disorienting to have it come in from the left

**Comment by jrjohnson** [comment]
I broke out the issue @jenzweben reported with objectives into its own issue.  The other things in this ticket are too generic.  @saschaben - can you modify this ticket to list the places where transitions need to happen or else create new tickets for each new transition?

**Comment by jrjohnson** [comment]
Individual tickets are open to add these animations.  I'm closing this generic ticket.
