### ISSUE TITLE
Provide "LM Agenda View" on Student Dashboard

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#2230]
Allow for a weekly type view of current resources as a parallel to our Agenda view in the dashboard -- instead of events, it would list the current and upcoming list of LMs associated with the activities in the Agenda list, sorted by week/due date.

![udpated](https://cloud.githubusercontent.com/assets/1753431/19095512/d787e9e0-8a4a-11e6-9dd4-fc51506c1e27.png)

this is in conjunction with #1665

**Comment by saschaben** [comment]
Note that this includes 2 distinct dashboard issues: 1; the agenda view, and 2: the new "MyCourses" list for student dashboard,  which is unlinked course names (unless of course a student is assigned as an instructor / director with privileges in the new permissions matrix), with a fa-archive icon link to go to the LM list for the course.

**Comment by jrjohnson** [comment]
Requires https://github.com/ilios/ilios/issues/1661
