### ISSUE TITLE
Getting This Error When Accessing the Admin Console (Manage Cohort)

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#2234]
![image](https://cloud.githubusercontent.com/assets/7493331/19369261/3a4fd69a-9159-11e6-96c3-af2aafc7dd24.png)

**Comment by dartajax** [comment]
Hitting the `Clear Errors and Return to Ilios` button takes the error message count from 6 down to 4 but does not clear up the situation.

**Comment by dartajax** [comment]
```https://ilios-stage.ucsf.edu/users/10996?isManagingCohorts=true```

**Comment by dartajax** [comment]
It happens when trying to load up the Cohorts.

**Comment by dartajax** [comment]
It does NOT happen on `https://ilios3-stage.ucsf.edu/users/10996?isManagingCohorts=true`

**Comment by saschaben** [comment]
this appears to be a data driven error, but we need to identify the gap where the bad data got in, and what exactly is causing the issue.

**Comment by stopfstedt** [comment]
fixed by deleting offending program year without cohort.
