### ISSUE TITLE
ILIOS_FRONTEND_API_HOST doesn't handle slash well

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#2243]
If you specify this env variable with a trailing slash you end up with a double // on requests to the server which then die.  We should handle a trailing slash better.

**Comment by stopfstedt** [comment]
i don't really see the issue here. as long as we know that the backend URL is not coming with a trailing slash out of the config, and we know that reliably, then we can code accordingly and always add the slash ourselves.

**Comment by stopfstedt** [comment]
fixed via #2310
