### ISSUE TITLE
Replace Edit Icon With Eyeball Icon When Read-Only in CI

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#2247]
This is true for finalized CI reports as well as sequence blocks and nested sequence blocks.

![image](https://cloud.githubusercontent.com/assets/7493331/19491826/2eb7bfb8-9529-11e6-8c3c-6b8948877728.png)

![image](https://cloud.githubusercontent.com/assets/7493331/19491838/3ca4e81c-9529-11e6-917f-c50b1e59d2f5.png)

![image](https://cloud.githubusercontent.com/assets/7493331/19491857/4e82e2be-9529-11e6-99c6-3ab5f82f3960.png)

**Comment by stopfstedt** [comment]
the eyeball was there originally, but i replaced it with the edit icon for consistency reasons. also, we're using the eyeball in other places and for other purposes already (as a "show more" in the sessions table on a course page).
i'll close this ticket as "won't fix" for now.
