### ISSUE TITLE
Parent Learner Groups Are Not Being Attached to Offerings 

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#2253]
In the example below, I want to attach `ABG Small Group 1` and its sub group `ABG Small Sub 1` both to the offering.

![image](https://cloud.githubusercontent.com/assets/7493331/19532391/5b72a668-95f0-11e6-83b5-8c8537fb060a.png)

This is done by selecting `ABG Small Group 1` and by inference `ABG Small Sub 1` as well since it is a sub group of the group that was selected.

It looks good judging from the screen shot below.

They both appear to be attached to the Offering; however the Save action has not been performed yet.

![image](https://cloud.githubusercontent.com/assets/7493331/19532466/b4748e0c-95f0-11e6-84dc-a9cfdef6084e.png)

After saving ...

![image](https://cloud.githubusercontent.com/assets/7493331/19532496/cf881da8-95f0-11e6-8f86-6cd872d37f6e.png)

Only `ABG Small Sub 1` has been actually added to the Offering.

This is visible from the header as well.

![image](https://cloud.githubusercontent.com/assets/7493331/19532561/1311ab66-95f1-11e6-8696-2efbfb43dea5.png)

After clicking Edit again on the Offerings Editor, it is now obvious here too that the higher level learner group `ABG Small Group 1`, which is the parent of `ABG Small Sub 1` is now available for selection.  It should be attached to the offering.

![image](https://cloud.githubusercontent.com/assets/7493331/19532704/c324d03c-95f1-11e6-9ebf-87bef0d9b116.png)

Even after re-selecting `ABG Small Group 1`, it does not get attached after the Save event is processed.

**Comment by jrjohnson** [comment]
@saschaben is this a bug? Seems like it might just be the behavior we expect since you're attaching only to the leafmost node of the tree. Should you be able to attach to a top group and *not* all of its leafs?

**Comment by saschaben** [comment]
@jrjohnson I believe this is just inconsistency in display: selecting a top-level group will by nature include ALL sub-leaves. by selecting a subset of lower lever leaves from a group, we by nature stop the inclusion of the top level group (if TOP = 1+2+3, then 1+2-3 <> TOP anymore). This isn't a bug per se, but we aren't expressing it well in the UI.

**Comment by dartajax** [comment]
duplicate
