### ISSUE TITLE
CI Academic Year Selector Should Enforce One CI Report per Year

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#2257]
Since there is only one CI Report that can be generated for each Academic Year, the Years for which CI Reports CI Reports have already been generated should not be available in the drop-down menu for selection.

![image](https://cloud.githubusercontent.com/assets/7493331/19541711/3634fdc4-961d-11e6-9399-d7ff45723180.png)

There is currently no problem adding a duplicate.

![image](https://cloud.githubusercontent.com/assets/7493331/19541726/503fd2ac-961d-11e6-8afb-f57dfa8379c6.png)

**Comment by stopfstedt** [comment]
non-issue. this was discussed, and there is no hard business reason to force uniqueness here.
