### ISSUE TITLE
Replace go away nav with tab for offering and learnign material details

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#227]
Currently when a use opens a parent objective on a course it opens in a new page.  Instead open the content within the objective detail pane on the course edit page.

**Comment by jenzweben** [comment]
Edit MeSH mock
![course-detail-page-editmode-tabs-mesh](https://cloud.githubusercontent.com/assets/5023894/6401773/8bd0dbf8-bdb7-11e4-8a42-850d2ff8ab7f.png)

**Comment by jenzweben** [comment]
Edit Parent Objective Mock:

![course-detail-page-editmode-tabs-parentobjectives](https://cloud.githubusercontent.com/assets/5023894/6401779/9ba59d3e-bdb7-11e4-8dc4-329f81e3df56.png)

**Comment by jenzweben** [comment]
Adding MeSH to an Objective:

![course-detail-page-editmode-tabs-mesh](https://cloud.githubusercontent.com/assets/5023894/6402248/0ab98a84-bdbb-11e4-911e-7186fdec5130.png)

**Comment by jenzweben** [comment]
Adding Parent Objective:

![course-detail-page-editmode-tabs-parentobjectives](https://cloud.githubusercontent.com/assets/5023894/6402263/1b637624-bdbb-11e4-8319-ef4a3052c8c7.png)
