### ISSUE TITLE
delete icon does not get added/removed when program year gets unpublished/published.

### ISSUE THREAD

**Issue by stopfstedt** [ilios/frontend#2283]
find an unpublished program year with an empty cohort from a list. note that the trashbin/delete icon is shown next to it. now, open that program year and publish it. return to the list of program years.
you would expect that the trashbin icon does not show since the programyear is published. the trashbin is still there. refresh the page, and it's gone.
the same applies to the reverse scenario, where unpublishing a published program year should result in the trashbin being shown, but it's not (until the page is refreshed).

fix this.

**Comment by djvoa12** [comment]
Closing as this workflow does not exist anymore per @stopfstedt.
