### ISSUE TITLE
Draft Learning Materials Showing Up in Calendar Feed

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#2292]
From a Student's feed ...

![image](https://cloud.githubusercontent.com/assets/7493331/19777856/f672a818-9c2e-11e6-9528-cdd1a9bde3e8.png)

From Ilios Courses and Sessions ...

![image](https://cloud.githubusercontent.com/assets/7493331/19777890/179f3916-9c2f-11e6-87f1-61b254065e4c.png)

Course / Session reported ...

https://curriculum.ucsf.edu/courses/1010/sessions/28986

**Comment by jrjohnson** [comment]
Moved to https://github.com/ilios/ilios/issues/1659
