### ISSUE TITLE
Add link to course materials from calendar event view

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#2301]
a link should be added to the calendar event page, to access the course materials page,  à la the print summary. Route should be accessed by the `fa-archive` icon displayed appended to the materials label:

![claarch](https://cloud.githubusercontent.com/assets/1753431/19864708/aa248262-9f56-11e6-998d-77627d838e5b.png)

**Comment by saschaben** [comment]
see also #2230

**Comment by dartajax** [comment]
Review for closure - may not be necessary anymore.

**Comment by dartajax** [comment]
The links that @saschaben indicated at the top of this ticket would take the users to the Learning Materials Summary for this Course. To get there from Courses and Sessions ...

![image](https://user-images.githubusercontent.com/7493331/56701627-f3169280-66b4-11e9-8a36-548afb6a8e59.png)

`Access All Materials for this Course` is the current call out label as shown in the initial screen shot at the top of the ticket. User would see something like ...
![image](https://user-images.githubusercontent.com/7493331/56701709-4852a400-66b5-11e9-94cf-ae317c36de2e.png)

... after clicking the link.

**Comment by dartajax** [comment]
Steps to reproduce ...

* Login into demo3 or local as Admin User
* Click Calendar
* Click All Events
* Do a filter on Pathogens ... 
![image](https://user-images.githubusercontent.com/7493331/56775802-9c28c000-677d-11e9-99da-ef5ee33f3862.png)
* Click on the Calendar Event dated 4/22 at 8:10 am
* You end up at Calendar Detail
https://ilios3-demo.ucsf.edu/events/S0120190422O134965
![image](https://user-images.githubusercontent.com/7493331/56775862-f3c72b80-677d-11e9-8e78-5c3cfba87a3d.png)
* The screen shown above should have the links to Learning Materials Summary (refer to screen shot at top of Git issue for reference)
https://ilios3-demo.ucsf.edu/courses/1505/materials
