### ISSUE TITLE
Publish Action does not fire in IE11

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#2316]
Selecting a `Publish` `Schedule` or `Publish As-Is` action from a Publish drop down control fails in IE 11.

fix it!

**Comment by jrjohnson** [comment]
This may be a deeper Ember bug.  Unfortunately IE doesn't play nicely with ember-twiddle so it is hard to tell.  I'm going to have to spin up an app with just a `li` that can be clicked and see if I can get actions to fire.

**Comment by jrjohnson** [comment]
Not an ember bug.  I built a new application with just this issue and it works fine in ie11. So this is on our end for sure.
