### ISSUE TITLE
Program Year >> Manage Terms Button Too Far Over to the Right

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#2343]
See the screen shot for details.

![image](https://cloud.githubusercontent.com/assets/7493331/20120496/ef57aeba-a5c1-11e6-838f-801df91e09da.png)

**Comment by gboushey** [comment]
@dartajax @saschaben Looks like this may have been resolved by an earlier fix.  Checked this morning and alignment of buttons on program detail page is no longer too far to right, appears to be be working properly.

**Comment by saschaben** [comment]
Yes, thiss appears to be resolved --- @dartajax please confirm and if OK please close.

**Comment by dartajax** [comment]
Will do.

**Comment by dartajax** [comment]
LGTM :+1:
