### ISSUE TITLE
Program Cohort Level Display Is Incorrect

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#2381]
At this point in time, Class of 2019 is Level 2 and Class of 2020 is Level 1 but as shown in the screen shot below, Class of 2019 is being listed as Level 1 but it should be Level 2.

![image](https://cloud.githubusercontent.com/assets/7493331/20574095/c369564e-b167-11e6-9cfe-a11b3e0bb996.png)

**Comment by saschaben** [comment]
not a bug. the level of a cohort and the assigned level of a course are not linked. a course cold be set to  level 1, yet have cohorts which are at levels 2,3,4 associated with it. we do not and do not plan to enforce any relationship here.

**Comment by saschaben** [comment]
if the bug is only that the cohort level display is incorrect, please correct the ticket.

**Comment by dartajax** [comment]
That is the bug.  The Cohort Level Display Is Incorrect.

**Comment by dartajax** [comment]
This is possibly related to ilios/ilios - 308 and 309.

**Comment by dartajax** [comment]
Can we fix this one? When you look at the first year cohort, it shows up as level 0. It should be level 1 - it's confusing to users and to me as well.

**Comment by dartajax** [comment]
* Log in to demo or netlify as an admin user 
* Go to `Courses and Sessions`
* Add a New Course

**Comment by dartajax** [comment]
* Open up the new Course 
* Click `Show Details`

**Comment by dartajax** [comment]
* Scroll down to `Program Cohorts`
* Click `Manage Cohorts`

**Comment by dartajax** [comment]
Disregard the above - bug may have been squashed.

**Comment by dartajax** [comment]
I just re-tested again - doesn't seem to be a problem anymore.
