### ISSUE TITLE
Learning material notes don't display on course print page

### ISSUE THREAD

**Issue by gboushey** [ilios/frontend#2382]
Learning material notes don't display on a print page.

In the print-course.hbs template, we iterate through the sessionLearningMaterials and call attributes  via lm.learningMaterial.notes.  This is the correct pattern for most learning material data, but notes is attached to the sessionLearningMaterial, so we need access this directly on sessionLearningMaterial via lm.notes.  This attribute doesn't exist for the learningMaterial model. 

Because the length of a note can be long, we may want to discuss how to allocate column width to this field before putting in a fix.

**Comment by saschaben** [comment]
Let's definitely review prior to developing a fix; since notes can variously be directed toward learners or explicitly hidden from learners, we will want to think about how this is reflected in any presentation.

**Comment by gboushey** [comment]
I should clarify this:

as it stands, in print-course.hbs, we are calling

`{{lm.learningMaterial.notes}}`

This field ("notes")  doesn't exist on learning-material.js, it only exists in the subclasses session-learning-material.js and course-learning-material.js.  The code is looping through the session-learning-material, calling the parent class, and trying to access a field that doesn't exist.  The fix is very simple - instead of calling the parent class, just access the field directly on the session learning material

`{{lm.notes}}`

Sounds like we don't want to print the notes field anyway?  If so, I won't put in a pull request.  

@jrjohnson - want to just leave this as is for now?  I'd call it a "bug" if we're trying to access a variable that doesn't exist, but since we don't want to display it, it's probably not a particularly important thing to fix...
