### ISSUE TITLE
Escape Regular Expressions on Course Filter

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#2386]
See the title ...

Adding expressions such as `\` causes problems when searching for a course.

**Comment by dartajax** [comment]
After hitting the backspace key on the keyboard, you get this ...

![image](https://cloud.githubusercontent.com/assets/7493331/20689278/7068ef84-b579-11e6-8435-302fd7b48907.png)

**Comment by saschaben** [comment]
This must be addressed globally. Affects course filter (course list page), session filter (course management page), learning materials filter (My Materials).
