### ISSUE TITLE
My Reports - All Learning Materials for Course Not Returning All Data

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#2445]
Here is the definition from the matrix of this report ...

```all learning materials attached at course or session level to the selected course (C+S)```

When a report of All Learning Materials for a Course is run, only the Course level Learning Materials are returned in the Report.

**Comment by saschaben** [comment]
see also #1637

**Comment by jrjohnson** [comment]
This is likley fixed and just needs to be tested and closed.

**Comment by saschaben** [comment]
Not fixed. This report query currently only returns course-level LMs. Should be modified to return all LMs for course and sessions (and ILM sessions)  of the course.
