### ISSUE TITLE
Update "Loading" wave for topic load etc

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#245]
the current image for loading with its "loading Ilios" tag is inappropriate for the overlays internal to a course or other entity in the system when adding/removing a topic or a tag or whatever where we are doing stuff.

Create a new wave loader which either says "saving" or is just a naked wave for use in these instances.

**Comment by jrjohnson** [comment]
@jenzweben - you probably just need to make a decision here.  Do we need to say ```Saving...``` or ```Saving Topics``` or just a plain loader with no text at all.  The wave loader component will need to be modified to do this work, but I can do that modification and I don't think any CSS will need to change unless you want to use a different animation for those cases.

**Comment by jenzweben** [comment]
I am working on a simpler loading animation so let me think about this...but off the top of my head I think "Saving..." is good and we can animate this elipses.  I will create the css for this...

**Comment by jenzweben** [comment]
Here's an update http://monsoon-design.com/UCSF/pulse2.html  I will keep working on this because I want it to "draw itself"

**Comment by saschaben** [comment]
@jenzweben I like this but I'm not sure it feels quite as friendly as the wavicle. awaiting the next draw itself version.

**Comment by jenzweben** [comment]
perhaps a thicker line and curves instead of points?

**Comment by saschaben** [comment]
I think yes on both --- esp. the curves.

**Comment by jenzweben** [comment]
Draws itself http://monsoon-design.com/UCSF/pulse4.html  but I still need to finesse it a bit to enhance friendliness and will try out some gradient stuff too.

**Comment by jrjohnson** [comment]
Yes!

**Comment by jenzweben** [comment]
:)

**Comment by jenzweben** [comment]
Draws and erases itself...http://monsoon-design.com/UCSF/pulse5.html

**Comment by saschaben** [comment]
slick. At the moment it gives me flashbacks to grad school (it's vaguely UT-esque: "Hook'em 'horns!").

**Comment by jrjohnson** [comment]
Can it start erasing itself sooner?  Like before it is done drawing soon?  Might end up being a bad idea, but I think it would feel less like a loop if the erase happened sooner.

**Comment by saschaben** [comment]
@jrjohnson yes, this is what I was originally thinking with my comment in the meeting: not a loop but a worm. @jenzweben if it's doable, let's do it.

**Comment by jenzweben** [comment]
Here's what we should go with http://monsoon-design.com/UCSF/pulse5.html  I will still keep experimenting and if I can do the worm then it will be icing on the cake

**Comment by jenzweben** [comment]
Here's one for saving http://monsoon-design.com/UCSF/saving.html  tested on chrome, ff & safari

**Comment by jrjohnson** [comment]
Note for developers: http://connoratherton.com/loaders has a bunch of fast loading animations.  See what they're doing differently to make the 'performant' when we implement this one.

**Comment by jenzweben** [comment]
updated loading animation http://monsoon-design.com/UCSF/pulse8.html
