### ISSUE TITLE
Clicking on a Multi-Day Event Link Causes a 'slug' Error to be Raised

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#2474]
![image](https://cloud.githubusercontent.com/assets/7493331/21664178/d9d19f2e-d299-11e6-8a89-12c344d9e8bf.png)

To reproduce, 

![image](https://cloud.githubusercontent.com/assets/7493331/21664198/050df070-d29a-11e6-852b-9082eb9c8845.png)

scroll down and click one of the multi-day links 

![image](https://cloud.githubusercontent.com/assets/7493331/21664307/7aaa15ca-d29a-11e6-87a2-04439f7c910e.png)

Is this something that used to work and now does not?

**Comment by stopfstedt** [comment]
fixed via  ilios/calendar#147.
