### ISSUE TITLE
More Color / Shading Contrast Needed in Button Selectors (Offering vs Small Groups)

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#2477]
It seems difficult to tell which type of Offering is going to be created.  See the screen shot below.  The shading is too similar between the two buttons.  We should come with buttons that have a bigger visible difference when they are selected or not.

These buttons are used in other places throughout the application.  I just happened to notice it while doing offering creation.

![image](https://cloud.githubusercontent.com/assets/7493331/21694852/0cc32752-d33c-11e6-82d5-dfac48b72088.png)

**Comment by stopfstedt** [comment]
looks like this now:

![Selection_259](https://user-images.githubusercontent.com/1410427/95137658-6a12e000-071d-11eb-94a9-26dca3b6f567.png)
