### ISSUE TITLE
Design better consistent display for parent objectives

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#248]
Need a way to display one or more parent objectives that is consistent and does not cause a context break between showing one and showing many.

For course: as discussed, let's go with the current _Parent Obj. Text (Parent Competency)_ when only one parent chosen (ie only one cohort), and _Name of Cohort (Parent Comepetency)_ for more than one, along with some sort of tooltip / info link to show full info. should use ellipsis on these as well.

For session: we need something that will be more generic for both 1 or 1+n patterns, that won't discourage the actual linking of multiple parents, nor make the content of those parents completely opaque.

**Comment by jenzweben** [comment]
![screen shot 2015-03-03 at 8 55 24 am](https://cloud.githubusercontent.com/assets/5023894/6467448/17df3314-c183-11e4-9736-ff91736b65c9.png)

**Comment by saschaben** [comment]
@jenzweben this looks great. Can you add a quick mock (or a note to this mock) for the case where only one cohort is available (and we don't show the cohort name)? This will require some slick code changes by @jrjohnson to allow for the *IF* statement in the cohort selector as well as the course objective display, but I think it will be the best solution.

**Comment by jenzweben** [comment]
1 Cohort Mock
![screen shot 2015-03-03 at 9 40 15 am](https://cloud.githubusercontent.com/assets/5023894/6468353/5d59fc3e-c189-11e4-8eac-21fd2c47780b.png)

**Comment by saschaben** [comment]
alrighty -- @jrjohnson I believe this is ready for the code mill.

**Comment by jrjohnson** [comment]
@saschaben - have you imagined this mock when there are 25 objectives each with a double link?  I'm concerned it may be difficult to see which objective connects to which competency when we're not at the bottom of the screen.  Maybe @jenzweben can create a more detailed mock?  Alternatively I can just build this and we can iterate as long as the basic concept is going to work.

**Comment by saschaben** [comment]
@jrjohnson I think we need to just iterate on this: the double links would make it a busy panel, yes, but keep in mind that this is an exception case, not the primary use case. I think this model is "good enough" for an initial launch -- certainly better than what we have now.

**Comment by jrjohnson** [comment]
Sounds good.

**Comment by jrjohnson** [comment]
@saschaben, @jenzweben - how does this work with multiple parents on the session objectives?  Do we display the cohort there as well?  The course?  Just the multiple parents?

Choose Wisely: Nothing is easiest.  The course title is easy.  The program title for the parent objective is hard.

**Comment by saschaben** [comment]
@jrjohnson I think that we need to consider that the case for sessions is different than for course:

For course, the common use case is 
>  1 objective > 1 cohort > 1 parent. 

the pattern of
> 1 objective > 1 + _n_ cohorts > 1 + _n_ parents

 is the exception.

For sessions, the common use patterns are
> 1 objective > 1 cohort > 1 + _n_ parents (the desired or encouraged pattern)
>  1 objective > 1 cohort > 1 parent (the lazy option). 

the exception is 
> 1 objective > 1 + _n_ cohorts > 1 + _n_ parents

While I think we can get by with the current model for the common use patterns, I am worried that this display pattern carried out at the session level could become untenable for the exception patterns: if there are 10 session objectives each associated to 10 course objectives for each of two cohorts....This is why we have resorted to displaying a count rather than the content in this sort of situation in the past. This isn't an issue at the course level.

I don't know what the optimal solution is here if we are going to use the exact same pattern at course and session level. Otherwise, I think we just need to create a different means of display at the session level, whether that is count of parents rather than content (and a required click to view in the objective selector), or so other means of aggregation.

@jenzweben @jrjohnson thoughts?

**Comment by jrjohnson** [comment]
I'm ok with a different pattern asking as it doesn't punish users for linking to multiple objectives.
