### ISSUE TITLE
acceptance test broken

### ISSUE THREAD

**Issue by stopfstedt** [ilios/frontend#2494]
example:
https://travis-ci.org/ilios/frontend/jobs/190426014

`not ok 87 Firefox 45.0 - Exam Partition #1 - Acceptance: Program Year - Stewards: save`

**Comment by stopfstedt** [comment]
works fine when run in browser (latest Chrome/Linux and Firefox v50/Linux).

**Comment by jrjohnson** [comment]
This is broken locally for me after running a nomless. I'm guessing it is an issue with the latest ember-data version.  Investigating.

**Comment by jrjohnson** [comment]
Confirmed downgrading ember-data deals with this.  PR forth coming.
