### ISSUE TITLE
Add per-school ability to enable/display specific course/session attributes

### ISSUE THREAD

**Issue by thecoolestguy** [ilios/frontend#2503]
Several schools have expressed the need for being able to remove default course/session attributes that they do not use, and to be able to add/enable others that are not provided by default.  We need to be able to add new attribute fields to the database by request, and in-turn allow school's to enable the functionality and display of these attributes as needed on their respective install.

In Ilios 2, school's could re-label an attribute they don't use (eg, "Special Attire Required") in order to reappropriate it for another not already included in the system (eg, "Attendance Required"). 

Due to the nature of the download-on-demand Frontend of Ilios 3, schools do not have access to which attributes should or shouldn't be displayed, nor do they have the ability to change their respective label upon display.

We need to investigate and implement the best route to allow for this to happen.  Currently, the processflow being considered is the following:

1. Schools request the desired custom attribute they need and we add it to the database via a migration.
2. We provide an interface for them to enable/display the extra attributes.
3. Attributes should have 3 states: Never Set (null), enabled/displayed, disabled/not displayed.

**Comment by saschaben** [comment]
visual thoughts:

![school_specials](https://cloud.githubusercontent.com/assets/1753431/21865999/3122c75e-d7fd-11e6-821b-c11de8984c54.png)

![school_specials2](https://cloud.githubusercontent.com/assets/1753431/21866004/3599952e-d7fd-11e6-9dec-41df09ed0c2c.png)

**Comment by jrjohnson** [comment]
Do we need to allow users to be able to set something to the third (null) state?  I was thinking that would just be what was stored in the DB when a field was disabled.  For the actual control in the session overview just the yes / no would be needed.

**Comment by thecoolestguy** [comment]
We discussed having it null until it was activated as you suggest, but I don't think there's a reason to set it back to null again... My notes just mentioned that we should allow for nulls in that column.
