### ISSUE TITLE
Creation Of New CI Report Results In Duplicate Academic Year in Drop-Down

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#2513]
![image](https://cloud.githubusercontent.com/assets/7493331/21902230/f6971dfc-d8af-11e6-832a-ebc34f9414a0.png)

Each year appears once ...

![image](https://cloud.githubusercontent.com/assets/7493331/21902313/574f5484-d8b0-11e6-8dcb-e3a47c57ec01.png)

2018-2019 is selected.

![image](https://cloud.githubusercontent.com/assets/7493331/21902348/78e304ba-d8b0-11e6-85fc-6adb04131a9f.png)

`Done` saves the new report.

Pull up the new report and review the contents of the Academic Year Drop-down as shown below - 2018-2019 (or whatever Academic Year you use) is now duplicated in the drop-down.  The existence check seems to have failed and a new year got added.

![image](https://cloud.githubusercontent.com/assets/7493331/21902451/cfbd97e6-d8b0-11e6-80f3-845b8b9297fc.png)

![image](https://cloud.githubusercontent.com/assets/7493331/21902467/dcf6e4f8-d8b0-11e6-8cf1-311f49753618.png)

![image](https://cloud.githubusercontent.com/assets/7493331/21902529/1adf8fa4-d8b1-11e6-9646-50fac8650b2c.png)

**Comment by stopfstedt** [comment]
@dartajax i fixed this in the PR #2508, so when you do the review there please check if this problem is fixed as well. thanks!

**Comment by dartajax** [comment]
Looks good to me.

**Comment by dartajax** [comment]
+1
