### ISSUE TITLE
Expand big text doesn't work in editable field

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#2519]
When a lot of content is sent to editable-field component it truncates it with an expand icon at the end, but clicking that icon opens the editable field as opposed to showing the expanded content.

**Comment by stopfstedt** [comment]
example: session description (instructional notes also applies, and possibly other places)

![Selection_460](https://user-images.githubusercontent.com/1410427/56693764-24ce3000-669a-11e9-81e7-15c2e84748e1.png)

![Selection_461](https://user-images.githubusercontent.com/1410427/56693834-3f080e00-669a-11e9-8ba9-00a43b57a780.png)

perhaps the ellipsis at the end of the truncated text can be used as expand toggle.
