### ISSUE TITLE
Fix Stewardship Functionality - Hide Button if No Permissions Exist

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#2529]
When logged in as an Instructor / Developer, the `Manage Stewards' button is available and the list of Stewing Schools and Departments is displayed - school only (as in Dentistry) - dept's not displayed if no read permissions for user.

![image](https://cloud.githubusercontent.com/assets/7493331/22036291/cd52ac26-dca7-11e6-838e-0c735b23f66e.png)

After clicking the `Manage Stewards` button, the user is presented with two blank boxes as shown below.

![image](https://cloud.githubusercontent.com/assets/7493331/22036345/065f7940-dca8-11e6-8358-d2a0856e388a.png)

**Comment by jrjohnson** [comment]
Fixed in ilios/ilios#1722
