### ISSUE TITLE
Bottom Border of Drop-Down Missing When No Parent Objectives Exist

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#2550]
See the screen shot below for reference.

![image](https://cloud.githubusercontent.com/assets/7493331/22343940/e2583100-e3ae-11e6-9474-9f96bcb1f53e.png)

**Comment by ShortonIT** [comment]
Need more information/navigation to replicate issue. All dropdown menus found has complete box borders. Interns Nanci/Michael/Stacey @dartajax 

![Screenshot (292)](https://user-images.githubusercontent.com/103003096/162805002-066d9ab7-f406-4985-9536-d4b766d92bba.png)

**Comment by dartajax** [comment]
This one may get closed as I as well have been unable to reproduce the issue. Based on my original screenshots, I believe this was in Programs where parent objectives are added but I'm not sure. I'm still looking around and may close this if I can't reproduce it.
