### ISSUE TITLE
Style for generic forms

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#257]
#252 adds a table as structural style for a new course.  This is an OK fix for now, but we should really have a generic style for forms which is not table based.  Tables are a bad way to handle structure and this style will make it difficult to add fields and harder to re-use in other places like new sessions, new programs, etc...

We need to create a generic form styles which we can use in multiple places.

**Comment by jrjohnson** [comment]
For example, new sessions now have to be specifically styled the same as courses.
![screen shot 2015-03-03 at 4 33 28 pm](https://cloud.githubusercontent.com/assets/349624/6475783/17e29d16-c1c3-11e4-99b1-1856c86c4b6a.png)

**Comment by jenzweben** [comment]
Not sure exactly what you need from me...If you're talking about structure, I don't know the best, correct way to code it... regarding the way it should look, then we should consult the mocks...

**Comment by jenzweben** [comment]
reminder - I'm not a developer

**Comment by jrjohnson** [comment]
You're right.  I wrote this too fast.  What I need from you is a consistent set of mocks for forms.  For example the add course and add session mock display data very differently and they really do the same thing.

Then we can talk about the data presentation in those mocks and make some standardization decisions.  For examples: I would also like to see label placement for form elements to be on top of the element in all cases because that works way better as the size of the window changes.

Then we can write the structure and pass it back to you for styling.

My main point is that I want to think about forms more generically and not one at a time.  For the best user experience all of these should look and behave the same way and that is much easier to accomplish if they are all structured and styled from the same base set of patterns.

**Comment by jrjohnson** [comment]
Group Decision:  We will use a basic two column form which will collapse to one column if the screen is small.  In smaller forms only the left column will be used.

@jenzweben will create 5 mocks to cover permutations of button placement
1. Button on right of right column
2. Button on left of left column
3. Button on right of left column
4. Button on left of right column
5 Button on right of right column if there is only content in the left column

Then assign to @thecoolestguy to create the form style.

**Comment by jenzweben** [comment]
Button on the right of right column:
![session-add-3-option1](https://cloud.githubusercontent.com/assets/5023894/6512951/45d1bd8c-c32c-11e4-8be4-0f12185dc704.png)

**Comment by jenzweben** [comment]
Button on the right of right column (add course)
![add-course-v3-option1](https://cloud.githubusercontent.com/assets/5023894/6512994/9c46e070-c32c-11e4-97f3-bd160d3a7579.png)

**Comment by jenzweben** [comment]
Button on left of left column

![add-course-v3-option2](https://cloud.githubusercontent.com/assets/5023894/6513030/e1f006e2-c32c-11e4-9b6d-c4d47a36187d.png)

**Comment by jenzweben** [comment]
Button on the left of right column is not an option as it looks ridiculous

**Comment by jenzweben** [comment]
Button on right of right column with 2 column form
![add-course-v3-option2](https://cloud.githubusercontent.com/assets/5023894/6513154/cfa3a920-c32d-11e4-9730-139865b557ce.png)

**Comment by jenzweben** [comment]
Button on left of left column
![session-add-3-option3](https://cloud.githubusercontent.com/assets/5023894/6515009/aaaee2ac-c33b-11e4-8b4f-0ff71b6b59e7.png)

**Comment by jenzweben** [comment]
@saschaben I think that right alignment of right column is the best...please choose a solution and then assign to JJ.  Thanks!

**Comment by saschaben** [comment]
Right on right is the selection; @thecoolestguy is on deck.

**Comment by jrjohnson** [comment]
@thecoolestguy a few things I thought of that need to go in our forms.
1. a title space (something like 'New Course' that describes the content)
2. elements should be wrapped in their label 
```html
<label>
My Good Input:
<input type='text />
</label>
```
We have to do it this way because it is difficult in ember to get the id that will be generated for an item so doing the traditional ```<label for='myinput'>``` doesn't work.

**Comment by thecoolestguy** [comment]
Got form alignment working to allow for single column (for wide fields, like dropdowns, text, and textarea), 2-column (for side by side fields with long labels), and 3-4 column for small label/value pairs.  Should be reviewed/discussed (see commit above).  Currently color-coded to show the set up (see attached image) -- needs to be re-colorized and more spacing/padding/margin styling...
![generic_form_styling](https://cloud.githubusercontent.com/assets/248570/6955177/f76e4228-d88e-11e4-9d61-d7e35ff2b0c9.png)

**Comment by thecoolestguy** [comment]
I'm still working on some styling of checkboxes and labels, but here is the breakdown of the label/field structure:

https://gist.github.com/thecoolestguy/47936ad626b6985d5290
