### ISSUE TITLE
Results list header not responsive

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#258]
The resultslist-header area handles changing windows size very poorly.  Instead of shrinking or breaking it goes into an overflow condition and displays a scroll bar.
Sometimes it disappears entirely if you make the windows small then big again.

![screen shot 2015-03-03 at 4 36 43 pm](https://cloud.githubusercontent.com/assets/349624/6475834/c3f6aaa2-c1c3-11e4-939e-ab405040a36c.png)

**Comment by jenzweben** [comment]
I think I'll need help from Jason on this one as it's a structural issue and you saw what I did to the add new course template...

**Comment by jrjohnson** [comment]
@jenzweben - yes, agreed.  I assigned a bunch of style tickets to you as a placeholder so they didn't get lost before they were investigated.  But I put them in 0.3.0 so you can ignore them for now.  When we start working on that milestone you will probably just want to take 15 minutes to confirm the issue and see if it is something you know how to fix.  If not then put it back in the pot for someone else.

**Comment by thecoolestguy** [comment]
Closing... Problem fixed in another issue.
