### ISSUE TITLE
Move New Course Label to the Right to Line Up With Courses Label

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#2582]
This is low hanging fruit I admit.  It would look better if the `New Course` were over to the right by about 4 nbsp's or a tab or whatever would make it line up with `Courses`

![image](https://cloud.githubusercontent.com/assets/7493331/22478383/7706d476-e79e-11e6-938b-4f190424c350.png)

**Comment by jrjohnson** [comment]
Fixed in #3578
