### ISSUE TITLE
Froala Text Editor Boxes Don't Display Bulleted or Numbered Lists Consistently

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#2584]
Essentially, the froala text boxes that have the potential to be truncated for display purposes ...

* Objective Description (Session and Course level)

... do not properly display the bullet points or numbered lists in edit mode.

![image](https://cloud.githubusercontent.com/assets/7493331/22479460/ab060ca2-e7a2-11e6-8a48-3b3b85a87f74.png)

after saving ...

![image](https://cloud.githubusercontent.com/assets/7493331/22479476/bffbce8a-e7a2-11e6-8c05-b08bf7686864.png)

But, the Course Description field does.

see below how the bullet points are viewable in edit mode (preferred situation) ...

![image](https://cloud.githubusercontent.com/assets/7493331/22479520/e1e27030-e7a2-11e6-8f20-2ba896964a68.png)

**Comment by dartajax** [comment]
This is true also for Learning Material description.

**Comment by loganh0522** [comment]
I am having the same issue, any update on this?

**Comment by djvoa12** [comment]
@dartajax I think this might have squashed itself.

**Comment by dartajax** [comment]
Yep. Seems to have been fixed one way or the other.
