### ISSUE TITLE
Initial term not correctly selected in new report

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#2605]
Create a new report without changing the term and the first term by id  will be selected instead of the first term in the drop down.  This may happen with other subjects as well.

**Comment by saschaben** [comment]
we've seen this "pre-selection" issue in other dropdowns. I don't think we've addressed it broadly in MyReports yet --- it may be more effective to wait until a refactoring, but let's discuss.

**Comment by gboushey** [comment]
resolved through #2634
