### ISSUE TITLE
It's Possible To Scroll Into Complete White Space - Confusing to User

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#2617]
I was tinkering with some testing for @stopfstedt and I accidentally scrolled too far down and this is the result of that.  Shouldn't there be a point at which you can't scroll down any further?

![image](https://cloud.githubusercontent.com/assets/7493331/22706704/16a138ec-ed25-11e6-82a8-f62d36a2ccba.png)

**Comment by jrjohnson** [comment]
What page is this on?

**Comment by dartajax** [comment]
I don't know if I can reproduce this.  If not, I will close it up.

**Comment by dartajax** [comment]
Re-testing - can't duplicate - gonna close it up.
