### ISSUE TITLE
Shading Needed on Ilios Flyout Menu to Indicate Navigation

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#2621]
I noticed after reporting a bug that I may not be able to duplicate #2617 that it is not possible to know which area of Ilios I was in since none of the menu items on the Ilios flyout menu ever receive any shading.

It is true the user will know where he / she is by looking at the top of the screen but it is possible to scroll down and the top of the screen is no longer visible - shading on the Ilios menu would be nice.

Here is how it is -- I have scrolled far down on the Courses and Sessions page.

![image](https://cloud.githubusercontent.com/assets/7493331/22718436/367cba26-ed55-11e6-9bae-f1acce84dc3b.png)

what about this or something much better?  The same shading that is used upon mouse-over could be used like this ...

![image](https://cloud.githubusercontent.com/assets/7493331/22718474/769d33f6-ed55-11e6-8f5d-f63b39522e5b.png)

**Comment by jrjohnson** [comment]
Fixed in #3578
