### ISSUE TITLE
Apply schoolConfig session attribute options

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#2626]
Session overview can now be customized as of #2606.  We need to apply this setting in two areas:
1) Session creation / editing
2) Users calendar view

@saschaben I believe you said we should always hide the options on the administration of sessions once they are hidden by the school config, but if there has already been a value set for a session created in the past that we should show that value on the calendar even if the option is now turned off for the school.  Is that right?

**Comment by saschaben** [comment]
@jrjohnson that is correct: values set will always display for delivery to students etc, regardless of whether config is active or not for admins.
