### ISSUE TITLE
Get Rid Of Edit Action Icon in Instructor Groups

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#2632]
Four reasons for this ...

1. The horizontal alignment is slightly off from the trash icon
2. In Learner Groups, it has already been removed and we should be consistent
3. The editing of Instructor Groups is accomplished by clicking on the Instructor Group title
4. It's way too close to the trash can.

![image](https://cloud.githubusercontent.com/assets/7493331/22753300/81ef14c2-edf0-11e6-8646-641e43654926.png)

**Comment by dartajax** [comment]
![image](https://cloud.githubusercontent.com/assets/7493331/22753354/b5beb154-edf0-11e6-9130-7d42206c8469.png)

**Comment by dartajax** [comment]
In Learner Groups, the edit button is no longer displayed. Instead there is a "Copy" button which is not something we currently offer in Instructor Groups. It might be better to get rid of the "Edit" button ... or close this ticket.

**Comment by stopfstedt** [comment]
taking inventory here for a minute: 
- lists of Schools, Programs, Instructor Groups, CI Reports, CI Report Sequence Blocks, and Offerings currently have "Edit" button
- list of Learner Groups, Courses, Sessions, Learner Groups, and Program Years do not have an "Edit" button
- _all_ of those list have an "Edit" button equivalent in the linked title of their respective list items


we should consolidate, either throw the "Edit" button out or apply it on all list views.

**Comment by dartajax** [comment]
Thank you @stopfstedt for the list and for your comments. We can discuss this at tomorrow's meeting. Personally, I'd vote to just get rid of the edit buttons entirely. My $.02.
