### ISSUE TITLE
Call Out Needed for the Feed Button Icon on the Dashboard

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#2633]
It would be handy from a user's perspective if there was a mouse-over / hover-over call out indicating `Generate Calendar Feed` or something when a user hovers over the feed button.

![image](https://cloud.githubusercontent.com/assets/7493331/22763204/302646c4-ee18-11e6-8b6b-a31b702a9afd.png)

**Comment by mhgh22** [comment]
Feed Button not located on dashboard. There is a feed button under Calendar but the hover-over says "Show ICS Feed Options" -Michael/Nanci/Stacey
![illios_LI](https://user-images.githubusercontent.com/103135575/162045572-583ff901-f185-4bf0-9e55-608c9fed73ee.jpg)

**Comment by dartajax** [comment]
![image](https://user-images.githubusercontent.com/7493331/162087207-2eb82936-3d28-4380-805b-7da4f3ed99cd.png)

The call out says "Show ICS Feed Options" and then later "Hide ICS Feed Options" and of course there is only one "option". We could do a new ticket to address this if we are so inclined. However, it looks to me that the issue as entered has been resolved. Thanks for checking this out. There used to not be a callout at all which is why I originally entered the ticket.
