### ISSUE TITLE
Provide for variable time window on Agenda view of activities / Materials

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#2662]
we should allow for the variation of the current 60 day forward window. Some options:
This Week
This Block (could be very challenging)
Next 4 weeks
Today +/- n Days

**Comment by nancirose** [comment]
Under Activities the Header reads next 60 Days, however the display starts from today's date through the week ending 4/15. There is no tab or arrow allowing you to click beyond. There are no options for variable time window. 

![Screenshot (73)](https://user-images.githubusercontent.com/103001847/163235127-1c927993-cca6-4621-a83e-3ec686ec6a30.png)

Under Materials there is a toggle for next 60 days, however there are no materials to view.

![Screenshot (74)](https://user-images.githubusercontent.com/103001847/163235197-43168548-a717-4f61-831f-fb05e5e3be8b.png)

-N, M, S @saschaben

**Comment by jrjohnson** [comment]
Agenda view is going away.
