### ISSUE TITLE
Move Save / Cancel Buttons To the Right Schools >> Competencies >> Manage

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#2672]
The `Manage Competencies` button is over to the right as shown below.

![image](https://cloud.githubusercontent.com/assets/7493331/23238400/9c4dc062-f916-11e6-87ca-08f5ac01e996.png)

The Save / Cancel buttons are much further to the left as shown below.

**Comment by dartajax** [comment]
![image](https://cloud.githubusercontent.com/assets/7493331/23238423/bd5a12f6-f916-11e6-8f98-c039a15ce90d.png)

**Comment by jrjohnson** [comment]
Fixed in #3578
