### ISSUE TITLE
Move "Move Learners" Button Down a Bit

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#2676]
This is in Learner Groups.  I just thought it looks weird and could be improved by moving the button down a bit.

See screen shot.  See how "Anna Mendoza" and the button are kind of overlapped.

![image](https://cloud.githubusercontent.com/assets/7493331/23274441/959f1da0-f9b7-11e6-9ba5-1396f06dd0dc.png)

**Comment by jrjohnson** [comment]
Fixed in #3578
