### ISSUE TITLE
Full Calendar on Day View Requires Right Scroll and is Confusing

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#2677]
Basically, with the inclusion of the Legend showing the time of day and a fully populated calendar, there is extra room to the right (the same width as the Legend) the user has to scroll to see the final offerings.  It becomes confusing because you lose the Legend and the calendar doesn't make too much sense.

See the screen shot.

Here is why I scrolled (or a user might).
![image](https://cloud.githubusercontent.com/assets/7493331/23275554/c82b2198-f9bb-11e6-9497-b2617fd390ff.png)

Here is how it looks after scrolling to the right.  The times of day are missing.

![image](https://cloud.githubusercontent.com/assets/7493331/23275607/06481800-f9bc-11e6-84fd-1e8a084b3e89.png)

**Comment by saschaben** [comment]
css grids should take care of this.
