### ISSUE TITLE
Drop-Down Getting Cut Off - Screen Size Issue

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#2679]
You can see in the first screen shot that the drop-down to switch languages, log off, or go to My Materials is being cut off.  It is possible to scroll to see it and that is what is pasted in the second screen shot below.

Before scrolling ...

![image](https://cloud.githubusercontent.com/assets/7493331/23283695/51369074-f9dc-11e6-9201-fee67d09ff4f.png)

After scrolling ...

There is even some blank white space in the upper right corner.

![image](https://cloud.githubusercontent.com/assets/7493331/23283769/b76b75a8-f9dc-11e6-9ec8-804db0ffa80a.png)

**Comment by jrjohnson** [comment]
Place to start investigating: I believe we switched implementations for our dropdown component a few weeks ago.  The old one used to have some options to style it for the right edge of the screen.  I would guess that didn't make it into the new version.
