### ISSUE TITLE
Caption Does Not Update with Back Button Action 

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#2680]
I was reviewing the My Materials from the upper right drop-down and then decided to click the back button on my browser (Chrome).  The caption did not update to reflect the fact that I am not back on My Profile.

![image](https://cloud.githubusercontent.com/assets/7493331/23284163/dc413f64-f9de-11e6-9d6a-526a89067298.png)

**Comment by dartajax** [comment]
Actually, if you are on My Materials and then you click My Profile, the result is the same.

**Comment by jrjohnson** [comment]
Good catch: this is a problem with the route for my profile.  It needs to include an override for the application controller title property.
