### ISSUE TITLE
Investigate building and hosting frontend ourselves

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#269]
There is no reason each campus needs to host the ilios frontend asset code as it will be static in any case where heavy customization isn't going on.  While we could (and probably will) distribute that code as part of the backend api build we should investigate placing it on a CDN and serving it from there to each campus.  In this model each campus would only need to host a single HTML file which had configuration information (like API server location).  Authentication would happen against the API server and could be placed in front of the html file or as part of a separate token process.

This would provide several benefits:
1. If there have been no API changes a campus would be able to update the version of ilios they are providing by changing a single HTML file.
2. Take advantage of the significant speed and reliability improvements offered by a CDN
3. Make our distribution and packaging of Ilios much easier.

**Comment by saschaben** [comment]
A _really_ interesting idea, one that brings up a bunch of other issues as well. Let's talk more about this.
