### ISSUE TITLE
Use new Chained else blocks

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#270]
Once #268 is merged we can start using if/elseif/else blocks
```handlebars
{{#if isAtWork}}
  Ship that code!
{{else if isReading}}
  You can finish War and Peace eventually...
{{/if}}
```
This is a big improvement in readability for templates and we need to go back through existing templates looking for syntax like:

```handlebars
{{if foo}}
  {{if foobar}}
    something
  {{else}}
    something else
  {{/if}}
{{else}
  wow this is complicated
{{/if}}

**Comment by saschaben** [comment]
is this still an issue? if not, please close, thx.

**Comment by jrjohnson** [comment]
Probably, but this ticket is WAY to generic.  Will open tickets when I find this issue specifically.
