### ISSUE TITLE
Clickable Areas Are Too Wide In Course Objectives and Possibly Elsewhere

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#2712]
I noticed while testing that the click events take place far out of where a user might think anything would happen.

This is a pretty small deal I admit but I wanted to point it out.  I got confused myself when I accidentally called Add New Objective.  I don't know why I clicked my mouse but it was weird when it reacted.

![image](https://cloud.githubusercontent.com/assets/7493331/23528034/2658231a-ff4d-11e6-93d4-72ba44dc2bb7.png)

**Comment by jrjohnson** [comment]
Fixed in #3578
