### ISSUE TITLE
Delete Learner Group Fails When Sub Groups with Members Exist

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#2713]
See below ...

![image](https://cloud.githubusercontent.com/assets/7493331/23529363/2a12cdf2-ff52-11e6-94d0-49c1f51d7dd8.png)

After clicking as shown above ...

![image](https://cloud.githubusercontent.com/assets/7493331/23529483/aab7cc50-ff52-11e6-8c6b-dc033e96f6e2.png)

And then ...

Failure.

![image](https://cloud.githubusercontent.com/assets/7493331/23529538/dd052914-ff52-11e6-846e-346f77851680.png)

**Comment by stopfstedt** [comment]
this behaviour is correct. we "just" need to check for groups with populated subgroups, and then not show the trashbin/delete icon.

**Comment by stopfstedt** [comment]
alternatively, we could lift this restriction and cascade deletions down to learnergroup/learner associations.
@saschaben please advise. thanks!

**Comment by stopfstedt** [comment]
discussed this with @saschaben - i'll try to resolve this first by checking for populated (sub)-groups in the frontend, putting spinners into place on each list item etc.
if this doesn't hold up due to performance reasons we'll have to consider alternatives.

**Comment by jrjohnson** [comment]
If we can delete groups with learners why would we not allow a cascading delete of groups with subgroups with learners?  Or should we be preventing both?
