### ISSUE TITLE
More Room Needed To Edit School  Competency

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#2715]
See below ...

![image](https://cloud.githubusercontent.com/assets/7493331/23530240/b9b2b32a-ff55-11e6-9651-3b83090a8b87.png)

![image](https://cloud.githubusercontent.com/assets/7493331/23530295/fbb7cdbe-ff55-11e6-8c19-aecc749e4e9e.png)

**Comment by jrjohnson** [comment]
Fixed in #3578
