### ISSUE TITLE
Prevent Unpublished Program Years From Being Attached to Courses

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#2738]
![image](https://cloud.githubusercontent.com/assets/7493331/23924395/be8fe9be-08c7-11e7-85be-9ee7006f47fa.png)

but then ...

Select a course and attach the "unpublished" cohort.

![image](https://cloud.githubusercontent.com/assets/7493331/23924462/0d154dc2-08c8-11e7-9836-8533a87b2d31.png)

Review, rinse, and repeat.

![image](https://cloud.githubusercontent.com/assets/7493331/23924556/5ea28e5c-08c8-11e7-802f-6a3248007764.png)

**Comment by stopfstedt** [comment]
that's gonna be a tricky one to pull, considering that some courses probably are linked to unpublished program years. 
furthermore, this may not be a bug at all - a feasible workflow could be to create, but not publish, a program year and then build out all the courses for it.
@saschaben - please advise. thanks!

**Comment by dartajax** [comment]
I think this will be closed. We will be getting rid of the concept of publishing program years entirely.

**Comment by dartajax** [comment]
Superseded by #3675
