### ISSUE TITLE
Missing Translation -- Learner Groups -- Move to Group (Sub Group)

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#2745]
![image](https://cloud.githubusercontent.com/assets/7493331/23974787/57aeea00-099a-11e7-9fc0-00cc354d1fda.png)

**Comment by stopfstedt** [comment]
this problem only seems to exist on our demo server. 

lasted HEAD of `master` as well as the code that's currently in production do not have this problem.

**Comment by jrjohnson** [comment]
@dartajax I'm not able to re-produce this.  I seem to remember from discussions that maybe there was some special conditions required.  Can you add them here if you recall what they were?

**Comment by dartajax** [comment]
I couldn't reproduce this. I got it to the point where it appears just like the screen shot but there is no missing translation. I am thinking of closing this.

**Comment by dartajax** [comment]
I was now able to reproduce this ...

* Create a new group adding the cohort 
* Create several sub groups using the `Create (x) Sub Groups` function.
* Navigate to one of the newly created sub groups
* Click `Manage`.
* Mouse over the green (+) symbol by one of the names of the higher level group. -- Missing translation

**Comment by dartajax** [comment]
I just re-tested following the steps outlined by me a couple of years ago - no longer a bug.
