### ISSUE TITLE
Parent Objective Competency labels loading as "undefined"

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#275]
I'm seeing this on initial load in Master right now, consistently:

![ilios 2015-03-06 14-57-45](https://cloud.githubusercontent.com/assets/1753431/6538015/599ebb54-c411-11e4-9ee0-c77b0280ae4e.png)

Not sure if this is dealt with in another issue, or know, but if not, we need to fix.

**Comment by jrjohnson** [comment]
Should by fixed in #274
