### ISSUE TITLE
After Publishing New Program Year, Error Message Received

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#2769]
I published the Class of 2021 (from Not Published) and received the following error message ...

**
![image](https://cloud.githubusercontent.com/assets/7493331/24119707/6cc7cdf2-0d6f-11e7-8385-1406e161aced.png)
**

The Program Year did get published but should not have received that ugly message.

**Comment by saschaben** [comment]
This error is occurring when you click the "Back to Programs" link from the program year after publishing.

**Comment by dartajax** [comment]
I apologize for not including that piece of information.  I think I clicked `Programs` from the flyout menu myself.

**Comment by saschaben** [comment]
...and now I cannot reproduce at all. GAAAARRRRRRRN!

**Comment by dartajax** [comment]
I just got the error message when I published and then clicked `Learner Groups`, which is actually what I did the first time.

**Comment by jrjohnson** [comment]
@dartajax I went around publishing every program year I could find and wasn't able to re-produce.  Are you hitting this consistently?

**Comment by dartajax** [comment]
Haven't been able to reproduce ... yet. I assigned to myself and will close soon.

**Comment by dartajax** [comment]
I just tested some more. We can re-open if it reappears; but I couldn't reproduce it either.
