### ISSUE TITLE
'form' authentication throws 403 error when user tries to change OWN password

### ISSUE THREAD

**Issue by thecoolestguy** [ilios/frontend#2777]
![changing_own_password_403](https://cloud.githubusercontent.com/assets/248570/24205934/0a3fc33a-0eda-11e7-8e20-b7abec1ae2c9.png)
When using Ilios' native "form" authentication, users cannot change their own password, but they can change the password of other users (given the proper permissions to do so).  We need to allow user to change their own password or remove the form fields and notate the restriction.

**Comment by jrjohnson** [comment]
I think the solution is going to be allowing the change as opposed to turning off the form so I'm moving this over to the API.

**Comment by jrjohnson** [comment]
And.... that was wrong.  The API allows authentication to be updated, but we have merged the update of a users account withe the update of their authentication info so it fails.  More permanent relief will be in ilios/ilios#1772 but we can probably make some changes on the frontend to help with this.

**Comment by jrjohnson** [comment]
This was addressed in the API and is now working.
