### ISSUE TITLE
Admin Console Directory Update Count Not Working Properly

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#2785]
![image](https://cloud.githubusercontent.com/assets/7493331/24259106/1c70247c-0fad-11e7-8dd7-1c97bdac7ab0.png)

The formatting doesn't look right either.  It should look more like the pane/panel on the right (Cohort Assignment).

**Comment by saschaben** [comment]
3/30/17 UPDATE: with user sync running sucessfully, the count is now correct. BUT: the formatting is not. It is remaining as above when count  > 0, when it should look like the box on the right (yellow border, no fill, alert icon)
