### ISSUE TITLE
Session Copy Functionality Not Working Correctly - 400 Payload Error

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#2800]
See the screen shots -- this is on demo3.

It does copy to the target course but blows up on the return.

![image](https://cloud.githubusercontent.com/assets/7493331/24368709/4c6435d4-12d6-11e7-856b-266e8513fc45.png)

![image](https://cloud.githubusercontent.com/assets/7493331/24369474/fd7e71c0-12d8-11e7-9217-aa155810a891.png)

![image](https://cloud.githubusercontent.com/assets/7493331/24369495/0b2959f2-12d9-11e7-95b8-b404f46a4f59.png)

**Comment by jrjohnson** [comment]
Seems to be that `position` is not being sent with the copy request.  Investigating.
