### ISSUE TITLE
Move "None" Label over to the Right a Bit on MyReports

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#2809]
This is some serious low hanging fruit; but it would look better if the "None"s lined up better.

![image](https://cloud.githubusercontent.com/assets/7493331/24427773/00cf9046-13c1-11e7-88ff-4b19b640b982.png)

![image](https://cloud.githubusercontent.com/assets/7493331/24427783/09c8a868-13c1-11e7-9854-fc6de9616c6c.png)

**Comment by mhgh22** [comment]
"None" under "My Reports" looks better than before but is still slightly misaligned. -MNS @dartajax

![Screenshot 2022-04-13 at 11-12-20 Ilios Dashboard](https://user-images.githubusercontent.com/103135575/163249021-3d835571-3092-463a-b195-d1b631dce6c5.png)
