### ISSUE TITLE
Instructor Picker for Offering fails when desired name is already listed as Course Director

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#2838]
It works the way it should be working when assigning instructors to ILM's. The ILM Instructor selector is working fine. The standard Offering Instructor picker is NOT.

See below ... 

"Stan Fields" is a Course Director as shown below.

![image](https://cloud.githubusercontent.com/assets/7493331/24635045/f99a0e5e-1885-11e7-9185-e13cc535e87b.png)

# ILM ...

"Stan Fields" can be added as Instructor for the ILM as shown below.

![image](https://cloud.githubusercontent.com/assets/7493331/24635117/6c5e128c-1886-11e7-8f42-d7a7b7c00dc4.png)

![image](https://cloud.githubusercontent.com/assets/7493331/24635128/7a6a6d62-1886-11e7-853c-71bb9fde00c3.png)

When an User is already assigned as Director for a Course, that user can't be added as Instructor for an Offering in that Course.  Conversely, when a User is already added as Instructor for an Offering, they CAN still be added as Director for the Course.

# Standard Offering

Running a search for "Stan Fields" blows up. It does not say no records returned. It does not provide other results. "Stan Fields" cannot be added because he is a Course Director in this Course.

![image](https://cloud.githubusercontent.com/assets/7493331/24635226/fe27bfd8-1886-11e7-8061-5a0447f80e33.png)

And then ...

No "Stan" - no results at all - "Stan" can't be added.

![image](https://cloud.githubusercontent.com/assets/7493331/24635238/0f10e11c-1887-11e7-8608-d8f5adebff7b.png)

**Comment by stopfstedt** [comment]
i can't reproduce this problem. seems to be working fine for me. @dartajax can you please verify that this problem still exists? thanks.

**Comment by dartajax** [comment]
This appears to have been fixed.

**Comment by stopfstedt** [comment]
i threw a `yield timeout(100);` into the `search` task of the `user-search` component (near the bottom), just to slow things down. 
this plopped the following warning into the console: 


> ember-concurrency detected a potentially hazardous "self-cancel loop" between parent task `searchTask` and child task `search`. If you want child task `search` to be canceled when parent task `searchTask` is canceled, please change `.perform()` to `.linked().perform()`. If you want child task `search` to keep running after parent task `searchTask` is canceled, change it to `.unlinked().perform()`

observations:
1. `{{user-search}}` is one of multiple components that uses the `{{search-box}}` component.
2. unlike the other components, it passes a task as action to `{{search-box}}` (vs. passing a property or an action). 

rewriting the `search` task in `{{user-search}}` may fix this problem, will start there.

**Comment by stopfstedt** [comment]
no dice either when changing from task to (async) action. 
fwiw, i parked the modified code in a [feature branch](https://github.com/stopfstedt/frontend/tree/2838_instructor_search) for later review/work.

**Comment by stopfstedt** [comment]
more sleuthing: for reasons yet to be determined, the `{{instructor-selection-manager` component re-initializes when search results contain any users previously selected as director. which explains the reset described here and visible in the screencast referenced in #3462
