### ISSUE TITLE
Attempting to editing offerings twice in same web-session throws blank page on update

### ISSUE THREAD

**Issue by thecoolestguy** [ilios/frontend#2850]
NOTE: This error was reproducible in some sessions/offerings, but not in others.  User experienced the problem in production, but we reproduced on https://ilios3-stage.ucsf.edu.  Here's the problem:

When editing an offering's details in the UI, you can do so once to any offering and save the item without problem or delay.  

HOWEVER, in most cases, when you attempt a second edit (of the same offering OR another!) during the same user session, one of three things happens:

1. clicking on the edit icon for (any) offering throws a blank page.
2. clicking on the edit icon allows you to edit the offering, but throws a blank page upon save.  Refreshing the browser from the blank page shows that the change has actually been saved and the offering is updated, but it takes a refresh to see that.
3. The task works as expected. 

Here are the links we used to create both of the problem scenarios listed above (#1 and 2), but we get mixed results when trying each multiple times: sometimes it works, sometimes it does not:
1. https://ilios3-stage.ucsf.edu/courses/1143/sessions/33533
2. https://ilios3-stage.ucsf.edu/courses/978/sessions/30677

**Comment by thecoolestguy** [comment]
@saschaben has verified that this only happens on the 'edit offering' action(s)

**Comment by saschaben** [comment]
the error:

![error1](https://cloud.githubusercontent.com/assets/1753431/24767982/e1a256da-1ab5-11e7-8d61-8f2c4e9232f4.png)

**Comment by stopfstedt** [comment]
low level errors, it seems. i was able to get away from this by replacing `{{liquid-if` with regular `{{if` in the `offering-manager.hbs` template, and by cleaning up that conditional
rewrote `offering-form.js` partially in order to support that change, unfortunately this introduced new regressions (non-breaking). and now i'm out of time.

**Comment by jrjohnson** [comment]
A minor success:  I have narrowed this down to the `learnergroup-tree` component and built a test which will fail:

```javascript
test('edit offerings twice #2850', async assert => {
  assert.expect(2);
  server.create('learnerGroup', {
    cohort: 1,
    children: [4],
  });
  server.create('learnerGroup', {
    cohort: 1,
    parent: 3,
    children: [5, 6],
  });
  server.createList('learnerGroup', 2, {
    cohort: 1,
    parent: 4,
  });
  server.db.cohorts.update(1, {learnerGroups: [3, 4, 5, 6]});

  const editButton = '.offering-detail-box i:first';
  const form = '.offering-form';
  const save = `${form} .done`;
  const room = '.offering-block-time-offering-location:first';

  await visit(url);
  await click(editButton);

  await click(save);
  assert.equal(find(room).text(), 'room 0', 'location/room is correct');

  await click(editButton);
  await click(save);
  assert.equal(find(room).text(), 'room 0', 'location/room is correct');
});
```

Goes in tests/acceptance/course/session/offerings-test.js

The issues seems to be related to the depth of the learner groups tree which is probably why it is sporadic and will affect some programs more than others.

**Comment by jrjohnson** [comment]
Boo.  False positive.  That test doesn't yet fail reliably.

**Comment by jrjohnson** [comment]
This isn't an ember bug.  I can render very deeply nested trees without a problem in other contexts.  I can also render a deep set of `{{learnergroup-tree}}` components in isolation.  This is some kind of scary dragon which  is going to require significantly more investigation.
