### ISSUE TITLE
Make My Activities / Week At A Glance / My Materials Searchable and Sortable

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#2859]
This is a suggestion from UCSF SOD that I wanted to put in as a suggestion for an enhancement for us to consider.

**Comment by dartajax** [comment]
Upon reviewing this ticket, it may need two things ...

1. Team Discussion (hence the tag) to determine what is (or is not) is scope
2. This ticket may be closed in lieu of three or four smaller tickets.

**Comment by jrjohnson** [comment]
Materials done, others questionable. Closing.
