### ISSUE TITLE
Fail Better When Generated Sub Group Names Are Too Long

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#2869]
Here is what happens ...

Attempting to add (using the auto generate of sub groups which adds the final two or more characters to the newly generated group names) a title longer than 60 characters results in the following error in the logs ...

```[2017-04-14 22:16:22] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\HttpException: "Object(Ilios\CoreBundle\Entity\LearnerGroup).title:     This value is too long. It should have 60 characters or less. (code d94b19cc-114f-4f44-9cc4-4138e80a87b9) " at /var/www/ilios/src/Ilios/ApiBundle/Controller/ApiController.php line 473 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\HttpException(code: 0): Object(Ilios\\CoreBundle\\Entity\\LearnerGroup).title:\n    This value is too long. It should have 60 characters or less. (code d94b19cc-114f-4f44-9cc4-4138e80a87b9)\n at /var/www/ilios/src/Ilios/ApiBundle/Controller/ApiController.php:473)"} []```

* Steps to reproduce 
Pick a group with a 59 char name like this one ...

`S17_CP113 Pharm Prac_PharmD Class of 2020 Conference Groups`

![image](https://cloud.githubusercontent.com/assets/7493331/25057946/86d8106c-2129-11e7-89cd-d0af59d7d261.png)

After the attempt at `Save` ...

![image](https://cloud.githubusercontent.com/assets/7493331/25057954/9f56232c-2129-11e7-81f3-8fa2ab9dff22.png)

![image](https://cloud.githubusercontent.com/assets/7493331/25057961/b01e7466-2129-11e7-8c0a-8839e29fc985.png)

After clicking as shown above, do NOT refresh the page and try to add a Learner to this non-existent Sub Group.

![image](https://cloud.githubusercontent.com/assets/7493331/25058020/486b0842-212a-11e7-9c09-4c12a688d9ef.png)

Same error ...

![image](https://cloud.githubusercontent.com/assets/7493331/25058031/5dfd288e-212a-11e7-9931-6b089acc6fa6.png)

**Comment by jrjohnson** [comment]
We discussed solutions in our meeting and came up with 2:
1) Truncate the subgroup name before appending the count so the generated group is never too long
2) Prevent with an error message creating subgroups if the name is too long.
