### ISSUE TITLE
Align The Add LM Drop-Down With the Other Controls

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#2875]
![image](https://cloud.githubusercontent.com/assets/7493331/25103525/bef3b196-2371-11e7-92db-d25e7fce4491.png)

**Comment by dartajax** [comment]
The `Add` drop-down should be moved a bit to the left.

**Comment by dartajax** [comment]
This is true for both Courses and Sessions.

**Comment by jrjohnson** [comment]
Fixed in #3578
