### ISSUE TITLE
Apply Back Link solution from PR #2882 more broadly

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#2890]
the cleanup of the "back to session" link for the session review page should be used as well in the following locations:

- _Back to Course_ (from course review)
- _Back to Courses List_ (from Course)
- _Back to Session List_ (from Course)

- _Back to Program Year_ (from program year review)
- _Back to Program Years_ (from program year detail)
- _Back to Programs_ (from program)

**Comment by jrjohnson** [comment]
Fixed in #3578
