### ISSUE TITLE
Internal Page Loader Component

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#290]
Right now we are using the wave loader, but that could change in the future.  For areas internal to a page where we are waiting on a promise and want to display an indicator we need a different component so we can easily change the animation at a later date.

**Comment by saschaben** [comment]
for latest loader component, see #245

**Comment by saschaben** [comment]
some options for the text of the loader:

"The doctor will be with you shortly..."
"almost there..."
"wait for it..."
"yeah, baby..."
