### ISSUE TITLE
Visualization fails to calculate correctly

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#2930]
generates `NaN` value instead of correctly calculating percentage values on a course with properly mapped objectives:

https://deploy-preview-2929--ilios-frontend.netlify.com/data/courses/905/objectives
![ilios courses and sessions 2017-05-01 10-24-42](https://cloud.githubusercontent.com/assets/1753431/25587336/6f71d804-2e58-11e7-9dad-b4ac41304693.png)

**Comment by jrjohnson** [comment]
@saschaben this now renders as 
<img width="897" alt="empty" src="https://cloud.githubusercontent.com/assets/349624/25790002/4c9f18e8-336a-11e7-8d7b-f66a97d32199.png">

It is a course with no objectives. Should we remove the chart if there is no data? Or leave it blank as it is now with the list of un-rendered objectives on the right?

**Comment by saschaben** [comment]
If there is no mapped data, then we should either: remove the chart and replace it with a label:

` No Course Objectives Currently Linked to Instructional Time.`

![donut](https://cloud.githubusercontent.com/assets/1753431/25814029/b8a352dc-33d0-11e7-820d-3ae13e315615.png)

Or leave the donut as is and provide the label above in addition.


![donut2](https://cloud.githubusercontent.com/assets/1753431/25814030/b8a4df76-33d0-11e7-80a4-7bd3adb159dc.png)

**Comment by jrjohnson** [comment]
@gabycampagna which one of these do you think provides the best UX?

**Comment by gabycampagna** [comment]
I think it might take a bit a time to figure out how disable the donut or change the fill color in D3. I can research and see if it is simple to implement.  

It would be better to have something to replace the chart for the user so they don't wait a model that will never load.

I suggest we use the 1st option with a label and add an Icon similar to the "meh" icon in place of the chart. 
![meh](https://cloud.githubusercontent.com/assets/597090/25826159/9015431e-33fa-11e7-9fbf-223c2123ea9f.jpg)

**Comment by gabycampagna** [comment]
Or we keep the empty chart "as is" in its current state of blue with the label above it. That is the simplest solution for now.

**Comment by saschaben** [comment]
...or
![optionmeh](https://cloud.githubusercontent.com/assets/1753431/25826628/60ab8302-33fc-11e7-8f7f-3f01221b64a0.png)

**Comment by saschaben** [comment]
but seriously: if we can drop the chart object and replace with a meh, that actually would be great. I'm a little uneasy about showing a chart with effectively invalid (non)data...but that is acceptable if the effort in replacing it with something else is more than a few hours.

**Comment by gabycampagna** [comment]
Cute pic of the lost cat!  :1st_place_medal: 

Font awesome does include the "meh" icon. 

It will save us time on trying to figure out how to change the d3 chart and render it as "disabled".   

I was looking for a "null" icon but I couldn't find it in the font awesome library.  I found the meh and thought it would be a good fit.

**Comment by jrjohnson** [comment]
Looks great.  Love it.  Make it happen!

**Comment by gabycampagna** [comment]
"Meh" icon has been added.  Branch has been approved and merged to frontend/master.

<img width="1422" alt="screen shot 2017-05-09 at 1 08 02 pm" src="https://cloud.githubusercontent.com/assets/597090/25870352/a8eae010-34b8-11e7-81e8-d3eab05e7755.png">
