### ISSUE TITLE
Manage sessionType aamcMethods

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#2972]
A session type can be linked to many aamcMethods. It should be possible to manage this link for session types which are not linked to sessions and for new session types.

Summary of discussion below: We can use a simple dropdown to link a single aamcMethod to a single session type. Additionally those aamcMethod with an id beginning with AM can only be linked to sessionType which have the assessment flag set to true and those which begin with IM can only be linked to non-assessment session types.

**Comment by saschaben** [comment]
Here are the rules (as they stand now):

- A session type may have only one mapped value at a time
- Session Types *must* have a mapping to be used with the CI
- to be an assessment method vs instructional method requires the assessment flag and a selection of summative/formative.

**Comment by jrjohnson** [comment]
We currently have the API and DB configured to map a session type to many AamcMethods - is that incorrect?

**Comment by saschaben** [comment]
not necessarily - but in practice, as of today, there is no way to demarcate or pre-select which mapping you might use if there are >1. That's for us, as well as for the CI upload portal/report. so I don't think we need or want to constrain the API/DB at this point. FYI, https://github.com/ilios/ilios/wiki/The-Curriculum-Inventory-Manager#mapping-instructional-and-assessment-methods

**Comment by saschaben** [comment]
There is the issue of a session where there might be multiple methods desired: eg, a session that is a 20 minute lecture and then small group PBL, and then an exam -- but right now we aren't providing a means of doing all that in a single session - and we're moving more toward allowing linkage of sessions instead to address the issue - and the CI only reads the primary mapped value for a method at this point anyway, and throws out the other info.

**Comment by saschaben** [comment]
closed with #3031
