### ISSUE TITLE
.ics Feed Copy to Clipboard Confirmation Needed On Dashboard Calendar

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#2976]
Similar to how it is now in the Admin Console, it would be helpful to have confirmation here as well once the copy file icon has been clicked.

![image](https://cloud.githubusercontent.com/assets/7493331/26017647/8c039a00-371f-11e7-9ee2-aa30dfb82c4a.png)

**Comment by jrjohnson** [comment]
Fixed in ilios/common#176
