### ISSUE TITLE
Occasionally The First Report Entered Does Not Show Up / Requires Refresh

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#2977]
![image](https://cloud.githubusercontent.com/assets/7493331/26018172/223a1178-3722-11e7-8723-f823e44e7209.png)

![image](https://cloud.githubusercontent.com/assets/7493331/26018182/2c9e11a0-3722-11e7-8fb4-0705f58e6654.png)

Still showing None 

I am logged in as Nicholas Gutierrez right now.

After refreshing the screen `F5`, the report appears. See below.

![image](https://cloud.githubusercontent.com/assets/7493331/26018226/6857ee46-3722-11e7-8e29-527b816757c6.png)

**Comment by dartajax** [comment]
This actually happened to me once when there already was a report there -- reporting on an Exam Type. So it might not just be the first one when this happens. It could be any time.

**Comment by dartajax** [comment]
See also #2838

**Comment by stopfstedt** [comment]
refs #3176
