### ISSUE TITLE
Old Naming Convention Still Applies When Nothing Selected in Reports

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#2978]
![image](https://cloud.githubusercontent.com/assets/7493331/26018319/ff736e9a-3722-11e7-9b3a-5050339c8a10.png)

After clicking Save ...

Old style title

![image](https://cloud.githubusercontent.com/assets/7493331/26018342/179d6444-3723-11e7-89a2-7560236900ca.png)

It should be "All Courses in Medicine".

**Comment by jrjohnson** [comment]
This may be resolved and just needs to be tested and closed.

**Comment by dartajax** [comment]
This has been fixed. Gonna close it up.
