### ISSUE TITLE
Issues for redress after 0.2.0 ember update

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#298]

**Comment by saschaben** [comment]
1. attempting to delete a director throws:
>> 2vendor.js:52061 Uncaught Error: <ilios@component:course-overview::ember6220> had no action handler for: removeDirector

2. no longer handling empty collections, causes failure to load any entity affected:

3. Unable to delete course.

**Comment by jrjohnson** [comment]
Requires #299
