### ISSUE TITLE
Running A Report On Yourself Causes My Reports To Blow Up

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#2997]
I was logged in on demo3 as Nicholas Gutierrez and tried to set up a report for Medicine >> Courses >> Instructor >> "Nicholas Gutierrez". 

After pressing Save, the screen flickers and attempts to repaint but never completes.

It blinks between blank as shown below ...

![image](https://cloud.githubusercontent.com/assets/7493331/26332713/60c516ca-3f0d-11e7-9a68-fc52dcd7bd24.png)

or something more like this ...

![image](https://cloud.githubusercontent.com/assets/7493331/26332725/7c80b068-3f0d-11e7-9ade-ffa9120219b9.png)

... where only one report - the offending one - is not displayed. It loops over and over trying to repaint.

**Comment by dartajax** [comment]
I think this has been squashed - initially unable to reproduce - assigning to myself for closure.

**Comment by djvoa12** [comment]
@dartajax I was just assigned to this one. I can't reproduce this one.

**Comment by dartajax** [comment]
I also couldn't reproduce. Thankfully it has now been closed.
