### ISSUE TITLE
"My Courses" and "My Reports" should not require hard refresh.

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#3000]
Currently, it is necessary to do a hard refresh (F5) to get updated information in "My Courses" and "My Reports". This information should refresh when a user switches to "Calendar" and then back to "Week At A Glance" for example. Slack notes below ...

dartajax [8:33 AM] 
"My Courses" requires hard refresh.

dartajax [8:38 AM] 
so does "My Reports"

[8:38] 
"Week At Glance" loads up.

[8:38] 
In other words, when information changes, those two should refresh automatically - "My Courses" and "My Reports".

[8:41] 
Or not automatically but at least when you are switching views and the data has changed.

**Comment by saschaben** [comment]
Truth.

**Comment by jrjohnson** [comment]
Seems to be resolved.
