### ISSUE TITLE
Delete Objective From Program Year Functionality Missing

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#3003]
With Courses and / or Sessions, the trash can icon appears if you have Developer rights.

In Program Years, the trash can is missing.

![image](https://cloud.githubusercontent.com/assets/7493331/26464745/b4de0334-413d-11e7-88cf-a3b4f2492b86.png)

**Comment by saschaben** [comment]
We want to deal with this soon, and we will want to deal with it correctly:

1: if an objective is NOT linked to any courses, it should be deletable;
2: if an objective IS linked to 1 or more course objectives, it is not deletable, but should be able to be set as INACTIVE;
3: all program year objectives default to ACTIVE, and have the option of being set to INACTIVE;
4: once set to INACTIVE, the program year objective no longer is provided as a linking option for course objectives;
5: an attribution of INACTIVE has no impact on the existing display, reporting, or delivery of a program year objective.

This is the same pattern used for vocabulary terms.

**Comment by jrjohnson** [comment]
We'll need to add an `active` attributes to objectives in the DB, but then they will apply  to courses and sessions as well.

**Comment by saschaben** [comment]
@jrjohnson understood. I think this is fine, as we can auto-default the value to be `active` across the board, and will be exposing it in the UI only for program year. But it gives us some future-proofing options around the possibility of ever banking and reusing objectives in course/session.....we will just need to do the necessary backfill migrations and code coverage everywhere....

**Comment by stopfstedt** [comment]
has been dealt with.
