### ISSUE TITLE
Make Control Widgets Aware of State

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#3011]
For example ...

![image](https://cloud.githubusercontent.com/assets/7493331/26657204/56ecb5a2-4617-11e7-9c38-ae89297e87f3.png)

This is also true in Learner Group management when the button says ...

![image](https://cloud.githubusercontent.com/assets/7493331/26657227/79e31d1c-4617-11e7-9869-352b8b101d7c.png)

... when all 217 users are already in the Learner Group called `DartAjax`.

**Comment by jrjohnson** [comment]
Please split this into two tickets as the will be addressed separately.
