### ISSUE TITLE
Offering Column Headers Should Not Appear in Edit Offering Mode

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#3019]
Steps to reproduce 

* Pull up a Session 
* Click to edit an Offering

![image](https://user-images.githubusercontent.com/7493331/26904839-d0197542-4b98-11e7-9062-c2cf5a99b472.png)

**Comment by jrjohnson** [comment]
When editing one offering you can see the others, this is part of the original design so I'm going to close as a won't fix.
