### ISSUE TITLE
Put % In Visualization As Well for Reference

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#3024]
I would probably not need to be as big of a font size as this depiction; but hopefully this is helpful. It's hard to tell when you are reading the callout which slice of the pie (and %) is being referenced.

![image](https://user-images.githubusercontent.com/7493331/27055519-8f33cfc0-4f79-11e7-8463-143fb442e643.png)

**Comment by saschaben** [comment]
see also #2959

**Comment by saschaben** [comment]
this issue has been mooted for the current visualizations.
