### ISSUE TITLE
New School Label Needs Alignment - Further to the Right

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#3025]
Here's how it is ...

![image](https://user-images.githubusercontent.com/7493331/27104283-9071cdb6-5040-11e7-82fd-e77380bced1e.png)

Move it over to the right a little bit to align underneath Schools.

![image](https://user-images.githubusercontent.com/7493331/27104414-0de7fa40-5041-11e7-9ff2-2cb113e35767.png)

**Comment by jrjohnson** [comment]
Fixed in #3578
