### ISSUE TITLE
New School - Hide Headers on Vocabularies When There is No Data

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#3027]
![image](https://user-images.githubusercontent.com/7493331/27106898-41a61fde-504a-11e7-8862-3282c26de39e.png)

**Comment by nancirose** [comment]
Issue appears to be resolved.
![Screenshot (76)](https://user-images.githubusercontent.com/103001847/163441142-3fb4b29f-0088-4ba3-b937-2c065a776f34.png)

-Nanci, Michael

**Comment by dartajax** [comment]
You are correct - this issue has been resolved. I will close this. Great stuff.
