### ISSUE TITLE
New School - Hide Headers on Session Types When There is No Data

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#3028]
![image](https://user-images.githubusercontent.com/7493331/27106931-68d485e6-504a-11e7-8aed-8685bc95d162.png)

**Comment by mhgh22** [comment]
Issue appears to be resolved.

![Screenshot 2022-04-14 at 10-22-28 Ilios Schools](https://user-images.githubusercontent.com/103135575/163442320-2a90e6ad-f68d-482e-acb4-e5e31c6fc13f.png)

-MNS @dartajax

**Comment by dartajax** [comment]
Same as with the previous one - related to #3027 - will close.
