### ISSUE TITLE
Remove Down Arrow From School Vocabularies When None Exist - Not Needed

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#3030]
![image](https://user-images.githubusercontent.com/7493331/27107128-4d9ea54e-504b-11e7-92d7-1482c438131e.png)

**Comment by nancirose** [comment]
There is no down arrow when there are no listings. Issue appears resolved.
![Screenshot (76)](https://user-images.githubusercontent.com/103001847/163455868-a472e89f-ea74-4d1f-8d14-cb7a8c573b2d.png)

**Comment by dartajax** [comment]
You are correct - thanks for checking - I will close this issue.
