### ISSUE TITLE
Week at Glance -- Provide A Method of Choosing Whether to Open or To Save a PDF File 

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#3038]
It would be helpful for students to be able to choose whether they wish to ...

* A. download a document (PDF's especially) or 
* B. open the document in a browser window immediately

We can start with PDF's since these are the most likely to be easily opened in a new browser window; although we would need to test with all browsers possible.

**Comment by jrjohnson** [comment]
This should also apply to the materials list and the single event view.

**Comment by dartajax** [comment]
This applies to ...

* Week at A Glance
* My Materials
* Event Detail

**Comment by stopfstedt** [comment]
done and done.
