### ISSUE TITLE
Change 60-day view window for activities / materials

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#3044]
time to look at making this a configuration issue.

**Comment by jrjohnson** [comment]
Agreed, but at what level? Campus, users primary school, primary cohort, individual user?

Conceivably we can do more than one of these. Campus could set the default and then we could make the '60 Days' Label clickable and the user could edit it and we could store that as their default.

**Comment by saschaben** [comment]
If and when we adopt personal preferences in Ilios, I think this would be an ideal candidate. Until then, it should be addressed at a School level.

**Comment by jrjohnson** [comment]
Removing this component, closing!
