### ISSUE TITLE
Don't Allow Instructor Group Deletion Unless Empty - Same As Learner Groups

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#3046]
With Learner Groups, we do not allow their deletion unless the Group itself is empty - 0 members. We should be doing the same thing here.

![image](https://user-images.githubusercontent.com/7493331/27447654-a79afb6e-5736-11e7-87d9-f1ee47b0d7a6.png)

**Comment by stopfstedt** [comment]
checked with Sascha, he says this restriction is not needed.
