### ISSUE TITLE
Present Better Error When Adding School Competency is not Allowed (non-Developer Users)

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#3055]
See Below ...

![image](https://user-images.githubusercontent.com/7493331/27553510-fa888ebe-5a5f-11e7-96d1-e7c3a0c900ac.png)

![image](https://user-images.githubusercontent.com/7493331/27553525-079df292-5a60-11e7-803a-0085d0da5995.png)

![image](https://user-images.githubusercontent.com/7493331/27553541-1fd5d0aa-5a60-11e7-877c-834da1d9a823.png)

![image](https://user-images.githubusercontent.com/7493331/27553560-2cd495c0-5a60-11e7-9fb3-8f61d593742e.png)

Result of this action ...

![image](https://user-images.githubusercontent.com/7493331/27553577-3d10c418-5a60-11e7-99a5-359d403aabf7.png)

**Comment by saschaben** [comment]
unable to replicate on demo; can you try to replicate in  incognito?

**Comment by dartajax** [comment]
This occurred when I was logged in to demo3 as demo_facutly4 - I will check the permissions on that user. It may be a permissions issue not a bug.

**Comment by dartajax** [comment]
The user has rights to SOM (Primary School) and SOP. The user does not have Developer rights. I was trying to edit Competencies on SOM. Are Instructors / Course Directors supposed to be able to edit School competencies?

**Comment by saschaben** [comment]
A: No. Only developers have the ability to edit school - level attributes.

**Comment by dartajax** [comment]
That makes sense. Should we have that Schools menu item available for them at all then?

**Comment by dartajax** [comment]
This applies to all of the other functionality on the School page as well. New tickets for each functional area may be required. It might be easier to close this ticket and make new ones for all, with the possibility of disabling the functionality instead of having after the fact error messages.

![image](https://user-images.githubusercontent.com/7493331/27560505-3d87a420-5a79-11e7-8227-38e84f88097b.png)
