### ISSUE TITLE
calendar event detail back button does not maintain filter selections

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#3061]
the new back button doesn't persist filter selections if calendar filters are on and actively selected...

**Comment by jrjohnson** [comment]
This isn't a bug with the back button - it is a problem with storing state. We probably need to push filters into the URL or at least into the controller which is a singleton and will maintain that state for us. Let's wait for #3048 to work on this.

**Comment by dartajax** [comment]
This issue still affects users.

**Comment by dartajax** [comment]
Steps ...

* Log onto Ilios as an Admin user - netlify or demo
* Click `Calendar`
* Select `All Events` toggle
* Select `Show Filters`
* Select 2018-2019 in the year drop down
* Select `Lecture`
* Scroll forward a couple of weeks when there is more activity (week of April 28, 2019) for example
* Click on one of the green lecture rectangles to go to the event detail screen 
* Click the `Back` link to come back to the calendar

Notice that the filter that was applied "Lecture" has been removed and All Events with no filter is now being displayed again.
