### ISSUE TITLE
School Competencies Not Formatted Correctly in Netlify Preview 

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#3071]
Here is what I am seeing when I was testing a PR -- #3070 which I will probably approve soon ...

![image](https://user-images.githubusercontent.com/7493331/27701170-ee8f6ed2-5cb4-11e7-9ba3-686076668e9e.png)

It looks okay until it is compared to what it should be (what is thankfully currently in prod) ...

![image](https://user-images.githubusercontent.com/7493331/27701220-0a4f491c-5cb5-11e7-974c-fb24cd9eff7a.png)

The one below has a box around it and proper indentation of Competency Domains.

**Comment by jrjohnson** [comment]
This was caused by inadvertently removing the .static_list class. We need to replace it with the mixin from ilios/common.
https://github.com/ilios/frontend/pull/3048/files#diff-5e9f85ea444f46c5c98e504c2c23ca05L138
