### ISSUE TITLE
supplemental vs required no longer displayed in event detail page

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#3084]
the flag for displaying supplemental vs required activities has dropped from display; it needs to be added back to Calendar Event Detail & to Week at a Glance.

Prior to addressing this, we need to determine what icon set will best represent this to students; keeping in mind that "required" is the default state, and "supplemental" is the flag when the attribute is turned on.

**Comment by jrjohnson** [comment]
How about http://fontawesome.io/icon/calendar-minus-o/ for supplemental?
