### ISSUE TITLE
Update style for headers of information in publish "Review" pane

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#309]
Right now, there is no visual distinction for the user between _required_ and _desired_ fields in the review pane(s). We need to clarify for the user so that there is no confusion regarding why something may be unpublishable -- and have no option to publish that is visible. A simple fix would be to un-bold all desired fields, and leave bold required fields. Or something along those lines.

COURSE LEVEL:
**Course Title** - required
**Cohorts** - required
_Topics_ - desired
_Objectives_ - desired
_MeSH Terms_ - desired

![course 2015-03-13 12-40-08](https://cloud.githubusercontent.com/assets/1753431/6646041/777d2616-c97e-11e4-9ae1-5d53e995b786.png)

SESSION LEVEL:
**Session Title** - required
**Offerings** - required
_Topics_ - desired
_Objectives_ - desired
_MeSH Terms_ - desired

![session 2015-03-13 12-39-40](https://cloud.githubusercontent.com/assets/1753431/6646027/54f3e59e-c97e-11e4-93f7-c4e481323b7a.png)

**Comment by jenzweben** [comment]
How about this?  
![screen shot 2015-03-23 at 10 34 34 am](https://cloud.githubusercontent.com/assets/5023894/6786237/479a39d0-d148-11e4-9131-a9fcb578dfbe.png)

**Comment by saschaben** [comment]
@jenzweben this looks good -- especially if we can provide a mouseover tooltip on the red asterisk and legend "you will not be able to publish until all required fields are completed" ( @jrjohnson ??)
