### ISSUE TITLE
Cancel Button On Demo3 >> Add New Users (Bulk) Does Nothing

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#3096]
![image](https://user-images.githubusercontent.com/7493331/28332053-30ccaf60-6ba8-11e7-8774-c652772d86d4.png)

**Comment by dartajax** [comment]
That button still does nothing.

**Comment by dartajax** [comment]
The format has changed but the issue remains.

**Comment by stopfstedt** [comment]
fixed.
