### ISSUE TITLE
Update Filter button language labels

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#3099]
To make the filter buttons more accurate, the language should be changed on the "course / session type" button to be:

![newbutton](https://user-images.githubusercontent.com/1753431/28342826-11ce54c0-6bcf-11e7-9ca0-541eaea7b3b4.png)

This will also allow for the addition if needed of other categories of filter along with the cohort / program data (like groups and objectives for instance).

replaces #853

**Comment by dartajax** [comment]
also replaces #782
