### ISSUE TITLE
Remove extra header showing up in Sessions section of Course Detail Page

### ISSUE THREAD

**Issue by jenzweben** [ilios/frontend#310]
Currently seeing this:

![screen shot 2015-03-16 at 12 14 14 pm](https://cloud.githubusercontent.com/assets/5023894/6674311/03bdcc08-cbd6-11e4-9c09-b50d12c8a0e4.png)

Should look like this:

![screen shot 2015-03-16 at 12 09 56 pm](https://cloud.githubusercontent.com/assets/5023894/6674315/118d1078-cbd6-11e4-8b0c-1df8f19c849a.png)

**Comment by jenzweben** [comment]
@thecoolestguy what's the status on this?  Is it clear what needs to be fixed?

**Comment by saschaben** [comment]
I think this is fixed now.

**Comment by jenzweben** [comment]
I just rebased but I'll check again tomorrow but it still looks incorrect to me - showing 2 session headers (one orange and one gray with gray bg that should not be there....

![screen shot 2015-04-30 at 4 27 43 pm](https://cloud.githubusercontent.com/assets/5023894/7424449/f27eb9ae-ef55-11e4-8322-2ed5dc851c2e.png)
