### ISSUE TITLE
Put calendar icon inside date box

### ISSUE THREAD

**Issue by jenzweben** [ilios/frontend#311]
This is totally icing on the cake but might also be a usability issue I was expecting to open the calendar picker by clicking on the calendar icon instead of in the date box...

Existing:
![screen shot 2015-03-16 at 12 42 27 pm](https://cloud.githubusercontent.com/assets/5023894/6674879/f62ece9e-cbd9-11e4-9ec4-815b72206a2e.png)

Desired:
![screen shot 2015-03-16 at 12 42 10 pm](https://cloud.githubusercontent.com/assets/5023894/6674883/ff6f3480-cbd9-11e4-826d-2d8f7ba3ed8a.png)

**Comment by dartajax** [comment]
I had seen that one but I thought mine was different since the icon (whether inside the box or not) did not seem to do anything.  Oh well, we will test to make sure it works before closing this one (#311) in any case.

**Comment by jenzweben** [comment]
I'll upgrade from "icing on the cake"  :)

**Comment by dartajax** [comment]
That sounds good.

**Comment by dartajax** [comment]
Quick comment - I noticed that the calendar pops up when you click into the field but will not pop up when clicking on the icon.  So ... the functionality is there but the icon doesn't do anything.  It seems to work well however.
