### ISSUE TITLE
Need To Handle Missing Data So That Dashboard Always Loads

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#3132]
There was a situation recently where the user had a report in "My Reports" that referenced a Course (Course 10) that has since been deleted.

This caused the entire dashboard not to load as a result. This can be seen in the snippet below.

```[2017-08-02 17:00:18] app.ERROR: {"mainMessage":"Expected: '<course:10>' to be present in the adapter provided payload, but it was not found.","stack":"Error: Expected: '<course:10>' to be present in the adapter provided payload, but it was not found.\n    at a (https:\/\/d26vzvixg52o0d.cloudfront.net\/assets\/vendor-db9fe70bfc871382ef59d47bc636e6ef.js:11693:25)\n    at r (https:\/\/d26vzvixg52o0d.cloudfront.net\/assets\/vendor-db9fe70bfc871382ef59d47bc636e6ef.js:11692:30)\n    at ...```

We need to have a workaround so that even if data is missing, the Dashboard still loads.

**Comment by stopfstedt** [comment]
on it.

**Comment by stopfstedt** [comment]
closed via #3133.
