### ISSUE TITLE
Print Preview Does Not Display ILM Due Dates

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#3141]
see the screen shots for reference ...

![image](https://user-images.githubusercontent.com/7493331/29231726-1f23ba08-7e9d-11e7-875a-03e2fb6b4b15.png)

![image](https://user-images.githubusercontent.com/7493331/29231770-41101620-7e9d-11e7-9f43-b3f65908387a.png)

**Comment by stopfstedt** [comment]
several other session-related data points that are not coming through either

- session description
- ilm hours
- is ilm?

fixing these as well while at it.
