### ISSUE TITLE
Course Screen (Directors) Not Loading Up Completely Until Hard Refresh

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#3147]
One of the directors was missing from the initial load. It is not limited to one record - kind of random. I have seen ones where more than one were missing.

![image](https://user-images.githubusercontent.com/7493331/29291305-ffc7fbee-80f7-11e7-9347-3b2982911e7f.png)

**Comment by dartajax** [comment]
This also happened in ILM Instructors I just noticed. New ticket?

**Comment by jrjohnson** [comment]
This is resolved with a downgrade of ember data but a test should be added before this issue is closed.

**Comment by stopfstedt** [comment]
@jrjohnson we already covered the display of course directors in an acceptance test, here: https://github.com/ilios/frontend/blob/v4.0.0/tests/acceptance/course/overview-test.js#L65
what else should be added in that matter?

**Comment by jrjohnson** [comment]
I honestly don't remember. Will go ahead and close.
