### ISSUE TITLE
In French or Spanish Clicking "All Events" or "My Schedule" Causes Calendar to Shift Days (1 or 2 Days)

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#3158]
It causes the calendar to switch to start on Monday (instead of Sunday) or Tuesday (instead of Sunday).

Steps and screen shots below ...

Calendar >> English >> All Events 

... starts with Sunday (correct behavior)

![image](https://user-images.githubusercontent.com/7493331/29330582-833cadce-81ae-11e7-8664-641b078fef3b.png)

Now switch to Spanish ...

![image](https://user-images.githubusercontent.com/7493331/29330620-a0c69db4-81ae-11e7-9b08-e23a69b88b4b.png)

We're still fine since "dom." is Sunday.

![image](https://user-images.githubusercontent.com/7493331/29330634-adb1c300-81ae-11e7-81a6-f24218b2c6b8.png)

Now click the button "Mi Horario" = "My Schedule" and watch the shift take place. Results below ...

![image](https://user-images.githubusercontent.com/7493331/29330688-d6628bb8-81ae-11e7-8433-dd38c05430fb.png)

"dom." switched way over to the end of the week when it should be starting the week off. We did this same test at our meeting and it switched all the way to Tuesday (instead of Monday) so during your testing, that may be the case.

**Comment by saschaben** [comment]
This wil be resolved with CSS grids.
