### ISSUE TITLE
Publish link drop downs are getting cut off

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#317]
the right margin of the ember view panel is cutting off the edge of the dropdown values in the publish control selector.
![ilios 2015-03-17 11-54-42](https://cloud.githubusercontent.com/assets/1753431/6695186/7e6ff9e6-cc9c-11e4-894c-31593094b59f.png)

![ilios 2015-03-17 11-55-07](https://cloud.githubusercontent.com/assets/1753431/6695187/81a8d5ba-cc9c-11e4-9cec-dbaf21ffa8b9.png)

modifying the padding/margins of .detail-view .detail-header .actions should clear this up.

**Comment by jenzweben** [comment]
need a new class for the publish menu - right now it's using the global action-menu

**Comment by thecoolestguy** [comment]
Let's have the edges right-align instead... This will fix the underlap problem without having to setup another containing grid that could affect alot of previous styling...
