### ISSUE TITLE
[meta] Refactor Reporting in MyReports

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#3176]
MyReports is getting creaky, and as we enter another accreditation cycle, our needs are only expanding. We should refactor reporting to provide a more robust formula for data returns. In part it should:

Coordinate with the visualizations;
Provide for multi-select search (and mixed predicate) options;
Allow for Academic Year filtering;
Provide print/export capability.

This supercedes issues ilios/frontend#2837, ilios/frontend#1520, ilios/frontend#1381, ilios/frontend#2445, ilios/frontend#2809, ilios/frontend#2978, ilios/frontend#2997,  ilios/ilios#4339, ilios/ilios#4338, ilios/frontend#3435

**Comment by stopfstedt** [comment]
ember export library https://github.com/roofstock/ember-cli-data-export

**Comment by saschaben** [comment]
11/2107: With UCSF SOM facing an upcoming LCME accreditation cycle, reporting needs to become a priority in the coming year. This ticket and affiliated issues will be our primary tracker for the updates and changes to existing reporting features

**Comment by dartajax** [comment]
refs #3457

**Comment by dartajax** [comment]
refs #3487

**Comment by stopfstedt** [comment]
refs #3589

**Comment by dartajax** [comment]
refs #4241

**Comment by stopfstedt** [comment]
refs #4543

**Comment by dartajax** [comment]
refs #4738

**Comment by dartajax** [comment]
refs #4800

**Comment by dartajax** [comment]
refs #5471

**Comment by jrjohnson** [comment]
Closing meta tickets.
