### ISSUE TITLE
update calendar filter course list

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#3177]
The current filter on the calendar for "course" shows only the course title. In order to avoid confusion over longitudinal courses given across multiple years but with the same name), we should append the external_id as a parenthetical. Courses without an external ID would still just show name.

**Comment by saschaben** [comment]
Current:

![filters1](https://user-images.githubusercontent.com/1753431/29586428-8a0eacc4-873f-11e7-98b0-e6cb968fe071.png)

Proposed:

![filters2](https://user-images.githubusercontent.com/1753431/29586440-92639560-873f-11e7-90ba-eae517d2354c.png)

**Comment by stopfstedt** [comment]
merged and done.
