### ISSUE TITLE
Indentation Needed for Session Offerings to Line Up With Sessions

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#3188]
This is how it is ...

![image](https://user-images.githubusercontent.com/7493331/29734291-2c3ff2f6-89a6-11e7-9bca-3ea0db520371.png)

Should be more like ...

![image](https://user-images.githubusercontent.com/7493331/29734308-4fabd58e-89a6-11e7-8dc0-949db414fff8.png)

**Comment by jrjohnson** [comment]
Fixed in #3578
