### ISSUE TITLE
None Label Should Not Be Visible When Entering the First Report in My Reports

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#3203]
![image](https://user-images.githubusercontent.com/7493331/29895285-693d3eb2-8d8d-11e7-9e77-952b5b1f7ab7.png)

This "None" label should disappear until Cancel is pressed and there are still no reports.

![image](https://user-images.githubusercontent.com/7493331/29895305-7bda2c9c-8d8d-11e7-94ca-3a9fbf3154b1.png)

**Comment by jrjohnson** [comment]
That is all the reports you have. It is at none at that point. It's actually pretty tricky to make it go away in this way.
Could the whole list be invisible when entering a new report?

**Comment by dartajax** [comment]
That might actually be good to keep the whole existing list invisible when entering a new report. I can close this one and enter that one -- also low priority for sure.

**Comment by dartajax** [comment]
After testing, I will just close it. I see your point.
