### ISSUE TITLE
Visualization Popup Session List Gets Cut Off When It Is Larger on screen than the Lower Boundary of the Display Container

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#3205]
See the screen shot below for reference. The list of the Sessions associated with the selected Competency is getting off when it exceed the size of the Display Container.

![image](https://user-images.githubusercontent.com/7493331/29899743-26efe018-8da2-11e7-8673-41586ee3a69b.png)

**Comment by jrjohnson** [comment]
I believe this was fixed in #3549. @dartajax please verify and re-open if necessary.
