### ISSUE TITLE
Mesh does not return correct results

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#322]
Mesh basically doesn't work. Any search on any topic returns the same results subset:
>>
Calcimycin
Temefos
Abattoirs
Abbreviations as Topic
Abdomen
Abdomen, Acute
Abdominal Injuries
Abdominal Neoplasms
Abdominal Muscles
Abducens Nerve
Abelson murine leukemia virus
Abetalipoproteinemia
Congenital Abnormalities
Abnormalities, Drug-Induced
Abnormalities, Multiple
Abnormalities, Radiation-Induced
ABO Blood-Group System
Abomasum
Abortifacient Agents
Abortifacient Agents, Nonsteroidal

and that's it/.

**Comment by jrjohnson** [comment]
Is this in the vagrant environment?

**Comment by saschaben** [comment]
this is with the vagrant environment as well as the dev fixtures

**Comment by jrjohnson** [comment]
API issue create as: https://github.com/ilios/ilios/issues/811
