### ISSUE TITLE
New Vocabulary Added >> List Not Refreshed

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#3229]
![image](https://user-images.githubusercontent.com/7493331/30185356-e5033ef4-93d5-11e7-96ac-d8e536f14aea.png)

It should have been added to the list below. The count now is update to (3) but the list is not refreshed.

![image](https://user-images.githubusercontent.com/7493331/30185387-09f58be0-93d6-11e7-948f-f857293f3923.png)

**Comment by dartajax** [comment]
Worse yet, clicking on the `New Vocab Type` "link" doesn't work either - It can't find the newly added vocabulary.

**Comment by stopfstedt** [comment]
just checked the code and this component could/should receive a rewrite. un-assigning myself from this ticket, for now. but will try to grab it again soon. very soon.
