### ISSUE TITLE
Courses and Sessions >> Add New Session saves as Published Automatically

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#323]
I may not have the latest code; but I noticed that while adding a new session, it is saved automatically as Published.  The Course is already published - that's true (even though there is no cohort and that should not have been allowed either); the user should still be able (or required) to select the publish status of each session being added.

**Comment by saschaben** [comment]
hrrm. new entities should always save to the "unpublished" state. good catch.

**Comment by saschaben** [comment]
Actually, it looks like new sessions do not, but I believe this is related to #289; we can test this as soon as #308 is merged.
