### ISSUE TITLE
Prompt and Confirmation Needed When Session Type Gets Deleted

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#3231]
If a Session Type can be deleted (ie. hasn't been used), and it gets deleted / removed in Ilios, there is no message asking the user if he or she is certain this is what is wanted AND there is no confirmation once the action has been completed.

See below.

![image](https://user-images.githubusercontent.com/7493331/30187764-d70e92da-93df-11e7-87eb-92059bef1540.png)

And then ... (crickets)

This list appears to flutter but the user should be prompted and then should receive a confirmation with even a possibility of undoing that action just in case.

![image](https://user-images.githubusercontent.com/7493331/30187798-0233d844-93e0-11e7-8da3-aecda96e805b.png)

**Comment by dartajax** [comment]
This issue still exists.

**Comment by mhgh22** [comment]
Cannot confirm since "delete option" trash can is grayed out.

![Screenshot 2022-04-14 at 12-18-59 Ilios Schools](https://user-images.githubusercontent.com/103135575/163461673-03aa02b0-d65f-4ea0-bd49-48f81fbaa20e.png)

-MNS @dartajax

**Comment by dartajax** [comment]
Related to #3230 in the sense that it has to do with adding or removing sessions types. I tested and it's still an issue.
