### ISSUE TITLE
Improved Formatting Needed For LM's on Event Detail

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#3233]
![image](https://user-images.githubusercontent.com/7493331/30299058-d31e5c98-9702-11e7-97aa-d401a491fcc0.png)

**Comment by dartajax** [comment]
The logic behind this ticket is that a Learning Material's description appears with too much space below and above it and it should be indented and if possible have a smaller, non-bold font.

**Comment by jrjohnson** [comment]
@dartajax please add a link to demo where this is happening so it's easier to discover / test.

**Comment by ShortonIT** [comment]
Formatting appears okay.  Cannot confirm or duplicate if "required prep work" font is smaller, non-bold font and spacing. @dartajax Interns Nanci/Michael/Stacey
![ticket 3233](https://user-images.githubusercontent.com/103003096/162278587-26560e52-8cb4-432e-b8ca-873631cec02c.PNG)

**Comment by dartajax** [comment]
![image](https://user-images.githubusercontent.com/7493331/162283855-0bf12bac-b7fd-43cc-8f5b-204e2d1794ac.png)
