### ISSUE TITLE
Learner Group Deletion Should Be Available If Not Attached to Published Offerings Regardless of Membership

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#3249]
I have always thought this should be the case. Currently we only allow empty Learner Groups to be deleted. This ability to delete a Learner Group should be based on whether or not it is attached to any offerings, regardless of whether there are learners in the group.

It seems strange to have to remove all of the learners to remove the group. It is true that the user is prompted before removing a learner group; but no mention is made about how many offerings are attached to the group.

The main reason Learner Groups should not be deleted is because they are used in Calendared learning activities - not because there happen to be learners in the group.

![Selection_412](https://user-images.githubusercontent.com/1410427/55595138-55ecbd80-56f7-11e9-82d9-cb75453f2bd9.png)

**Comment by stopfstedt** [comment]
to re-phrase this old ticket:

the emptiness check should not be for users assigned to a learner group, but whether the learner group is linked to offerings or ilms. groups that are linked should not be deletable.

**Comment by stopfstedt** [comment]
expanding the scope a bit - add a column to the learner group list table that show how many courses are linked (via ilms or offerings) to each learner group.
