### ISSUE TITLE
Inconsistent Placement Of Text and Drop-Down Controls - New Session

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#3266]
This is a cropped image showing the placement of the controls when adding a new session to a particular course in SOD.

![image](https://user-images.githubusercontent.com/7493331/30764735-2c01144e-9fa1-11e7-9bb5-88c8ce39e43a.png)

Otherwise they are in line but too far over to the left. Some courses cause this out of line business and some don't - title length maybe?

Here is a course in SOM with better alignment ...

![image](https://user-images.githubusercontent.com/7493331/30764834-9398140e-9fa1-11e7-90b2-fd3f626d2d38.png)

**Comment by dartajax** [comment]
https://ilios3-demo.ucsf.edu/courses/1204 - SOM - OK but too far over to the left.

https://ilios3-demo.ucsf.edu/courses/1165 - SOD - alignment not correct

**Comment by jrjohnson** [comment]
Probably happens when the length of session types is too short, need CSS to take up the full space.

**Comment by nancirose** [comment]
Since we don't have access to add new sessions, issue was unable to be duplicated. 
-Nanci, Stacey, Michael

**Comment by nancirose** [comment]
Unable to add session in SOD.  However, attached is screenshot of session in SOM which appears okay.
-Nanci, Michael, Stacey

![Screenshot (77)](https://user-images.githubusercontent.com/103001847/163844387-fdbec734-b5f1-42d6-a830-dcb654fcbed6.png)
