### ISSUE TITLE
tighten up the display of availability dates for timed release learning materials

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#3272]
for all LMs with timed release values, the following rules should be applied to the display of the timing information:

> 1: `Available: [startdate]` _ONLY_
   Displays prior to `[startdate]`
   does not display after `[startdate]`

> 2: `Available until [enddate]` _ONLY_
   Displays prior to `[enddate]` including availability window
   does not display after `[enddate]`

> 3: `Available: [startdate] and Available Until [enddate]`
   Displays prior to `[startdate]` including availability window
   does not display after `[enddate]`

**Comment by jrjohnson** [comment]
I feel like end day should say was available until. To avoid confusion about why it is broken.

**Comment by saschaben** [comment]
no was. I hate was.

**Comment by jrjohnson** [comment]
@saschaben can you confirm the capitalization in:
> Available: [startdate] and Available Until [enddate]

**Comment by saschaben** [comment]
Good catch. This should be a match to the (sentence) case style in the other messages: `Available: [startdate] and available until [enddate]`. Please update.

**Comment by jrjohnson** [comment]
Also need to confirm that nothing displays after the end date passes? Just an un-clickable link?

**Comment by saschaben** [comment]
Correct

**Comment by dartajax** [comment]
![image](https://user-images.githubusercontent.com/7493331/35120883-6e4d9192-fc4e-11e7-8d94-09f7243de20e.png)

The titles of these LM's reflect their status. This may be what we were wanting to accomplish.

**Comment by dartajax** [comment]
Except the second example above `In Zone End Date - No Start` should display the `End Date` per rule number 2 above.

2: Available until [enddate] ONLY
Displays prior to [enddate] including availability window
does not display after [enddate]

**Comment by dartajax** [comment]
Another rule buster -- `In Zone Start / End` should display the End Date per rule number 3.

3: Available: [startdate] and Available Until [enddate]
Displays prior to [startdate] including availability window
does not display after [enddate]

**Comment by saschaben** [comment]
@dartajax is correct: any item with an end date set should always display the end date prior to that end date (rules 2 and 3), regardless of whether or not start date is past.
