### ISSUE TITLE
Draft Mode LM's Are Not Being Checked Anymore

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#3273]
Since the advent of timed release, it appears that the frontend is not checking to see if a Learning Material is finalized or not. It is only checking the start and end release dates of the LM.

In this example, none of the LM's have timed release but three of the eight are in Draft mode and should not be displayed on the Event Detail or Week At a Glance.

![image](https://user-images.githubusercontent.com/7493331/30836778-45525a5e-a215-11e7-8eb4-e423260b6b32.png)

A logged in student sees this ...

![image](https://user-images.githubusercontent.com/7493331/30836855-b360e0ba-a215-11e7-822a-486c01a92056.png)

The blue arrows point to LM's that should not be displayed since they are in draft mode.

![image](https://user-images.githubusercontent.com/7493331/30836888-ea053e18-a215-11e7-8ce0-208c11fb74eb.png)

**Comment by stopfstedt** [comment]
backend issue. working on it.

**Comment by stopfstedt** [comment]
fixed.
