### ISSUE TITLE
Courses and Sessions >> Add (New) Session (or edit) >> Search For Directors Result Box Should Disappear on Lost Focus

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#329]
As a user, I noticed that after searching for a Director and clicking elsewhere, that the result callout of "keep typing" or "no results found" is persistent.  It should disappear if the user (me) clicks elsewhere.
![keeptyping](https://cloud.githubusercontent.com/assets/7493331/6719643/40f6f4a6-cd79-11e4-8122-c52751b6e7a9.JPG)

**Comment by jrjohnson** [comment]
We use a different component for this now and it does disappear when the input box is filled. It also includes an (x) to close it manually.
