### ISSUE TITLE
"connection lost" banner gives false positives which do not clear

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#3315]
In certain situations, our "connection lost" banner displays when a live network connection is available, and cannot be cleared without disconnecting/reconnecting the network. This could be due to misreading the initial state on load --- this is often seen when a machine wakes from sleep, or moves while in sleep mode from one network (or network node) to another. I'm going to guess that the sniffer does not actually check for network state, but only for a change state, and so if the "state" of the netwrk changes without disconnection, we get borked. Not sure quite how we resolve this.

**Comment by jrjohnson** [comment]
This seems to be a reported chrome bug, but there is no solution. @saschaben if you can come up with reliable repeat steps that seems to be what is missing. Though - this report suggests it is sporadic when waking up from sleep, which i think is what you're already seeing. https://bugs.chromium.org/p/chromium/issues/detail?id=678075

**Comment by saschaben** [comment]
Yeah -- reading the report thread, this seems to be it. Sporadic, hard to replicate, intermittent when waking from sleep on a mac. I guess we will just endure.
