### ISSUE TITLE
Courses and Sessions >> Session >> Add Parent Objective to Session Objective Strange Highlighting Behavior

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#335]
I noticed (but for some reason, am unable to screen shoot) that when the user (me) selects a different Parent Objective, the previously selected one ends up having a box around it.  If the user (me) selects a different level, the previous top level is selected still.  I am glad to demonstrate this since this ticket is confusing I admit.

**Comment by saschaben** [comment]
browser / mouse artifact.

**Comment by dartajax** [comment]
House cleaning issue close -- couldn't reproduce
