### ISSUE TITLE
new loading scaffold has 10px offset on load

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#3357]
The current grids for the dashboard and course loading scaffolding is approximately 10px offset to the right of the actual dashboard containers. This causes the content to appear to "jump" to the left when content actually loads.

**Comment by saschaben** [comment]
ugh. nevermind. Is due to the load-in of the vertical scroll.

Would be nice to find a way to address this with more finesse.

**Comment by jrjohnson** [comment]
css grids may be the answer to this. I was trying to figure out if it had shipped yet in Edge, but I didn't see anything definitive.  Was supposed to ship 10/17
https://gridbyexample.com/browsers/
