### ISSUE TITLE
filter/search on course list page no longer working

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#336]
looks like we lost this in the last batch of merges.

**Comment by jrjohnson** [comment]
Well now we have tests. So hopefully we can stop dropping features when we add code.

**Comment by saschaben** [comment]
closing: duplicate of #319

**Comment by saschaben** [comment]
not a duplicate. my bad. This is the freetext search box not working. 319 was the year filter not working.

text search on course list is still busted.
