### ISSUE TITLE
Restyle offering time block start/end time label

### ISSUE THREAD

**Issue by jenzweben** [ilios/frontend#337]
Currently, the labels "Start:" and "End:" are in the same class as the actual times and the times should be bold while the labels are not...

**Comment by jrjohnson** [comment]
@jenzweben  - this is start, end in offerings correct?  Should we make it:
```html
<span class='offering-block-time-time-starttime'><label>Start:</label> 10:00am</span>
```

or does it need to be
```html
<span class='offering-block-time-time-starttime'><label class='offering-block-time-time-starttime-label'>Start:</label> 10:00am</span>
```

**Comment by jenzweben** [comment]
the latter
