### ISSUE TITLE
Add Learner Group Calendar to Ilios

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#3401]
We should add a calendar to the Learner Groups functional area of Ilios which will display the weekly view of the calendar displaying all of the offerings associated with the selected learner group for the current week. 

Can we make this one scrollable to go forward or backwards in time?

**Comment by dartajax** [comment]
This is similar to the way we have calendars in the Admin console person lookup as well as the Offerings editor.

**Comment by jrjohnson** [comment]
@dartajax / @saschaben what events should appear on this calendar? Just those attached to the current group? Or should we include sub-groups as well?

**Comment by dartajax** [comment]
If I had my wish list, I would want it to display the events for the current group. But if the current group has sub-groups below it, to have the ability to toggle the sub group events to display or not would blow minds - including mine.
