### ISSUE TITLE
Suggested Starting Point for Offerings Editor

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#3402]
I came up with a quick mock of an idea of how to improve the offerings editor. It is by no means complete. More screen shots will be added to this issue to better explain the scenarios. Hopefully this will serve as a good starting point for us to discuss.

![new_offering_3](https://user-images.githubusercontent.com/7493331/33103600-0976719c-ced8-11e7-9c76-d5bad17c09c0.png)

**Comment by dartajax** [comment]
Fields needed ...

If offering ...
* Start Date 
* Start Time (with time zone indicator)
* Duration 
    * Hours
    * Minutes
* Make Recurring Toggle
* Location (with no default disclaimer)
* URL
* Instructors (with no default disclaimer) - Instructors and Instructor Groups (maybe make two fields like Learners)
* Learners
   * Learners -search for and selected
   * Learner Groups - search for and selected
* Save and Cancel buttons

**Comment by dartajax** [comment]
Fields needed ...

If small groups // new offering ...

* Start Date
* Start Time (with time zone indicator)
* Duration
   * Hours
   * Minutes
* Make Recurring Toggle
* Learner Groups - search for and select

URL's get added later. Location and Instructor can and will accept defaults (no message needed) or can be added later like URL's - same process.

**Comment by dartajax** [comment]
This new screen shot may be another useful approach to take as we look at the larger picture of the offerings editor re-design. 

![image](https://user-images.githubusercontent.com/7493331/91497231-72e8da00-e872-11ea-8f4b-41ab9dd2d549.png)

**Comment by dartajax** [comment]
Additionally, regarding the screen shot mock above, the idea of having a "Participants" label in the "Details" area sort of to group together Instructors and Learners as "Participants". Also, if this is a new offering, we should have the default be to have "Manage Instructors" and "Manage Learners" open by default. In the mock above, the user would need to click on the right facing triangle to get to this functionality and view.

**Comment by stopfstedt** [comment]
closed via https://github.com/ilios/common/pull/1716
