### ISSUE TITLE
Courses and Sessions >> Add New Course >> Suggestion -- Place Add Cohort Higher on the Screen

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#342]
I noticed that while adding a new course, it might make more sense to bring the cohort association area higher up on the screen.  It is something that I imagine the user would want to do fairly early on in the process of created a new course.

Even parent objectives (objectives come first currently) can't be assigned until one or more cohorts have been selected.

**Comment by dartajax** [comment]
And yes, it is true that the user cannot assign parent objectives (competencies) until the course objectives have been entered.

**Comment by jrjohnson** [comment]
We settled on this order based on user feedback. I'm going to close, but feel free to re-open if different feedback has emerged.
