### ISSUE TITLE
Instructor selection resets while selecting/adding instructors to offerings

### ISSUE THREAD

**Issue by thecoolestguy** [ilios/frontend#3462]
When attempting to add multiple instructors to an offering, instructor info may need to be entered twice before becoming selectable and selections can often reset before saving.

Kylie has been experiencing trouble with adding instructors to offerings and has created a screencast to show what is happening at https://ucsf.box.com/s/lf6s4x4phh7ppw6naiow4kri3e0o9cry

Error is reproducible and is therefore bug.  Is probably related to the Ember concurrency issue we addressed in #2838

**Comment by stopfstedt** [comment]
confirmed that this duplicates #2838. in the given screencast, the instructor picker dialog blows up when a user who's directing the offering-owning course is added to the offering.
