### ISSUE TITLE
Courses and Sessions >> Expand / Collapse All Sessions

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#347]
I don't see an option to Expand All Sessions / Collapse All Sessions like there is in 2.4.x.

**Comment by saschaben** [comment]
We should address this as a follow-on to #226

**Comment by dartajax** [comment]
I meant to keep this open.  I am sorry for the confusion.  There does need to be a mechanism for expanding all sessions at the same time.

**Comment by jrjohnson** [comment]
@dartajax  Does this mean to expand all of the offering summaries for all of the sessions?  Because sessions themselves no longer expand at all.

**Comment by saschaben** [comment]
@jrjohnson this refers to the "eyeball" summary inspection view for sessions, and relates to the use case for reviewing a course prior to publication for completeness.

**Comment by jrjohnson** [comment]
Ok - any thoughts on where to put such a control?  Does it only expand the sessions that appear in the list (which is paged) or does it automatically also load every session onto the screen?

**Comment by saschaben** [comment]
This should refer only to those sessions that appear in the list on screen. I would think an über eyeball next to the sort control for offerings would be the appropriate placement. BUT...to really address use need, this should actually be a different mode of view: one which displays a list of all offerings for all displayed sessions in correct aggregated date order. This is what they are driving at as well in #1264.

**Comment by dartajax** [comment]
We have this now.
