### ISSUE TITLE
Publish flow incorrect on ILM session fields

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#353]
When a session is checked as "Independent learning", its nature changes: it has a due by date which is both required and unavoidable. It never has offerings. So when testing state for publishing, an ILM session should NOT check for having offerings, and publishing SHOULD be available without them.

**Comment by jrjohnson** [comment]
Lets add to this that the offerings list should not be available at all from an ILM session.

**Comment by saschaben** [comment]
I mispoke: it never HAS to have offerings. There are actually good reasons to continue to allow ILM sessions to have offerings attached. Great pedagogical discussion there, total waste of time to have it here though. See #354.
