### ISSUE TITLE
Validation Error On CI Seq Block Entry - Duration Should Not Be Req'd If St/End Dates are Present

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#3530]
Currently if you enter and save a start date and and end date for a sequence block in a CI Report but there was already an entry saved in the duration field, it becomes impossible to delete the duration value even though it should be possible because EITHER duration OR start / end date is required as entry in this area.

![image](https://user-images.githubusercontent.com/7493331/35948924-d3b9ec62-0c23-11e8-8627-5443333627e5.png)

**Comment by stopfstedt** [comment]
hmm ok. noted!
for the time being, you can work around this by putting a `0` in.

**Comment by dartajax** [comment]
ok - thanks for letting me know

**Comment by stopfstedt** [comment]
ok, just played this through. there is no way to have it both ways. the duration field must have a value. so setting it to `0` is the solution.
