### ISSUE TITLE
ILM requires addition of option to add groups directly

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#354]
in line with #353, ILM sessions are a different beast: when the ILM checkbox is activated, the functionality that must occur is:

1: appearance of instructional hours and due by date fields;
2: ability to add groups to the ILM directly, rather than via an offering.

the ability to add offerings per usual to the ILM session should remain (please don't ask why, but it's actually quite useful).

**Comment by jrjohnson** [comment]
So I'm thinking the best way to do this is to put an offering manager in ILM sessions at the same level as objectives / learning materials and using that same format.  It would display the groups by default and then allow the user to 'manage' those groups with a click.  I would then remove the group list for the overview at the top.  
@saschaben, @jenzweben does that make sense?

**Comment by saschaben** [comment]
@jrjohnson If I am reading correctly, I like it. That is really where the control is most accessible in this instance. then once the selection /entry process is complete, groups are assigned and will display in the offerings list, and be added to the group list at course level. As long as the possibility to edit remains openly available to the user, this seems like a reasonable approach

**Comment by saschaben** [comment]
Further: if we follow this route, the new manager should be at the top of the stack: eg right below the (current) session group list and above objectives, and it would effectively replace the group list for an ILM.

questions: 
*how do we handle the case of a session with offering assignments that gets "clicked over" to an ILM? (currently we destroy all groups associations and offering records, and start from scratch). 
*How do we handle the case of an ILM session with groups and time assignments that gets "clicked over" to a normal session? (currently we destroy all group associations as well as the ilm_session_facet, and start from scratch).

I'm not suggesting we get fancy here on the functionality side, but I want us all thinking about the user flow in the new interface for this type of conversion action.
