### ISSUE TITLE
New Vocabulary Label Title Label Needs Some Padding

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#3548]
It looks strange squished up against the grey divider bar. The whole thing would look better if there was alignment in the center with Title and the Done / Cancel buttons lined up and equal padding spacing at the top (above Title and entry field) and bottom (below Done / Cancel).

![image](https://user-images.githubusercontent.com/7493331/36321271-168de35a-12fe-11e8-9bdd-62c2cfde4a34.png)

Something like this?

![image](https://user-images.githubusercontent.com/7493331/36321748-c38b7364-12ff-11e8-97c1-e0fa2885b421.png)

**Comment by jrjohnson** [comment]
Fixed in #3578
