### ISSUE TITLE
Courses and Sessions >> Combined Publish Action Menu Items are Truncated

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#357]
See the screenshot - I love it though having all in one menu.
![cutoffpublish](https://cloud.githubusercontent.com/assets/7493331/6761643/8215b900-cf12-11e4-8900-f26f6ff2890e.JPG)

**Comment by saschaben** [comment]
closing -- duplicate of #317

**Comment by dartajax** [comment]
darnit - I didn't see the other other one - sorry
