### ISSUE TITLE
Allow First and Last Name Discrepancies to Be Resolved - Group Assignment Tool

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#3607]
We need to be able to verify on UC ID and allow for first name AND last name mismatches to still be uploaded / assigned.

**Comment by dartajax** [comment]
Wish List - to be able to add a Learner to the Cohort if they are not - advised out of scope - how difficult would that be:?

**Comment by jrjohnson** [comment]
@dartajax adding the user to a cohort should be it's own ticket I think. We can address as another enhancement. It isn't necessarily difficult.
