### ISSUE TITLE
Add filter to manage topics

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#3613]
When looking for a term in a vocabulary a lot of scrolling is necessary to find a term in a long list.  We should add a filter to this.

**Comment by saschaben** [comment]
this is becoming a critical issue foru se of the ucsf49 prior to accreditation visit.

**Comment by stopfstedt** [comment]
suggested workaround for the time being  - use the page search provided by the browser:

![selection_008](https://user-images.githubusercontent.com/1410427/38276194-13d11f00-3749-11e8-81ea-9a06a7c4ac0e.png)

**Comment by jrjohnson** [comment]
This was fixed at some point. Closing.
