### ISSUE TITLE
Course DELETE Not Working 

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#3620]
![image](https://user-images.githubusercontent.com/7493331/37546949-5813175c-292c-11e8-9724-c5e71ded3c22.png)

**Comment by dartajax** [comment]
After dismissing the errors and returning to Ilios ...

![image](https://user-images.githubusercontent.com/7493331/37547014-a024a5ba-292c-11e8-8b5e-d790a06bb6a4.png)

**Comment by dartajax** [comment]
The school does not load up with the payload.

**Comment by jrjohnson** [comment]
This may be permission based. Can you verify on demo?

**Comment by dartajax** [comment]
It happens on demo3 as well - logged in as demo_dev1.

**Comment by jrjohnson** [comment]
Some courses cannot be deleted because they are the ancestor of another course. So once a course has been rolled over it cannot be deleted.
