### ISSUE TITLE
Visualizations do not calculate/sum fractional times correctly

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#3636]
a calculation bug remains in our course visualizations: when counting ILM durations of less than an hour, we aren't getting correct counts. See below -- "histology" is tagged in 2 ILM sessions, one with a duration of 0.75, and one with a duration of 0.5 hours. So we should see a 1.25 hour ("75 Minutes") duration. Instead we see 0.0.

![0 minutes histology](https://user-images.githubusercontent.com/1753431/37838775-032b8d9c-2e76-11e8-84e3-ac4af92f2c14.png)

Sample sessions in question are:
https://deploy-preview-3473--ilios-frontend.netlify.com/courses/1194/sessions/35073
https://deploy-preview-3473--ilios-frontend.netlify.com/courses/1194/sessions/35057

**Comment by jrjohnson** [comment]
This is caused by my bad decision to use parseInt when summing ILM times. We're dropping anything less than 1 and poorly summing everything else.
