### ISSUE TITLE
Minor Spacing Error In Vocabularies

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#3645]
![image](https://user-images.githubusercontent.com/7493331/37935612-0623a3e8-3107-11e8-81a6-ba780df374d2.png)

Should be ...

`Childhood Development Disorders >> Developmental/Learning Disorders >> Autism`

rather than ...
`Childhood Development Disorders >>Developmental/Learning Disorders >>Autism`

If I am incorrect myself on this, we can close the issue.

**Comment by dartajax** [comment]
This has been fixed once the vocabulary item has been saved ...

![image](https://user-images.githubusercontent.com/7493331/72943134-147eda80-3d2a-11ea-80ad-dae812b3e108.png)

But not when in edit mode ...

![image](https://user-images.githubusercontent.com/7493331/72943161-2791aa80-3d2a-11ea-849e-3730d3e8e822.png)

**Comment by stopfstedt** [comment]
fixed via https://github.com/ilios/common/pull/1666
