### ISSUE TITLE
Add New MeSH Term to Course (when one already exists) - Confused By Process

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#371]
I am a bit confused and will attempt to document what I am thinking.  There may be a pull request pending for this issue and if so, I apologize.

I see this ...
![addmesh](https://cloud.githubusercontent.com/assets/7493331/6791105/d652d1ca-d169-11e4-8ab6-d8455ad6ab9a.JPG)

I would like to add an additional MeSH the course objective (indicated by the squiggly blank arrow - my specialty) -- I click on the word "pharmacokinetics" and the following screen appears.
![addmesh2](https://cloud.githubusercontent.com/assets/7493331/6791167/493b42da-d16a-11e4-86bf-d5441445ab8b.JPG)

I now see there are two MeSH terms -- that is because these are Course level MeSH terms not Course Objective level MeSH terms.  I have to scroll up to find the following ...
![addmesh3](https://cloud.githubusercontent.com/assets/7493331/6791199/8817db76-d16a-11e4-9713-637ae705a692.JPG)

So I know that I am adding a MeSH term to an objective so that is where I would add one.  How do I know with which of the 23 Objectives I am associated this MeSH term?  At a minimum, if someone clicks to add a MeSH term to a Course Objective, should not the user be routed to the correct location to take care of this action?  The user should not have to figure out which location is for Course MeSH terms and which location is for Course Objectives MeSH terms.  I know I got confused.

Also, there should be a text element (label or whatever) indicating to the user to which Objective is the one to attach the MeSH term they are trying to find..

**Comment by jenzweben** [comment]
I did some research into scrolling to a specific spot in a page:

http://jsfiddle.net/UPRkm/

this one is not as smooth and it has an unnecessary red header bar but...
http://jsfiddle.net/katowulf/cFYQt/

**Comment by jrjohnson** [comment]
I'm linking this to #539.
