### ISSUE TITLE
Suggested Padding and Header Improvements on Learner Groups

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#3737]
![image](https://user-images.githubusercontent.com/7493331/39386531-f1822a54-4a29-11e8-9892-9895a5a8f86e.png)

**Comment by dartajax** [comment]
This padding setting actually seems to fix #3735 possibly.

**Comment by stopfstedt** [comment]
needs some further discussion. the tables styles are common (and defined in `ilios/common`) and shared among all other tables in the UI. should we apply this more generally? 
will demo on how this may look tomorrow during our weekly meeting.

**Comment by jrjohnson** [comment]
Superseded by life 😁
