### ISSUE TITLE
Course Cohort Management Blows Up 

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#3756]
I am logged in on stage as a user with School Administrator permissions. As such, I should be able to "Update All Courses". 

Some simple updates do not cause issues. I added a Course Administrator for example.

Clicking `Manage Cohorts` caused the following error to occur.

![image](https://user-images.githubusercontent.com/7493331/39454016-c1afef8a-4c8d-11e8-9f70-90ab13890463.png)

**Comment by dartajax** [comment]
After a couple of refreshes, I am able to access the Manage Cohorts functionality with no problem.

**Comment by dartajax** [comment]
Could this be similar to the last one #3753 in the sense that it takes more than one click or refresh to get the correct behavior

**Comment by jrjohnson** [comment]
Fixed in ilios/common#222
