### ISSUE TITLE
Courses and Sessions >> Session >> Add Description >> Save not Occurring

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#376]
I noticed while trying to add a description to a Session that did not have a description, the green check button wasn't processing the save event.

![wontsaveohno](https://cloud.githubusercontent.com/assets/7493331/6807503/12a0c07c-d20c-11e4-96ec-f2f27cffd723.JPG)

Clicking the green check icon does not do anything.  I hope this is not a duplicate - please close if so.

**Comment by jenzweben** [comment]
Same here

**Comment by jrjohnson** [comment]
This will be resolved by #359 I will leave both open for now.

**Comment by jrjohnson** [comment]
Closed by #455
