### ISSUE TITLE
Course and Sessions >> Navigation Question >> Back to Courses List Disappears after Selecting Session

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#377]
I noticed that the link "Back to Courses List" is there when the user shows up to Course and Sessions detail initially but disappears after a Session has been pulled up.

![link1](https://cloud.githubusercontent.com/assets/7493331/6813163/ad8ac37a-d230-11e4-8cc2-65d69cabc81e.JPG)
![link2](https://cloud.githubusercontent.com/assets/7493331/6813167/b08ffa18-d230-11e4-85a4-29bcc34f396e.JPG)
![link3](https://cloud.githubusercontent.com/assets/7493331/6813171/b41b766c-d230-11e4-83cc-874feae9e78e.JPG)

**Comment by dartajax** [comment]
It disappears from the persistent header after a Session is accessed.

**Comment by jenzweben** [comment]
I have replicated this bug.

**Comment by dartajax** [comment]
Can we get this one fixed soon?  It's not a showstopper but would be great if we didn't have to fumble around it in our training sessions.

**Comment by djvoa12** [comment]
[See PR](https://github.com/ilios/frontend/pull/910)
