### ISSUE TITLE
Courses and Sessions >> Course Details >> Close Button Missing at Top of Screen

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#378]
Dupe warning and my apologies if so ...

I had thought after clicking "View All / Edit" ...
![viewalledit](https://cloud.githubusercontent.com/assets/7493331/6813568/8ec8236c-d233-11e4-9555-29245d78d111.JPG)
... that there would be a "Close" button up at the top of the screen so the user does not have to scroll way down to minimize the extra Course details stuff.
![close](https://cloud.githubusercontent.com/assets/7493331/6813584/b6f04bb2-d233-11e4-8609-1b64940372fa.JPG)

**Comment by saschaben** [comment]
Rather than a windowshade, let's consider providing a "hide details/collapse" text link somewhere at the top of the course that only displays when details are expanded....or another icon in the action icons list.

**Comment by saschaben** [comment]
duplicaete
