### ISSUE TITLE
Update Session Count (after Filtering)

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#381]
It seems to me anyway that it would be nice functionality if the Session counter would get updated after the user performs a filter so you (the user) can see how many records have been returned.  When there is no filter in place, the full number of Sessions would display.  However many sessions meet the filter criteria (or lack thereof) would be counted by the Session counter (Sessions(x)) as shown below ...

![sessions120](https://cloud.githubusercontent.com/assets/7493331/6830727/07b0144c-d2d9-11e4-8dd8-d6ed2ffb6801.JPG)

Another snapshot here -- where it says 120, it could change to 1 in this example ...
![sessions1201](https://cloud.githubusercontent.com/assets/7493331/6830776/53f15e56-d2d9-11e4-9865-4a13c9b4cd9c.JPG)

**Comment by dartajax** [comment]
I suppose there could be another counter on the page somewhere if that Sessions label can't be updated.  My point is that it would be nice to see how many records are returned by filtering the total data set.

**Comment by jrjohnson** [comment]
This is very easy to implement either way.  I will leave it up to @jenzweben to decide if we want this number to reflect total or filtered value.  Or even something like (4 of 120).

**Comment by jenzweben** [comment]
@dartajax what is the usage scenario...we should evaluate the usefulness / need for showing filtered count against clutter & dev time...I'm thinking it might be overkill but you're most familiar with users & usage...

**Comment by dartajax** [comment]
I entered this in to GitHub thinking as a user that it would be good if the count reflected how many records were returned after applying the filter being applied.  I like what @jrjohnson says (x of total).  That would be the most useful in my opinion.
