### ISSUE TITLE
Copy An Offering

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#3816]
Add an option to copy an offering within the same session. Would copy it exactly with all groups and times the same.

Discussion:
Add two copy buttons, one copies the offering with groups, the other copies with times. You have to choose one or the other to avoid creating a bunch of duplicate offerings accidentally.

**Comment by saschaben** [comment]
This one confuses me: if it carries all groups AND times, then it is effectively not usable. I could see the value in copying an offering with EITHER all the same time(s) OR all the same group(s), maybe....

**Comment by jrjohnson** [comment]
Killing as user request has gone stale.
