### ISSUE TITLE
Replace vendor scrollbar styles with mixin

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#382]
The current styles defined for scrollbars in global.scss are vendor specific.  Wes should replace them with a mixin which abstracts the details and makes future compatibility simpler.

https://css-tricks.com/snippets/sass/custom-scrollbars-mixin/

**Comment by jenzweben** [comment]
I styled the scrollbars....just want to confirm that this ticket is to improve the way it's coded?  just want to confirm because I want to keep the styles that I put in...

**Comment by jrjohnson** [comment]
Yes styles will stay the same.  I came across the vendor styles and wanted to remind myself to replace them with a mixin later.  Purely a dev problem.

**Comment by jenzweben** [comment]
:) thx

**Comment by saschaben** [comment]
is this still an issue to be addressed? If not, please close, thx.
