### ISSUE TITLE
Adding A User to An Instructor Group Should Provide Instructor Access To Ilios

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#3851]
An acceptable workaround to allow Instructors to access Courses and Sessions before they have been attached to Offerings is to add them to an Instructor Group. Then when they log in to Ilios, they will have access to Courses and Sessions and the Ilios flyout menu at the same level as an Instructor who is attached to an Offering.

This already should be happening actually in this situation.

**Comment by jrjohnson** [comment]
Fixed in https://github.com/ilios/ilios/pull/2156
