### ISSUE TITLE
Mystery Black Rectangle Appears In Offerings Area

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#3877]
Pretend the black arrow in there is a mouse - sorry I didn't capture the actual mouse. Anyway, the black rectangle appears there with nothing in it.

![image](https://user-images.githubusercontent.com/7493331/41618075-0a407ff8-73b7-11e8-9e05-e194714eb5cb.png)

**Comment by jrjohnson** [comment]
This is the result of hovering over a group with no parents. It's the tooltip that would normally show the group tree. We shouldn't show this tooltip if a group has no parents.
