### ISSUE TITLE
Hard Refresh Should Not Be Required to Remove A Course Previously Selected for a Higher Level Sequence Block Shou

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#3915]
To illustrate this ...

* Create a new CI report
![image](https://user-images.githubusercontent.com/7493331/42650831-5a5a5ed8-85c2-11e8-9f19-661296799de6.png)

* Create a Sequence block with a Course attached - in this case Airways, Blood, and Circulation 
![image](https://user-images.githubusercontent.com/7493331/42650890-8a57d8fe-85c2-11e8-9c32-1ed141d89bf8.png)

* Click to add a nested Sequence Block
![image](https://user-images.githubusercontent.com/7493331/42650989-d452b65e-85c2-11e8-8f78-9b581ceafd26.png)

In the past, we noticed that ABC (Airways, Blood, and Circulation) was still available for selection for a nested sequence block, which would be a problem. This time I was unable to recreate the bug possibly due to the long delay in getting the screen shots and documentation. This may still be a bug.

**Comment by dartajax** [comment]
Hard refresh took care of the issue the time we noticed this happened.

**Comment by stopfstedt** [comment]
feedback from a discussion with @dartajax  and @jrjohnson, some of it captured/highlighted in the screenshot below

**outer table**

- expand/collapse icon in header needs to have better contrast, size and positioning
- apply title attribute (shows on hover) to all column headers, for consistency reasons

**inner table**

- put more emphasis on table caption ("Offerings"), or get rid of it altogether
- top-align time values in first column
- apply bottom border to table-spanning row containing date information
- **bug:** zebra striping is inconsistent
- _nice to have_: floating table header

![selection_056](https://user-images.githubusercontent.com/1410427/42652744-31940dc2-85c8-11e8-81b5-63fb9b3445d1.png)

**Comment by stopfstedt** [comment]
@djvoa12  can you please have a look whether this still applies? thanks.

**Comment by djvoa12** [comment]
@stopfstedt @dartajax I don't think this is applicable anymore. It squashed itself.
