### ISSUE TITLE
Ugly Ajax Timeout Messages

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#3958]
These are occurring in production - after approximately 20 minutes and maybe not in every situation. Users reported seeing them as well but since a refresh loads everything back up, they haven't complained. We should handle this better.

![image](https://user-images.githubusercontent.com/7493331/43667136-94eec6ae-972b-11e8-8934-d3d16abcfbac.png)

**Comment by saschaben** [comment]
agreed. My suspicion is that users are accessing sessions which have one or more offerings which they don't have proper permissions to manage. You'll see the same thing on print summary -- a refresh will reload the available parts of the display absent the disallowed bits. we should review for better handling.
