### ISSUE TITLE
Add Learning Materials Needs to be Styled

### ISSUE THREAD

**Issue by jenzweben** [ilios/frontend#396]
This might be a work in progress but it needs styling.  Here's how it looks:

![screen shot 2015-03-30 at 1 13 27 pm](https://cloud.githubusercontent.com/assets/5023894/6905740/0e171614-d6df-11e4-8f04-0bf6d1ab610c.png)

Here's the mock:
![screen shot 2015-03-30 at 1 15 45 pm](https://cloud.githubusercontent.com/assets/5023894/6905749/155b1a88-d6df-11e4-93f1-46b76bd083ca.png)

**Comment by saschaben** [comment]
when we style this, we need to remember to provide form styles for all three variants: document (shown above), link (requires inline display of URL), and citation (requires inline display of citation).

**Comment by saschaben** [comment]
moving this to 0.3.0. Can be worked in conjunction with #452.

**Comment by jrjohnson** [comment]
Fixed in #671
