### ISSUE TITLE
Better Formatting Needed in Narrow Window View of New Inline Offerings Manager 

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#3986]
This would if a user is using a tablet or phone to do Ilios updates to the Offerings in the new Session List being pushed out soon.

There also is no way to cancel a search because the `"Cancel"` is too far to the right as well.

A couple screen shots to illustrate ...

![image](https://user-images.githubusercontent.com/7493331/44492210-83797080-a618-11e8-8a0f-94a3209a023a.png)

![image](https://user-images.githubusercontent.com/7493331/44492298-d4896480-a618-11e8-8cd8-26a08ba12deb.png)

**Comment by dartajax** [comment]
This could soon be irrelevant / redundant as we redo the Offerings manager. We can just close this ticket if that is the case.

**Comment by stopfstedt** [comment]
![Selection_026](https://user-images.githubusercontent.com/1410427/99112989-5facf700-25a3-11eb-9078-ef75c7cc6e36.png)
![Selection_025](https://user-images.githubusercontent.com/1410427/99113001-63407e00-25a3-11eb-9ae7-1810fad1814f.png)

fixed with the recent re-design of the offering form.
