### ISSUE TITLE
Course Title Editing Box

### ISSUE THREAD

**Issue by jenzweben** [ilios/frontend#401]
The check & undo buttons should be on the RIGHT of the inline editing box and the box should be as wide as possible...

![screen shot 2015-03-30 at 2 45 12 pm](https://cloud.githubusercontent.com/assets/5023894/6907506/9252b904-d6eb-11e4-8328-2accb54c4082.png)

**Comment by saschaben** [comment]
@jenzweben buttons are currently on left; is this just a mandate to "Align left and make textbox  _**As Large As Is Possible**_"?

**Comment by jenzweben** [comment]
Sorry - I'm dyslexic they should be on the RIGHT since we have them on the right or below everywhere else.  Not sure about Large vs. Wide...I'd need to see what happens if we go to multi-line editing box.

**Comment by saschaben** [comment]
Got it. Buttons to the right! and I mis-stated: _**AS WIIIIDE AS IS POSSIBLE!**_

Q: will buttons go to the right or left of the academic year label which follows the title? to the left of it means a jumping label (the year has to move out of the way when we shift mode), and to the right means we have buttons quite far from their action component....
