### ISSUE TITLE
View / Edit Session: scroll-to session placement in list is mis-aligned

### ISSUE THREAD

**Issue by jenzweben** [ilios/frontend#403]
When a user clicks on a session that is in the lower part of the session list, the Session details page needs to be auto-scrolled down so that the user can see the Overview section currently, the Session details page is transitioning in at the middle...so users see this

![screen shot 2015-03-30 at 2 55 31 pm](https://cloud.githubusercontent.com/assets/5023894/6907708/5a111ac0-d6ed-11e4-9008-a949452cbe3e.png)

and they should see this:

![screen shot 2015-03-30 at 2 59 48 pm](https://cloud.githubusercontent.com/assets/5023894/6907723/762fa280-d6ed-11e4-9295-79365c193c5a.png)

**Comment by jrjohnson** [comment]
Example implementing scrolling to a selector:
https://github.com/ilios/frontend/blob/master/app/components/detail-objectives.js#L25
