### ISSUE TITLE
Publish Sessions Dropdown contents

### ISSUE THREAD

**Issue by jenzweben** [ilios/frontend#404]
I think we said that we were going to add "Session" to the dropdown menu items in order to differentiate between publishing a Course & a Session...

![screen shot 2015-03-30 at 4 28 00 pm 2](https://cloud.githubusercontent.com/assets/5023894/6909350/0c73b266-d6fa-11e4-9bd3-40de31258aec.png)

**Comment by jenzweben** [comment]
Update - I just saw that we do have "UnPublish Course" and "UnPublish Session" but other options such as "Mark as Scheduled" are not specifically labeled...

**Comment by saschaben** [comment]
I'd like to leave this as is until we can get feedback from users --- the shifts in the overall design have significantly improved the issue, and once we add a "publish all sessions" button somewhere I think it will be event more differentiated. So for now let's hold off on addressing the drop down terminology. If we need to add "session" and "course" to the translation file for these labels later, we will.

**Comment by jenzweben** [comment]
OK
