### ISSUE TITLE
CI Report Rollover Fails with a Permissions-Related Error when User Has Permissions

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#4040]
I am logged in on demo3 as the power user "Nicholas Gutierrez" - profile shown below. Lower shot shows him being assigned as CI Report administrator.

![image](https://user-images.githubusercontent.com/7493331/45327925-76141f80-b50e-11e8-8e05-a13eda774483.png)

![image](https://user-images.githubusercontent.com/7493331/45327933-84fad200-b50e-11e8-9ef3-194f9bcf1160.png)

He is ROOT anyway so that should supersede anything.

![image](https://user-images.githubusercontent.com/7493331/45327982-a3f96400-b50e-11e8-81cc-e41421ab8052.png)

After clicking Done ...

![image](https://user-images.githubusercontent.com/7493331/45327999-b70c3400-b50e-11e8-8f87-3b1e20f27854.png)

**Comment by jrjohnson** [comment]
Moving this to ilios/ilios#2228
