### ISSUE TITLE
CI Report Enhancement Request - Be Able to Specify Start / End Dates for New Report

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#4042]
Below is the interface used in rolling over CI Reports. The start and end dates should be included here with the default being one year later (or a different amount of years if a different target year was chosen) for each of the values. They can then be changed to reflect accuracy. This way when the rolled over CI Report is created, it will not have the previous report's start and end dates.

![image](https://user-images.githubusercontent.com/7493331/45379623-6ef41c80-b5b5-11e8-9cff-eb1f3e544ed7.png)

**Comment by stopfstedt** [comment]
per a conversation with @saschaben, the start/end-date attributes should _not_ be available for manual override on rollover.
instead, they should be set server-side on rollover, based on the given july 1st to june 30th range within the given academic year.
