### ISSUE TITLE
Add / Maintain Learning Material Issues with Weblink and Citation

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#406]
During testing, it became apparent that when the user (me) adds a Learning material to a Course or a Session that is of the type Weblink or Citation, the actual weblink or citation does not actually get saved and is not available for modification anywhere.
![addweblink](https://cloud.githubusercontent.com/assets/7493331/6931003/64d5c8ea-d7bd-11e4-9c27-310f87814a42.JPG)

I entered the information as shown below ...  The actual weblink is www.yahoo.com and the content owner I entered was yahoo.com".

![addweblink2](https://cloud.githubusercontent.com/assets/7493331/6931005/66e204b4-d7bd-11e4-92f8-64877e1e0c7e.JPG)

Coming back to the Learning Materials page after clicking Done, it is obvious there is no mention of the actual URL www.yahoo.com.

![addweblink3](https://cloud.githubusercontent.com/assets/7493331/6931006/6899bed2-d7bd-11e4-8bec-f37cfbedf37c.JPG)

Now after clicking the :link:  Link to Yahoo link shown below, the following screen appears with nowhere to edit / view or otherwise reference the actual weblink entered previously "www.yahoo.com".  The same thing happens with Citations.  Adding / Modifying Learning Materials works fine with "files" but not "weblinks" or "citations".

![addweblink4](https://cloud.githubusercontent.com/assets/7493331/6931007/6a5a84d6-d7bd-11e4-868a-862db80b309c.JPG)

**Comment by saschaben** [comment]
Key here is that we are dealing with three different sets of metadata: our current display only represents that of  a digital document / asset.
For web link, please use https://www.dropbox.com/s/g56g81k214fkx6t/Learning-Materials-Details-Link.png?dl=0
For citation please use the same format, replacing "URL" label with "citation" label.
The interface must be smart enough to know what it is displaying.

**Comment by jrjohnson** [comment]
Closed in #550
