### ISSUE TITLE
Add Instructor Group Assignment Tool

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#4071]
We could clean up the Instructor Group area of Ilios at the same time as adding the ability to assign a whole bunch of Instructors into an Instructor Group. Unlike Learner Groups, we would not need to worry about sub-group assignments. This would happen at just one level.

This was a user-suggested enhancement. It may only be used at the beginning of the school term but would save a lot of time.

**Comment by saschaben** [comment]
let's review if we can make this conform more to the admin user search pattern.

**Comment by jrjohnson** [comment]
We're going to close as adding bulk instructors isn't going to be supported.
