### ISSUE TITLE
Courses and Sessions >> Status Menu should be Locked Down until Form Fully Loaded

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#408]
What was noticed was the following ...

* Fire up Courses and Sessions ...
* Select A Course (which has been published)
* Change its status from Published to Scheduled 
* Notice that the only Available Status to select is now UnPublish Course, which would take the Course back to Not Published and this is fine and dandy; but the option to Publish a Course should also be available.
* After tinkering with this (switching back and forth) for a few times it becomes obvious that the correct options are now available.  Maybe this drop-down menu should be locked until the form is fully loaded.

**Comment by saschaben** [comment]
improvements have obviated this issues
