### ISSUE TITLE
Session List Does Not Always Load up the Correct Learner Group Member Count if Same Group

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#4081]
![image](https://user-images.githubusercontent.com/7493331/46109892-c211c600-c196-11e8-9b07-260d9b457192.png)

There are 9 Learners in the group. It gets counted the first time but the count needs to be included for the other offerings as well.

https://curriculum.ucsf.edu/courses/1462

**Comment by saschaben** [comment]
Thats because the count is really "how many different groups are associated with this activity?" -- not "how many times is a group entity attached to an offering".

**Comment by dartajax** [comment]
![image](https://user-images.githubusercontent.com/7493331/46112141-5d5a6980-c19e-11e8-937e-d268e651b38e.png)

**Comment by dartajax** [comment]
It is better now. 

![image](https://user-images.githubusercontent.com/7493331/72942957-a2a69100-3d29-11ea-9ebc-b8959643b700.png)
