### ISSUE TITLE
Event Detail View LM's Need Better Formatting

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#4088]
Here is an event to review to see what I am on about ...

https://ilios-frontend.netlify.com/events/S0120180919O122016

I put the bright green highlighted rectangles in to show how the LM's and their attributes are grouped together.

![image](https://user-images.githubusercontent.com/7493331/46236233-a9d6ae00-c332-11e8-8f42-87c19f02ace4.png)

It is quite difficult to tell that the "Required pre-work ..." goes with upper LM and not the lower due to the way it is grouped. "Required pre-work ... " is an instructional note.

**Comment by dartajax** [comment]
Maybe we could shade stripe them or put a dashed line or other line of some sort to delineate the LM's better.

**Comment by dartajax** [comment]
And make the spacing (vertical) spacing better and more obvious what goes with what.

**Comment by jrjohnson** [comment]
Probably needs to be re-done if still an issue, in good shape now.
