### ISSUE TITLE
Page jumps around when toggling My Courses / All Courses

### ISSUE THREAD

**Issue by jenzweben** [ilios/frontend#413]
There is some lateral movement happening...I believe it's due to the appearance and disappearance of the scroll bar based on length of content in page

**Comment by jenzweben** [comment]
http://stackoverflow.com/questions/9201968/content-jumps-horizontally-whenever-browser-adds-a-scrollbar

**Comment by jenzweben** [comment]
https://css-tricks.com/eliminate-jumps-in-horizontal-centering-by-forcing-a-scroll-bar/

**Comment by jenzweben** [comment]
Assigning to JJ as I imagine he has an opinion about the best solution for this...

**Comment by saschaben** [comment]
yup:
`html {
 overflow-y: scroll; 
          }`

solves the problem
