### ISSUE TITLE
Session list action menu needs to have all the applicable actions

### ISSUE THREAD

**Issue by jenzweben** [ilios/frontend#414]
right now - edit is the only option

Complete list:
Edit Session
Delete Session
Publish Session
UnPublish Session
Mark as Scheduled

![screen shot 2015-04-02 at 4 01 48 pm](https://cloud.githubusercontent.com/assets/5023894/6975495/b96ad572-d951-11e4-849e-27eee3bd00a9.png)

**Comment by dartajax** [comment]
@saschaben is this one of those we can close since Publishing is done in the session detail area now?

**Comment by saschaben** [comment]
gonna leave this open as a potential enhancement.
