### ISSUE TITLE
Expand / Collapse Mechanism Changes 

### ISSUE THREAD

**Issue by jenzweben** [ilios/frontend#417]
Because it doesn't look like the page is expanding, Valentina was confused about the functionality.  If we display the close button only at the bottom or at least remove the bar (leaving only a tab that says "close")

![close-button](https://cloud.githubusercontent.com/assets/5023894/7010495/9d05413a-dc56-11e4-809a-4ae7f26280b4.png)

We also need to change the wording on the expand bar since it says "View All / Edit" please use "View Details"

**Comment by thecoolestguy** [comment]
Fixed with PR #438
