### ISSUE TITLE
Method Of Pagination or Longer Scroll Needed in Admin Console Student Assignment

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#4194]
![image](https://user-images.githubusercontent.com/7493331/49406262-ee534100-f709-11e8-8b3d-2f324f3c0f3b.png)

After clicking Manage with 95 students possibly needing assignment ...

![image](https://user-images.githubusercontent.com/7493331/49406326-2490c080-f70a-11e8-8f23-6fca5ba0fc34.png)

There is no way to do a "Show All" at the top and there is no way to navigate to the next page at the bottom of the screen.

**Comment by stopfstedt** [comment]
this is a bug. the list only contains the first 25 records.

fix: display all records.

let's deal with pagination as a separate, follow-up item.

**Comment by stopfstedt** [comment]
to reproduce: log in as a user with elevated privileges, then pick "Admin" from the main navigation. click the "Manage" button in the "Students Requiring Cohort Assignment" pane to get to that screen.
