### ISSUE TITLE
Update Cancel / Done Button Style 

### ISSUE THREAD

**Issue by jenzweben** [ilios/frontend#421]
See mock - style guide included

![new-save-cancel-buttons](https://cloud.githubusercontent.com/assets/5023894/7011500/80d7296c-dc5e-11e4-91fe-eb3d60b7bc23.png)

**Comment by thecoolestguy** [comment]
Is the text of the buttons in bold?  Kind of looks like it in the mock...

**Comment by saschaben** [comment]
@jenzweben should verify, but I'm pretty sure that's a yes.

**Comment by thecoolestguy** [comment]
It definitely looks better bolded... I've pushed it.  If it's wrong, I'll fix it.

**Comment by jenzweben** [comment]
good choice

**Comment by thecoolestguy** [comment]
http://i.imgur.com/LLIe7ep.jpg
