### ISSUE TITLE
Adding Student as Session Director to One Session Should Not Convert All MyCourses Links to Hyperlinks

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#4218]
Adding Student as Session Director to One Session Should Not Convert All MyCourses Links to Hyperlinks.

Here is a screen shot from a student who does not engage in any non-learner Ilios activities ... yet.

![image](https://user-images.githubusercontent.com/7493331/50123430-73b01880-0215-11e9-9928-d387d8ccc4b2.png)

After adding this student to Session as Administrator, the links in MyCourses all become enabled even though this student (and session administrator) was only added to be administrator of one session in one course. Now that student will be able to navigate (and not make changes) to Courses and Sessions. It is confusing but may actually be the correct behavior. It would seem better if the MyCourses page now had links directly to the location where this user has permission and would be editing. 

![image](https://user-images.githubusercontent.com/7493331/50123511-e5886200-0215-11e9-91ef-c93e6d96d498.png)

**Comment by stopfstedt** [comment]
per team conversation - this is correct behaviour.
