### ISSUE TITLE
After Adding Competency Domains for New School, Error Results on Save

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#4223]
![image](https://user-images.githubusercontent.com/7493331/50618909-a52e1280-0eaa-11e9-93ed-4a297ff4f7a4.png)

This is a new school - maybe permissions have not been set yet.

**Comment by stopfstedt** [comment]
was able to trigger this failure on a pre-existing school that had no competencies. although not consistently.

**Comment by dartajax** [comment]
I think this has been resolved - trying to reproduce right now.
