### ISSUE TITLE
Add Header to Session Detail Page - Offerings Section

### ISSUE THREAD

**Issue by jenzweben** [ilios/frontend#424]
Currently looks like this:

![screen shot 2015-04-06 at 1 30 43 pm](https://cloud.githubusercontent.com/assets/5023894/7011814/2ec745d2-dc61-11e4-8947-3261f15f4e6f.png)

Should look like this:

![screen shot 2015-04-06 at 1 28 50 pm](https://cloud.githubusercontent.com/assets/5023894/7011816/385e3ede-dc61-11e4-97df-d2994b4831b2.png)

**Comment by thecoolestguy** [comment]
Oh, I just realized this didn't include the header... I just put the toggle up there and got everything inline
