### ISSUE TITLE
Borders Missing

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#4242]
![image](https://user-images.githubusercontent.com/7493331/50937791-2563f300-142a-11e9-879e-7ba5eaf5844a.png)

**Comment by stopfstedt** [comment]
i'm only seeing this in chrome, and only at certain zoom sizes (90%, for example), but not a default/100% zoom.

firefox does not exhibit this problem.

**Comment by stopfstedt** [comment]
don't think there's anything that can be done on our end - browser bug.
