### ISSUE TITLE
Remove Code from Inside Inline Editing of Objectives

### ISSUE THREAD

**Issue by jenzweben** [ilios/frontend#426]
When I click to edit an objective, I see a bunch of code in there...

![screen shot 2015-04-06 at 1 52 51 pm](https://cloud.githubusercontent.com/assets/5023894/7012229/686129ae-dc64-11e4-8f3d-3a9cc19bf9f1.png)

**Comment by saschaben** [comment]
This is from the process of using cut and paste from MS word to enter objectives. stripping the garbage out is problematic. doable, but problematic. Moving forward, we need a simple inline editor which will allow for markup/markdown, and will provide a stripped text version of any cut&paste.

**Comment by jenzweben** [comment]
I think this could be a big deal if users typically cut & paste...I did a quick Google search and found this http://jsfiddle.net/erikwoods/Ee3yC/  Maybe it will help?

**Comment by jrjohnson** [comment]
Right now this box accepts HTML input so the code has to stay.  Its actually a *feature* - the user can specify HTML in their objective title.  In this case the use has pasted in crap code, but thats not something we can help with until skynet comes online.

I opened a new ticket to have a WYSIWYG editor on these elements: https://github.com/ilios/frontend/issues/458
