### ISSUE TITLE
Collapse course-level learning materials in the WaaG listings (or remove them entirely)

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#4281]
The significant number and repetition of LMs from the _course level_ is cluttering the "Week at a Glance" (WaaG) to the point of non-usability. since they are always represented in the event detail page anyway, let's pull them out of WaaG and display ONLY LMs directly associated with each session.

n.b. Requires completion of ilios/ilios#822

**Comment by stopfstedt** [comment]
@saschaben remove or dedupe? please advise, thanks.

**Comment by saschaben** [comment]
This appears to have been addressed. Please verify and close, or update as needed.
