### ISSUE TITLE
Admin Console Blows Up When Retrieving User Record in Linked ILM (Netlify)

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#4290]
Possibly this is related to the calendar display available in the Admin Console.

https://ilios-frontend.netlify.com/users/14859

![image](https://user-images.githubusercontent.com/7493331/52146337-4cbc7300-2618-11e9-8bb5-f05cd2e11acb.png)

**Comment by stopfstedt** [comment]
traced it down to https://github.com/ilios/common/blob/master/addon/components/ilios-calendar-pre-work-event.js#L11, will dig some more but that's where the failure originates from.
