### ISSUE TITLE
Display Changes Needed in Session List for ILM's Linked to Sessions

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#4298]
In the case below, two of the three ILM's are linked to upcoming sessions. Maybe something like this? ...

![image](https://user-images.githubusercontent.com/7493331/52309768-03d92700-2956-11e9-82d7-5451b9510e5f.png)

**Comment by jrjohnson** [comment]
Meeting notes. Replace Due prior to with an icon from https://fontawesome.com/icons?d=gallery&q=fork&s=solid and maybe truncate title or allow wrapping lets see it both ways.

**Comment by saschaben** [comment]
icon options:
my top vote goes to either https://fontawesome.com/icons/user-clock?style=solid
or https://fontawesome.com/icons/hand-point-right?style=solid
after that, runners up are https://fontawesome.com/icons/code-branch?style=solid
or https://fontawesome.com/icons/bacon?style=solid

**Comment by dartajax** [comment]
I like the right hand point for what it's worth.

**Comment by djvoa12** [comment]
1) Need to agree on an icon. [This](https://fontawesome.com/icons/user-clock?style=solid) looks fine to me.
2) De we want `ILM: [ICON] [Truncated Title]` or `ILM: [ICON] Due prior to: [Truncated Title]`? If seeing the entire title is not necessary, then truncating it would be ideal.

**Comment by dartajax** [comment]
Regarding your second question, we would like it to be ...

`ILM: [ICON] Due prior to: [Truncated Title]`

**Comment by jrjohnson** [comment]
We talked in Ilios team meeting this morning and `user-clock` and `ILM: [ICON] Due prior to: [Truncated Title]` are the way to go.

**Comment by djvoa12** [comment]
Okay. Things just got more complicated. Jon explained to me that ILM's dont' necessarily have a post-requisite and post-requisite aren't necessarily ILMs. That kinda destroys this design above. How should we proceed? We have three UI that needs showing: ILM note, first offering date/time, and post-requisite link. I need a logic control flow that decides which one gets shown based on certain conditions. Please advise.

@dartajax @saschaben

**Comment by djvoa12** [comment]
```
[ILM] [first offering date/time]
Due prior to: [post-requisite link]
```
Do we go with something like above? If ILM, then show [ILM]. Always show first offering date/time. If there is a post-requisite, show the second row.

**Comment by dartajax** [comment]
```1) ILM Due by: 4/4/2019 (Traditional ILM with Due Date - will still exist)
2) ILM Due Prior to: ABC Exam (New style ILM linked to Session)
3) 4/4/2019 12:10 PM (Traditional Offering with First Offering Displayed - no post requisite)
4) Due Prior to: ABC Exam (Non-ILM Session with post requisite)```

**Comment by dartajax** [comment]
```
1) ILM Due by: 4/4/2019 (Traditional ILM with Due Date - will still exist)
2) ILM Due Prior to: ABC Exam (New style ILM linked to Session)
3) 4/4/2019 12:10 PM (Traditional Offering with First Offering Displayed - no post requisite)
4) Due Prior to: ABC Exam (Non-ILM Session with post requisite)
```

**Comment by djvoa12** [comment]
I just had an extensive discussion with Dave. We are going with this logic flow:
```
Logic Control Flow:

Is it ILM?
  Does it have a post-requisite?
    ILM Due prior to: ABC Exam
  Does it not have a post-requisite?
    ILM Due by: 4/4/2019 12:10 PM
Is it not ILM?
  Does it have a post-requisite?
    Due Prior to: ABC Exam
  Does it not have a post-requisite?
     4/4/2019 12:10 PM
```

**Comment by dartajax** [comment]
```
Logic Control Flow:

Is it ILM?
  Does it have a post-requisite?
    ILM Due Prior to: ABC Exam
  Does it not have a post-requisite?
    ILM Due by: 4/4/2019 12:10 PM
Is it not ILM?
  Does it have a post-requisite?
    Due Prior to: ABC Exam
  Does it not have a post-requisite?
     4/4/2019 12:10 PM```
