### ISSUE TITLE
Need Add File Dialog Box for Add Learning Materials Form

### ISSUE THREAD

**Issue by jenzweben** [ilios/frontend#431]
We need a way for user to select a file from their computer when they have selected to Add Learning Materials - File

**Comment by jrjohnson** [comment]
@ebryn - please work with @thecoolestguy on the needed modifications to our API and how we will handle saving a file that has a relationship to an ember-data model.

**Comment by ebryn** [comment]
The file uploading over AJAX primitive is FormData: https://developer.mozilla.org/en-US/docs/Web/API/FormData

Some Ember libs that wrap it:
https://github.com/benefitcloud/ember-uploader
https://github.com/abuiles/ember-attachable

**Comment by thecoolestguy** [comment]
I've added the ember-cli-uploader (https://github.com/benefitcloud/ember-cli-uploader) and created the component for it, and added the upload field/button to the new LM form, but I'm still looking into what's necessary on the PHP backend (http://symfony.com/doc/current/cookbook/doctrine/file_uploads.html, I'm guessing) and how to handle the responses after upload (https://github.com/benefitcloud/ember-uploader#finished-uploading).

**Comment by jrjohnson** [comment]
Let's split this up for now and just be sure you have the ember part working. Then create a new ticket kn ilios/ilios with a sample payload and we can figure out how to work the API.
