### ISSUE TITLE
Add Search Box to ILM "due prior to" Drop Down Selector

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#4319]
This is loosely related to #4318 in the sense that it deals with the "due prior to" Drop Down Selector. It would be helpful to add the functionality to be able to search for and find the correct session to link to an ILM. This is because Courses often have one or two hundred sessions and it would be helpful to narrow this down using a search like on Courses and Sessions where one would search for a session.

**Comment by dartajax** [comment]
steps ...

* log in as Admin user with full permissions
* Pull up a course (Renal ...)
* Select an Independent Learning Module (ILM)
* click to review / modify session details

![image](https://user-images.githubusercontent.com/7493331/54841947-cfaf9080-4c8d-11e9-9173-016e08cf9492.png)

![image](https://user-images.githubusercontent.com/7493331/54842207-9166a100-4c8e-11e9-8469-48a023722f55.png)

![image](https://user-images.githubusercontent.com/7493331/54842239-a6433480-4c8e-11e9-851f-b9c6c5a0f8ba.png)

* Review contents of the drop-down - many sessions - we would like a way to search to find the correct session to link to

* This could be similar to the search in Courses and Sessions where we searched for "Renal". I am not sure how that works with a drop-down though. Does it? Could it?

**Comment by stopfstedt** [comment]
searching within a dropdown is doable with native `<select>`, as @djvoa12 points out we'd have to use something like https://github.com/cibernox/ember-power-select.

worth it?
would sorting/grouping options in the dropdown differently be a viable alternative? @dartajax  thoughts?

**Comment by jrjohnson** [comment]
I think more than a searchable select is needed here. Instead I'd go for a filterable table containing the session name as well as some additional attributes (first offering, type).
