### ISSUE TITLE
Handle prework display dupes for admin and director views

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#4328]
when prework targets a small group activity, and admin or director role will see all potential values for that item. this creates a ton of visual cruft and duplication in WaaG and Calendar.

So, like we aggregate our "multiple" offerings in the calendar grid, we should do the same for  prework listings in WaaG and the ILM box.

![Ilios Dashboard 2019-02-13 15-50-54.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5551233e5601aa8f0097f50b/125516c66e82c728ace21e0d46c198932c91c38d8efab741ab5ce290691477227049f3793dd4b068ee1736545f424ba853444d04bea6d37ef5f22e7a98590ee9d86f0920c43e17aceb811cbe52ba20831e80e7ef8b5edcfa7f74b9dfd0126754505a9bf54f34a9934acd5df64ae14f54ad13306be1647b.png)

**Comment by stopfstedt** [comment]
@saschaben in terms of data attributes - what are the criteria that define a duplicate here?
i assume same session and same start/end-time are qualifying factors, but what else? should same event title be considered as well?
please advise, thanks!

**Comment by jrjohnson** [comment]
I'm not sure start/end will work because these are probably dupes due to the small groups.  in `thing1 due before thing2` I think we can dedupe on `thing1` session (which is the id).

**Comment by stopfstedt** [comment]
i let this percolate a little. my current thought on this is that we should group _"like"_ pre-requisites and only show the first one by default. with the rest of them hidden behind some sort of collapse/expand toggle (thinking a button with ellipsis in it). dropping "duplicate" pre-reqs altogether seems sub-optimal to me, since we cannot guarantee that they are in fact _the same_.

will crank out something tomorrow and share screenshots here for further discussion.

**Comment by stopfstedt** [comment]
current state of affairs:

![selection_308](https://user-images.githubusercontent.com/1410427/53130517-5baf8a80-351f-11e9-9963-fe9fc3391f9a.png)

sorted:

![selection_309](https://user-images.githubusercontent.com/1410427/53130510-57836d00-351f-11e9-8edc-2b54f5c929db.png)


"duplicates" tucked away behind button:

![selection_310](https://user-images.githubusercontent.com/1410427/53130503-53574f80-351f-11e9-9d68-3e455b6637f4.png)

other thoughts on the button would be to label it "expand" and "collapse". 

@saschaben  thoughts?

**Comment by stopfstedt** [comment]
closed via ilios/common#528
