### ISSUE TITLE
When External / Course ID is left Blank, the Label Comes Down on the Screen

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#435]
see screen shot below ...

![noidforthisone](https://cloud.githubusercontent.com/assets/7493331/7034825/1978fd24-dd38-11e4-9e88-006f639302a8.JPG)

External ID (or Course ID) should be up at the same level as Start and Level when there has not been an External (Course) ID entered.

**Comment by saschaben** [comment]
needs a default "click here to edit" placeholder.
