### ISSUE TITLE
Back Button Doesn't work when returning to course list

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#44]
Reproduce:
Got to /courses 
Pick a course
Click the back button

Symptom: List does not load.

@saschaben: Can you check this again and see if this is a real bug or just a problem we had this morning?

**Comment by saschaben** [comment]
this issue affects all page to page navigation in re the course list: we have discussed the back button, but I'm noticing that navigation back and forth via the menu also is not firing off correctly. fer instance, got to dashboard, then to course list, then to a course, then menu link back to course list, and....while the correct target shows up in the bottom of the browser marquee style, the address bar doesn't change. click the nav again, and it changes, but doesn't get the query string appended.
