### ISSUE TITLE
Competencies Box Displays When No Competencies Have Been Entered

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#441]
This occurs upon adding a New Course before a Cohort has been selected.  Under Competencies, there is a shell of a box which would contain the Competencies from that Program Year that have been associated with Course Objectives.  No data = visibility not true.

**Comment by jenzweben** [comment]
Duplicate of #393

**Comment by dartajax** [comment]
Darn it.  I did a search before entering.  Sorry.
