### ISSUE TITLE
Row Level Save Button

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#443]
I thought it might useful if one were to be modifying a bunch of course attributes at once (header level stuff) to have a row-level save button (green check box / cancel combo).

This would happen if a user were to change the start date and the end date and the level of a course.  The user would only have to confirm once rather than three inline edit save confirmations.  I wanted to throw this out there.

**Comment by dartajax** [comment]
It would avoid a situation like this ....

![courserowlevel](https://cloud.githubusercontent.com/assets/7493331/7078719/a4cdb93e-ded0-11e4-9ae3-d5a58db95fad.JPG)

**Comment by dartajax** [comment]
Another option to this would be to require that the user save or cancel one inline editing field before moving on the next -- sort of like a modal form in some ways ... but not.

**Comment by dartajax** [comment]
The same is true of Session as shown below ...

![sessionrowlevel](https://cloud.githubusercontent.com/assets/7493331/7079055/8bd40858-ded4-11e4-9b5c-05f17be31666.JPG)

**Comment by saschaben** [comment]
Since form fields now allow save with a"Enter" keystroke, this is essentially mooted.
