### ISSUE TITLE
UPDATED: ILM = ON should hide "Associated Groups" label and data in session.

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#445]
I noticed that attaching groups to ILM Sessions directly works really nicely; however it would be better if the Associated Groups could be attached at the header level for ILM's.

The "Learner Groups" section with the "Manage Learner Groups" button may not be necessary if we move the "Manage Learner Groups" button up to the higher level (the same level as "Associated Groups").  This button would only be available for ILM's.

**Comment by saschaben** [comment]
@jenzweben can you render a mock showing this modification so we can review. thanks!

**Comment by dartajax** [comment]
Ilios 2.4.x 

>> Courses and Sessions >> Pull up a course
>> Scroll to the bottom of existing Sessions and click "Add Session"
>> Select Independent Learning check box (see screen shot)

![kryptonics](https://cloud.githubusercontent.com/assets/7493331/7419218/92eba4d4-ef28-11e4-9c73-5c3c76712e50.JPG)

**Comment by jenzweben** [comment]
I found a bug related to this...when you add a new session, and select "Independent Learning" then submit, you then have to check the ILM box and this should be pre-selected...I will create a ticket and also create a mock to address Dave's request.

**Comment by dartajax** [comment]
Ilios 3.x

We have the functionality in 3.0 as shown below however I believe we were discussing removing Associated Groups if Independent Learning is selected and showing Associated Groups if Independent Learning is not selected - maybe no new mock necessary?

![krypto3](https://cloud.githubusercontent.com/assets/7493331/7419487/32f93422-ef2a-11e4-8fc2-020b76693090.JPG)


![krypto3_2](https://cloud.githubusercontent.com/assets/7493331/7419479/29141aee-ef2a-11e4-94fa-839819e2bdb4.JPG)

**Comment by saschaben** [comment]
![ilm](https://cloud.githubusercontent.com/assets/1753431/7419933/43d46980-ef2d-11e4-91bb-a8da962c3319.png)

**Comment by dartajax** [comment]
Well here's my handiwork (day late dollar short)
![monopoly2](https://cloud.githubusercontent.com/assets/7493331/7420056/32610176-ef2e-11e4-9de0-aca0aa3146e7.JPG)

**Comment by dartajax** [comment]
Oops.  I will close this since it was a mock up request that is not necessary.

**Comment by saschaben** [comment]
Changing title to actually describe the existing issue. Screenshots attached above should be fully explanatory.
