### ISSUE TITLE
Sort object keys and enforce with linting

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#4487]
For consistency we can sort object keys alphabetically, but we should enforce this with the linting rule https://eslint.org/docs/rules/sort-keys

Going to assign this to @djvoa12 since he's on a tear re-sorting objects anyway.  This way they're all done in one set and consistent.

It looks like there isn't an auto fix option for this officially due to worries about changing some runtime behavior. I think our tests are fairly good though and maybe we can try out https://www.npmjs.com/package/eslint-plugin-sort-keys-fix as a quick install, run, fix option.

I think my preferred rule definition would be 

`"sort-keys": ["error", "asc", {"natural": true}],`

Another option would be to add this as a default and then add ignore's to all existing files.

**Comment by djvoa12** [comment]
I have been messing with this for few hours on common repo. I finally figured out how to run the command line to auto-fix as much as possible (only fixed like 60-70%. Honestly, I think we should either scratch this idea or apply this rule to specific areas/files. It would auto-sort anything in an object.

We definitely don't want the below for components. Again, I feel like we should punt on this one.
```
// .../components/detail-cohorts.js

export default Component.extend({
  actions: {
    manage(){
      this.get('course.cohorts').then(cohorts => {
        this.set('bufferedCohorts', cohorts.toArray());
        this.set('isManaging', true);
      });
    },
    save(){
      this.set('isSaving', true);
      const course = this.get('course');
      course.get('cohorts').then(cohortList => {
        let bufferedCohorts = this.get('bufferedCohorts');
        let removedCohorts = cohortList.filter(cohort => {
          return !bufferedCohorts.includes(cohort);
        });
        cohortList.clear();
        bufferedCohorts.forEach(cohort=>{
          cohortList.pushObject(cohort);
        });
        RSVP.all(removedCohorts.mapBy('programYear')).then(programYearsToRemove => {
          course.get('objectives').then(objectives => {
            RSVP.all(objectives.invoke('removeParentWithProgramYears', programYearsToRemove)).then(()=> {
              course.save().then(()=>{
                this.set('isManaging', false);
                this.set('bufferedCohorts', []);
                this.set('isSaving', false);
              });
            });
          });


        });

      });

    },
    cancel(){
      this.set('bufferedCohorts', []);
      this.set('isManaging', false);
    },
    addCohortToBuffer(cohort){
      this.get('bufferedCohorts').pushObject(cohort);
    },
    removeCohortFromBuffer(cohort){
      this.get('bufferedCohorts').removeObject(cohort);
    },
  },
  bufferedCohorts: null,
  classNames: ['detail-cohorts'],
  'data-test-detail-cohorts': true,
  editable: true,
  init() {
    this._super(...arguments);
    this.set('bufferedCohorts', []);
  },
  isManaging: false,
  isSaving: false,
  layout,
  subject: null,
  tagName: 'section'
});
```

**Comment by jrjohnson** [comment]
Ok. Let's skip.
