### ISSUE TITLE
Provide delete action for all course/session entities

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#450]
please make sure that action control includes (or form panel includes) option to delete. This is for ALL entities in course:

- [x] Course Objective
- [x] Parent Objective
- [x] cohorts
- [x] Mesh - all levels
- [ ] Learning material - all levels
- [x] Course Director
- [x] Session
- [x] session objective
- [x] session offering
- [x] Session description
- [x] All offering details (Learners, Instructors, Location)

**Comment by jrjohnson** [comment]
@saschaben since deleting a learning material is non-permanent (as in it can be re-added with a simple search) do we still need a confirmation message?  Or can clicking the trash can be enough?  I guess accidental clicks might be an issue, thoughts?

**Comment by saschaben** [comment]
Yeah. in order to avoid accidental removals, we need a message. Best would be "You are about to remove [learning material title] from this [session/course]. Do you want to continue?"

**Comment by jrjohnson** [comment]
@saschaben Should deleting a session description be something to click, or just if you empty out the field it should save as empty?

**Comment by saschaben** [comment]
@jrjohnson ideally, session description would have a "clear description" type of clickable, to delete it -- and if you were to just go in and delete everything, it would have the same effect. A zero-length string for description (or a string with some length but no valid chars) should never be something we save as a value.

**Comment by jrjohnson** [comment]
Ok - can we do a delete everything in the box for this pass, and then go back and add a clear button if we have time?

**Comment by saschaben** [comment]
Yes
