### ISSUE TITLE
Linked ILM's Not Showing Up Correctly for Non-Student Learners

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#4501]
This was noticed by Admin users and verified by me. What happened was Admin users ended up putting themselves into a Cohort (School of Medicine Bridges 2022) and then into a Learner Group for a specific course occurring right now.

https://ilios3-demo.ucsf.edu/courses/1505

The above course is the course to review - all of the ILM's (except for one) have been linked to sessions.

For a student, it correctly looks like ...

`All Weeks Student` - similar to Week at a Glance but nothing is happening this week so there is nothing to display right now. 

![image](https://user-images.githubusercontent.com/7493331/56383258-4c228a00-61ce-11e9-8f17-bdc82442149e.png)

`Calendar Student` - scrolled forward a week to get the same data as shown above.

![image](https://user-images.githubusercontent.com/7493331/56383382-868c2700-61ce-11e9-8667-e7da381c5b50.png)

For a non-student Admin user who has been added to the cohort and learner group (IDS 121D), it incorrectly looks like ...

`Calendar`
![image](https://user-images.githubusercontent.com/7493331/56383735-71fc5e80-61cf-11e9-83ac-f40193e786b4.png)

The 4 ILM's appearing at 5pm on Sunday should NOT be on the calendar. They should be in area below (like what the student saw above in `Calendar Student` or `All Weeks Student`).

`All Weeks` 
![image](https://user-images.githubusercontent.com/7493331/56383871-c6074300-61cf-11e9-874c-afc71c827234.png)

More info coming later ...

**Comment by dartajax** [comment]
One aspect of this bug is ...

<RESEARCH TIP>
In the screen shot above labeled `All Weeks`, when the Admin (non-student Learner) was logged in, the ILM's that do not display correctly and still retain the `Due By Sunday 5:00PM` value instead of the linkage to the session all have more than one offering. The one that showed up correct only had one offering.
</RESEARCH TIP>

**Comment by jrjohnson** [comment]
@dartajax please verify that this is still an issue.

**Comment by jrjohnson** [comment]
Mooted by new prework.
