### ISSUE TITLE
Bulk Session Objective Upload Functionality Requested

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#4546]
It has been brought up to me that it would be helpful if there were a way to upload a bunch of session objectives at the same time.

Below is an example of what the .csv might look like. Those are seven objectives in a session. Basically, the issue is that when a course is rolled over, some of the objectives need to be changed or replaced. It might be easier if Course Coordinators and planners kept updated spreadsheets or .csv files to upload when the new year rolls around ... in one power move.

![image](https://user-images.githubusercontent.com/7493331/57653773-81c95180-7587-11e9-89f9-789ed5e8db9d.png)

**Comment by saschaben** [comment]
objective data is too multidimensional to be easily managed as an upload in bulk. Unfortunately we won't be able to move on this.
