### ISSUE TITLE
Trash can is active, but unable to delete course.

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#4556]
On an unpublished course with all session unpublished, where all learner group associations have been removed, and the trash can is active on the course list, the course fails to delete. cannot replicate yet, but perhaps related to https://github.com/ilios/frontend/issues/988

or perhaps networking issue? However no offline banner was displayed...

After removal of sessions, course deletion worked. but again, unable to reproduce, and uncertain if a session fail/network issue or a bug in the deletion code.

**Comment by dartajax** [comment]
This is still an issue.

**Comment by dartajax** [comment]
![image](https://user-images.githubusercontent.com/7493331/58196684-b7ed8c00-7c7f-11e9-8997-4dfba538f8dd.png)
