### ISSUE TITLE
Add WYSIWYG editor option to inplace-textarea / big-text components

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#458]
Currently used for editing objectives we need to be able to enable a nice text editor in these fields.

**Comment by saschaben** [comment]
perhaps something like https://www.npmjs.com/package/ember-cli-medium-editor (which includes a "pasteAsPlainText" config value...)?

**Comment by jrjohnson** [comment]
This isn't the best addon, also the medium editor doesn't support lists, which I think is our number 1 use case for not going with plain text.

@saschaben - what functionality do we actually need in objective titles?

**Comment by saschaben** [comment]
We need to provide at the very least: font styling (bold/ital/underline/etc); ordered/unordered lists; font sizing; The minimum functional requirements for format can be determined by looking at the existing 2.4.X editor toolbar -- and then adding the ability to directly import externally sourced/formatted cut&paste text in a clean format. please keep in mind that users are NOT going to learn markdown, any more than they know HTML. Controls must be WYSIWYG, and providing toolbar control over formatting is the most commonly understood way for them to interact with text. The markdown route makes good sense, but we still need to remember that our audience is really not sophisticated about this stuff.

I think we can approach the toolbar functions in phases --- we won't get too much grumbling if we can provide text styling (bold/ital/underscore) text sizing and lists to start, and then iterate over the other features. "Clean" cut&paste import is non-negotiable.

**Comment by jrjohnson** [comment]
Ok - if we can drop support for lists then we will be in better shape.  Cut and paste is workable in that extraneous junk will get stripped out.  However we won't always correctly interpret what the user has entered.  So they will loose styling for size of characters, but may keep bold.  I'm not finding any editor that can do better than that.

**Comment by saschaben** [comment]
we can't drop support for lists.

**Comment by jrjohnson** [comment]
Ok - doesn't matter.  It runs out the medium editor can be modified to allow ordered and unordered lists.  So I think this is the right path for us.  I will put something together so we can demo it.

**Comment by jrjohnson** [comment]
Notes from #619 
**UPDATE 5/26:**
good to go with medium editor. Issues to address are:
1. when you click to manage it needs to open the editor immediately, rather than requiring two clicks to open the editor.
2. we need to provide a plain text editor option along with WYSIWYG
3. Objective display needs to show styling
4. we need to find an appropriate means of scrubbing existing extraneous code tags from the objective data, along with our cut&paste solution to scrubbing new input data.

**Solutions**
- determine a tag whitelist for accepted markup
- find a means of both scrubbing and validating the scrub

QUESTIONS:
can we do this without users having to look and approve?
can we add a column to track cleansing of data?


*Try out the medium editor when changing objective titles.*

*Thoughts?*

**Comment by jrjohnson** [comment]
We will use the ember-ckeditor addon.  Currently waiting on an option to pass configuration in.  Our configuration would look like:
```javascript
CKEDITOR.editorConfig = function( config ) {
	config.toolbarGroups = [
		{ name: 'clipboard', groups: [ 'clipboard', 'undo' ] },
		{ name: 'editing', groups: [ 'find', 'selection', 'spellchecker', 'editing' ] },
		{ name: 'links', groups: [ 'links' ] },
		{ name: 'forms', groups: [ 'forms' ] },
		{ name: 'tools', groups: [ 'tools' ] },
		{ name: 'document', groups: [ 'mode', 'document', 'doctools' ] },
		'/',
		{ name: 'others', groups: [ 'others' ] },
		{ name: 'basicstyles', groups: [ 'basicstyles', 'cleanup' ] },
		{ name: 'insert', groups: [ 'insert' ] },
		{ name: 'paragraph', groups: [ 'list', 'indent', 'blocks', 'align', 'bidi', 'paragraph' ] },
		{ name: 'styles', groups: [ 'styles' ] },
		{ name: 'colors', groups: [ 'colors' ] },
		{ name: 'about', groups: [ 'about' ] }
	];

	config.removeButtons = 'Subscript,Table,Image,HorizontalRule,Strike,RemoveFormat,Superscript,Outdent,Indent,Blockquote,Styles,Format,About,Cut,Copy,Paste,Redo,Undo,Anchor,Unlink,Link';
};
```

**Comment by jrjohnson** [comment]
Maybe try tinymce? https://gist.github.com/koriroys/dc53d8d7034512a995bc/6f254b373bd88c675cf07abaca9f4dd483e6fca5
