### ISSUE TITLE
New action dropdown

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#46]
@jenzweben can you take a look at these two options and let me know which you woudl prefer:
1. http://rsschermer.github.io/ember-rl-dropdown/
2. http://dropkickjs.com/

Number is slightly easier to implement, so unless you want the search and group functionality in the dropkick one lets go with that.

**Comment by jenzweben** [comment]
Definitely #1

**Comment by jrjohnson** [comment]
@jenzweben please take a look at improving style on the new dropdown action menu.  I think we can use the same basic structure for other drop down things like the publish button.  There is for sure a z-index issue when the menu is at the bottom of a list.
.
