### ISSUE TITLE
Create Learner Groups Detail Page

### ISSUE THREAD

**Issue by jenzweben** [ilios/frontend#460]
![learner-groups-edit-v9](https://cloud.githubusercontent.com/assets/5023894/7280312/98055bca-e8d6-11e4-9da3-848cc67d86f5.png)

**Comment by jenzweben** [comment]
Collapsed View
![learner-groups-edit-v8 collapsed](https://cloud.githubusercontent.com/assets/5023894/7238358/9474e5ec-e756-11e4-8979-7a7bf5005df5.png)

**Comment by jrjohnson** [comment]
There is a lot of link blue in the header and overview area that I'm not sure about.  Are those clickable?  Can you annotate to indicate what clicking each one does?

**Comment by saschaben** [comment]
@jenzweben can comment further, but AFAIK all blue is  clickable EXCEPT the total group membership in blue in the header. That will need modification to a label.

**Comment by jenzweben** [comment]
I will update the mock - I think I was exploring the ability to click on the total to add more members but that might have been a left-over from a previous iteration.

**Comment by jenzweben** [comment]
OK I updated the mocks & replaced them above to avoid confusion

**Comment by saschaben** [comment]
@jenzweben the new mocks aren't displaying for me, can you reconfirm the uploads?

**Comment by jrjohnson** [comment]
@jenzweben / @saschaben - the select list for changing the group membership of a learner - is that supposed to be an edit in place element (with the checkbox and the x / cancel button)?  That seems like it would make the most sense.  It can also change as soon as someone changes the selected value, but mistakes will cause the user to disappear from the view and be hard to track down and fix.

**Comment by saschaben** [comment]
@jrjohnson to keep things from getting out of hand I think this will need to be an edit in place element.

**Comment by saschaben** [comment]
@jenzweben @jrjohnson @thecoolestguy I'm also wondering if the default text for the group members really needs to re-identify the group -- this seems redundant. Shouldn't it mo' better be along the lines of "click to change group affiliation" or somesuch?

**Comment by jenzweben** [comment]
@saschaben do you mean the header text?

**Comment by saschaben** [comment]
no, I mean this text:

![create learner groups detail page issue 460 ilios frontend 2015-05-06 11-23-41](https://cloud.githubusercontent.com/assets/1753431/7500426/7478c04a-f3e2-11e4-85ca-c6f2ead52e27.png)

**Comment by jenzweben** [comment]
Gotcha - or maybe an edit icon? I will mock something up
