### ISSUE TITLE
Require Unique Learner Group Names

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#4601]
See screen shot ...

![image](https://user-images.githubusercontent.com/7493331/58994515-9d4e0380-87a5-11e9-9fb3-050d9a63305b.png)

All I had to do to get this was ....

1. Create an empty copy of a Learner Group and get rid of the word "(Copy)" from the title.
2. Change the name of a Learner Group to be exactly the same as another sub group.

**Comment by dartajax** [comment]
Either route 1 or 2 can be followed.

**Comment by jrjohnson** [comment]
Other than being confusing what's the downside to this? If a programs wants to do something weird and confusing should we stop them?

**Comment by dartajax** [comment]
The downside to this is if Learner Groups are accidentally created with the exact same name, it may be hard to track down which one is attached to offerings. It seems from a "DartAjaxy Business Rule Like" thing to offend my senses.

**Comment by dartajax** [comment]
If @saschaben says it's hogwash, we can close it.

**Comment by dartajax** [comment]
It may not be necessary but since my validation sensors went off, I put in the ticket.

**Comment by dartajax** [comment]
Gonna close this one under the Spiderman principle - with great power ...
