### ISSUE TITLE
global search: display matching attributes

### ISSUE THREAD

**Issue by stopfstedt** [ilios/frontend#4608]
each item (courses as well sessions) in the global search payload contains a `matchedIn` property which is a list of attributes-names that matched the given search term.

display this information as part of the search results list interface.

**Comment by djvoa12** [comment]
@stopfstedt there's an inconsistency for the `matchIn` values.

It comes in as an array of strings.
```
"matchedIn": ["description", "title", "learningmaterials"]
```
It also comes in as an array of objects as well.
```
				"matchedIn": {
					"0": "description",
					"2": "objectives",
					"3": "title",
					"4": "learningmaterials"
				}
```
Should we pick one?

**Comment by jrjohnson** [comment]
Whoops. Can you file this as an issue in ilios/ilios and assign it to me?  Should be strings.

**Comment by djvoa12** [comment]
https://github.com/ilios/ilios/issues/2529
