### ISSUE TITLE
Create Instructor Groups Landing Page

### ISSUE THREAD

**Issue by jenzweben** [ilios/frontend#461]
![instructor-groups-landing-v3](https://cloud.githubusercontent.com/assets/5023894/7238578/2835270a-e758-11e4-9ee8-4aaea35db613.png)

**Comment by saschaben** [comment]
OK good to go.

**Comment by jrjohnson** [comment]
This mock is a little bit out of date - the actual implementation should place the 'Add New' button into the results list header as it is on the courses list.

**Comment by saschaben** [comment]
Do we need a new mock, or can we go forward with this one and apply the updated formatting to button placement and header labeling? If new is needed, please request from @jenzweben.

**Comment by jrjohnson** [comment]
I don't think a new mock is necessary - just wanted to put a note in there about the difference.
