### ISSUE TITLE
Create Program Detail Page

### ISSUE THREAD

**Issue by jenzweben** [ilios/frontend#463]
![programs-detail](https://cloud.githubusercontent.com/assets/5023894/7238632/9b887306-e758-11e4-895f-736926cc0db5.png)

**Comment by saschaben** [comment]
Good to go. Two FYIs:
* Publish buttons and badges should match current controls in course and session;
* action button list should include Edit | Archive | Delete (@jrjohnson do we also want publish controls here? Hmm.)

**Comment by jrjohnson** [comment]
@saschaben - I don't think we should put published controls in the table rows.  That's too much power to give with just the summary information.  You should have to open them to click them.

@jenzweben - Lots of blue in the table of program years, I think they should probably just be black text except for matriculation year which should have a square away icon and link to the program year detail page.  Is that correct?

**Comment by saschaben** [comment]
@jrjohnson so re the program year links....wasn't the idea click anything in the row to open the edit detail? If we go with square away and black, would that no longer be the case?

**Comment by jrjohnson** [comment]
Oh ok - the click anywhere pattern isn't something we have other places, but I can make that work if thats what we want.  I don't have a preference - just need to know what the right path is.

**Comment by saschaben** [comment]
NP. Go with black nonlink and square icon. Follow course list format.
