### ISSUE TITLE
Create Program Year Detail Page

### ISSUE THREAD

**Issue by jenzweben** [ilios/frontend#464]
![programyear-detail-2](https://cloud.githubusercontent.com/assets/5023894/7239754/47c06aa4-e761-11e4-9a8b-c953de11b8a7.png)

**Comment by saschaben** [comment]
@jenzweben the mock is missing an "add directors" form field. Assuming we will follow the format of course overview on this...

**Comment by jenzweben** [comment]
got it - I will update the mock

**Comment by jenzweben** [comment]
Updated mock and replaced original

**Comment by saschaben** [comment]
looks good.

**Comment by jrjohnson** [comment]
@jenzweben @saschaben
1. For consistency can we use the same slide in / out for program years that we do for sessions in a course?  So the program overview is always visible? cc  
2. I'm going to use the manager pattern from the course details page for competencies, objectives, topics, and stewarding schools - any objections?
3. The left right pattern here for competencies is really interesting and maybe should be the default for this type in the future, for now can I use the same pattern as topics?

**Comment by saschaben** [comment]
@jrjohnson I'll let @jenzweben chime in too, but: excepting competencies, I'm fine with all this, at least for an out the gate release. For competencies though, keep in mind that we have competency domains as categories subdividing the nested competency subdomains; this means that the topics pattern -- which is flat -- is inadequate to represent the nesting without some hackery.

Let's go ahead with all the options above (unless @jenzweben sees issues) excepting competency management, which we should discuss tomorrow as to tree / nesting / other options for display.
