### ISSUE TITLE
New Offering Auto Scroll Needed

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#4647]
To reproduce ...

* Go to Courses and Sessions 
* Select or create a Course 
* Select or create a Session 
* Click the (+) button as shown below to add an Offering ....

![image](https://user-images.githubusercontent.com/7493331/60040524-0f5f8d00-966e-11e9-996b-965220606064.png)

After clicking, 

![image](https://user-images.githubusercontent.com/7493331/60040885-d542bb00-966e-11e9-874a-33089454b00d.png)

It would be better to present the user with this ...

![image](https://user-images.githubusercontent.com/7493331/60040944-f60b1080-966e-11e9-970f-a083a7b5d4bd.png)

**Comment by dartajax** [comment]
Still exists. `low hanging fruit gets the bees`

**Comment by stopfstedt** [comment]
@dartajax a while back, we changed this to auto-scoll to the bottom of the offering form. sounds like this is what you had in mind  here. can you confirm? if so, then pls close this ticket, otherwise let me know what (still) needs to be done here. thanks!

**Comment by dartajax** [comment]
@stopfstedt - it does now auto-scroll to the bottom of the offering form - I wanted it to not scroll to the bottom necessarily but rather like this ... 

![image](https://user-images.githubusercontent.com/7493331/95141451-15c02e00-0726-11eb-9c7e-ca40fe7e828c.png)

rather than ...

![image](https://user-images.githubusercontent.com/7493331/95141481-2b355800-0726-11eb-9984-f462b06d0a11.png)

... which is how it currently is. I can probably close this since it is in better shape than it was.

**Comment by stopfstedt** [comment]
@dartajax thanks for the feedback. i found the other scroll-related issue, where scroll to bottom was explicitly stated as the desired behaviour. https://github.com/ilios/common/issues/899
