### ISSUE TITLE
Search Removes Commas & Dashes From Initial Results

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#4648]
In the new global search, when a user picks the results and the results contain commas and / or dashes, these are stripped out initially.

To reproduce, ...

* Search for and select as shown below - `Brain, Mind, and Behavior 2015-16`

![image](https://user-images.githubusercontent.com/7493331/60052133-61fa7280-9689-11e9-8722-bb0987b9cddf.png)

* Notice in the screen shot below that the commas and the dash have been removed. It also appears that the space occupied by the commas & dash is now occupied by blank space. As in `Brain  Mind  and Behavior 2015 16`

![image](https://user-images.githubusercontent.com/7493331/60052272-a980fe80-9689-11e9-9e6d-c22956f5fd2c.png)

**Comment by saschaben** [comment]
fixed
