### ISSUE TITLE
Provide Better Padding For My Courses

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#4657]
Make My Courses have the same formatting as My Reports - in this case, they are both set to "none". The same formatting issue is present when they have contents as well.

![image](https://user-images.githubusercontent.com/7493331/60138693-25e61100-9760-11e9-8850-714d80351448.png)

**Comment by dartajax** [comment]
`low hanging fruit gets the bees`

**Comment by m11dedhia** [comment]
Hello @dartajax sir,
I am willing to work on this issue, could you please provide further details on it?
Thank you

**Comment by dartajax** [comment]
Hi @m11dedhia, I think the "More Padding in All Weeks Issue" has been resolved so we may end up closing that one. This one may be good for you though.

Basically we would like this ...

![image](https://user-images.githubusercontent.com/7493331/95769368-9faf5000-0c6c-11eb-848c-b67d7685b2c7.png)

rather than this ...

![image](https://user-images.githubusercontent.com/7493331/95769408-af2e9900-0c6c-11eb-835e-6c469cb2277d.png)

The "None" label underneath the larger "My Courses" label needs to line up better with the "My Courses" label. Both labels "None" underneath "My Reports" and "None" underneath "My Courses" should line up in the same manner. I think in my screen shot mock, the "None" underneath "My Courses" might be slightly more over to the right than the "None" label under "My Reports". We want them to align better.

**Comment by m11dedhia** [comment]
Hello sir @dartajax ,
I am new to ember and i tried installing the front end and used echo based command for the backend but when i am running the server on localhost:4200, i am getting this error.
![image](https://user-images.githubusercontent.com/13602231/95770180-a70b4380-0cd6-11eb-969a-ca89cf325e5c.png)




This is my log on the command line


```
PS C:\Users\Megh\Documents\GitHub\ilios> npm start

> ilios@26.3.3 start C:\Users\Megh\Documents\GitHub\ilios
> ember serve


Running without permission to symlink will degrade build performance.
See https://cli.emberjs.com/release/appendix/windows/ for details.

Created VERSION.txt with 26.3.3+80dcb7d1
- building... [Babel: ember-cli-flash > applyPatches]DEPRECATION: The use of the private `{{-in-element}}` is deprecated, please refactor to the public `{{in-element}}`. ('ember-cli-head/templates/components/head-layout.hbs' @ L1:C0)  [deprecation id: glimmer.private-in-element]
        at logDeprecationStackTrace (C:\Users\Megh\Documents\GitHub\ilios\node_modules\ember-source\dist\ember-template-compiler.js:1917:21)
        at HANDLERS.<computed> (C:\Users\Megh\Documents\GitHub\ilios\node_modules\ember-source\dist\ember-template-compiler.js:2014:9)
        at raiseOnDeprecation (C:\Users\Megh\Documents\GitHub\ilios\node_modules\ember-source\dist\ember-template-compiler.js:1944:9)
        at HANDLERS.<computed> (C:\Users\Megh\Documents\GitHub\ilios\node_modules\ember-source\dist\ember-template-compiler.js:2014:9)
        at invoke (C:\Users\Megh\Documents\GitHub\ilios\node_modules\ember-source\dist\ember-template-compiler.js:2026:9)
        at deprecate (C:\Users\Megh\Documents\GitHub\ilios\node_modules\ember-source\dist\ember-template-compiler.js:1982:28)
        at BlockStatement (C:\Users\Megh\Documents\GitHub\ilios\node_modules\ember-source\dist\ember-template-compiler.js:10801:59)
        at visitNode (C:\Users\Megh\Documents\GitHub\ilios\node_modules\ember-source\dist\ember-template-compiler.js:7729:16)
        at visitArray (C:\Users\Megh\Documents\GitHub\ilios\node_modules\ember-source\dist\ember-template-compiler.js:7820:20)
- building... [PostcssCompiler]autoprefixer: C:\Users\Megh\Documents\GitHub\ilios\assets\ilios.css:2231:3: start value has mixed support, consider using flex-start insteadautopr| building... [Bundler][BABEL] Note: The code generator has deoptimised the styling of C:\Users\Megh\Documents\GitHub\ilios\node_modules\zxcvbn\lib\frequency_lists.js as it exceeds the max of 500KB.
- building... [Bundler][BABEL] Note: The code generator has deoptimised the styling of C:\Users\Megh\Documents\GitHub\ilios\node_modules\google-libphonenumber\dist\libphonenumber.js as it exceeds the max of 500KB.

Build successful (205038ms) – Serving on http://localhost:4200/

Slowest Nodes (totalTime >= 5%)                                                          | Total (avg)
-----------------------------------------------------------------------------------------+-----------------------
Babel: ilios-common (2)                                                                  | 108752ms (54376 ms)
Babel: ilios (5)                                                                         | 26721ms (5344 ms)
```


### How do i overcome this error?

**Comment by m11dedhia** [comment]
> Hi @m11dedhia, I think the "More Padding in All Weeks Issue" has been resolved so we may end up closing that one. This one may be good for you though.
> 
> Basically we would like this ...
> 
> ![image](https://user-images.githubusercontent.com/7493331/95769368-9faf5000-0c6c-11eb-848c-b67d7685b2c7.png)
> 
> rather than this ...
> 
> ![image](https://user-images.githubusercontent.com/7493331/95769408-af2e9900-0c6c-11eb-835e-6c469cb2277d.png)
> 
> The "None" label underneath the larger "My Courses" label needs to line up better with the "My Courses" label. Both labels "None" underneath "My Reports" and "None" underneath "My Courses" should line up in the same manner. I think in my screen shot mock, the "None" underneath "My Courses" might be slightly more over to the right than the "None" label under "My Reports". We want them to align better.

Thank you, i understood what needs to be done

**Comment by dartajax** [comment]
That might be beyond my knowledge level sadly. I will see if we can get someone to chime in on that.

**Comment by m11dedhia** [comment]
@dartajax Thank you sir

**Comment by jrjohnson** [comment]
@m11dedhia that error is probably caused by having no API server to work from. You'll need to follow [these steps](https://github.com/ilios/frontend#running--development) to build from our demo server. Then you can use the credentials:
user: `demo_student24`
password: `demostudent24` to authenticate.

**Comment by m11dedhia** [comment]
Hello @jrjohnson sir,
I tried adding the backend using the .env file by writing this piece of code : 
```
echo "ILIOS_FRONTEND_API_HOST=https://ilios3-demo.ucsf.edu" > .env
```
Still can't figure it out. Its still showing me the same error.

**Comment by jrjohnson** [comment]
I'm sorry this is so difficult @m11dedhia. Can you tell me what errors are showing up in the browser console?

**Comment by m11dedhia** [comment]
Hello @jrjohnson sir,
Sorry for not being able to convey it properly here is the browser console : 
![image](https://user-images.githubusercontent.com/13602231/95816194-19fad580-0d3c-11eb-8b4d-93f7ee4acc7a.png)

Thank you.

**Comment by jrjohnson** [comment]
That error indicates that the change you made to `.env` didn't work. Can you try two things for me:
1) Change into the directory where you checked out this code and run `ls` and then run `cat .env` and add the results here
2) Completely stop and re-start the ember server `npm start`.

**Comment by m11dedhia** [comment]
Hello @jrjohnson sir, 
Here are the results : 
1. 
running ```ls``` : 
```
PS C:\Users\Megh\Documents\GitHub\ilios> ls


    Directory: C:\Users\Megh\Documents\GitHub\ilios


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        12-10-2020     21:44                .dependabot
d-----        12-10-2020     21:44                .github
d-----        12-10-2020     21:44                app
d-----        13-10-2020     01:26                config
d-----        12-10-2020     21:57                dist
d-----        12-10-2020     21:44                lib
d-----        12-10-2020     21:44                mirage
d-----        12-10-2020     22:16                node_modules
d-----        12-10-2020     21:44                public
d-----        13-10-2020     01:26                tests
d-----        12-10-2020     21:44                translations
d-----        12-10-2020     21:44                vendor
-a----        12-10-2020     21:44            123 .dockerignore
-a----        12-10-2020     21:44            386 .editorconfig
-a----        12-10-2020     21:44            289 .ember-cli
-a----        13-10-2020     00:52            110 .env
-a----        12-10-2020     21:44            260 .eslintignore
-a----        12-10-2020     21:44            590 .eslintrc.js
-a----        12-10-2020     21:44            425 .gitignore
-a----        12-10-2020     21:44            124 .npmrc
-a----        12-10-2020     21:44              4 .nvmrc
-a----        12-10-2020     21:44             76 .stylelintrc
-a----        12-10-2020     21:44            232 .template-lintrc.js
-a----        12-10-2020     21:44             40 .watchmanconfig
-a----        12-10-2020     21:44            276 app.json
-a----        12-10-2020     21:44           4594 CODE_OF_CONDUCT.md
-a----        12-10-2020     21:44            202 Dockerfile
-a----        12-10-2020     21:44           2538 ember-cli-build.js
-a----        12-10-2020     21:44           1131 LICENSE
-a----        13-10-2020     01:26        1220247 package-lock.json
-a----        13-10-2020     01:26           4437 package.json
-a----        12-10-2020     21:44           2986 README.md
-a----        12-10-2020     21:44            812 testem.js
```
running ```cat .env```
```
PS C:\Users\Megh\Documents\GitHub\ilios> cat .env
ILIOS_FRONTEND_API_HOST=https://ilios3-demo.ucsf.edu
```

2. I completely stopped and re-started the server with ```npm start``` . This is the command line code:
```
PS C:\Users\Megh\Documents\GitHub\ilios> npm start

> ilios@26.3.3 start C:\Users\Megh\Documents\GitHub\ilios
> ember serve


Missing npm packages: 
Package: ember-page-title
  * Specified: ^6.0.1
  * Installed: 5.2.3

Package: ilios-common
  * Specified: ^51.0.0
  * Installed: 50.1.2

Run `npm install` to install missing dependencies.



Stack Trace and Error Report: C:\Users\Megh\AppData\Local\Temp/error.dump.8d7005bca05797c6987a32aeaa132252.log
An error occurred in the constructor for ember-cli-dependency-checker at C:\Users\Megh\Documents\GitHub\ilios\node_modules\ember-cli-dependency-checker

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ilios@26.3.3 start: `ember serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ilios@26.3.3 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Megh\AppData\Roaming\npm-cache\_logs\2020-10-13T06_28_18_464Z-debug.log
```
I understand that this contains missing packages but earlier when i started the servers i got no such error. Should i install the missing dependencies using ```npm install``` on the current directory?
Thank you for helping.

**Comment by jrjohnson** [comment]
Yes, install missing dependencies. I would do that with `npm ci`, but `npm install` will work as well.

**Comment by m11dedhia** [comment]
Hello @jrjohnson sir,
Since I don't know much about ```npm ci``` , could you please shed some light on what's the difference between that and ```npm install``` ?
I looked up on the internet and it said that ```npm ci``` is beneficial when using it in test environment, but i didn't quite understand that.
Thank you.

**Comment by m11dedhia** [comment]
hello @jrjohnson sir, 
the problem still remains and it shows the same error message.

> Hello sir @dartajax ,
> I am new to ember and i tried installing the front end and used echo based command for the backend but when i am running the server on localhost:4200, i am getting this error.
> ![image](https://user-images.githubusercontent.com/13602231/95770180-a70b4380-0cd6-11eb-969a-ca89cf325e5c.png)
> 
> This is my log on the command line
> 
> ```
> PS C:\Users\Megh\Documents\GitHub\ilios> npm start
> 
> > ilios@26.3.3 start C:\Users\Megh\Documents\GitHub\ilios
> > ember serve
> 
> 
> Running without permission to symlink will degrade build performance.
> See https://cli.emberjs.com/release/appendix/windows/ for details.
> 
> Created VERSION.txt with 26.3.3+80dcb7d1
> - building... [Babel: ember-cli-flash > applyPatches]DEPRECATION: The use of the private `{{-in-element}}` is deprecated, please refactor to the public `{{in-element}}`. ('ember-cli-head/templates/components/head-layout.hbs' @ L1:C0)  [deprecation id: glimmer.private-in-element]
>         at logDeprecationStackTrace (C:\Users\Megh\Documents\GitHub\ilios\node_modules\ember-source\dist\ember-template-compiler.js:1917:21)
>         at HANDLERS.<computed> (C:\Users\Megh\Documents\GitHub\ilios\node_modules\ember-source\dist\ember-template-compiler.js:2014:9)
>         at raiseOnDeprecation (C:\Users\Megh\Documents\GitHub\ilios\node_modules\ember-source\dist\ember-template-compiler.js:1944:9)
>         at HANDLERS.<computed> (C:\Users\Megh\Documents\GitHub\ilios\node_modules\ember-source\dist\ember-template-compiler.js:2014:9)
>         at invoke (C:\Users\Megh\Documents\GitHub\ilios\node_modules\ember-source\dist\ember-template-compiler.js:2026:9)
>         at deprecate (C:\Users\Megh\Documents\GitHub\ilios\node_modules\ember-source\dist\ember-template-compiler.js:1982:28)
>         at BlockStatement (C:\Users\Megh\Documents\GitHub\ilios\node_modules\ember-source\dist\ember-template-compiler.js:10801:59)
>         at visitNode (C:\Users\Megh\Documents\GitHub\ilios\node_modules\ember-source\dist\ember-template-compiler.js:7729:16)
>         at visitArray (C:\Users\Megh\Documents\GitHub\ilios\node_modules\ember-source\dist\ember-template-compiler.js:7820:20)
> - building... [PostcssCompiler]autoprefixer: C:\Users\Megh\Documents\GitHub\ilios\assets\ilios.css:2231:3: start value has mixed support, consider using flex-start insteadautopr| building... [Bundler][BABEL] Note: The code generator has deoptimised the styling of C:\Users\Megh\Documents\GitHub\ilios\node_modules\zxcvbn\lib\frequency_lists.js as it exceeds the max of 500KB.
> - building... [Bundler][BABEL] Note: The code generator has deoptimised the styling of C:\Users\Megh\Documents\GitHub\ilios\node_modules\google-libphonenumber\dist\libphonenumber.js as it exceeds the max of 500KB.
> 
> Build successful (205038ms) – Serving on http://localhost:4200/
> 
> Slowest Nodes (totalTime >= 5%)                                                          | Total (avg)
> -----------------------------------------------------------------------------------------+-----------------------
> Babel: ilios-common (2)                                                                  | 108752ms (54376 ms)
> Babel: ilios (5)                                                                         | 26721ms (5344 ms)
> ```
> 
> ### How do i overcome this error?

**Comment by m11dedhia** [comment]
Hello @jrjohnson sir,
Sorry to disturb you but i have still not been able to solve this issue, could you please help me?
Thank you

**Comment by ShortonIT** [comment]
Original issue appears to be resolved, but there now appears to be a cosmetic issue of unequal spacing:  My Reports and My Courses formatting with slight mismatch in spacing where My Reports content begins with a space before writing starts. Intern team: Nanci/Michael/Stacey
![Ticket 4657v2](https://user-images.githubusercontent.com/103003096/162050576-0bb78c8d-daac-4e85-a454-671f0b6f2986.PNG)
