### ISSUE TITLE
Show More In Search Results Needs Show Less to Return the View

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#4673]
* Do a Search 

![image](https://user-images.githubusercontent.com/7493331/60369690-5a004280-99a9-11e9-854f-ab31d1c2144e.png)

![image](https://user-images.githubusercontent.com/7493331/60369780-99c72a00-99a9-11e9-8cf3-46445e94ae5c.png)

After showing all, there should be a way to "Show less" to return to the original view.

**Comment by jrjohnson** [comment]
I disagree. Let's discuss.
