### ISSUE TITLE
Add a few more courses to Ilios 3.0 Alpha Pre-release

### ISSUE THREAD

**Issue by jenzweben** [ilios/frontend#473]
So that users have more to test with.  Thanks!

**Comment by saschaben** [comment]
1. Family and Community Medicine 110 (2014-15) - course_id = 552
2. Foundations of Patient Care Year 2 (2014-15) - course_id = 605

**Comment by jrjohnson** [comment]
Adding new courses to the dev testing environment puts a few of the files over 100kb which causes a lot of issues for ember serve and will make it hard to work with - possibly slowing development of everything else significantly.  I'm going to close this as not possible.  We can work on getting a real API server up soon which will have a full complement of data.
