### ISSUE TITLE
CI Report Should Not Be Rolled Into A Year with a Finalized CI Report

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#4740]
I noticed that you can roll over a CI report into another year that already contains a finalized CI report. This should not be the case. If a year already has a finalized CI report, that year should not be available in the rollover drop-down.

A situation like the one below may ensue ...

![image](https://user-images.githubusercontent.com/7493331/62493605-646ee280-b786-11e9-8dc0-9286755bd2b0.png)

**Comment by stopfstedt** [comment]
discussed with the team, the outcome was that we won't pursue this.
