### ISSUE TITLE
Session Descriptions Appear to Be Links But Are Not Links

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#4747]
![image](https://user-images.githubusercontent.com/7493331/62738981-8a93bd00-b9e8-11e9-82dd-591b0ded598c.png)

**Comment by dartajax** [comment]
When you mouse over them, the pointer makes it appear they are links as well as if there is somewhere to navigate to by clicking the session description - there isn't.

**Comment by saschaben** [comment]
I think this has been addressed within the accessibility updates. please verify and close if true!
