### ISSUE TITLE
re-locate pulse loader animation

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#475]
with #474. the pulse is currently in the high left of the screen. this worked for the earlier rainbow wave, but not so for the new image.

relocate to center of rendered screen to balance. (@jenzweben determine optimal location and mock, and then pass on to @thecoolestguy)

**Comment by jenzweben** [comment]
Need to get confirmation about which in-page items may require loading animation please...

**Comment by saschaben** [comment]
@jenzweben if I understand this, not sure your question relates to this issue directly, but: in-page items would be 
* Course Objective
* Course Parent Objective/Competency
* Session Type (in course session list)
* Session First Offering (in course session list)

**Comment by jenzweben** [comment]
In order to mock up loader animation placement, I needed to know which items might have a loader - thanks!

**Comment by saschaben** [comment]
In this ticket I was only referring to the full page transition loader, but I hear ya.

**Comment by jenzweben** [comment]
Here's the full page loading animation location mock

![pulse-loading-location](https://cloud.githubusercontent.com/assets/5023894/7303400/37f6ed0a-e9a5-11e4-8014-4883591d63a0.png)
