### ISSUE TITLE
Spoofing As A Year One SOP Student on Stage, Year 3 Courses Not Loading

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#4772]
![image](https://user-images.githubusercontent.com/7493331/63124425-1add7f00-bf60-11e9-9780-c5d3d60c34ef.png)

**Comment by dartajax** [comment]
Quick update - the person I was logged in as is not actually a member of any cohort in Ilios ... yet. This is because stage hasn't been refreshed in a while.

**Comment by dartajax** [comment]
Another update - more testing - now I am spoofing a student who is most definitely in the cohort (year 2 student now). Same error results when trying to load level 3 stuff into the calendar.

**Comment by dartajax** [comment]
Course Level filter may be borked.

**Comment by jrjohnson** [comment]
Retest with new permission changes please @dartajax

**Comment by dartajax** [comment]
Manual testing passed.
