### ISSUE TITLE
Search: User Search no longer returning properly filtered/ordered results

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#4788]
Now that it works so nicely in the Admin Console, it would be nice if the selection process for an offering's instructor worked as well also.

Performing a search for "Nicholas Gutierrez" on demo puts the correct result right at the top ...

![image](https://user-images.githubusercontent.com/7493331/63552821-9b1a5c00-c4ed-11e9-8ceb-575cc47f83a0.png)

Performing a search for "Nicholas Gutierrez" to be attached to an offering as Instructor does not yield such great results. The user will have to scroll quite a ways to find the correct person to attach as instructor.

![image](https://user-images.githubusercontent.com/7493331/63552923-e16fbb00-c4ed-11e9-823e-c659d5b9e8be.png)

Since it is ordered by First Name, the user has to scroll down to find the correct instructor - as shown below. 

![image](https://user-images.githubusercontent.com/7493331/63553033-27c51a00-c4ee-11e9-883c-7b8e6ecf23d8.png)

**Comment by saschaben** [comment]
Instructor search occurs at:

User Admin user search
Course Director
Course Admin
Session Admin
Offering Instructor

All these areas currently fail to return filtered results with exact match first.
