### ISSUE TITLE
Search:  Results are not ordered/filtered correctly for Course Leadership

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#4789]
related to #4788 -- see screen shot below 

This is for adding a Director or Administrator to a Course using Course Leadership >> Manage Leadership

Course Director ...
![image](https://user-images.githubusercontent.com/7493331/63554032-21846d00-c4f1-11e9-84ad-cc3113da91e8.png)

Course Administrator ...
![image](https://user-images.githubusercontent.com/7493331/63554073-44168600-c4f1-11e9-8838-89c2eafc04ba.png)

**Comment by jrjohnson** [comment]
This API issue was resolved in ilios/ilios##2614 and released in `v3.68.2`.
