### ISSUE TITLE
New course creation needs work

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#48]
When clicking new course button on /courses:
[ ] Fix title translation to have some content
[ ] Fix start / end dates to have content
[ ] When the course detail page open the title edit box should be open and focused
[ ] The default title should be "Add Course Title: YYYY-MM-DD hh:mm:ss"

**Comment by jrjohnson** [comment]
We should set default values in the model:
http://emberjs.com/guides/models/defining-models/

Can be a scalar or we can use a function:
```javascript
createdAt: attr('string', {
  defaultValue: function() { return new Date(); }
})
```

**Comment by jenzweben** [comment]
Don't forget that we want to have a div expand down when a user clicks on "Add New" (course) that will have the contents of the Overview section.

**Comment by jenzweben** [comment]
Here's the new mock - assigning to @saschaben for review - if it's good to go, please assign to @jrjohnson if it needs work please assign back to me.  Thanks!

**Comment by saschaben** [comment]
@jenzweben no mock here in the ticket, please reattach, thanks!

**Comment by jenzweben** [comment]
![add-course](https://cloud.githubusercontent.com/assets/5023894/6240607/9f94c42c-b6c5-11e4-897a-359b59029de0.png)

**Comment by saschaben** [comment]
The required fields for course creation are:
1. Title
2. Academic Year

Not a problem to me providing the other fields in this entry form as shown, but they should allow for blank/null entry - except for: level, which should default to "1"; Clerkship should default to "Not a Clerkship".

Please add a field for Academic Year.

Q: can a course for one Academic Year be added to a page filtered on a different Academic Year? If so, field should be a select. If not, should be static (but still needs to be displayed for context.) I think we probably need to allow the former rather than the latter.

**Comment by jrjohnson** [comment]
Yes, no problem technically with adding a course to any year from here.
I don't like the blue text here.  I feel like a white input box is a better indication that something needs to be entered.  We also won't have a 'live edit' option since there is nothing to edit yet until save is clicked.

I love the idea of the cancel x at the top, I'm not sure it should be blue which is an edit color for us so far.  The red cancel x from the other live edit fields would seem like a better option.

**Comment by jenzweben** [comment]
![add-course-v2](https://cloud.githubusercontent.com/assets/5023894/6272999/d0d1ec66-b820-11e4-9664-0008253432d2.png)

**Comment by jrjohnson** [comment]
@saschaben can you remind me what you want to do for default start and end date?  I believe it was September 1 of academic year to December 31st of academic year.  Is that correct?  Does it need to change for courses created in October or February?

**Comment by saschaben** [comment]
There are two options for default:

1. Start date = first day of academic year. Thus works be most appropriate when making a course prior to year's start (ie before June 30)
2. Start date = Current date.

End date should default to start date + 60, or 8 weeks.

**Comment by jrjohnson** [comment]
And I believe first day of academic year is currently hardcoded at July 1?  So we could do
if today before 7/1 set to 7/1 else today?

**Comment by jrjohnson** [comment]
@saschaben Also - do we want to restrict these dates to within the bounds of the academic year?  Or let them set a 2/13/15 course in the 2013 year?

**Comment by saschaben** [comment]
@jrjohnson dates should not be restricted once a course is instantiated. Defaults should only be there to avoid nulls and to act as suggestions. No one will ever really use them. And because of the academic year - educational year stuff, we can't constrain start and end dates.
