### ISSUE TITLE
Course Learning Materials Summary Count Should Update After Filter

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#4815]
In the example below, a filter was performed on "smart goals". The list which was originally 150 items has now been reduced to 11 items due to the search / filter performed. It would be handy if the count also refreshed to let the user know how many records got returned by their filter / search.

![image](https://user-images.githubusercontent.com/7493331/64384834-f9b20080-cfea-11e9-9798-647409b5fa9a.png)

**Comment by dartajax** [comment]
This is also true in many other places and may be a global ticket if addressed at all.

Here is a screen shot of a filtered session list. This would be nice if the count reflected the number of sessions returned by applying the filter.

![image](https://user-images.githubusercontent.com/7493331/64386621-7d212100-cfee-11e9-8248-0c7b20697ad1.png)

**Comment by jrjohnson** [comment]
Agreed as a group, we'll want to address. @dartajax will add **every** place this may apply into a meta ticket.
