### ISSUE TITLE
Icons Missing From Admin Console

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#4829]
Here is an old screen shot from the user guide. I was planning on refreshing this graphic and some other stuff in the guide when I realized that the icons other than the "disabled" icon are not showing up in the Admin Console.

Or is it no longer supposed to be appear like what is shown below? 

![image](https://user-images.githubusercontent.com/7493331/64997074-8171f780-d894-11e9-91e5-18d8d473bbed.png)

Currently it looks like more like this ...

![image](https://user-images.githubusercontent.com/7493331/64997182-ce55ce00-d894-11e9-902c-405f0c108a12.png)

There should be "existing" or "add new" icons by the user records which do not have the krankenwagon (ambulance) icon.

**Comment by stopfstedt** [comment]
![Selection_051](https://user-images.githubusercontent.com/1410427/66245032-16138c80-e6c0-11e9-9eec-be9413c24bfa.png)

icons are all there. see screenshot from production above.
