### ISSUE TITLE
Program Duration Change Should Update Class of Graduation Year

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#4848]
Initially when a new Program is entered, there is nowhere to specify the program's duration. Only the Program title is initially entered.

![image](https://user-images.githubusercontent.com/7493331/65624343-81ea4c80-df7e-11e9-9751-cf8e23e1b2d8.png)

After clicking `Done`...

![image](https://user-images.githubusercontent.com/7493331/65624380-962e4980-df7e-11e9-91dd-9a1515f92481.png)

After clicking the `Long Study` link ...

![image](https://user-images.githubusercontent.com/7493331/65624413-ad6d3700-df7e-11e9-8ed6-8fb7bdc379ef.png)

After clicking the (+) button to add a Program Year since there are none yet ...

There is still nowhere to specify a program year (or program's) duration.

![image](https://user-images.githubusercontent.com/7493331/65624489-de4d6c00-df7e-11e9-8d3b-71c5a1856477.png)

After clicking `Done` to create the 2019-2020 program year ...

![image](https://user-images.githubusercontent.com/7493331/65624562-04730c00-df7f-11e9-869e-b0d5c12b1b4b.png)

Notice that there is a hard-wired determination that this is a 4 year program since the Cohort has been assigned the name "Class of 2023". But this is supposed to be 10 year program with. It should be "Class of 2029" but up until now there still has been nowhere to specify this.

After clicking the "Matriculation Year 2019-2020" link ...

and 

After modifying the 4 year program to be a 10 year program and saving this ...

We now have a 10 year program that graduates in 4 years as shown below ...

![image](https://user-images.githubusercontent.com/7493331/65624846-85ca9e80-df7f-11e9-957d-a41cec777327.png)

**Comment by saschaben** [comment]
This is trickier than it seems.

While the assumption is that a program is not going to suddenly go from a 4-year to a 10-year study length, there is the chance of that sort of change. But: first, would that be added as a new program, in order to graduate out the existing students? Similarly, if we were to allow for Ilios to change that grad year retroactively, would the students who entered a 4-year program suddenly require an additional 7 years of study?

If the duration is improperly added as a typo, I would expect it to be caught before a buildout of the program begins. If not, it is probably easier to manually update the db label for "class of" than to engineer flexibility into this.

thoughts?

**Comment by dartajax** [comment]
My thoughts are that we currently hard code the "Class of ####" business at 4 years. In the interface, there is no way to change the program year graduation at all.

**Comment by dartajax** [comment]
Unless I am missing something (which is entirely possible).

**Comment by dartajax** [comment]
In my example, I added a new program year with the 10 year duration and the following occurs ...

![image](https://user-images.githubusercontent.com/7493331/65627771-ef00e080-df84-11e9-90a7-31fceff57304.png)

If one were to want the first program year to be 10 years as well indicating the correct class of #### setting, I don't know how that could be done. The program years adjust once the duration has been updated. We need to allow for the program duration to be set at program creation time so the initial year shows up with the correct class of #### designation. Dig?

**Comment by dartajax** [comment]
Essentially the first year of a new program is hard wired to be 4 years in duration. The user shouldl be able to set this value upon program creation.

**Comment by saschaben** [comment]
duration is not hard wired: once a new program is instantiated, you can set the duration along with the other program attributes (name, short title). these are expected to be set PRIOR to the creation of program years.

**Comment by dartajax** [comment]
Oops. You are correct. I will close this.
