### ISSUE TITLE
Search: Include Academic Year Somewhere In Output

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#4896]
Please review the screen shot below. The Course name never changes (and this is common). How would a user know which link to follow or which year to filter down to to find the results?

![image](https://user-images.githubusercontent.com/7493331/67513386-90945400-f64f-11e9-9775-8cab89e46b84.png)

**Comment by saschaben** [comment]
See also #4847

**Comment by jrjohnson** [comment]
Fixed in #4891
