### ISSUE TITLE
Search For Learner Group In Offering Manager Not Returning Correct Values

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#4921]
The search for learner groups does correctly select the parent learner group but does not apply the filter to return only the matching sub groups. In our production environment, this has made the process of editing / creating offerings tedious.

![image](https://user-images.githubusercontent.com/7493331/68326230-e02b4480-007f-11ea-8271-ab7069323a84.png)

Searching for "ZZ" ...
![image](https://user-images.githubusercontent.com/7493331/68326855-0f8e8100-0081-11ea-8bf7-072b31604730.png)

Scroll to bottom and find "ZZ" eventually.

![image](https://user-images.githubusercontent.com/7493331/68326920-33ea5d80-0081-11ea-8170-9311e4eee854.png)

**Comment by jrjohnson** [comment]
@dartajax I'm not able to reproduce this anymore. Can you test? I think we may have fixed it.
