### ISSUE TITLE
Different icons for adding Student Group vs. Instructors for Session Offerings

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#493]
It has been suggested that it would be helpful to have different icons for the addition or association of Student Groups to Session Offerings vs. Instructors (or Instructor groups) -- see screen shot with arrows indicating the identical icons.

![sessionoffering](https://cloud.githubusercontent.com/assets/7493331/7359719/9a226262-ecf6-11e4-93af-4ea55e1c1836.JPG)

**Comment by dartajax** [comment]
![](http://i.imgur.com/UOFF8Ej.jpg)


# The Ilios User Guide 
####v 3.0 Release

# Contents
- General Information
- Logging In 
- Dashboard
- if your [hyperlink syntax](http://markdownpad.com)

#### General Information
#### Logging In
#### Dashboard


# Contents
  - [Specification](#specification) 
  - [Dependencies Title](#dependencies-title)
  - [DartAjax](#dartajax)
  - [CoolestGuy](#coolestguy)
  - [More Stuff](#morestuff) 

## Specification
Example text blah. Example text blah. Example text blah. Example text blah. 
Example text blah. Example text blah. Example text blah. Example text blah. 
Example text blah. Example text blah. Example text blah. Example text blah. 
Example text blah. Example text blah. 

this 

is not 

a 

drill 

## Dependencies Title
Example text blah. 

Example text blah. 

Example text blah. 

Example text blah. 

Example text blah. 

Example text blah. 

Example text blah. 

Example text blah. 

Example text blah. 

Example text blah. 

Example text not. 

Example text blah. 

Example text blah. 

Example text blah.

## Dartajax 
the shirt 

the stuff
 
the faraway stuff

the even further
 
what?

hey

cjeckl 

,e pui

out down here


## CoolestGuy

Time 

Is 

Now 

And all

That jazz

and stuff

down here 

hey look at me 

## More Stuff

what 

the hell?

is what 

knowing all or not 

now

**Comment by saschaben** [comment]
(oops, didn't mean to close!) maybe we can just use the fa-users or multiple fa-user-plus icons....?

**Comment by saschaben** [comment]
@jenzweben perhaps consider using the fa-stack class? Along the lines of...

![fa-stack](https://cloud.githubusercontent.com/assets/1753431/7418663/625eae3c-ef24-11e4-9e6f-854ad6b13c99.png)

**Comment by jenzweben** [comment]
I think that's the best available choice from Font Awesome but it is pretty ugly - I will try to make a custom one.

**Comment by saschaben** [comment]
Yeah -- I added the border with fa-stack to try and differentiate it (and deflate some of the ugliness). Unsuccessfully obviously.

**Comment by jrjohnson** [comment]
If at all possible I'd like to avoid custom images - they are a pain to maintain long term.

**Comment by saschaben** [comment]
The fa-stack class allows to combine multiple icons, if we can come up with a rendering that is suitable that is a composite of stock fa images. My attempt clearly didn't do it. but using the fa-users plus a fa-plus..? multiples of fa-user-plus? let's get creative here.

**Comment by jenzweben** [comment]
@saschaben I'm in the office today so if you can show me how to use fa-stack I will come up with something good.

**Comment by jenzweben** [comment]
Here is the css:
/// <style>
        .transparent-user {
          top: -4px;
            left: -4px;
            color: rgba(51, 51, 51, .5)
        }
        
        .little-icon {
            font-size: 90% !important;
            position: relative;
            bottom: 0px;
            left: 2px;
            color: rgba(51, 51, 51, .7)
        }
        
        .plus-icon {
            font-size: 65% !important;
            position: relative;
            top: -52px;
            left: 11px;
            color: #333333;
    </style>///

Here is the html:
///<i class="fa fa-user fa-stack-1x transparent-user"></i>
  <i class="fa fa-user fa-stack-2x little-icon"></i>
        <i class="fa fa-plus fa-stack-1x plus-icon"></i>///

preview:
![screen shot 2015-05-04 at 11 58 26 am](https://cloud.githubusercontent.com/assets/5023894/7460014/ea9fdb58-f254-11e4-867a-c7d182059e48.png)

**Comment by jenzweben** [comment]
Backup plan is to use fa-group but it's not really correct because it should have a + in addition to the ugly group of users in the icon...

**Comment by saschaben** [comment]
preview looks great. MUUUUCH better than the ugly fa-users.

**Comment by jenzweben** [comment]
Another option is for me to create a separate custom font face that would not be linked to font-awesome...whilst it will be additional files and not an elegant coding solution it might work to save dev time...

**Comment by jrjohnson** [comment]
I propose we use fa-users to differentiate for now and we can add something custom later if necessary.  Maybe by the time we get back around to this font awesome will have a different groups icon.
