### ISSUE TITLE
Course LM Rationale Cannot Be Unchecked or Reverted

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#4941]
If you find yourself in the situation below and it is determined that you do not indeed possess the copyright permission to this file, there is no way to back out of this and enter the reason. Cancel and Done are the only options. More tickets coming for this area I must admit.

![image](https://user-images.githubusercontent.com/7493331/69084445-1c07c780-09f9-11ea-920a-f2ad73bd346a.png)

**Comment by jrjohnson** [comment]
I think I fixed this accidentally in https://github.com/ilios/common/pull/966. Can you verify?

**Comment by dartajax** [comment]
The check box is now useable to get out of the situation outlined above. Just de-select it and then the rationale box appears - this is how it is supposed to be. Closing this ticket.
