### ISSUE TITLE
Copyright Rationale Check Not Being Enforced on Course LM

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#4943]
I imagine this is the case with Session LM's as well.

![image](https://user-images.githubusercontent.com/7493331/69086991-6a1dca80-09fb-11ea-8850-d4971a115caf.png)

After clicking Done ...

![image](https://user-images.githubusercontent.com/7493331/69087831-c1bc3600-09fb-11ea-9588-29be7fa65a39.png)

**Comment by stopfstedt** [comment]
conditional form validation does not jive with component at all. make three forms/components out of that.
