### ISSUE TITLE
Token Copy Should Have Confirmation Message For User

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#4945]
![image](https://user-images.githubusercontent.com/7493331/69104253-94cc4b00-0a1c-11ea-96de-b36382d8bd5f.png)

Refer to how the copy .ics works on calendar for guidance maybe. There the user is provided with a confirmation message which disappears in a cpl seconds.

**Comment by stopfstedt** [comment]
duplicates #5596 and #5448
