### ISSUE TITLE
Issues With User Event (1. Unnecessary Break  2. Timed LM's) on the Calendar

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#4968]
When a student is viewing their learning events by clicking on the calendar event (as opposed to viewing on the Week at a Glance (WaaG) where this is not an issue), they are not being provided the “available starting/ending” date info for a listed LM.

There is also an unintended and not needed or wanted line break that occurs after the clock icon appears. We need to get rid of this break. This does not appear to be an issue on routes for WaaG, for school events, or for non-student user views.

Below is an example of how it appears on the Week at a Glance for a student. This is correct.

![image](https://user-images.githubusercontent.com/7493331/69583621-2cd3b280-0f90-11ea-9295-4b4e7ac28dfb.png)

Below is an example of how a student would see the event if they were to click on the calendar.

This is not correct. "Drafty in Here" should be on the same line as the clock icon (no break) AND the information regarding the LM's availability needs to be added (similar to the way it appears in the upper screen shot).

![image](https://user-images.githubusercontent.com/7493331/69582776-2e9c7680-0f8e-11ea-9ebb-f0941f1ec18f.png)

**Comment by dartajax** [comment]
Related to #4969

**Comment by jrjohnson** [comment]
Works now.
