### ISSUE TITLE
Need Better Display of Objectives On Event Detail

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#4995]
Here is the objective ...

![image](https://user-images.githubusercontent.com/7493331/70355229-79d44600-1826-11ea-9625-8a45c280a3a6.png)

Here is the same objective in Event Detail ...

![image](https://user-images.githubusercontent.com/7493331/70355278-95d7e780-1826-11ea-929a-04b2684c3c96.png)

**Comment by jrjohnson** [comment]
I'm not able to reproduce this @dartajax can you add course and session details?

**Comment by dartajax** [comment]
![image](https://user-images.githubusercontent.com/7493331/70459508-2d2c7d00-1a69-11ea-86a5-c78b0be0eb0a.png)


![image](https://user-images.githubusercontent.com/7493331/70459717-97ddb880-1a69-11ea-8b84-5e05e9a3e303.png)

**Comment by dartajax** [comment]
![image](https://user-images.githubusercontent.com/7493331/70459754-afb53c80-1a69-11ea-8df1-4311767428e5.png)

**Comment by jrjohnson** [comment]
This is a single objective with a list in the description.

**Comment by dartajax** [comment]
Still an issue ...

This ...
![image](https://user-images.githubusercontent.com/7493331/99452195-17aa0f00-28d8-11eb-8095-5b02456772ef.png)

becomes this ...
![image](https://user-images.githubusercontent.com/7493331/99452283-33adb080-28d8-11eb-96de-dc9749487e9e.png)

there are no ellipses or anything either to even see the rest in this case

**Comment by dartajax** [comment]
never mind my ellipses comment
