### ISSUE TITLE
Course detail overview structure

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#50]
Re-structure both edit and non-edit overview to display label on top of content.  
![course-detail-page-editmode-publish-missing-v13](https://cloud.githubusercontent.com/assets/349624/6115411/667daf58-b05a-11e4-8eb3-f6f7fcbb036a.png)

**Comment by thecoolestguy** [comment]
This is fixed once we add the proper style to the inline-label-data-block class... @jenzweben, can you add a 'inline-label-data-block' class to css and give it a style of 'display: inline-block'

**Comment by thecoolestguy** [comment]
Also, I think this code is the same for viewing AND editing, but i'm not sure.  I couldn't find code for it anywhere else.
