### ISSUE TITLE
Add Instructors To Independent Learning Sessions

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#500]
**final decision**:
*Remove associated groups when ILM session is active.  Put an Instructors manager in the content below the Learner Groups manager for ILM.*

There needs to be a way to add Instructors to Independent Learning Sessions (ILM's) similar to the way we will be adding Learner Groups to ILM's.

In Ilios 2.4.x ...

![yeastbeer](https://cloud.githubusercontent.com/assets/7493331/7422981/63345ff6-ef46-11e4-80d0-e57a46f55b6f.JPG)
![yeastbeer2](https://cloud.githubusercontent.com/assets/7493331/7422982/6580ca38-ef46-11e4-8bf6-46d415540c95.JPG)
![yeastbeer3](https://cloud.githubusercontent.com/assets/7493331/7422986/6792b62e-ef46-11e4-80de-039081cd942f.JPG)

**Comment by dartajax** [comment]
In Ilios 3.x so far ..

Student groups can be added to ILM's but Instructors cannot - we need that functionality.

**Comment by saschaben** [comment]
@jenzweben can you mock this up -- adding an instructor/instructor group selector to ILM sessions?

**Comment by jrjohnson** [comment]
Awaiting mocks in #568
