### ISSUE TITLE
Fonts no longer rendering on buttons for FF

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#5000]
looks like we've lost our style rendering for fonts on button elements in Firefox (but not in Chrome):
![Ilios Dashboard 2019-12-11 12-52-38](https://user-images.githubusercontent.com/1753431/70659573-35292000-1c15-11ea-9766-8b629c79812b.png)

----
here too: 

![Ilios Dashboard 2019-12-11 12-52-51](https://user-images.githubusercontent.com/1753431/70659578-38bca700-1c15-11ea-9480-22e9b0e29f65.png)

Unless we want mismatched serif fonts in these places, I suggest we look into this.....

**Comment by stopfstedt** [comment]
cannot confirm. 
i'm looking at it with FF 71.0 on Linux.
![Selection_078](https://user-images.githubusercontent.com/1410427/70675546-4c303800-1c3e-11ea-9f6d-bff27984dfd2.png)
