### ISSUE TITLE
Missing translation: learnerGroups.learners Message On Offerings Editor

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#501]
See screenshot -- I may out of date again since there are changes I don't have yet that may not have been merged / committed yet.

After selecting Edit from the drop-down in the Session Offerings editor for one of the sessions with offerings, the screen looks similar to what is shown below ...

![missingtranslation](https://cloud.githubusercontent.com/assets/7493331/7424108/4f8a7308-ef52-11e4-9af1-bbdcf67045e3.JPG)

**Comment by saschaben** [comment]
relates to #452

**Comment by jrjohnson** [comment]
@dartajax great catch!  Those are really tough to spot but they are always bugs.  I'm going to assign this to you and we can work on a fix together.
