### ISSUE TITLE
Ability To Back out of New Session Offering missing

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#502]
Click Add New as shown

![addnewoffering](https://cloud.githubusercontent.com/assets/7493331/7424197/721363e8-ef53-11e4-9d1c-284094476d70.JPG)

See comment in screen shot - how would one back out if they don't want to add an offering?  

***Maybe this won't matter once Delete functionality is added, eh?***

![addnewoffering2](https://cloud.githubusercontent.com/assets/7493331/7424286/4677fb12-ef54-11e4-8285-79bda84efab2.JPG)

**Comment by saschaben** [comment]
![ability to back out of new session offering missing issue 502 ilios frontend 2015-04-30 16-22-23](https://cloud.githubusercontent.com/assets/1753431/7424363/25dfe846-ef55-11e4-8d57-a7a4134f428e.png)
 this is the cancel button.

**Comment by dartajax** [comment]
I need to check this tomorrow to see if the Cancel button is working properly.  I have a feeling the new form may take care of that as well.
