### ISSUE TITLE
Save and Cancel Buttons Are Not Necessary In Competency Manager Anymore

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#5020]
This is because the saving of competencies is done in-line style. The Save and Cancel buttons don't actually do anything (especially the Cancel button) in this context.

![image](https://user-images.githubusercontent.com/7493331/71279304-a059ad00-230d-11ea-987e-7f55c9f0a5c0.png)

The Save and Cancel buttons are available in-line on this form now. Once the user has saved or canceled the save event, the outer buttons are no longer necessary and don't really do anything.

**Comment by jrjohnson** [comment]
Looks like it doesn't actually save though, a page refresh leaves the original in place. Weird stuff going on here, need to clean it up.

**Comment by saschaben** [comment]
Is this part of the new glimmer component? because it's actually a break from the existing pattern of modify & save globally; it enforces a requirement for line item saves that disallows the saving of multiple adds/edits all at once. Not sure this is a good direction.

**Comment by jrjohnson** [comment]
No, save is still global, but when you click the revert icon it doesn't look like it reverted, on a refresh it does. So this isn't a new issue, its just something the Octane conversion uncovered.

**Comment by dartajax** [comment]
those buttons are actually needed and save the whole set
