### ISSUE TITLE
[meta] Admin Console Improvements

### ISSUE THREAD

**Issue by stopfstedt** [ilios/frontend#5078]
- [ ] #1472
- [x] #1593
- [ ] #1594 
- [x] #1952
- [x] #2100
- [ ] #2208 
- [ ] #2889 
- [x] #3093
- [x] #3095
- [ ] #3096 
- [ ] #3897
- [ ] #4377
- [x] #4701 
- [x] #4824
- [ ] #5548

**Comment by jrjohnson** [comment]
Closing meta.
