### ISSUE TITLE
Add New Offering Cancel Event Doesn't Work Completely

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#508]
See below ...

***1.***
![cancel1](https://cloud.githubusercontent.com/assets/7493331/7434234/1712303c-efee-11e4-9e8a-15811a29f7f8.JPG)
***2.***
![cancel2](https://cloud.githubusercontent.com/assets/7493331/7434237/1b3f122e-efee-11e4-8415-e7d9b91dbf40.JPG)
***3.***
![cancel3](https://cloud.githubusercontent.com/assets/7493331/7434238/1ebf873a-efee-11e4-876f-1ae90cfb41cd.JPG)
***4.*** After clicking the Cancel button in Step 3 (above) the screen looks like this (see below) and it appears an offering was indeed added even though I wanted to cancel.

![cancel4](https://cloud.githubusercontent.com/assets/7493331/7434241/245691e8-efee-11e4-92d4-204b4a0d7a2f.JPG)

**Comment by saschaben** [comment]
relates to #452
