### ISSUE TITLE
Need to add class called "schoolsfilter" to the div #schoolsfilter state where a user only has access to one school so that I can style that element

### ISSUE THREAD

**Issue by jenzweben** [ilios/frontend#51]

**Comment by jenzweben** [comment]
learnergroups - I will also be creating a mock in like 5 mins

**Comment by jenzweben** [comment]
![learner-groups-landing-v7](https://cloud.githubusercontent.com/assets/5023894/6138640/a9f1525c-b137-11e4-91fe-5da6b173570c.png)

**Comment by thecoolestguy** [comment]
So, the current 'schoolsfilter' element currently reads "<div id="schoolsfilter" class="filter">Medicine</div>" (for a single-school or multi-school user)

Are you saying that you want it to remain the same for multi-school users but, for single school users it should read: "<div id="schoolsfilter" class="filter schoolsfilter">Medicine</div>"?

**Comment by jenzweben** [comment]
So this case is for when a user only has access to a single school.  If they have multiple schools, they'll see a dropdown.  

Somewhere, somehow we need to add a label - "School:" and conditionally show the name of it (Medecine, Nursing, Pharmacy etc.)

**Comment by jenzweben** [comment]
The end result would be School: Medecine or School:  Pharmacy

**Comment by thecoolestguy** [comment]
fixed in #127
