### ISSUE TITLE
Change Pencil Icon To Down Arrow and Also Have Up Arrow Available

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#5110]
refs #4809

What this means ...

First of all if you want to review a series of 8 offerings to make sure each offering has the correct instructor (or instructor group) assignment, you are not actually wanting to `edit` the offering necessarily and indeed if you lack permissions you wouldn't be able to do that anyway. So a down (expand) arrow would be more accurate anyway. Then once you have reviewed the offering you can contract it by using the available up arrow button to minimize that particular offering.

I believe this would be helpful this because I am currently going through this exact process for one of our schools - double checking report output.

![image](https://user-images.githubusercontent.com/7493331/73892244-38164a80-482b-11ea-89f5-7f93071e7dca.png)

![image](https://user-images.githubusercontent.com/7493331/73892316-77dd3200-482b-11ea-888e-eeebe7ff0515.png)

The screen expands to display the details of this offering. It take up a lot of screen space to be certain. The only way to get this offering to close is to scroll down and click Cancel. It would be handy to be able to contract the offering from the top of its details. Maybe offerings could be nested inside sessions the same way sessions are nested inside of courses.

**Comment by stopfstedt** [comment]
sounds like you want a read-only view of the offering details that can be quickly toggled in and out of. that would be a new component that essentially mirrors the offering form, but without input elements. 

@dartajax  can you confirm?

**Comment by dartajax** [comment]
I know what I wanted was to be able to look at the details and then not have to scroll to the bottom to close/contract it. I think what you are suggesting is correct.
