### ISSUE TITLE
URL Occasionally Dropping Query String Variables

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#5112]
It is not super consistent but when I was going to the following ...

ttps://curriculum.ucsf.edu/courses?school=3&year=2020%20-%202021

I was ending up at ...

https://curriculum.ucsf.edu/courses?school=3

or ... 

https://curriculum.ucsf.edu/courses ...

and sometimes it would work normally as it should and send me back to School of Pharmacy (3) and 20-21 year.

**Comment by stopfstedt** [comment]
reviewed in production. whatever the issue was, this has been fixed since. filtering works as intended, and filter args in the url are correctly applied.
