### ISSUE TITLE
Check Box Values on Program Year Objective Competency Not Getting Set

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#5128]
I am not sure if the title will suffice as far as an explanation is concerned. So there will be more details below.

![image](https://user-images.githubusercontent.com/7493331/74363846-419a3800-4d80-11ea-9a99-5752af719b6b.png)

Whether the value is retrieved or the value is changed and checked using the mouse, the value does not get updated.

**Comment by dartajax** [comment]
This is still an issue.

**Comment by stopfstedt** [comment]
just checked, this has been corrected in the mean time.
