### ISSUE TITLE
need better styling of saved topics

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#514]
**final decision**:
4 columns alphabetical vertically down.  Setup the grid so they drop down when the page is too small.

_Right now the read-only topics list is unwieldy when there are more than four or five items -- take a look at a typical program year for an example._

_We need to style the list so that it is readily legible; either badge styles (like the edit format) without the "remove" x, or a more formatted list. Open to blue sky ideas here but let's get something!_

**Comment by jenzweben** [comment]
Here is a version that shows topics in columns of 11 items each...

with lots of topics:
![screen shot 2015-05-04 at 3 54 17 pm](https://cloud.githubusercontent.com/assets/5023894/7464721/2049a232-f27a-11e4-9757-b5ab943d1ca4.png)

with few topics:
![screen shot 2015-05-04 at 3 56 27 pm](https://cloud.githubusercontent.com/assets/5023894/7464724/29fc66ac-f27a-11e4-87bf-25faee054941.png)

**Comment by saschaben** [comment]
If this can be coded, I'm all for it. @thecoolestguy @jrjohnson thoughts?

**Comment by thecoolestguy** [comment]
It can definitely be coded.  Does the number of topics ever change?

**Comment by jenzweben** [comment]
I'm going to do another option

**Comment by jenzweben** [comment]
P.S. Topics are editable so the number of Topics may change...

**Comment by saschaben** [comment]
number of topics is always indeterminate. Current implementations run anywhere from 44 to 192 topics in the select list, and a program will usually have all available topics applied....

**Comment by jenzweben** [comment]
Here's an option that shows badges...of course we could also put badges behind the columnar version...

![screen shot 2015-05-04 at 4 48 17 pm](https://cloud.githubusercontent.com/assets/5023894/7464973/7f7915b4-f27d-11e4-9317-8d6888b53748.png)

**Comment by jrjohnson** [comment]
I like the 5 columns - that looks great with the big list.  If we do them alphabetically left to right then a list of 3 would take up one row and a list of 6 would take up two rows with a single item on the left side of the second row.  My only negative is what do we do when a topic name is wider than a single column, does it break onto its own special line?  Might get weird.

The badges are ok, easier to implement for sure - but I don't know if it is necessarily easier to read - the columns use whitespace better to make everything more legible.

**Comment by saschaben** [comment]
A question of consistency: if we use the columns, then how does that jibe with our other lists of similar nature (directors, mesh, whatever)? do we apply it across the board as a pattern? If not, do we have a different but equally effective pattern for all other lists? Do we want a single pattern for all lists? a different pattern for each list or type of list (people lists = one way, tag lists = another way, content item lists = another way....)?

**Comment by jenzweben** [comment]
I think that usability (readability, scanability) should trump consistency - can we not show 3 items in a column?  As opposed to horizontally?

**Comment by saschaben** [comment]
OK. I think the columnar view comes back to how we want to be utilizing screen space, and how the users want to interact with it. vertical listings get verrry long very quick with this stuff. horizontal listings can get wonky with longer names.

This gets to be less of an issue when we can collapse individual sections, but until such a time....

@jenzweben do you want to mock up some comparisons? three items, then 11 items, then 13 items? horizontal vs vertical? (if not thats fine).

**Comment by jenzweben** [comment]
sure

**Comment by jenzweben** [comment]
This is horizontal with 11 items...
![screen shot 2015-05-11 at 10 05 29 am](https://cloud.githubusercontent.com/assets/5023894/7570470/523759b0-f7c5-11e4-8c72-963bc98c9e58.png)

My recommendation is to go with columns.
