### ISSUE TITLE
Unable to Add Users On Demo

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#5148]
I am trying to add a user to demo3 - after clicking the `"Done"` button, the spinner appears and then disappears but no user is added to the database.

![image](https://user-images.githubusercontent.com/7493331/75296979-8e036000-57e3-11ea-9437-f2c15c6b7161.png)

**Comment by stopfstedt** [comment]
tested locally against latest backend (w/o elasticsearch). works there.

**Comment by dartajax** [comment]
{code: 500, message: "Internal Server Error"}
code: 500
message: "Internal Server Error"

**Comment by thecoolestguy** [comment]
There wasn't anything immediately clear in the logs, so I bounced the service and rolled-out new containers and tested it.  It works for me now.

**Comment by dartajax** [comment]
I was trying to add Dan Lemon to Ilios on demo3 and was unable to do so. I was trying to add him as a student in the Class of 2023 BRIDGES.

**Comment by dartajax** [comment]
No longer an issue - users can be added no problem.
