### ISSUE TITLE
Need new class for Session BG

### ISSUE THREAD

**Issue by jenzweben** [ilios/frontend#515]
In order to visually differentiate Sessions vs. Classes to help lessen user-confusion we need to have a distinct bg color for Sessions 

Color = Hex: EFFBFF  RBG: 239,251,255

Here is the mock (shows Course Detail -Collapsed State)

![course-detail-page-v8-collapsed](https://cloud.githubusercontent.com/assets/5023894/7462037/7ec44a2c-f263-11e4-9ee3-72b39d94f74a.png)

**Comment by thecoolestguy** [comment]
The sessions section is created with a class of sessions-list, so I am using 'sessions-list' as the class for distinguishing this section.  A 'sessions' class will be added to the other, lower level elements for styling, but it is not needed here.
