### ISSUE TITLE
Need New Class for Sessions Table Header

### ISSUE THREAD

**Issue by jenzweben** [ilios/frontend#516]
In order to visually differentiate Sessions vs. Classes to help lessen user-confusion we need to have a distinct Table Header BG Color and Table Header Font Color too.

Color = Hex: 00617F or RGB: 0,97,127

Please and thank you.
![course-detail-page-v8-collapsed](https://cloud.githubusercontent.com/assets/5023894/7462101/ee687d94-f263-11e4-9652-bacf1ea198f3.png)

**Comment by thecoolestguy** [comment]
A class named 'sessions' has been added to the resultslist-list div element to accomplish the desired styling on the header row.

**Comment by thecoolestguy** [comment]
Fixed in completion of issue #542 (PR #588)
