### ISSUE TITLE
Need New Class for Session Section Header

### ISSUE THREAD

**Issue by jenzweben** [ilios/frontend#517]
In order to visually differentiate Sessions vs. Classes to help lessen user-confusion we need to have a distinct Color for Sessions Section Header 

Color = Hex: 00617F or RGB:  0,97,127

![screen shot 2015-05-04 at 1 50 23 pm](https://cloud.githubusercontent.com/assets/5023894/7462186/8f402b22-f264-11e4-8bd4-9dfab8780242.png)

**Comment by thecoolestguy** [comment]
A class of 'sessions' has been added along side the detail-title class attribute to accomplish the desired styling of the section header title.

**Comment by thecoolestguy** [comment]
Fixed in completion of issue #542 (PR #588)
