### ISSUE TITLE
Bullet Points Not Needed - Learner Group Default Instructor

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#5187]
![image](https://user-images.githubusercontent.com/7493331/76572727-16d2fa80-6478-11ea-81f4-f6a5b8df4e6c.png)

**Comment by stopfstedt** [comment]
![Let me handle this](https://arkhamdb.com/bundles/cards/03022.png)

**Comment by stopfstedt** [comment]
that already got fixed via https://github.com/ilios/common/pull/904

**Comment by jrjohnson** [comment]
#904 is in production (has been for Months). This seems like a regression.
