### ISSUE TITLE
Enable course status indicator on detail page

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#52]

**Comment by jrjohnson** [comment]
@jenzweben what icons are we using for Publish, Scheduled, and Not Published?  The only one I know right now is clock-o for the scheduled.

**Comment by jenzweben** [comment]
I’m thinking  fa-star for Published and fa-star-half-full for Not Published and at this point I’d rather use a single style

**Comment by jrjohnson** [comment]
Once #75 is merged the last step will be to apply colors depending on status.
