### ISSUE TITLE
A specific set of objectives parented to a specific set of PY objectives fail to keep their links

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#5202]
This is regarding rolling this course `https://ilios3-demo.ucsf.edu/courses/1292`
over into the following year 19-20. 

I added an objective which is not used in any sessions. It gets rolled over successfully. All of the other course objectives are mapped to sessions. Some of the parent relationships between course and program year are not maintained yet some are. I checked and the program years appear to me to have the same 35 objectives - linked to competencies. So what I'm trying to say is that it is something other than course objectives not linked to session objectives that is causing the rollover of that relationship to fail.

Source course objectives ...

![image](https://user-images.githubusercontent.com/7493331/77102100-8f383f00-69d5-11ea-9d05-e4d34eb66e99.png)

Rolled over course objectives ...

![image](https://user-images.githubusercontent.com/7493331/77102278-cdcdf980-69d5-11ea-9132-41c561e8aa66.png)

**Comment by stopfstedt** [comment]
not a bug. this happens when you attach a different cohort or no cohort at all during rollover. works fine if you specify the same cohort(s) attached to the course being rolled over.
