### ISSUE TITLE
Header for Manage Blocks

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#521]
We are using the same header on all kinds of managers.  Topics is a good example:
![screen shot 2015-05-07 at 11 22 26 am](https://cloud.githubusercontent.com/assets/349624/7522631/5d71fc08-f4ab-11e4-9571-64b7535b928e.png)

We should do something better to separate the Topics (11) Manage Topics.  @jenzweben can you mock something up?

**Comment by jenzweben** [comment]
I actually mocked this up for Competencies - The header should read "Manage Topics" without a number when they're in edit mode...

![program-competencies](https://cloud.githubusercontent.com/assets/5023894/7541017/c93c5cd8-f566-11e4-983a-f3c67c9f8b76.png)

**Comment by jrjohnson** [comment]
@dartajax - can you make a list of all the places that this occurs so we make sure to catch them all?

**Comment by dartajax** [comment]
Courses and Sessions 

## Course level ...

* **Manage Topics**
* **Manage Cohorts**
* **Manage MeSH**
* **Manage Objectives (?)** - Currently there is no way to remove a Course level objective.  Should we do a manage or allow a different way to delete a Course Objective?

## Session Detail level  ...
* **Manage Topics**
* **Manage Objectives** - Same as with Course level 
* **Manage MeSH**
* **Learning Materials** - This is ugly right now - see below ...

![learningmat1](https://cloud.githubusercontent.com/assets/7493331/7576097/3b5fcf4a-f7ef-11e4-8958-b614ccc13d57.JPG)

## Session Objective level ...
* **Manage MeSH** - How does the user know which Objective they are modifying?  I know we have a ticket for this.  The flow doesn't make sense yet (to me).
* **Manage Competencies** (currently **Select Parent Objectives)** - How can this be deleted once entered if it is not wanted?  Currently all that can be done is to change it.

## Program Year level ..
* **Manage Competencies**
* **Manage MeSH** similar to what occurs in Session Objective
* **Manage Topics**

**Comment by jrjohnson** [comment]
Thanks @dartajax - looks like a good list.
