### ISSUE TITLE
My Courses Links Should Be One URL not Two

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#5213]
![image](https://user-images.githubusercontent.com/7493331/77362327-f7f12580-6d0d-11ea-900b-d5f7d59e422f.png)

![image](https://user-images.githubusercontent.com/7493331/77362407-1a833e80-6d0e-11ea-907f-90e3f5c40fc2.png)

It's a bit confusing. As a user, one might think that if you follow the second link (the lower screen shot), it might take you to all of the 19-20 courses or to all of your 19-20 courses. Either way, it's the same link and should be just one link.

**Comment by jrjohnson** [comment]
It's different links to incorporate the different styles. Is it OK if the year is the same style as the name?

**Comment by dartajax** [comment]
I would say that's fine. I thought it was confusing that there were two "different" links. Pretty low importance on this one.

**Comment by dartajax** [comment]
You could also just make the course title the link and leave the year as marked up text with no link and the original style - just no link.

**Comment by stopfstedt** [comment]
has been fixed a while back

![image](https://user-images.githubusercontent.com/1410427/134008173-43619a2d-0fda-448e-8f1f-896323f32770.png)
