### ISSUE TITLE
fix styling of program year - competencies container

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#522]
the top border of the box is missing where selected competencies are displayed.

![ilios 2015-05-07 13-36-54](https://cloud.githubusercontent.com/assets/1753431/7525460/818a1dd8-f4be-11e4-82e2-81aadd32dbaa.png)

**Comment by jenzweben** [comment]
This is related - I mocked up how I'd like the section to look...

![program-competencies](https://cloud.githubusercontent.com/assets/5023894/7540855/a6419fb4-f565-11e4-8c92-4448aa85d27c.png)

**Comment by jenzweben** [comment]
I know that it might be hard to implement this but it would be great if we could remove the "x" that is currently on the Available list.  Both lists should be click able - clicking on an item will move it to the opposite container...

**Comment by saschaben** [comment]
@jenzweben @jrjohnson I think part of the issue is that the current implementation has the "selected" and "available" lists reversed from the above mock. This follows 2.4, but we can certainly change it to be more standardized. I do think that more labeling per above to identify what is selected and what is still in the bucket would be really helpful. 

So: flip the boxes, remove the "x"''s, and provide a "No Competencies Selected" default message in the selected box if it is empty.

**Comment by jenzweben** [comment]
I think that the standard behavior is available left, selected right but realize that current Ilios has it reversed.  I will update the mock.

**Comment by jenzweben** [comment]
![program-competencies-2](https://cloud.githubusercontent.com/assets/5023894/7542221/df7a42e0-f56f-11e4-8c61-9a75d00985b8.png)

**Comment by saschaben** [comment]
@jenzweben the reversal in ilios 2.x is due to me and my inexplicable but ingrained habit of thinking right to left, rather than left to right. It may be due to too many years studying mideast languages.

**Comment by jenzweben** [comment]
أنا أفهم

**Comment by saschaben** [comment]
then go eat

**Comment by jrjohnson** [comment]
@jenzweben in most places we use the grey background to indicate something that has been selected and can be removed.  Why is it swapped here (to show the things that can be added)?

**Comment by jenzweben** [comment]
That is a good question.  I think it's because I initially had Available on the left and Selected on the right (this is the web/ software standard) but swapped it to match Ilios and must've forgotten to switch the bg.  I will update the mock.

**Comment by jenzweben** [comment]
![program-competencies](https://cloud.githubusercontent.com/assets/5023894/7709829/6de649dc-fe14-11e4-81c5-20ef8d75c7a8.png)
