### ISSUE TITLE
fix styling of program year - objective Parent competency selection 

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#523]
once a competency is selected as a parent, the representation of that selection is a little lame:

![ilios 2015-05-07 13-38-24](https://cloud.githubusercontent.com/assets/1753431/7525495/b5a97078-f4be-11e4-8478-ac8b98d650e4.png)

This needs rethinking.

Also, if we go with a pattern similar to this, the label should read "Selected [Parent] Competency", not "current competency". (Parent may be unnecessary, but I thought I'd throw it in just to try it out).

@jenzweben can you review and provide some alterna-mocks?

**Comment by jenzweben** [comment]
Do you want me to mock up an ideal solution or should I work with JJ to figure out what's feasible for launch or both?

**Comment by saschaben** [comment]
let's try both --- come up with ideal and work downward with @jrjohnson to the real from there.

**Comment by jenzweben** [comment]
got it, thx

**Comment by jenzweben** [comment]
I think this is looking good @saschaben pls confirm...

![screen shot 2015-05-11 at 9 50 33 am](https://cloud.githubusercontent.com/assets/5023894/7570193/38f8f3b6-f7c3-11e4-8e4e-664db68a1373.png)

**Comment by saschaben** [comment]
@jenzweben  this bit is fine (aside from the missing top border): it's the "select parent competency for program objective" that we really need to tweak. But not at the moment since #538 just borked the competency selector....

**Comment by jenzweben** [comment]
sorry I'll delete that last comment...Here is the mock for the IDEAL solution

![program-competencies-2](https://cloud.githubusercontent.com/assets/5023894/7570552/dd45aab6-f7c5-11e4-89cf-907cbafd8604.png)

**Comment by saschaben** [comment]
@jenzweben -- still need to go one level deeper. the above mock is for "Select competencies for Program". We need to address the display for where we add a single competency from that list to be the parent of a Program objective.

**Comment by jenzweben** [comment]
How about this - it's the same pattern as selecting parent objective in Courses...

![screen shot 2015-05-11 at 12 50 34 pm](https://cloud.githubusercontent.com/assets/5023894/7573696/74e31b72-f7dc-11e4-9b02-7a88e8daf68f.png)

**Comment by saschaben** [comment]
not a bad idea at all. @jrjohnson what do you think of using the objective selector here to pick competencies?

**Comment by jrjohnson** [comment]
Awesome good call using the same picker.  I like it.

**Comment by dartajax** [comment]
It looks really great.  And I was able to test using heroku - nice.
