### ISSUE TITLE
fix styling of program year - objective competencies select list

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#524]
We need a different styling here for top-level competency domain listings, since they are not selectable in this scenario:
![ilios 2015-05-07 13-45-04](https://cloud.githubusercontent.com/assets/1753431/7525599/a253376a-f4bf-11e4-8f1e-d1c7952bdca0.png)

They should display as "not-link-blue" -- maybe just black?

**Comment by jrjohnson** [comment]
Use Cohort Model -> displayTitle for the cohort name.
