### ISSUE TITLE
Provide Some Navigational Context In My Materials

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#5243]
Here is a screen shot which should illustrate this point. A user can navigate to "My Materials" from anywhere in Ilios but it might be helpful to keep their origin bolded so they would know where they are returning to if they click the back button. Also a label indicating where they are currently would be helpful too.

![image](https://user-images.githubusercontent.com/7493331/78157841-5d6fa100-73f5-11ea-9475-e2ced6a68e04.png)

**Comment by dartajax** [comment]
It might even be nice to have a link somewhere "Back to [wherever you came from]" somewhere on the screen.

**Comment by stopfstedt** [comment]
superseded by https://github.com/ilios/frontend/issues/5248
