### ISSUE TITLE
Program Year requires additional labeling

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#525]
Once we leave the program year list view and get to the management view, we've lost the very critical labeling in Program Year of "Matriculation Year" and "Class of XXXX". these are tremendously annoying and vital contextual labels. Just the Academic Year header is not enough.

![ilios 2015-05-07 13-58-58](https://cloud.githubusercontent.com/assets/1753431/7525816/7720076a-f4c1-11e4-9b1b-5fb2eaf54160.png)

@jenzweben can you mock up adding this information into the management page, using either the current header (where we display the academic year) or as a replacement for the somewhat unnecessary and redundant "Overview" label in the year management block?

**Comment by jenzweben** [comment]
How about this?

![program-year-detail-3](https://cloud.githubusercontent.com/assets/5023894/7539835/9c8f35d2-f55e-11e4-96d3-1f2af0e0bec7.png)

**Comment by saschaben** [comment]
looks good to me.
