### ISSUE TITLE
Provide Counts For Learners and Learner Groups

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#5262]
We count up the Instructors but don't do the same for newly introduced individual Learners, and for that matter Learner Groups.

![image](https://user-images.githubusercontent.com/7493331/78942936-9354fb00-7a6f-11ea-917d-4c45fb341d68.png)

**Comment by dartajax** [comment]
Well we don't say "Selected" before Instructors either so we should standardize the nomenclature and counts.

**Comment by stopfstedt** [comment]
obsolete as of https://github.com/ilios/common/pull/1716
