### ISSUE TITLE
Add A URL Field for Offerings

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#5271]
It would be nice to a URL-formatted field to input an Offering's location if the location is remote - say a Zoom link or the like.

**Comment by dartajax** [comment]
How about naming it `URL` and allowing a maximum of 255 characters (varchar(255))?

**Comment by jrjohnson** [comment]
Looks like URLs can be up to 2k chars, even though it's not super common we should probably support a fairly long string here.

**Comment by dartajax** [comment]
![image](https://user-images.githubusercontent.com/7493331/84838889-8402a880-aff0-11ea-9798-b28cd2f01819.png)

**Comment by dartajax** [comment]
If the URL field value exists, place the link with the same image as with Learning Material link - example shown below

![image](https://user-images.githubusercontent.com/7493331/85607720-3c3fda80-b609-11ea-96c5-7902dd28bc94.png)

**Comment by jrjohnson** [comment]
This is where I'm worried we might need a title attribute for this. That link is hard to spot and difficult to tell what it might do. Alternatively  instead of generic URL we could call it `Live Session` which might make it easier to differentiate from a learning material as well.

**Comment by dartajax** [comment]
Maybe more like this for the data entry area of the offerings editor ...

![image](https://user-images.githubusercontent.com/7493331/85900197-3afee100-b7b4-11ea-8273-a982370ef75a.png)

**Comment by dartajax** [comment]
The screen shot below is for when a URL has been entered for the virtual offering. The link should only show up if it exists.

More like this for the Event Detail ...

![image](https://user-images.githubusercontent.com/7493331/85901764-591a1080-b7b7-11ea-9f50-711fcf82af55.png)

**Comment by dartajax** [comment]
Here is the same offering when students are once again welcome to pack into lecture halls - no URL field entered.

![image](https://user-images.githubusercontent.com/7493331/85902024-de9dc080-b7b7-11ea-832b-6db6e3508769.png)

**Comment by jrjohnson** [comment]
This looks great! I think we should make this available in week at a glance as well. Can you mock that up?

**Comment by dartajax** [comment]
I was wondering about WaaG - I will put that in on Monday for sure.

**Comment by dartajax** [comment]
Here's WaaG - a first attempt. If URL value has been entered, the link can appear in its own line, indented to match any Pre-work at this point - open to discussion - maybe a slightly smaller indent might be better.

![image](https://user-images.githubusercontent.com/7493331/86044703-51e54380-b9ff-11ea-8f48-4a607ed4f928.png)
