### ISSUE TITLE
Provide Warning Message When Duplicate Learner Group Names Are Assigned

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#5302]
This is so if a user changes a learner group name to one that has already been used, they will receive a warning message. They will not be prevented from using a duplicate name but will be warned about it to make sure they are aware of the situation.

We do learner group copy and always append the word "(Copy)" to the newly created learner group. This can be edited later and removed. Also when creating a new learner group, there is currently no check in place.

**Comment by stopfstedt** [comment]
was discussed with team, and we won't do any of this. see #5444
