### ISSUE TITLE
Blue "Selected" Bar In Program Year Objectives Selects Too Much

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#5326]
I admit the issue title is not the clearest. The screen shots below will hopefully help.

![image](https://user-images.githubusercontent.com/7493331/81426995-e8d40480-910e-11ea-8f6e-76cbcd80bdcf.png)

![image](https://user-images.githubusercontent.com/7493331/81427147-33558100-910f-11ea-82b6-fd19ff7d04dd.png)

**Comment by dartajax** [comment]
It is probably not even necessary at all in the lower of the two screen shots since we know the objective has been selected due to the blue box already surrounding it.

**Comment by stopfstedt** [comment]
can't reproduce this:

Firefox: 

![image](https://user-images.githubusercontent.com/1410427/134007073-c7835693-f0b6-492b-8184-bb07e6d99bf0.png)


Chrome:

![image](https://user-images.githubusercontent.com/1410427/134007184-fe288f53-1de1-43cc-b4c2-74940e983894.png)


@dartajax can you verify that this is still an issue? perhaps it's a Safari thing, in which case JJ should handle this.

**Comment by mhgh22** [comment]
Unclear about the blue box. If you are referring to the partial sky blue outline, we do not see it in the three main browsers(ff, chrome, edge). There is the standard blue box that selects everything when picking an objective(same with what Stefan is showing). Not sure if you meant this blue box and how it selects too much. - MNS @dartajax 

![Screenshot 2022-04-27 at 10-37-40 Ilios Programs](https://user-images.githubusercontent.com/103135575/165588612-ac4d6e69-6649-4657-b489-0ad0d44ec0b0.png)
