### ISSUE TITLE
Callouts On Program Year Objectives Appear To Be Reversed

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#5327]
The problem appears to be the callouts as shown below. 

![image](https://user-images.githubusercontent.com/7493331/81427728-0ce41580-9110-11ea-9646-a7f741b17522.png)

**Comment by dartajax** [comment]
I take some of this back. I think it is the callouts that are backwards actually - my first instinct may have been the correct one.

**Comment by dartajax** [comment]
I could tell something was fishy.

**Comment by jrjohnson** [comment]
They seem right to me, but maybe I'm backwards. When it is inactive the tooltip says `Activate` since that is the thing that will happen if you click. When they are active the tooltip says `Deactivate`.

**Comment by dartajax** [comment]
But they can't all be inactive currently.

**Comment by dartajax** [comment]
The active ones (which would be 95% of them) should have the lightbulb on and de-activate as the caption. No?
