### ISSUE TITLE
Change The Dashboard "My Materials" Link to "All Materials"

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#5349]
This is just for general clarity - kind of how "All Weeks" is in the WaaG area of the Dashboard.

![image](https://user-images.githubusercontent.com/7493331/82701975-f7014500-9c25-11ea-856b-855afa1b0903.png)

**Comment by stopfstedt** [comment]
has been fixed (a while back)

![image](https://user-images.githubusercontent.com/1410427/134007555-225bb9e4-1021-48d5-911e-d867625eb05b.png)
