### ISSUE TITLE
fix styling of learner groups and instructor groups - 2 row label should be 1 row label

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#535]
see screenshots below ...

Learner Groups ...

![lrnrgrp](https://cloud.githubusercontent.com/assets/7493331/7547064/d673909a-f59a-11e4-912f-739c8c17dff4.JPG)

And the ugliest mock award goes to ....

![lrnrgrp2](https://cloud.githubusercontent.com/assets/7493331/7547066/dae839e6-f59a-11e4-8f93-7c406c63b822.jpg)

Instructor Groups ...

![instructorgroup](https://cloud.githubusercontent.com/assets/7493331/7547088/454b8c16-f59b-11e4-8032-cfbe69df07ac.JPG)

the second ugliest mock award goes to ...

![instructorgroup2](https://cloud.githubusercontent.com/assets/7493331/7547091/4a838c92-f59b-11e4-87d5-d441e7f695ad.jpg)

**Comment by saschaben** [comment]
this has been addressed
