### ISSUE TITLE
If No Objectives Exist, Parentage Indicator Should Not Be Green

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#5380]
While technically it is true that all of the objectives have parents, that is only true because there are no objectives at all. This should be the indeterminate color since it is in more or an in-between state when there are no objectives to have parents anyway.

![image](https://user-images.githubusercontent.com/7493331/84210053-97e86080-aa6c-11ea-8ace-68479a1bd3a3.png)

**Comment by stopfstedt** [comment]
this has been fixed since. the summary is not shown if no objectives exist 

![image](https://user-images.githubusercontent.com/1410427/105785055-ea5c8b80-5f2e-11eb-8cf2-da80327b79b9.png)
