### ISSUE TITLE
Session Counter Should Refresh When Sessions Are Added

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#5390]
The Course has 80 sessions.

![image](https://user-images.githubusercontent.com/7493331/84832480-2ebf9a80-afe2-11ea-855c-0114fe6c7aee.png)

I am going to add one now.

![image](https://user-images.githubusercontent.com/7493331/84832521-4565f180-afe2-11ea-978e-dac24d5634ca.png)

After Save ...

![image](https://user-images.githubusercontent.com/7493331/84832608-76462680-afe2-11ea-9bdc-24db02e5ccba.png)

The 80 should be now 81 since there are 81 sessions. Granted this is related to the other ticket #5111 - actually it is pretty much a duplicate in reverse.

**Comment by stopfstedt** [comment]
this has been fixed since.
