### ISSUE TITLE
Fix style on some elements

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#542]
Styling was broken in #538 - the following should be fixed:

Course List: year select styling is broken. Responsive header color is incorrect with small screen. Add new course year select styling is broken.
Course details: mesh select styling is broken. topics select list is styling is broken. cohort select list styling is broken. Parent objective select list styling is broken.
Session details: learner group select list styling is broken. parent objective select list styling is broken. "Add Offering" button drop down styling is broken. Topics and mesh broken per course.
Learner groups: learners not in this group listing styling is broken.
Program Year: Competencies listing style is broken.
Publish button drop down styling is broken.

**Comment by thecoolestguy** [comment]
Slide-out Menu hover state was resolved in 11036163ad8dd27a above

**Comment by dartajax** [comment]
This looks good to me.

**Comment by thecoolestguy** [comment]
Closed via #588
