### ISSUE TITLE
Improve Pre-work Format on WaaG

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#5422]
It could be easily asked what in the world is even wrong here - not much actually. But it would seem better to have Pre-work be "Pre-work:" in both places rather than "Pre-work" and then "Pre-work :". 

so ... 

* ditch the extra space on the lower one 
* add the colon to the upper one 

![image](https://user-images.githubusercontent.com/7493331/86042221-b1d9eb00-b9fb-11ea-853c-9caae081fd2b.png)

**Comment by dartajax** [comment]
The font size decisions are another issue.

**Comment by m11dedhia** [comment]
Hello @dartajax sir,
I am willing to work on this, could you please assign this to me?
Thank you.

**Comment by nancirose** [comment]
Appears that nothing has changed. Still an issue. - Nanci, Michael, Stacey

![Screenshot (69)](https://user-images.githubusercontent.com/103001847/162793018-cc6e3840-1cd9-4f1e-9130-2d0b310ce966.png)

**Comment by stopfstedt** [comment]
obsolete ticket.
