### ISSUE TITLE
Add navigation to return to program years from program year detail

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#544]
I noticed while using the application that the following seemed strange to me but may not be a big deal.

![programstart1](https://cloud.githubusercontent.com/assets/7493331/7571468/ad05ca82-f7cc-11e4-95eb-0a5843de5ee6.JPG)
![programstart2](https://cloud.githubusercontent.com/assets/7493331/7571469/ae6d9774-f7cc-11e4-87ae-2df49ae0a297.JPG)
![programstart3](https://cloud.githubusercontent.com/assets/7493331/7571471/b039f052-f7cc-11e4-95a9-7f2249cdd2c5.JPG)

**Comment by jrjohnson** [comment]
@jenzweben - can you advise here?  I'm thinking back to Doctor of Medicine Program Years as a blue link in between the program overview and the program year header.

**Comment by jenzweben** [comment]
I think "Back to Program Years" would be good.
