### ISSUE TITLE
Need An Error Message If Session Description Cannot Be Saved

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#5443]
I pasted a screen shot into the Froala control and it looks like it can be saved. After clicking Save to process this, it is clear that nothing was saved.

![image](https://user-images.githubusercontent.com/7493331/86975309-ec930000-c12c-11ea-915f-d72c4f7be086.png)

![image](https://user-images.githubusercontent.com/7493331/86975604-88247080-c12d-11ea-8b3d-e1209630814d.png)

Why would anyone ever do this? Maybe an image provides the information they wish to convey in the Session's description. Either way, it looks like it is allowed but it is not allowed so we inform the user if someone were to try something like this.

**Comment by stopfstedt** [comment]
garbage in/nothing out.  there is no way for us to reach into the froala internals to determine whether the user input was sanitized/filtered-out or not.
