### ISSUE TITLE
Learner Groups Should Require A Unique Name

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#5444]
This may have been entered in the past - it seems familiar to me.

See screen shot - when re-naming sub groups, it is difficult to see the names of the other groups that are being re-named. Therefore it is possible and easy to use a sub group name more than once. We should enforce uniqueness here. See screen shot below.

![image](https://user-images.githubusercontent.com/7493331/87092071-a3f04b00-c1ef-11ea-9a1a-e31b63d70194.png)

**Comment by stopfstedt** [comment]
this request needs further clarification. at what level(s) should uniqueness be enforced? 
i'd also like to point out that this would be a frontend workflow change only - we cannot enforce this in the database schema after the fact.

**Comment by stopfstedt** [comment]
i'm putting this up for team discussion since i don't see a big benefit in doing the work on this.

**Comment by stopfstedt** [comment]
this never got discussed, so i'm assigning this to @saschaben as product manager to make a decision here.

**Comment by stopfstedt** [comment]
refs 
![image](https://user-images.githubusercontent.com/1410427/134007797-b92dfb8e-b30a-46af-a661-632fd29d981a.png)

**Comment by stopfstedt** [comment]
@saschaben ping on this. can we please have a decision on this? thank you.

**Comment by dartajax** [comment]
We are going to pass on this.
