### ISSUE TITLE
Copied Successfully Message Needed On Token in My Profile

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#5448]
It would be nice if after clicking as shown below - indicated by the blue arrow, there were a confirmation message of some sort that the token has been successfully copied to the clipboard. Currently there is no indication of anything happening at all. 

![image](https://user-images.githubusercontent.com/7493331/87177817-1cf3af00-c291-11ea-9a80-3524f5a0e8d8.png)

**Comment by stopfstedt** [comment]
duplicate of https://github.com/ilios/frontend/issues/5556
