### ISSUE TITLE
Manage Directors Redo

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#545]
Currently managing directors is the only place where we have no save / undo - we need to have that.  Follow the pattern currently in the topic manager.

Needs a mock which indicates how the list is displayed when not in edit mode and where the 'Manage Directors' button goes.

**Comment by jenzweben** [comment]
Here's what I'm thinking for the "off state" 
![course-detail-page-v9-collapsed](https://cloud.githubusercontent.com/assets/5023894/7574504/a7f4ea76-f7e2-11e4-89e1-1534cbb64b49.png)

**Comment by jenzweben** [comment]
@saschaben what do you think?

**Comment by saschaben** [comment]
@jenzweben how would a user activate the edit field? and where would control buttons be located?

I'm OK with the visuals (don't LOVE the comma delimited list, but it's what we have now, so I guess it will do), the red X on the badges seems a little intense compared with all else on the design, but layout-wise in all other respects I like!

**Comment by jenzweben** [comment]
Aah - the "Manage Directors" button dropped off 
![course-detail-page-v9-directors](https://cloud.githubusercontent.com/assets/5023894/7595410/b2c09892-f89b-11e4-9115-fcfc49783819.png)

**Comment by saschaben** [comment]
OK. that makes more sense :+1:

**Comment by dartajax** [comment]
Padric had made a comment during his performing of our usability script that the gray coloring of the Directors - gray badge might look like it’s disabled to users.  I realized this issue pertains to the restyling of the Directors functionality so hopefully this comment is in the right place or else I can make a new issue specifically for the coloring of the Director badge.
