### ISSUE TITLE
My Courses List on Dashboard Needs to Wrap Better with Long Course Titles

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#5453]
See screen shots ....

Nice ...
![image](https://user-images.githubusercontent.com/7493331/87327366-d7312380-c4e8-11ea-9077-13522009fcb0.png)

Now if one of the courses has a slightly longer title, not so nice ...

Kinda kludgey ...
![image](https://user-images.githubusercontent.com/7493331/87327546-08a9ef00-c4e9-11ea-933a-646f6171c917.png)

**Comment by stopfstedt** [comment]
![image](https://user-images.githubusercontent.com/1410427/105785215-3b6c7f80-5f2f-11eb-920a-49a970cddbe8.png)

this has been fixed since.
