### ISSUE TITLE
Include Student Advisor In Admin Console

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#5497]
see screen shot below 

![image](https://user-images.githubusercontent.com/7493331/89347893-77014d80-d660-11ea-8e88-2728d63af686.png)

**Comment by dartajax** [comment]
Consider also setting the "Performs Non-Learner Activities" flag to Yes as well but do not display Courses and Sessions menu.

**Comment by jrjohnson** [comment]
Looks good. That flag currently means user has access to a bunch of stuff that SAs don't have. So let's make all the display changes, but leave the flag along.
