### ISSUE TITLE
Course details objective title contains html

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#55]
When we render the objective title on the course detail page we need to either:
a. not escape the HTML and render it as is
or 
b. remove all html content and keep only the text and render that.

@saschaben I think we've talked about this, but is B a real option?  Can we just present the objective as a text object and ignore any HTML added by the program?  I think the only case where this would be a problem is when a list was used and we could start accounting for that in a later revision where we moved to markdown or something better suited to user entered content.

**Comment by dartajax** [comment]
Course #741 is ugly - SOM objectives pasted in.  Actually Session Objectives for this course are also ugly -- imagine that.

**Comment by dartajax** [comment]
Session -- 21065

**Comment by dartajax** [comment]
Ugly paste-ins abound in this course .../course_management?course_id=733

**Comment by dartajax** [comment]
Paste in ugliness session = 21544

**Comment by jrjohnson** [comment]
741 and 733 are both in 2015 and are not available in our test data which only covers SOM/SOP 2013 and 2014.  Can you find me something in those years?
