### ISSUE TITLE
List Load Slowly

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#551]
The initial lists on /courses /learnergroups /instructorgroup /programs seem to load very slowly.  I would guess that we're either using the route:model method incorrectly, or that everything is double loading due to query params getting set to default values.  How can we speed this up / where is the delay happening?

**Comment by ebryn** [comment]
We investigated this during our meeting today and it appears that the UI is "fast enough" when we disable Mirage's network delay.
