### ISSUE TITLE
Learner Groups - add form to learner list

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#552]
the learner list for groups is currently wrapping group names, causing all names to take up at least two rows of screen space.

We should fix this so each name defaults to using a single row unless the group name (or user name) is obscenely long and forces a wrap. It looks like something along the lines of 

```<div class="form-col-9 learnergroup-group-membership">```

should do the trick

**Comment by thecoolestguy** [comment]
I believe this is fixed by the changes in #606, please verify
