### ISSUE TITLE
Test run failing on Ember 3.20.4

### ISSUE THREAD

**Issue by snewcomer** [ilios/frontend#5529]
Found via @ember/data external partner tests.

https://github.com/emberjs/ember.js/blob/master/CHANGELOG.md#v3204-august-11-2020

Failing test - https://github.com/ilios/frontend/blob/cd3bbcaac554f1705b5ab4460f8dac4a0d4cd3fc/tests/acceptance/instructorgroup-test.js#L118

**Comment by jrjohnson** [comment]
Thanks @snewcomer, we're going to pin at `v3.20.3` in #5530 to wait for a fix for https://github.com/emberjs/ember.js/issues/19105 which looks to be causing this test failure (along with some other issues).
