### ISSUE TITLE
Use a JS Style Checker

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#555]
@ebryn - please attach style guide and info.

**Comment by ebryn** [comment]
The style checker we should use is called JSCS: http://jscs.info/
Easy to install into the app using `broccoli-jscs`: https://www.npmjs.com/package/broccoli-jscs
Here's a `.jscsrc` I'm using at another client: https://gist.github.com/ebryn/d90523c901ec8f436852

**Comment by saschaben** [comment]
is this still an issue to be addressed? If not, please close, thx.
