### ISSUE TITLE
use Ember.computed instead of prototype extension

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#556]
@ebryn - please include more info

**Comment by ebryn** [comment]
```
foo: function() {
}.property('bar')
```

should be converted to:

```
foo: Ember.computed('bar', function() {
})
```

which will align us better with ES7 property decorators which will look like:

```
@computed('bar')
get foo() {
}
```

and if you want to live on the super bleeding edge, you can start using the ES7 syntax today with: https://www.npmjs.com/package/ember-computed-decorators

**Comment by jrjohnson** [comment]
We can do this in one shot with https://github.com/abuiles/ember-watson#ember-watsonconvert-prototype-extensions

Its going to touch a lot of files though - so probably a nice end of week item to avoid merge conflicts.

**Comment by saschaben** [comment]
is this still an issue to be addressed? If not, please close, thx.

**Comment by jrjohnson** [comment]
Fixed at some point a while ago...
