### ISSUE TITLE
add input controls and output for learner group "needs accommodation" flag

### ISSUE THREAD

**Issue by stopfstedt** [ilios/frontend#5563]
companion ticket to https://github.com/ilios/ilios/issues/3083

**Comment by saschaben** [comment]
really bad mockup of what we need here. mouseover on icons would display "members of this group require accommodation". 
[Question: do we display icon for the entire tree, or just the subgroup it is set to (when set to a subgroup)? I'm thinking only the subgroup.]

![access1](https://user-images.githubusercontent.com/1753431/92790604-c8d47c00-f360-11ea-8e4d-305a4a647c93.png)
![access2](https://user-images.githubusercontent.com/1753431/92790609-c96d1280-f360-11ea-84d7-4d3d83b1fba0.png)

here we could do a check box or a toggle, and may want to provide some additional visual cue for when selection is true (eg the label goes bold, or something):
![access3](https://user-images.githubusercontent.com/1753431/92790611-c96d1280-f360-11ea-8522-847d590fbced.png)

**Comment by saschaben** [comment]
One more. Also, regarding the question above: maybe we can add an icon to the subgroup count, if there is a group in the subtree that requires, but the parent doesn't...?
![access4](https://user-images.githubusercontent.com/1753431/92792245-39c86380-f362-11ea-9601-f587935eb85e.png)

**Comment by stopfstedt** [comment]
@saschaben thanks for the mocks, these are great.
