### ISSUE TITLE
Program Cohort Picker needs formatting work

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#560]
here is what I am seeing - 

![cohortstuff](https://cloud.githubusercontent.com/assets/7493331/7594765/af7751de-f897-11e4-9948-0a16ec12d020.JPG)

**Comment by jrjohnson** [comment]
@jenzweben - can you see how our implementation compares to your mocks?  I'm guessing you already did a better job with this than my implementation.  If not please re-mock with @dartajax's suggestions?

**Comment by jenzweben** [comment]
on it!

**Comment by jenzweben** [comment]
OK here's how the Manage Cohorts screen should look:

![course-detail-cohorts-manage](https://cloud.githubusercontent.com/assets/5023894/7641766/b36279fe-fa40-11e4-802a-c1bd9b7e116b.png)

**Comment by jenzweben** [comment]
Looks like the Read-only (View) is good to go already

![screen shot 2015-05-14 at 1 53 10 pm](https://cloud.githubusercontent.com/assets/5023894/7641843/42c79552-fa41-11e4-9295-4857238ac83b.png)

**Comment by saschaben** [comment]
review for choice of pattern: above mock, or objective parent picker pattern. maybe put in front of user?
