### ISSUE TITLE
Unable to go 'back' through dashboard

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#563]
To reproduce:
1. Go to http://yahoo.com
2. Visit http://ilios-frontend-demo.herokuapp.com/
4. you will be redirected to the dashboard
3. Click back to return to yahoo - you get stuck on the dashboard.

I think this is caused by the index route transitioning to the dashboard here:
https://github.com/ilios/frontend/blob/master/app/routes/index.js#L5

@ebryn - are we using transitionTo incorrectly here?  I think I have some fear of using the application route or index route to do actual work and instead am delegating that to a dashboard route.  Am I being paranoid?

**Comment by ebryn** [comment]
@jrjohnson: you should be using `replaceWith` instead
