### ISSUE TITLE
Slide-out Menu Hover State height is too small

### ISSUE THREAD

**Issue by jenzweben** [ilios/frontend#564]
![screen shot 2015-05-12 at 2 22 51 pm](https://cloud.githubusercontent.com/assets/5023894/7599012/8c11dd9c-f8b3-11e4-87a7-dd85b5bb30a9.png)

**Comment by jrjohnson** [comment]
I think this is probably part of #542 so I'm assigning to @thecoolestguy

**Comment by thecoolestguy** [comment]
it is indeed, fixed in commit 11036163ad8dd27a of issue #542

**Comment by thecoolestguy** [comment]
Fixed in in issue #542
