### ISSUE TITLE
improve pattern for selection of instructors and instructor groups

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#568]
The current display is confusing and poorly prioritized.
![instructors](https://cloud.githubusercontent.com/assets/1753431/7615612/a4c94e2e-f953-11e4-9ad1-5a7f77211223.png)

in 2.4, we avoided this by concatenating the select lists of available groups and individuals, with groups simply listed first as selectable entities. @jrjohnson has noted that this is pretty tricky in the new model, so we have split the choosers. But right now presents a weird selection that implies the user should primarily be selecting instructor groups, which is incorrect. the default use case is a single instructor for a single offering/ILM.

Having the instructor group panel at top, always open, and taking up as much real estate on its own as it does is probably not a good call. We want the instructor (solo) selector to be primary here.

@jenzweben @jrjohnson can we get a revised mockup and implementation pattern for this, for both the above selection for an offering, as well as selection for an ILM...? Perhaps a version that brings the implemented/implementable code closer in line with our original mocks?

**Comment by jrjohnson** [comment]
I'm no longer convinced that we can't do this in one list if we want to. So Jen should feel free to draw this up however makes sense.

**Comment by jenzweben** [comment]
Excellent!  I'll start mocking

**Comment by jenzweben** [comment]
I don't see anything when I click on an instructor group - is the image above a mock or screenshot?

**Comment by saschaben** [comment]
screenshot from PR #500. to see the current pattern, go to https://ilios-frontend-demo.herokuapp.com/course/595/session/16523 and edit an individual offering.

**Comment by jenzweben** [comment]
**Key Decision**
We will have a single search / results box which will include both People & Groups.  Even though groups could be loaded faster than individual people, we will show results at the same time.  The label for the search field should be:  Search Instructors & Instructor Groups.
