### ISSUE TITLE
Confirmation Msg After Publish / UnPublish

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#570]
It would be nice if there could be a message to advise the user that a Course or Session (or other curricular object such as Program) has been successfully Published (or UnPublished).  

Per user feedback, it seemed really easy to use but it wasn't clear if the change "went through" since there is no longer a Save button to do this.  A message of some sort would be helpful.

**Comment by saschaben** [comment]
perhaps we could consider implementing something similar to what Slack is actually doing, in the edits for account preferences: the saved icon flashes briefly upon the change: https://www.dropbox.com/s/c294xwduk1rlf9l/screencast%202015-05-14%2021-44-32.mp4?dl=0

**Comment by jrjohnson** [comment]
We need notifications across the board.  I created #572 to document this.
