### ISSUE TITLE
Admin Console Year Selector Should Retain Its Value Upon Return via Back Button

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#5719]
![image](https://user-images.githubusercontent.com/7493331/100142628-0b2e3500-2e49-11eb-9b16-16b0e8d77f88.png)

![image](https://user-images.githubusercontent.com/7493331/100142977-7841ca80-2e49-11eb-87cc-01cd2eec647d.png)

![image](https://user-images.githubusercontent.com/7493331/100143153-bdfe9300-2e49-11eb-921b-471125234d2a.png)

**Comment by stopfstedt** [comment]
i can't get this addition to work with this component in its current form, it's the George Costanza Wallet.

will have another go at it tomorrow, perhaps breaking this thing up into smaller components will yield the desired result.

**Comment by stopfstedt** [comment]
btw, if we're doing sticky year selections, then we should also make the selected school sticky.
