### ISSUE TITLE
Manage School Leadership Form Fields and Check Boxes to Remove are Missing

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#5734]
I am logged in as a School Administrator. There should be check boxes to remove users from this role and I should be able to use them.

![image](https://user-images.githubusercontent.com/7493331/100943177-99419580-34b1-11eb-9b69-f65192b7a474.png)

There should also be search boxes down at the bottom that can be used to select users to be added to either of the two available School Leadership roles.

Here is the bottom of the list.

![image](https://user-images.githubusercontent.com/7493331/100943273-cbeb8e00-34b1-11eb-9a22-74997dff43e8.png)

I was logged in with root permissions and even then, the search options were not there and the boxes to remove users were also not available.

**Comment by stopfstedt** [comment]
duplicates #5732
