### ISSUE TITLE
Course List Issues with Screen Resize

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#5782]
Here it is looking normal ...

![image](https://user-images.githubusercontent.com/7493331/103826342-816aad80-502b-11eb-9717-afa5109995bf.png)

Now after reducing the width of the screen a bit ...

![image](https://user-images.githubusercontent.com/7493331/103826532-d8708280-502b-11eb-99c8-8a8e8aabb831.png)

Try to delete a Course and witness this majesty ...

![image](https://user-images.githubusercontent.com/7493331/103826746-41f09100-502c-11eb-9e58-9027d751fce8.png)

**Comment by stopfstedt** [comment]
> Here it is looking normal ...
> 
> ![image](https://user-images.githubusercontent.com/7493331/103826342-816aad80-502b-11eb-9717-afa5109995bf.png)
> 
> Now after reducing the width of the screen a bit ...
> 
> ![image](https://user-images.githubusercontent.com/7493331/103826532-d8708280-502b-11eb-99c8-8a8e8aabb831.png)

not going to happen at this time. the table components that we're using to lay this out supports two modes - small screen and big screen. you're  just hovering around that breakpoint here, have a look how it displays on cellphone screen sizes. introducing a third state (let's say for "medium sized" screens, e.g. tablets) is out of scope, and imo not worth the added complexity. this is not broken.


> Try to delete a Course and witness this majesty ...
> 
> ![image](https://user-images.githubusercontent.com/7493331/103826746-41f09100-502c-11eb-9e58-9027d751fce8.png)

this is a bug. working on it.
