### ISSUE TITLE
Learner Groups Member Re-assignment needs to look like a dropdown

### ISSUE THREAD

**Issue by jenzweben** [ilios/frontend#580]
Eventhough we might not technically be able to have a dropdown, we need to make the selector look like a dropdown - also the check & "x" should be to the right of the dropdown 

![screen shot 2015-05-18 at 10 19 04 am](https://cloud.githubusercontent.com/assets/5023894/7685993/7038a1c6-fd47-11e4-9af8-a84fd0b59b1c.png)

Should look like:
![screen shot 2015-05-18 at 10 20 52 am](https://cloud.githubusercontent.com/assets/5023894/7686026/b2225438-fd47-11e4-8282-86cb3f101545.png)

**Comment by jrjohnson** [comment]
These actually are dropdowns.  All of our select lists look like action menus as per #262

**Comment by jenzweben** [comment]
Action menus have a down caret (arrow)...these don't...

**Comment by jrjohnson** [comment]
Ah ok - thats one of the things being fixed in #542.  I'm going to close in favor of that.

**Comment by jrjohnson** [comment]
@thecoolestguy - can you take a look at why these dropdowns are missing their arrow?

**Comment by thecoolestguy** [comment]
This was set up as a 2 column form (form-col-6), when it should be just one column wide (form-col-12).  Each 1 "column" contains a label and data field.  I'll update the documentation further, but I believe this is fixed.
