### ISSUE TITLE
New Learner Group (subgroup) Text Box needs to be wider

### ISSUE THREAD

**Issue by jenzweben** [ilios/frontend#582]
So that user may read all of the hint text...

![screen shot 2015-05-18 at 10 29 20 am](https://cloud.githubusercontent.com/assets/5023894/7686208/fb4f900c-fd48-11e4-9229-0b2e075d07b9.png)

**Comment by jrjohnson** [comment]
Fixed at some point in the distant past.  Like maybe 2 weeks ago....
