### ISSUE TITLE
Low Priority Space Saving Suggestion

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#5834]
Get rid of the vertical space used by the rectangles - reduce padding by 50% - unless this is a shared component that can't be modified in this way.

![image](https://user-images.githubusercontent.com/7493331/101703280-68280e80-3a37-11eb-929b-3fdf69c284d5.png)

**Comment by stopfstedt** [comment]
reviewed and rejected. this is controlled by a global component style (`detail-container-content` adds a `2rem` top margin), going to a one-off is not worth the efforts an increased maintenance overhead imho.
