### ISSUE TITLE
make remaining academic-year toggles configuration-aware

### ISSUE THREAD

**Issue by stopfstedt** [ilios/frontend#5866]
![image](https://user-images.githubusercontent.com/1410427/108134765-a3644080-706b-11eb-8e26-c638a2fbafde.png)
![image](https://user-images.githubusercontent.com/1410427/108134887-deff0a80-706b-11eb-992c-da19e0ad8498.png)
![image](https://user-images.githubusercontent.com/1410427/108781865-6d1d3a00-751f-11eb-9b51-286548a1ad7b.png)

![image](https://user-images.githubusercontent.com/1410427/108134794-b0812f80-706b-11eb-9230-bfb100a491db.png)
![image](https://user-images.githubusercontent.com/1410427/108743127-55c55900-74ed-11eb-8fe3-491132009a1a.png)
![image](https://user-images.githubusercontent.com/1410427/108743212-6970bf80-74ed-11eb-98c3-ca5137b5b487.png)
![image](https://user-images.githubusercontent.com/1410427/108743043-3dedd500-74ed-11eb-924f-ef4e38ee9bfb.png)

refs https://github.com/ilios/ilios/issues/3272

**Comment by jrjohnson** [comment]
Adding course rollover to this list and suggesting that maybe we throw this in a service to make it easier to keep track of?
