### ISSUE TITLE
Enable Masquerading to Allow Emulating A Particular User's Screen for Troubleshooting

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#587]
This has been frequently requested and may finally be possible.  It would be really helpful for Ilios administrators and anyone with advanced user privileges to be able to see what any given user is experiencing when a problem is reported.  It would be very helpful to be able to view a user's calendar as he/she would be seeing it to solve problems.  Maybe a method of selecting a user from a drop-down menu could be provided (or some other method) to achieve this functionality.

**Comment by saschaben** [comment]
replaced and updatedby #1569
