### ISSUE TITLE
Course detail learning material list required status

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#59]
Change the template to display Yes/No instead of true false.  Yes should get a class of 'add' and no should get 'remove' (green / red).

**Comment by thecoolestguy** [comment]
Weren't we going to display 'Yes' for 'required' and nothing for 'no'?  I'll do it with 'No' for now, but I remember we were talking about 'No' being blank.

**Comment by jenzweben** [comment]
Jason - that's my understanding too

**Comment by saschaben** [comment]
"Yes" for required, "" for No. that's right.
