### ISSUE TITLE
Replace RGB colors with hex values in style sheets

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#590]
One of the things I like about using hex is that we can create a variable to store the colors.  This keeps us from having many shades of the same color that are essentially the same.  Using RGB values prevents this.

Thoughts @jenzweben @thecoolestguy @saschaben?

**Comment by jenzweben** [comment]
As long as there can be semi-transparency, I'm fine with hex...

**Comment by saschaben** [comment]
is this still an issue? if not please close, thx.

**Comment by jrjohnson** [comment]
We can store RGB in a variable, so this is no problem.
