### ISSUE TITLE
Remove usage of ember-modal-dialog

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#5900]
This addon isn't maintained much and it has trouble with the new Embroider build system. We're only using it in a few places, so let's transition away. Most of these cases are in `WaitSaving` which may not be necessary anymore with options in our API to save multiple items at the same time.

**Comment by stopfstedt** [comment]
remaining instances of <WaitSaving> usage:

```
app/components/learner-groups/root.hbs:  <WaitSaving
app/components/curriculum-inventory/report-details.hbs:    <WaitSaving>{{t "general.finalizingReport"}}</WaitSaving>
app/components/bulk-new-users.hbs:        <WaitSaving
app/components/assign-students.hbs:    <WaitSaving
app/components/learnergroup-subgroup-list.hbs:    <WaitSaving

```

**Comment by stopfstedt** [comment]
non-issue at this point - `<WaitSaving />` has shed its dependency on ember-modal-dialog and is good to use again.
