### ISSUE TITLE
Change "View Details" and "Close" to Show Details / Hide Details change icon 

### ISSUE THREAD

**Issue by jenzweben** [ilios/frontend#597]
Based on usability testing, users may be confused by the down caret icon and the language "View Details" on the open / close mechanism.  Please use "Show Details" (icon = fa-plus-square) and "Hide Details" (icon = fa-minus-square)

![screen shot 2015-05-20 at 9 22 37 am](https://cloud.githubusercontent.com/assets/5023894/7730906/dc40b4e0-fed1-11e4-84fe-5bee67acc6c9.png)

![screen shot 2015-05-20 at 9 19 27 am](https://cloud.githubusercontent.com/assets/5023894/7730920/e536bf5e-fed1-11e4-9eb1-52cdc82c7b8e.png)

**Comment by jrjohnson** [comment]
Lets add to this that when details are hidden the window position should scroll to put the show tab at the top of the screen instead of remaining somewhere in the sessions list.
