### ISSUE TITLE
Clicking Anywhere in Session List Row Should Take User to Edit That Session

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#607]
It seems with the mouse pointing as a finger and the entire row highlighted that clicking anywhere in the row of a session should perform the action of selecting the selected session for modification / review.

**Comment by jrjohnson** [comment]
I think the actual bug here is that there is a pointer and a highlight for the row when hovering.  Since we now have the eyeball click for offerings it doesn't make sense for the row itself to be clickable, you should click on the session name.  @jenzweben / @saschaben thoughts?

**Comment by dartajax** [comment]
I agree with you on that.  So if the user click the eyeball, the session offerings appear.  If the user clicks the session name, the edit session screen appears.  So there are two different actions that could occur.  I just wanted to point out that it looks like the whole row is selectable.

**Comment by dartajax** [comment]
Did you all discuss this at today's meeting?  I am curious to know what has been decided.

**Comment by jenzweben** [comment]
I'm going to mock up a solution where we highlight the bottom border of the selected row and when a user rolls over either the title or the offerings eyeball, that td background color will change.  I might also try a version where the whole row is highlighted and the title & eyeball have a darker bg color on hover...
