### ISSUE TITLE
Navigation Context Gets Lost In Event Detail

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#6095]
It has been pointed out, accurately enough, that this will not affect students who do not perform teaching activities. Many do however. This does affect all other Ilios users.

Here's what's happening ...

After selecting to view the Calendar, the user is brought to the following. The Calendar is part of the Dashboard. Dashboard is circled (actually an ellipse of course) on the side bar menu.

![image](https://user-images.githubusercontent.com/7493331/119903158-2283d300-befd-11eb-8772-d428d00fcff3.png)

Now I am going to view the details of an event - the one on May 24th at 9:15am to review the details. After clicking on the event ...

![image](https://user-images.githubusercontent.com/7493331/119903299-6545ab00-befd-11eb-88cf-35060c72c8b5.png)

The user never made a decision to leave the Dashboard and go elsewhere. Dashboard should still be **Dashboard**.

**Comment by jrjohnson** [comment]
Closed via #6096
