### ISSUE TITLE
Learner Groups - Subgroup Detail Page - needs "Back to Group" link

### ISSUE THREAD

**Issue by jenzweben** [ilios/frontend#611]
Right now when a user creates a subgroup, and goes to edit or view it, there is not link back to one level up

![screen shot 2015-05-21 at 1 38 24 pm](https://cloud.githubusercontent.com/assets/5023894/7758538/354f1264-ffbf-11e4-9573-7e902a96aa1b.png)

Should look like this:

![screen shot 2015-05-21 at 1 42 42 pm](https://cloud.githubusercontent.com/assets/5023894/7758549/498b5198-ffbf-11e4-8d5a-4a7cdd241ca6.png)

**Comment by jrjohnson** [comment]
@jenzweben I think the second mock is on the wrong level.  If the title was 2018 -> BMB Class -> BMB Sub that would make sense.  

When we are at that top level group should the link say back to learner groups, or just not be there?

When we are 3 levels down does the link say back to group?  Does it return to the top level, or one level up to the parent group?

**Comment by dartajax** [comment]
We noticed this today while testing with Valentina.  If in a Sub Group, there should be a link to go one level up to the next higher level group.  If at the top level sub group, there should be a link to navigate back to the list of Leaner Groups.

**Comment by saschaben** [comment]
will be addressed by breadcrumbs in ref. #1506
