### ISSUE TITLE
Labeling Issue With Time Released LM's

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#6139]
Week at a Glance -- correct ...

![image](https://user-images.githubusercontent.com/7493331/124976471-2ae32980-dfe4-11eb-88f9-eca0a161ac43.png)

Event Detail -- info missing ...

![image](https://user-images.githubusercontent.com/7493331/124976554-4bab7f00-dfe4-11eb-9394-0697e8d0a102.png)

**Comment by stopfstedt** [comment]
fixed via https://github.com/ilios/common/pull/2248
