### ISSUE TITLE
Increase Size of Search Box to allow Caption to be displayed Completely

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#617]
This is a super-small deal but if the search box were slightly wider the caption "Filter By Instructor Group Title" could display in full.

![biggerbox](https://cloud.githubusercontent.com/assets/7493331/7780800/7a70c21e-0098-11e5-83e9-299ad9039957.JPG)

**Comment by jrjohnson** [comment]
This was fixed when lists were re-styled.
