### ISSUE TITLE
Provide Sortable Columns >> Instructor Groups

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#6188]
There can be quite a few Instructor Groups in any given school. It would helpful to have sortable columns. This would make this screen more compatible with how Learner Groups function - better consistency and functionality.

![image](https://user-images.githubusercontent.com/7493331/127070554-562b0e68-043b-4f11-a1ad-4dc59a11e3a5.png)

**Comment by stopfstedt** [comment]
sorting by title and members is doable, i'm de-scoping sorting by associated courses since that would require a bigger rewrite, and more importantly the retrieval of a lot more data points (offerings, sessions, ilms), which doesn't seem worth the trade-off in sacrificing performance over, imo.
