### ISSUE TITLE
Action menu cutoff

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#620]
_Issue:_ The action menu on an individual offering is cutoff.

_Interim Solution:_ for the 3.0 release, **we will use edit/delete icons (trashcan, pencil)** while we continue to work to resolve the drop down control issue, and will target a solution for the re-introduction of the action controller in this place for 3.1 to accommodate the increasing list of expected actions.

**Comment by jenzweben** [comment]
There are a bunch of things going on...I think this is over my head :cry: 
I kinda got this to work but it's not "sustainable"

![screen shot 2015-05-26 at 2 52 06 pm](https://cloud.githubusercontent.com/assets/5023894/7825576/87bbcf9e-03c3-11e5-8346-542b80eddd6e.png)

**Comment by jrjohnson** [comment]
Ok - i've now tried a hundred things and I don't have a non-radical solution to this.  We have three options that I can see:
1. Change the menu to push down the content underneath it instead of overlaying it.
2. Completely replace our bourbon neat gid with a different one and hope that helps
3. Put offerings in a real table instead of a gird.

3 seems like the only viable solution, but I don't remember why the offerings are not in a table right now.  Does anyone else?  cc @saschaben @jenzweben @thecoolestguy

**Comment by jrjohnson** [comment]
oh - another option:

4.  Put a menu's worth of space between offerings.  This would add a LOT of white space to the page.

**Comment by saschaben** [comment]
@jrjohnson we used the non-table grid because of the layout and organization of the day/time labels on the left side of the offerings list. at least that is my recollection. If we can table it that would be great. 

Another alternative is to ditch the action menu control for a list of icons or something similar.

**Comment by jrjohnson** [comment]
Well going to a table will make #621 easier as well as any kind of future sorting.  I will give it a shot and see if it turns out terrible.
