### ISSUE TITLE
Update Ilios in Admin Console Not Functioning - Prod

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#6274]
![image](https://user-images.githubusercontent.com/7493331/138154416-ba2766be-dae5-4af3-bc9f-60560707f0bb.png)

None of the other links function either - can't disable the user's acct or remove the user's acct from the sync

**Comment by nancirose** [comment]
Able to see student file. Option to update unavailable.
-Michael, Stacey, Nanci

![Screenshot (81)](https://user-images.githubusercontent.com/103001847/165156213-86cff079-c279-46f3-b019-18df21f9939e.png)

**Comment by dartajax** [comment]
In order to edit (or attempt to edit) someone's record from the Admin Console, you should click the ...

![image](https://user-images.githubusercontent.com/7493331/165158021-0657315d-eeeb-41d9-8c2c-b810e2abeb5c.png)

... button and then try and save the record. 

Another showstopping caveat on this one: You won't have access to test this one in production since you are accessing our demo site not prod.

Since I have access to test this on production, I have assigned this to myself to re-test and possibly close since I believe this has been fixed since occasionally I clean up the records anyway and haven't seen this error while doing so. My original ticket was to report issues having to do with records that need attention in production. There are none of those records in demo since it is not hooked up to our campus directory system. Thanks for checking - I will re-test.

**Comment by stopfstedt** [comment]
click tested the originally described problem, this seems to have been resolved.
