### ISSUE TITLE
squish deprecations

### ISSUE THREAD

**Issue by stopfstedt** [ilios/frontend#6365]
crunching the log output of a recent CI test run.
```
$ egrep -or 'DEPRECATION:[^\\]+' frontend_deprecations.log  | sort | uniq -c | sort -rn
    176 DEPRECATION: competency.domain Computed Called [deprecation id: common.async-computed]
     75 DEPRECATION: cohort.rootLevelLearnerGroups Computed Called [deprecation id: common.async-computed]
     70 DEPRECATION: competency.treeChildren Computed Called [deprecation id: common.async-computed]
     61 DEPRECATION: curriculumInventoryReport.linkedCourses Computed Called [deprecation id: common.async-computed]
     54 DEPRECATION: curriculumInventoryReport._hasLinkedCourses Computed Called [deprecation id: common.async-computed]
     37 DEPRECATION: The `hash` helper was used in the `ilios/components/program-year/header.hbs` template as `@query={{hash}}`. This is ambigious between wanting the `@query` argument to be the `hash` helper itself, or the result of invoking the `hash` helper (current behavior). This implicit invocation behavior has been deprecated.
     35 DEPRECATION: cohort.school Computed Called [deprecation id: common.async-computed]
     32 DEPRECATION: curriculumInventoryReport.topLevelSequenceBlocks Computed Called [deprecation id: common.async-computed]
     30 DEPRECATION: curriculumInventoryReport.isFinalized called, check export attribute directly instead. [deprecation id: common.curriculum-inventory-report-is-finalized]
     26 DEPRECATION: cohort.program Computed Called [deprecation id: common.async-computed]
      8 DEPRECATION: The `noop` helper was used in the `ilios/components/my-profile.hbs` template as `@setIsManaging={{noop}}`. This is ambigious between wanting the `@setIsManaging` argument to be the `noop` helper itself, or the result of invoking the `noop` helper (current behavior). This implicit invocation behavior has been deprecated.
      6 DEPRECATION: curriculumInventorySequenceBlock.allParents Computed Called [deprecation id: common.async-computed]
      1 DEPRECATION: When calling `deprecate` you must provide `since` in options. Missing options.since in 
      1 DEPRECATION: When calling `deprecate` you must provide `for` in options. Missing options.for in 
      1 DEPRECATION: Using `computed.equal` has been deprecated. Instead, import the value directly from @ember/object/computed:
      1 DEPRECATION: Usage of the Ember Global is deprecated. You should import the Ember module or the specific API instead.
      1 DEPRECATION: `import { deprecate } from '@ember/application/deprecations';` has been deprecated, please update to `import { deprecate } from '@ember/debug';` [deprecation id: old-deprecate-method-paths]
      1 DEPRECATION: Ember Simple Auth: The automatic session initialization is deprecated. Please inject session service in your application route and call the setup method manually. [deprecation id: ember-simple-auth.initializer.setup-session-restoration]
      1 DEPRECATION: cohort.classOfYear Computed Called [deprecation id: common.async-computed]
```

eliminate as many as possible of these.

- [ ] DEPRECATION: competency.domain Computed Called [deprecation id: common.async-computed]
- [ ] DEPRECATION: cohort.rootLevelLearnerGroups Computed Called [deprecation id: common.async-computed]
- [ ] DEPRECATION: competency.treeChildren Computed Called [deprecation id: common.async-computed]
- [ ] DEPRECATION: curriculumInventoryReport.linkedCourses Computed Called [deprecation id: common.async-computed]
- [ ] DEPRECATION: curriculumInventoryReport._hasLinkedCourses Computed Called [deprecation id: common.async-computed]
- [x] DEPRECATION: The `hash` helper was used in the `ilios/components/program-year/header.hbs` template as `@query={{hash}}`. This is ambigious between wanting the `@query` argument to be the `hash` helper itself, or the result of invoking the `hash` helper (current behavior). This implicit invocation behavior has been deprecated.
- [ ] DEPRECATION: cohort.school Computed Called [deprecation id: common.async-computed]
- [ ] DEPRECATION: curriculumInventoryReport.topLevelSequenceBlocks Computed Called [deprecation id: common.async-computed]
- [ ] DEPRECATION: curriculumInventoryReport.isFinalized called, check export attribute directly instead. [deprecation id: common.curriculum-inventory-report-is-finalized]
- [ ] DEPRECATION: cohort.program Computed Called [deprecation id: common.async-computed]
- [x] DEPRECATION: The `noop` helper was used in the `ilios/components/my-profile.hbs` template as `@setIsManaging={{noop}}`. This is ambigious between wanting the `@setIsManaging` argument to be the `noop` helper itself, or the result of invoking the `noop` helper (current behavior). This implicit invocation behavior has been deprecated.
- [ ] DEPRECATION: curriculumInventorySequenceBlock.allParents Computed Called [deprecation id: common.async-computed]
- [x] ~~DEPRECATION: When calling `deprecate` you must provide `since` in options. Missing options.since in~~ comes from ember-simple-auth, outside of our control
- [x] ~~DEPRECATION: When calling `deprecate` you must provide `for` in options. Missing options.for in~~ comes from ember-simple-auth, outside of our control
- [x] ~~DEPRECATION: Using `computed.equal` has been deprecated. Instead, import the value directly from @ember/object/computed:~~ we don't use any CPs in frontend anymore.  fix this in common and those warnings will go away. 
- [x] ~~DEPRECATION: Usage of the Ember Global is deprecated. You should import the Ember module or the specific API instead.~~  comes from ember-simple-auth, outside of our control
- [x] ~~DEPRECATION: `import { deprecate } from '@ember/application/deprecations';` has been deprecated, please update to `import { deprecate } from '@ember/debug';` [deprecation id: old-deprecate-method-paths]~~  comes from ember-simple-auth, outside of our control
- [x] ~~DEPRECATION: Ember Simple Auth: The automatic session initialization is deprecated. Please inject session service in your application route and call the setup method manually. [deprecation id: ember-simple-auth.initializer.setup-session-restoration]~~ comes from ember-simple-auth, outside of our control
- [ ] DEPRECATION: cohort.classOfYear Computed Called [deprecation id: common.async-computed]

**Comment by jrjohnson** [comment]
Also ok to just add them to `config/deprecation-workflow.js` as silenced.

**Comment by stopfstedt** [comment]
i'm closing this meta ticket out - we can track and address the remaining deprecations individually since we don't get scrolling blind at this point anymore.
