### ISSUE TITLE
Trash can color consolidation

### ISSUE THREAD

**Issue by stopfstedt** [ilios/frontend#6392]
some of the trash can icons on delete buttons are red when active (programs list, learner groups lists), elsewhere they are standard blue.

settle on one color pattern here.

i'm going for blue here as it requires less code since it uses default application styles.

**Comment by jrjohnson** [comment]
I'd personally prefer that all delete trashcans be red, but I'm ok with this. Would like @saschaben and @dartajax to make the final call.
