### ISSUE TITLE
Courses List - Add New Button - move to filter-tools

### ISSUE THREAD

**Issue by jenzweben** [ilios/frontend#64]
Please move the Add New button to either the filter-tools div or above the table so that the table can utilize the full width detail-view

**Comment by saschaben** [comment]
This should probably be standardized across all page templates.

**Comment by jenzweben** [comment]
I've mocked it up for Learner Group Landing - working on Courses List mock now

**Comment by jenzweben** [comment]
Here's the new Courses List mock - it shows the scenario where a user has selected All Courses, School of Med, School of Nursing & School of Pharm for 2015

![course-list](https://cloud.githubusercontent.com/assets/5023894/6139859/a870a8c0-b145-11e4-9819-0d0c03df4a7a.png)

**Comment by jenzweben** [comment]
Here is the mock showing the scenario where a user has selected My Courses and only has access to one school - School of Medicine

![course-list-oneschool](https://cloud.githubusercontent.com/assets/5023894/6139960/d0dba264-b146-11e4-8a54-df49bbb6079c.png)

**Comment by saschaben** [comment]
comments/thoughts:  
1) If mulitple schools are selected in this case, should we show the dropdown with a single school ("medecine") rather than doing something else -- but, uselessly I have no suggestion at the moment....
2) Also, let's keep the color of the publish state labels in sync with course pages: not published = amber, scheduled = brown, published = green.

Otherwise, perfect.

**Comment by jenzweben** [comment]
Scenario:  All Courses, 3 Schools Selected (Medicine, Nursing & Pharma)
![course-list](https://cloud.githubusercontent.com/assets/5023894/6140068/36ff161a-b148-11e4-8d50-d00c7482cf54.png)

Scenario:  My Courses - only have access to 1 School (Med)
![course-list-oneschool](https://cloud.githubusercontent.com/assets/5023894/6140075/492d9df2-b148-11e4-9fd9-62e2308e491c.png)

**Comment by jrjohnson** [comment]
Can we go ahead and mock the school selector as a set of checkboxes?  Thats how we're going to need to code it.  If we come up with a better widget we can just replace.  We might even want to go with monkey buttons for lists of less than three (most common) and checkboxes if the count is above that.

**Comment by saschaben** [comment]
@jrjohnson @jenzweben let's do one with checkboxes then, for expediency, and put "finding a better selection widget for course list" on the future to do list for after thursday. Until we wrestle thru the issue of how to address (an unspecified number of) monkey buttons with labels of unknown possible length in a constrained space, I think we can leave off a rendering for that possibility.

**Comment by jenzweben** [comment]
monkey button grid?

![course-list-monkey](https://cloud.githubusercontent.com/assets/5023894/6152177/ff1942d8-b1cf-11e4-9488-ab2f8b0ff225.png)

**Comment by saschaben** [comment]
realtes to #42

**Comment by thecoolestguy** [comment]
putting this button in the 'filter-tools' section did not support the mock... Had to change grouplist structure entirely, see #118

**Comment by thecoolestguy** [comment]
fixed in 118
