### ISSUE TITLE
Multi-day offerings revert to single day on edit

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#642]
add a new multi-day offering:

![off1](https://cloud.githubusercontent.com/assets/1753431/7947081/b5dd4e72-092f-11e5-8cf7-611f36901a81.png)

edit it in any way (here adding a location), and save:

![off2](https://cloud.githubusercontent.com/assets/1753431/7947109/e0b5520c-092f-11e5-8af7-ea35729cba0e.png)

and it reverts to a single day event for the start day. note also the alignment issues.....

**Comment by jrjohnson** [comment]
Possible note: this might have been caused by #634

**Comment by saschaben** [comment]
I believe this has been corrected with the work done on #634 and #697; if so, this should be closed.

**Comment by saschaben** [comment]
closing
