### ISSUE TITLE
Add Instructor Group Save / Cancel Buttons Missing

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#644]
I noticed that I was trying to add a new instructor group and the Title field appears for the data entry but there are no buttons with which to process or cancel the Save Event.

**Comment by dartajax** [comment]
These buttons were placed on add Student Group but were overlooked it seems with add Instructor Group.

**Comment by jrjohnson** [comment]
This is almost certainly because they are missing the ```text``` class.

**Comment by jenzweben** [comment]
This might be an alignment issue now...
![screen shot 2015-06-08 at 10 55 31 am](https://cloud.githubusercontent.com/assets/5023894/8041426/ee9e9cce-0dcc-11e5-83b0-8a5f66633921.png)

I will take a look to see if it's css-related...

**Comment by saschaben** [comment]
not missing, just improperly sized. please adjust template/class.
