### ISSUE TITLE
Provide Padding for Program Leadership

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#6595]
Here is how it is ...

![image](https://user-images.githubusercontent.com/7493331/109885231-02f94900-7c33-11eb-960f-76130c12b409.png)

It might look better to line the "Program Leadership" caption up with the "Back to Programs" link. It would look more like this ...

![image](https://user-images.githubusercontent.com/7493331/109885574-95015180-7c33-11eb-8504-1e810b2c8da6.png)

**Comment by mhgh22** [comment]
There is more padding for "Program Leadership" and it is aligned with "Program Title". We think it looks better in the current format. -MNS @dartajax

![Screenshot 2022-04-18 at 11-55-17 Ilios Programs](https://user-images.githubusercontent.com/103135575/163861740-c56a2af2-c12b-40b5-926b-5ea2802b738e.png)

**Comment by dartajax** [comment]
Fair enough - I will close.
