### ISSUE TITLE
learner group delete buttons require correction in styling

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#667]
Text for the "yes" button doesn't appear; non-hover outline state doesn't appear for same.

![image](https://cloud.githubusercontent.com/assets/1753431/8012700/445859c2-0b78-11e5-8054-0e44b93eeeaf.png)

**Comment by jrjohnson** [comment]
Weirdly I think this is browser specific.  What is your screen shot from?

**Comment by saschaben** [comment]
taken from chrome. but same in ff and safari:

![3screen](https://cloud.githubusercontent.com/assets/1753431/8013768/60806d12-0b80-11e5-8e3f-c6f36e0dd578.png)

**Comment by jrjohnson** [comment]
Ah.  I just figured out that I was looking in a completely different place.  The learner group list.  Should be the subgroup list.  No mysterious browser difference after all.
