### ISSUE TITLE
uneven padding for dashboard menu buttons

### ISSUE THREAD

**Issue by mhgh22** [ilios/frontend#6675]
Padding is uneven for dashboard menu buttons(see: Weekly at a Glance)

![Screenshot 2022-05-20 at 12-55-12 Ilios Dashboard](https://user-images.githubusercontent.com/103135575/169602774-9ee74cb0-838d-4b91-8826-8b9284dc464a.png)

-Michael

**Comment by mhgh22** [comment]
Hello Stefan. When I created the ticket, I was actually referring to the uneven padding above/below the buttons. I'm probably not looking at the latest version(6679), so I might not be seeing all the changes. FYI.

-Michael

**Comment by jrjohnson** [comment]
Best place to see the latest is at https://ilios-frontend.netlify.app the distance isn't equal, but I hope it's aesthetically more pleasing now.
