### ISSUE TITLE
Hide Header in Learner Group Management if No Members in Group

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#6768]
The screen shot below illustrates this. To duplicate, find a learner group with no members and possibly with populated sub groups.

![image](https://user-images.githubusercontent.com/7493331/176261980-6f3c2779-c97f-43c5-9e19-e9d749c3cd8c.png)

Here is a wider shot.

The header might be applicable for the sub groups but not for the higher level group with zero members.

![image](https://user-images.githubusercontent.com/7493331/176263773-6a898d24-eaac-4327-b017-9a6e1d0b441e.png)

**Comment by stopfstedt** [comment]
the table header applies to both the "members in groups" list as well as the "all other members" list.
