### ISSUE TITLE
Edit title alignment on instructor groups

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#677]
When the inline-editing is opened for the title of a learner or instructor group the alignment of the header is messed up.

![5e33d2fe-0dc1-11e5-9b93-6c8d4d8a3616](https://cloud.githubusercontent.com/assets/349624/8040171/29fa5ac4-0dc3-11e5-93f0-b1050772b28f.png)

**Comment by saschaben** [comment]
this now only impacts instructor group headers.
