### ISSUE TITLE
Match template structure for 'Add New' for Sessions and Courses

### ISSUE THREAD

**Issue by thecoolestguy** [ilios/frontend#683]
The styling for adding a new course is correct, with padding around the containing box for the form fields, but the styling for 'Add new Session' is incorrect and it looks like it is being caused by some structural differences in the template further up the chain (ie, 'add new session' styling contains a 'detail-view' class higher up in the scaffolding, where sessions does not).  These two should match so their styling will also.

**Comment by jenzweben** [comment]
Here are some screenshots to hopefully help clarify:

Add New Course
![screen shot 2015-06-08 at 1 47 28 pm](https://cloud.githubusercontent.com/assets/5023894/8045037/7839d058-0de5-11e5-9f72-dfe11d4ff9ca.png)



Add New Session
![screen shot 2015-06-08 at 1 50 42 pm](https://cloud.githubusercontent.com/assets/5023894/8045027/6bb16b84-0de5-11e5-9589-30186739fd98.png)

**Comment by jrjohnson** [comment]
This is a grid issue that we're not going to fix right now.  It has to do with the way nested grids change the width of each column by a percentage.  The right choice is probably to use a different grid system.
