### ISSUE TITLE
Add File functions

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#685]
We have a 2-step archiving control, which allows for management of historical data for both users and analytics.

Archiving is available for COURSE, PROGRAM, PROGRAM YEAR

LOCK: the LOCK archive function sets the item to read only view for all users. No impact on search or reports.
FILE: the FILE archive function removes the item from UI display for active searches and lists, but NOT from reports or the calendar.

Archiving never deletes an item.

**Comment by saschaben** [comment]
This requires the addition of UI access for `DEVELOPER` users; should be added to the action icons on the COURSE, PROGRAM, and PROGRAM YEAR list pages.

**Comment by saschaben** [comment]
Icons to use are `fa-lock`/`fa-unlock`, and `fa-sign-in`

**Comment by jrjohnson** [comment]
I ran into an issue here.  Locked courses cannot be edited.  That permission is enforced by the API.  In order to be able to unlock locked courses we will need to create a new special endpoint for this single purpose which can then apply special permission to handle this one task.

**Comment by saschaben** [comment]
If need be we can just disallow the unlocking of courses universally until we address the API permissions issues. v2 only allowed one-way locking anyway, since we never implemented a superuser role, and we don't want people to easily be able to unlock closed courses....

**Comment by jrjohnson** [comment]
Ah, ok - I will proceed with that path and we can add unlock in at a later date.

**Comment by saschaben** [comment]
After discussion, it ahs been determined that the new UI obviates the need for the File/Archive function; we will implement lock and look to deprecate the archive feature in the near future.

**Comment by saschaben** [comment]
Closing this ticket in favor of #2153.
