### ISSUE TITLE
Concatenate Learner Groups Lower Level Label

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#688]
Please review the ugly mock shown below - the change is in the label that reads in the ugly mock "Class of 2018 Learner Groups" -- the "Class of 2018" was pre-pended to the label in order to provide more information to indicate which Cohort is being modified with the Learner Groups assignment.  Maybe we could use this same technique in Instructor Groups as well.

![lg](https://cloud.githubusercontent.com/assets/7493331/8047579/31b46b04-0dfc-11e5-9aff-1ea0f307d92d.JPG)

**Comment by jrjohnson** [comment]
Then wouldn't it need to say School of Medicine Doctor of Medicine Class of 2018?  Since all of those filters are also being applied?

Or Would it make more sense to put this information into the create new group form?

**Comment by dartajax** [comment]
The point was that we have the Learner Groups label up at the top and then we have it down below.  It was pointed out that we should provide more detail with the lower label.  Just the name of the Cohort as I put in my crappy mock is what was suggested but maybe the full name with school and program and program year might be better.
