### ISSUE TITLE
Filter users in Learner Group Assignment Form

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#689]
There should be a search field available for when a user wishes to search for a specific user who needs to be moved to a different sub group.  I apologize for the ugly mock.  I just wanted to demonstrate which part of the screen might need a search field.

![lgsrch](https://cloud.githubusercontent.com/assets/7493331/8047669/3f51c378-0dfd-11e5-8848-921099ae42bd.JPG)

Do we also need a search field available at the sub group level?

![lgtop](https://cloud.githubusercontent.com/assets/7493331/8047741/e435a666-0dfd-11e5-9e39-22561e82b1b7.JPG)

**Comment by jrjohnson** [comment]
Since the data is already on screen these will be filters.  @jenzweben - can you weigh in on style / location of the filter input element?

**Comment by jenzweben** [comment]
@saschaben & @dartajax is the most common use case that the user would want to search from the group or subgroup page or would it make more sense to have a search at the learner group list level?

**Comment by saschaben** [comment]
@jenzweben I think the most common use case will be a search from the group page that impacts all data on the page: so a search would not be just the current group members list (at the top of the page), or just the Learner Assignments list (in the middle of the page), or the "not in this group" list at the bottom of the page, but all three at once. Example: Sally Psychometry is a 1st year student, and calls the help desk saying her calendar is not displaying her classes. I know Sally is a member of the Class of 2018 East group with 90 members, so I search there -- but she doesn't show up as a member. She does, however, appear in the East/West Learner Assignments list. Aha! she is in the wrong group! I switch her, and all is well.

**Comment by jrjohnson** [comment]
We can put the filter box in all three places and make it so what you type in one shows up in all of them and filters everyone in all the sections.  (we don't have to do this, I'm just saying its easily doable)
