### ISSUE TITLE
Auto Generate New Learner Sub Groups

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#690]
There needs to be the functionality on the Learner Groups page where the user can click Add New (for 1 new sub group) and the name automatically is generated with the following naming convention ...

[Parent Group Name][Maximum Sub Group # + 1]

In other words, in you were creating a sub group inside Anatomy (and there already exist Anatomy 1 and Anatomy 2), your new group would automatically be named Anatomy 3 and this name would appear in the title field for the save event to be performed.

Also, it would be helpful if there were a drop-down menu where the user could specify the quantity of sub-groups to be created automatically.  Maybe we should have 1 be default and the user could change it.  

The names would be generated using the same logic.  If 4 New Sub Groups were to be created - assuming we just created Anatomy 3, the following four groups would be generated.

Anatomy 4
Anatomy 5
Anatomy 6
Anatomy 7

**Comment by jrjohnson** [comment]
What is the group called if there are sub groups named:

- anatomy with mike
- sam's lab

I assume it would still be called Anatomy 3?

**Comment by dartajax** [comment]
Yes.  If the other sub groups have been renamed (originally they were Anatomy 1 and Anatomy 2 and you do another new top level sub group, it would be called Anatomy 3 (until they change it to sam's club lab or whatever)

**Comment by saschaben** [comment]
@jrjohnson that is correct: the naming seed is always the current top level (or "LevelAboveCurrentLevel") name. So creating subs from Anatomy would give

Anatomy 1
Anatomy 2
Anatomy 3
Anatomy 4....

And creating subs from Anatomy 4 would create

Anatomy 4  1
Anatomy 4  2
Anatomy 4  3
Anatomy 4  4

And if you change Anatomy 3 to Oogie, and Anatomy 4 to Boogie, but Anatomy (top level remains unchanged) the next sub group created would have a default name value of....Anatomy 5.

**Comment by saschaben** [comment]
rules for creation:
1. sub-groups can be generated without members, OR with randomized populations from the parent group:
  a) "create XX groups" -- creates specified number of groups as empty containers, regardless of the parent group population. XX must be >0
  b) "create groups of XX learners" -- creates a set of groups populated by the members of the parent group, each containing no more than  the # of learners specified. XX must be >0
2. sub-group names follow the convention above.
3. for 1(b), randomization should use a truly randomizing function, not alpha or by id, or any other similar fudge.
