### ISSUE TITLE
Course Title Should Not Be Editable By Everybody (More Granular Permissions Needed)

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#694]
Currently, anybody logged in to the application can click on a Course's title and change it.  It has been pointed out that this box almost looks like a search box and some users might think they are searching for something when in fact they are changing the course's title (which is rarely done and should be done only by a few limited super users or the person who created the course).

**Comment by dartajax** [comment]
Valentina reiterated this one with me today.  She feels that basically no one should be able to edit a Course's title.

**Comment by saschaben** [comment]
part of permissions overhaul. cf. #986

**Comment by jrjohnson** [comment]
Will address with large permissions overhaul.
