### ISSUE TITLE
Add the offerings Small Group Generator

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#697]
We can't let the ball drop on this: implement the tool which allows the option of creating a collection of offerings, driven by the list of groups selected.

https://www.dropbox.com/work/usability?preview=SmallGroupGenerator.png

This includes modifying the "Add Offering" button to be a drop down, with the options of "Add a Single Offering" and "Add Multiple Offerings (small groups)"

**Comment by dartajax** [comment]
This one is very important to Valentina and will be helpful in our upcoming training sessions since people do use this functionality regularly.
