### ISSUE TITLE
modify language file label for learner group display

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#698]
This doesn't appear to have actually been addressed prior to closing and merging of #662:

app/translations/en.js lines 162-3 should be changed from 

```'topGroupMembersNotInGroup': '{{groupTitle}} Members NOT in this group',```
```'subGroupMembersNotInGroup': '{{groupTitle}} Members NOT in this Subgroup',```

 to 

``` 'topGroupMembersNotInGroup': '{{groupTitle}} Learner Assignments',```
```'subGroupMembersNotInGroup': '{{groupTitle}} Learner Assignments',```

**Comment by dartajax** [comment]
Can I work on this very simple fix?
