### ISSUE TITLE
Check for existing objectives before displaying session objective header

### ISSUE THREAD

**Issue by thecoolestguy** [ilios/frontend#701]
When there are no objectives for a session, the objective header still shows.  If there are no objectives, the header should not be displayed.

**Comment by jrjohnson** [comment]
<img width="1094" alt="screen shot 2016-10-11 at 11 10 10 am" src="https://cloud.githubusercontent.com/assets/349624/19282451/4d76ee32-8fa3-11e6-8088-4b6f6a9b280d.png">
