### ISSUE TITLE
Provide smoother animation of Show/Hide Details in Course

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#705]
A smoother accordion animation for the open/close action of the show/hide details tab in the course overview is needed for user experience. Right now it pretty much just flashes from one state to the other.

**Comment by thecoolestguy** [comment]
Some notes on this here:

https://css-tricks.com/snippets/jquery/smooth-scrolling/

Demo here:

https://css-tricks.com/examples/SmoothPageScroll/

Related to #597

**Comment by saschaben** [comment]
smoove!

**Comment by jrjohnson** [comment]
This animation no longer exists. Closing.
