### ISSUE TITLE
Provide "hide details" link at top of course page when Course Overview details are open

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#706]
pretty much as the title says. Possible location is as a up-facing tab on the dividing line where the "show details (downfacing) tab displays....

**Comment by jenzweben** [comment]
I think we need to clean up the implementation of "Hide Detail" at the bottom of the page so I mocked that up as well.

![hide-details-top](https://cloud.githubusercontent.com/assets/5023894/8382753/ddb08c58-1be9-11e5-96ad-a58540c0f74d.png)
![hide-details](https://cloud.githubusercontent.com/assets/5023894/8382754/ddb3be50-1be9-11e5-964c-9afd95b0e24e.png)

**Comment by saschaben** [comment]
well, they disliked the tab, so maybe something like this?

![ilios 2015-11-10 17-24-43](https://cloud.githubusercontent.com/assets/1753431/11081335/83908bbc-87d0-11e5-9877-b7f645be94cc.png)

**Comment by saschaben** [comment]
Or rather than a windowshade or text link, let's consider providing a "hide details/collapse" icon which only displays when details are expanded.


![closeit](https://cloud.githubusercontent.com/assets/1753431/16594073/6f515d24-429d-11e6-9c42-b864d8d58ea3.png)
