### ISSUE TITLE
Add Not found page for frontend

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#709]
When you visit on route that doesn't exist you get the browser unsupported error instead of a 404 page.  We need to add a route that will act as a 404 / Not Found page on the frontend.

```this.route("fourOhFour", { path: "*path"});``` will catch all requests so we just need a template that displays a nice message.

**Comment by saschaben** [comment]
How about the message 

"Rats! I couldn't find that. Please check your page address, and try again."

in a nice 1.5em display?
