### ISSUE TITLE
render message for older browsers

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#71]
In older browsers our site doesn't render at all.  We need to do some detection and display a nice error message instead of a white screen.

@jenzweben - can you design this screen?  It shouldn't depend on any of our existing content (header, navigation, footer) and be completely self contained like the login / landing page.

**Comment by jenzweben** [comment]
The login / splash pages have our header...not sure what you mean by "It shouldn't depend on any of our existing content..."

**Comment by jrjohnson** [comment]
Sorry, typed that fast.  A lot of our page is rendered in javascript including some of the header and all of the navigation.  Since JS will have failed in this case we need to have really simple static content on the screen.  If it needs to have a header it can, we can just reproduce the html outside of JS, but every element on the page will be a little bit of extra work to maintain as a on-standard piece of our site.

**Comment by jenzweben** [comment]
Here's what I recommend - (obviously, you'll need to specify which browsers are required)

![old-browser-message](https://cloud.githubusercontent.com/assets/5023894/6152632/9293bc3e-b1d3-11e4-9d5b-5964c33348c4.png)
