### ISSUE TITLE
Create a survey link in the footer

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#723]
In order to solicit feedback lets add a survey link to the application.
[sample survey](https://ucsf.co1.qualtrics.com/SE/?SID=SV_blJdoMAlWS75rGR&Preview=Survey&Q_CHL=preview&BrandID=ucsf)

The link could be gold stars and text 

Rate Ilios \* \* \* \* *

**Comment by dartajax** [comment]
We are going to do this I believe.

**Comment by saschaben** [comment]
rejected.
