### ISSUE TITLE
Change to Scheduled Status without Offering Should Not Be allowed

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#725]
There should be no circumstance where a session should be set to "scheduled" if there is no offering.  There wouldn't be anything to put on the calendar with "TBA" anyway.  It may not be a big deal; but this is how it is with 2.4.x Ilios.  You can't override (or not override) if there is no offering attached to the session.

**Comment by saschaben** [comment]
@dartajax is correct on this.

For future discussion, we should look at loosening up this publish process, now that the function is so much better exposed to the users. The current strict model may not need to stay "quite" as strict as we move forward....

**Comment by jrjohnson** [comment]
This is a valid state even though it is kind of weird.
