### ISSUE TITLE
Attempt to save instructor to ILM throws TWO 500 errors

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#733]
one for POST, one for PUT.
![ilios 2015-06-22 10-40-37](https://cloud.githubusercontent.com/assets/1753431/8288478/441507a2-18cb-11e5-918d-83df74c55c86.png)

**Comment by dartajax** [comment]
![addtoilm](https://cloud.githubusercontent.com/assets/7493331/9075507/7c98406e-3aca-11e5-82aa-ac001ebc6422.JPG)

**Comment by dartajax** [comment]
I was able to save without the errors Sascha reported though.
