### ISSUE TITLE
Redundant Instructor Label on Session Offerings

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#737]
Refs PR #728 

![branchtestinstructors](https://cloud.githubusercontent.com/assets/7493331/8292854/a345ee56-18e6-11e5-81e0-3b860238095e.JPG)

**Comment by dartajax** [comment]
However, check this out ...

Select a Session Offering with no Instructors yet ...

![branchtestnoinstructorsyet](https://cloud.githubusercontent.com/assets/7493331/8293326/8b6ca86c-18e9-11e5-9554-8b1b2db666c9.JPG)

No extra Instructor label yet ...

![branchtestnoextralabel](https://cloud.githubusercontent.com/assets/7493331/8293346/acb4bbfe-18e9-11e5-96fe-bd82dd5eec92.JPG)

![branchtestgrabinstructor](https://cloud.githubusercontent.com/assets/7493331/8293386/ee16d618-18e9-11e5-9a51-4267d7a43e44.JPG)

![branchtestgrabinstructor2](https://cloud.githubusercontent.com/assets/7493331/8293391/f785472a-18e9-11e5-8544-1a75da07694c.jpg)

After selecting the Instructor but actually before clicking Done ...

![braanchtestlabelsback](https://cloud.githubusercontent.com/assets/7493331/8293395/fdf7b962-18e9-11e5-827d-68321447df90.JPG)

**Comment by saschaben** [comment]
I think this is meant to allow differentiation between individuals and groups --- but it is unnecessary as noted. here's what we have now:

![instgroups1](https://cloud.githubusercontent.com/assets/1753431/8340467/9262c814-1a73-11e5-849d-b7942ff32db6.png)

and here is what we should have:

![instgroups2](https://cloud.githubusercontent.com/assets/1753431/8340612/7d5374e0-1a74-11e5-95fe-c7edf56e75a1.png)

**Comment by saschaben** [comment]
closed by #1311 and  #1869
