### ISSUE TITLE
Learner Group > Sub-Group table header and messaging should vanish when no subgroups are present

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#740]
See screen shot with comments below ...

It seems like we went to all the trouble to explain there are no sub-groups, we just should just hide the grid, non?  and shrink the section as well.

![confusion](https://cloud.githubusercontent.com/assets/7493331/8295593/1ec8ada2-18fb-11e5-9d26-6b6c4aa523c9.JPG)

**Comment by saschaben** [comment]
not only confusing, but doesn't follow the UI pattern we've taken up everywhere else. Chaging the title of this issue to reflect that.
