### ISSUE TITLE
Ability to Remove Course-Level Parent Objective Is Missing 

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#744]
This is true at the Course level only.  Once a Parent Objective is selected, another Parent Objective can be selected; but there is no way to remove a Parent Objective from a Course Objective.  We should have a way to do this.

Refs #450 

The use of the check boxes in Parent Objectives for Sessions (since more than one can be selected) ensures that a Parent Objective for a Session can indeed be removed.

**Comment by jrjohnson** [comment]
@dartajax this works fine for me.  Click on the selected objective and it is removed.  Are you seeing something different i another browser?

**Comment by saschaben** [comment]
not sure why this was re-opened; it appears to be working correctly (click the selected parent, it unselects). can we close it again?

**Comment by jrjohnson** [comment]
Nope, looks like it works, maybe re-opened on accident, or maybe just got fixed in the mean time.
