### ISSUE TITLE
Back to Courses List Doesn't Automatically Choose the Correct Course Year

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#745]
To duplicate ...

I know this is a weird one and probably not all that critical at all but I found it to be interesting and worth discussing .. albeit briefly maybe.

* We are in the year 2014-15, click Add New to add a new Course ...

![wrongyear1](https://cloud.githubusercontent.com/assets/7493331/8360862/5efc98ea-1b24-11e5-962d-cf25e8cd68e1.JPG)

* Enter the Course Name and even though we were in 2014-15, choose 2013-14 as the year (from the drop-down)

![wrongyear2](https://cloud.githubusercontent.com/assets/7493331/8360884/82ededf8-1b24-11e5-84d3-003c67d6ef86.JPG)

* Process the change by clicking Done

![wrongyear3](https://cloud.githubusercontent.com/assets/7493331/8360916/aae78620-1b24-11e5-8c85-1dd12e7b0305.JPG)

* Notice the year at the top indicates 2014-15.  Follow the link to review the course that was just entered

![wrongyear4](https://cloud.githubusercontent.com/assets/7493331/8360933/c0463f0c-1b24-11e5-831a-3b4240038afd.JPG)

* Now we are reviewing the Course that was just entered and it is clear that it is a 2013-14 Course.
* Click the Back to Courses link

![wrongyear5](https://cloud.githubusercontent.com/assets/7493331/8360950/e6c66fc6-1b24-11e5-8a54-bf03308c7f0e.JPG)

* We are now back to 2014-15 (which we never left anyway) but the Back to the Courses link should take the user back to the year they were manipulating, non?  It also seems strange that we are in a particular year and can pick a different year for the Course.  Maybe the Year drop-down doesn't need to be there for adding a Course because the year is already selected up at the top of the screen.  Essentially there are two year pickers.  Is that what we want?

![wrongyear6](https://cloud.githubusercontent.com/assets/7493331/8360981/1be5c724-1b25-11e5-8496-fd18b69611a0.JPG)

**Comment by jrjohnson** [comment]
I think this is exactly the behavior we want.  A user can create a course in any year and when they return to the list they are in the year that they left.  The other alternative would be 
1.  requiring the user to choose the year they wished to edit and then add the course.
2.  When the user goes back to the courses list placing them in a year they never selected.
