### ISSUE TITLE
Add Reports Generation tools component to Dashboard

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#747]
The new rendition of "My Reports". Please see #206 for additional details.

**Comment by thecoolestguy** [comment]
Can I get a french translation for "Associated to the" in the context of the reports. (ie, 'Session associated to the Course', etc)

**Comment by saschaben** [comment]
It's "associés à des", but since the objects are variably masculine or feminine  the grammar will be crap for this 50% of the time. The above is the masculine. If we want to err on the side of feminine, it's " associés à des".

Your choice.

**Comment by saschaben** [comment]
I mean associées à des is fem. ...

**Comment by saschaben** [comment]
for reports that have been generated, we want to output (for now) lists:

![myreportsoutput](https://cloud.githubusercontent.com/assets/1753431/11047623/6456feae-86e8-11e5-81ec-eb278cdd4cf7.png)

Forgive the brilliant design skillz there.
