### ISSUE TITLE
Add Courses list to Dashboard

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#749]
See #206 for details.

**Comment by jrjohnson** [comment]
Which courses appear in the list?  
- Everything from all of time?
- Courses where the current date is between the course start / end dates?
- Courses which start within the next few weeks?

Should courses be listed alphabetically or in order of start date?

Is Level something we actually need on this display, or is it just taking up space?

**Comment by saschaben** [comment]
Course list should provide all non-archived, non-locked courses to which the user is associated. Display should include title and year. List should be chronological.

We will probably want to eventually provide sort options and the ability to extend the to include archived info, but for now that isn't needed.

If there are no courses (I guess maybe a non-teaching faculty, or previous student), it doesn't need to appear.
