### ISSUE TITLE
Calendar Event Details needs fillout

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#759]
Calendar detail event view requires full display matching current view.

**Comment by jrjohnson** [comment]
@saschaben event detail course/session objectives are nested under the program year competency and domain.  What should this value be be when an objective has multiple parents from different program years?  I'm hoping we can do the school the course is in, but I'm guessing we need to base it on the cohort for the learner which is harder though not impossible.

**Comment by saschaben** [comment]
shwew. Yeah, this should probably be based on the cohort of the viewer for related events -- but that doesn't address the case of a user viewing an event that is not associated to them....

For the moment, we can cheat a little I think, since the current model allows for each objective to appear in multiple parent objective/competency buckets; let's just display ALL parents as grouping categories, regardless of program/school. So for  a course with one program parent:

_competency domain ABC_ (MD)
 
  **objective 1**
   **objective 2**
   **objective 3**

_competency domain DEF_ (MD)

  **objective 2**
   **objective 3**

_competency domain GHI_ (MD)

   **objective 4**

...and with muliple parents:

_competency domain ABC_ (MD)
 
  **objective 1**
   **objective 2**
   **objective 3**

_competency domain DEF_ (MD)

  **objective 2**
   **objective 3**

_competency domain GHI_ (MD)

   **objective 4**

_competency domain 123_ (PharmD)

   **objective 4**

_competency domain 456_ (PharmD)
 
  **objective 1**
   **objective 2**
   **objective 3**

_competency domain 789_ (PharmD)

   **objective 2**
   **objective 3**

This may give too much info for students in the cases where we have mulltiple parented courses, but that is the exception (for now) and I think we have time therefore to address this as an enhancement.
