### ISSUE TITLE
Learner Groups page - Add New btn location and need to add "School:" before "Medecine"

### ISSUE THREAD

**Issue by jenzweben** [ilios/frontend#76]
Add "Add New" button to Learner Groups page
I have it to the right of the table in the mockup but it might be better if we move it to the header so that the table can be full width...

![image](https://cloud.githubusercontent.com/assets/5023894/6138299/bdf9b274-b134-11e4-9675-c726e44b129e.png)

**Comment by jrjohnson** [comment]
@jenzweben please do a new mockup for this first so @saschaben can make a choice.

**Comment by jenzweben** [comment]
![learner-groups-landing-v7](https://cloud.githubusercontent.com/assets/5023894/6138632/a10a4c8e-b137-11e4-9b3f-735a5f1c1784.png)

**Comment by thecoolestguy** [comment]
fixed in merge #127
