### ISSUE TITLE
Add User Functionality Needs to Be Implemented

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#763]
Currently this occurs when a Search for a User in the Admin Console doesn't find the user.  Then, a new user account can be created.

First Name, Middle (optional), Last Name, Campus ID and Email Address are entered here.

Developer Privileges, Set as Director, Set as Instructor check boxes are available to set these options.

**Comment by dartajax** [comment]
I am not sure if this should be a new ticket or not but frequently Course Coordinators need to add Instructors manually though the interface.  We don't have this functionality available yet. I am going to ask Valentina about how often (1 out of x times) this happens.

**Comment by dartajax** [comment]
refers to #684

**Comment by dartajax** [comment]
refers also to #765

**Comment by saschaben** [comment]
closing in favor of #684
