### ISSUE TITLE
Admin Panel: Classify User Functionality Needs To Be Added

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#764]
This includes the following ...

* Search for one or more users whose records need maintenance.
* Assign them to the their Primary Cohort (if not done already)
* Assign them to one or more Secondary Cohorts or Secondary School.
* Disable the account
* Set them as "Instructor", "Director", or with Developer Privileges
* Designate them as a former student
* Exclude them from any synchronization that may take place.

**Comment by dartajax** [comment]
I may have forgotten that we should be able to modify Campus ID and email here as well, no?

**Comment by dartajax** [comment]
Refers to #684

**Comment by saschaben** [comment]
closing in favor of #684.
