### ISSUE TITLE
Add New Members to Cohort via Direct Entry or Spreadsheet .csv Upload

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#765]
In Learner Group Management, there is a button "Add New Members to Cohort".  This button opens up a pop-up form which can be used to either ...

1. Enter manually a new user directly into that cohort - using the following fields ... 

Last Name *
First Name *
Middle 
Phone 
Email *
Campus ID *
Other ID

The fields marked with * are required fields for manual entry.  

If the .csv route is chosen, a comma-delimited file which accounts for all of the fields can be uploaded.

**Comment by dartajax** [comment]
Related to #684 -- this is the first of the seven tickets which will end up closing that ticket once all seven have been addressed.

**Comment by saschaben** [comment]
closing in favor of #684.
