### ISSUE TITLE
Switch 'courseTitle' with 'title'?

### ISSUE THREAD

**Issue by thecoolestguy** [ilios/frontend#770]
The 'courses.courseTitle' key correlates to 'Course' on line 161, while the 'courses.title' key correlates to 'Course'... Maybe we should swap these?

|commit|file reference|pull request|   |
|------|--------------|------------|---|
|d64efda71937697f77c959d81fb11bc7f2d3bc57|[app/locales/en/translations.js#L161](https://github.com/ilios/frontend/blob/d64efda71937697f77c959d81fb11bc7f2d3bc57/app/locales/en/translations.js#L161)| #769 |[![#769](http://app.review.ninja/assets/images/icon-alt-36.png)](http://app.review.ninja/ilios/frontend/pull/769)|

**Comment by saschaben** [comment]
is this still an issue? if not, please close. thx.
