### ISSUE TITLE
Logout Users when they close their browser

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#779]
Currently because we store our authentication token in LocalStorage users stay logged in until the intentionally logout.  Closing the browser window should cause a logout.

The easiest path is to store the token in a cookie instead of LocalStorage and to set the cookie to expire at the end of the session.

Looks like we can do this with a simple config change, will need to investigate further to ensure this is compatible with our JWT solution:
https://github.com/simplabs/ember-simple-auth/tree/master/packages/ember-simple-auth-cookie-store

**Comment by saschaben** [comment]
This includes switching of permissions from one value to another  (see #1072)

**Comment by saschaben** [comment]
I am suspecting that this is actually having an impact on usability in a number of areas. escalating.

**Comment by jrjohnson** [comment]
This was resolved for the app in #1289 - but it is entirely possible that we are having authentication issues with the embedded app since there is no logout option there.
