### ISSUE TITLE
increase slider toggle width to allow for translations

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#782]
in some areas, notably show/hide calendar for offerings, the toggle does not provide enough space for non-english labels. We should provide for this, by one of the following methods (or something similar)
1. increasing the width of this toggle control generically;
2. remove the word "calendar" and replace with the icon fa-calendar;
3. find a means of dynamically changing the width according to the contents of the slider.

I don't expect this to be a major issue with the toggle in other areas (like my courses) which are far less impacted.

**Comment by dartajax** [comment]
I guess we could shorten some of our translations if need be as well, non?

**Comment by dartajax** [comment]
Or, we could abbreviate and then use the -Alt attribute to display the full text if it gets truncated.  Or just make them bigger by 30% - I think we have the room.

**Comment by dartajax** [comment]
This can be closed as well I think but I can't find the PR or issue that corresponds with switching the toggles to buttons.

**Comment by dartajax** [comment]
Refer to #3099 which will replace this one -- obsolete.
