### ISSUE TITLE
Ilios Calendar Doesn't Display Properly on iPad or Smart Phone

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#786]
I checked out an iPad from the Library and tested the calendar.  It doesn't display properly.

On the left side, there is a listing of the days of the week ...

Sun 7/19
Mon 7/20
Tue 7/21
Wed 7/22
Thu 7/23
Fri 7/24
Sat 7/25

And below that listing and over on the right side of the screen appears the listing of the times of day starting with 12:00am

                                                                                                                                                    12:00 am
                                                                                                                                                     1:00 am

and so on ..

**Comment by dartajax** [comment]
The appearance issues occur when using Safari on a regular sized computer as well.  Safari is rendering the calendar in a strange manner.  This occurs on Chrome as well on the iPad but only on Safari using a Mac or PC.

**Comment by saschaben** [comment]
While it is not confirmed, I believe this is just the same issue with flexbox identified as a bug in ebryn's calendar code. at the simplest level, we need to use correct and complete flexbox syntax for all style declarations.
