### ISSUE TITLE
Course Short ID (External ID) Should be Displayed in Calendar Mouse-Over Call Out

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#787]
This was requested by Pharmacy.  It would be helpful if the External ID for the Course was visible when the user mouses over a calendar item (offering).  They would like to be able to quickly see which course is attached to that offering.

![calendarcallout](https://cloud.githubusercontent.com/assets/7493331/8790351/cabd6ba4-2f01-11e5-8523-ae20e88e3008.JPG)

**Comment by saschaben** [comment]
we currently display full course name in day and week view, but not month. this needs to be fixed. When doing so, we should ADD the external ID value as well as a prepend for the course name ("COURSE: IDS 122.5 - Adventures in Pharmaceutical Experimentation"

**Comment by stopfstedt** [comment]
moved to ilios/calendar/#94
