### ISSUE TITLE
Publish All / Publish All (as is) Functionality Missing From Courses And Sessions

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#797]
In the current version of Ilios (2.4.8), there is a button to Publish All -- this is at the Course Level and it publishes all sessions and the course itself. There should also be a way to Publish All (as is) at this level.  This would present the user with the list of all the things that are missing from both the Course and the Sessions and assuming the user has reviewed this information allow for the Course and Sessions to be published as is.  The user should also have the ability to choose which to Publish as-is and which to leave as-is in Not Published mode.

In the 2.4.x, this is a button.  Maybe in the new version, it could be included in the drop-down menu at the course level.  Either way, we should scope this out and provide this functionality.

**Comment by jrjohnson** [comment]
@saschaben do we have a mock for this?  Where should this button go?

**Comment by jrjohnson** [comment]
@saschaben are users going to want to be able to use this publish all option to schedule all at any point.  Would that include all of the already published sessions?  That isn't supported in our current design.

**Comment by saschaben** [comment]
I don't see that as an issue --- the only reason to schedule all is if "all" are missing items -- in which case they would be listed and selectable. setting everything to scheduled as a bulk override is not a use case we will support at this point.
