### ISSUE TITLE
Calendar Navigation Issue on iPad or Smaller Device

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#801]
See the screen shot for details ...

![ipadnav](https://cloud.githubusercontent.com/assets/7493331/9043308/5dd84eaa-39c9-11e5-8dc6-13299b6927b4.jpg)

**Comment by saschaben** [comment]
This will require a small modification to CSS `#site-container` value for `padding-left` from the current 40px to a minimum of 48px. This should suffice for effective usability on mobile devices without a major disruption of the layout.
