### ISSUE TITLE
ILM Instructional Hours does not allow for fractional time

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#815]
The instructional hours field currently will only accept whole numbers. Fractions of hours are rounded down.

The Instructional Hours value should allow hours to be entered in whole numbers as well as fractions thereof, allowing for two decimals (2.25, 3.5, 4.75, 0.25). Fractions entered as 3 or more decimals should be round up to the nearest 2-decimal fraction.

**Comment by jrjohnson** [comment]
Moved to API.
