### ISSUE TITLE
Ghost Image of Suggested (Auto-Generated) Course ID missing in new Ilios version

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#816]
I noticed that there is a ghosted out External (Course) ID in version 2.4.x of Ilios. This occurs after adding a new course or pulling up an existing one where a Course ID was not specified. Do we want Ilios 3.x to have this display or just put something into the database without notifying the user ... or pass a NULL or empty string to that field if the user does not specify a Course ID?  

The link below is to the image I originally uploaded to the ilios/ilios issue which shows how it appears in 2.4.x.

https://cloud.githubusercontent.com/assets/7493331/6648728/87d0e630-c99a-11e4-8ebc-c426ce5db44e.jpg

**Comment by saschaben** [comment]
fixed in #1519
