### ISSUE TITLE
All Events / My Schedule Not Sticky

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#828]
I noticed that when you load up the Dashboard Calendar with All Events (using the provided toggle) and then ...

* Navigate away from the Dashboard
* Return to the Dashboard 

... that the toggle has returned to My Schedule (from All Events).  This is not a huge deal obviously but if these are sticky sessions, the toggle should remain in the position it was before navigating away, non?

**Comment by jrjohnson** [comment]
This is now fixed
