### ISSUE TITLE
Topics Are Not Loading Up (Calendar Filter / Courses and Sessions)

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#837]
I first noticed this when I was filtering on the calendar and instead of showing the list of Topics, only the word "topics" is displayed.

![notopics](https://cloud.githubusercontent.com/assets/7493331/10008409/2aa19ef2-6083-11e5-9749-f2adda9a5c0e.JPG)

Also on Courses and Sessions, it is missing.  API endpoint or something missing? - Disciplines vs Topics change?  Anyway, here's the shot from Courses and Sessions ...

![managetopics](https://cloud.githubusercontent.com/assets/7493331/10008484/e91e7a30-6083-11e5-858c-5b0a5ad10367.JPG)

**Comment by saschaben** [comment]
this has been addressed
