### ISSUE TITLE
allow for modfication of academic year in CI draft reports

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#843]
the way it is now: Academic Year is entered on creation of a report as a 4-digit free entry value. Once saved it is non-editable.

The way it should be: Either provide a select list for Academic year which mirrors the representation in other areas (eg "2014-15") OR provide the ability to modify the year value for the report up to the point where 1 or more courses have been selected and associated with a sequence block.

This will provide a much better user experience, and will reduce the potential for error (building a report frame, and then realizing it is set to the wrong year (2015 instead of 2014 for instance, for the 2014-15 report), and having to delete and rebuild, which is onerous.

**Comment by saschaben** [comment]
cf 519

**Comment by stopfstedt** [comment]
has been addressed.
