### ISSUE TITLE
Breadcrumb Navigation Back to Previous Location(s) Needed

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#844]
I noticed this primarily in Learner Groups.

This would make a good navigation pattern for other places if possible.

Click a Group name (Anatomy Lab)

![part1lg](https://cloud.githubusercontent.com/assets/7493331/10235191/2d4f431a-684f-11e5-9c80-1354bb845efe.JPG)

goes to ...

![part2lg](https://cloud.githubusercontent.com/assets/7493331/10235193/312b36ce-684f-11e5-9d55-068fe314b2f4.JPG)

Click the name of a Sub-group (Anatomy Lab 1)

![part3lg](https://cloud.githubusercontent.com/assets/7493331/10235195/348488f2-684f-11e5-87b5-955ec17246de.JPG)

goes to ...

![part4lg](https://cloud.githubusercontent.com/assets/7493331/10235197/38353848-684f-11e5-9e70-3d37a6db645f.JPG)

**Comment by jrjohnson** [comment]
Will be addressed in #1506
