### ISSUE TITLE
Rearrange Toggle Buttons on Dashboard

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#852]
The buttons on the Dashboard need to be displayed in the following order ...

`Schedule` | `Filter` | If filter on, 'Topic / Detail' or 'Course / Type'

Ugly mock below ...
My Schedule / All Events ---------------- Show Filter On / Off --------------- Course/Type or Topic/Detail

![combo](https://cloud.githubusercontent.com/assets/7493331/10296011/a318f320-6b79-11e5-895a-6c9f64a7e220.JPG)

**Comment by saschaben** [comment]
must be ready for friday 23rd demo training.

**Comment by djvoa12** [comment]
[View PR](https://github.com/ilios/frontend/pull/908)
