### ISSUE TITLE
Change Course/Type toggle to Course/Session Type

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#853]
![sessiontypetoggle](https://cloud.githubusercontent.com/assets/7493331/10296398/0dc52966-6b7d-11e5-9104-faf8f03d60e5.JPG)

Obviously the toggle itself may need to be resized / restyled in order to allow the full text of "Course/Session Type" to be displayed.

**Comment by dartajax** [comment]
This can be closed I believe since we have changed to buttons and will be revamping this in the future when we can.

**Comment by saschaben** [comment]
replaced by #3099
