### ISSUE TITLE
Add a "Clear" Option for Each Filter Column

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#856]
This is the same screenshot as the previous Issue I just entered.  When I was doing the mock, I added the concept of needing to be able to clear any selected filter.  You can see the rough mock of it int the right corner of this screen shot.
![sesstypefilter2](https://cloud.githubusercontent.com/assets/7493331/10296910/11d44c30-6b82-11e5-93b0-1f3b0deed480.jpg)

**Comment by saschaben** [comment]
This is currently addressed with the global "clear options available for filters.

**Comment by jrjohnson** [comment]
Fixed in #940
