### ISSUE TITLE
Create inline-label-data-block style in css and give it style of 

### ISSUE THREAD

**Issue by thecoolestguy** [ilios/frontend#86]
I've created several divs with a class of 'inline-label-data-block' in #50, #85.  This class needs to be assigned a style of 'display: inline-block'

**Comment by jenzweben** [comment]
should I put this style in _global.scss?  also, which page is a good one to reference where the class will be applied?

**Comment by jrjohnson** [comment]
@jenzweben I think they should go in detailview for now.  Then we can move them depending on how we end up organizing learner group detail which is the other place they might apply.

**Comment by jenzweben** [comment]
Jason & I are cool with it being in _global.scss

**Comment by jrjohnson** [comment]
Fixed #105
