### ISSUE TITLE
Front End Validation Error On Removing Course Director

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#861]
code: 400
errors: {errors: ["This form should not contain extra fields."],…}
message: "Validation Failed"

{"code":400,"message":"Validation Failed","errors":{"errors":["This form should not contain extra fields."],"children":{"lastName":[],"firstName":[],"middleName":[],"phone":[],"email":[],"addedViaIlios":[],"enabled":[],"campusId":[],"icsFeedKey":{"errors":["This value should not be blank."]},"otherId":[],"examined":[],"userSyncIgnore":[],"reminders":[],"learningMaterials":[],"publishEvents":[],"reports":[],"school":[],"directedCourses":[],"learnerGroups":[],"instructorUserGroups":[],"instructorGroups":[],"instructorIlmSessions":[],"learnerIlmSessions":[],"offerings":[],"instructedOfferings":[],"programYears":[],"alerts":[],"roles":[],"primaryCohort":[],"cohorts":[],"pendingUserUpdates":[]}}}

I picked this up in Inspect Element >> Network tab.  It occurs when a Course Director is removed.

**Comment by jrjohnson** [comment]
This was probably fixes in #857 can you pull a new master and test again?

**Comment by dartajax** [comment]
I will do that.  Thanks.

**Comment by dartajax** [comment]
Now I got this ...

code: 403
message: "Forbidden"

**Comment by dartajax** [comment]
Also of note, when I remove a director from a course (receiving the 403 above), all of the sessions get removed from the course.

**Comment by dartajax** [comment]
This may be related and / or duplicate of #864

**Comment by dartajax** [comment]
This seems to no longer be happening on demo3 - I am going to close this issue.
