### ISSUE TITLE
Manage Cohort (on Course) Issue - All Session Offerings Disappear - No Output Errors Found

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#864]
Try this with Inspect Element on ...

* Pull up a Course and expand the details ....

http://localhost:4200/courses/748?details=true

See that there are 65 Sessions for this Course

![review1](https://cloud.githubusercontent.com/assets/7493331/10353658/7031d2d4-6d0d-11e5-9e75-4226834a1e5f.JPG)

* Click the Manage Cohorts button

There is no need to change anything.  

* Click the Green confirmation button.

See that the 65 Sessions for this Course are now missing.

![review2](https://cloud.githubusercontent.com/assets/7493331/10353693/c96b6126-6d0d-11e5-877e-0423c6b95691.JPG)

From the Console tab, 

Deprecations were detected, see the Ember Inspector deprecations tab for more details.

VM156:100 -- 

Clicking on the link above gets this ...

in ember.debug.js ...

`  _emberMetalCore["default"].warn = function (message, test) {
    if (!test) {
      _emberMetalLogger["default"].warn("WARNING: " + message);
      if ('trace' in _emberMetalLogger["default"]) {
        _emberMetalLogger["default"].trace();
      }
    }
  };`

From the ember tab ...

`2 Depending on arrays using a dependent key ending with `@each` is deprecated. Please refactor from Ember.computed('cohorts.@each', function() {});` to `Ember.computed('cohorts.[]', function() {}).`

`
1 The default behavior of shouldReloadAll will change in Ember Data 2.0 to always return false when there is at least one "program" record in the store. If you would like to preserve the current behavior please override shouldReloadAll in your adapter:application and return true.`

@jrjohnson , is this helpful?

**Comment by dartajax** [comment]
A similar thing is happening when Topics are maintained.

**Comment by jrjohnson** [comment]
Will be fixed in https://github.com/ilios/ilios/pull/1061
