### ISSUE TITLE
further styling for small groups generator

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#866]
1. we need some spacing between the buttons and the border:
![addpaddingbottom](https://cloud.githubusercontent.com/assets/1753431/10406777/d09e2484-6e97-11e5-86ca-723f80f274ef.png)

2. monkey buttons should be styled to match Ilios Blue button color when on.
![monkeybuttonstyling](https://cloud.githubusercontent.com/assets/1753431/10406793/fdd9f1ee-6e97-11e5-9a04-ac0734000f1e.png)

3. the search/form entry for onstructor should either get increased in size so that it is centered, or moved to be center aligned over the buttons:
![center-orincreaseformfieldsize](https://cloud.githubusercontent.com/assets/1753431/10406814/1b9a591c-6e98-11e5-8e2a-86d18cb1709a.png)

**Comment by saschaben** [comment]
refs. #1311

**Comment by jrjohnson** [comment]
Will resolve remaining issues in #2213
