### ISSUE TITLE
MeSH Terms Need Styling -- Like Topics

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#867]
Notice in the screenshot below how topics are arranged in columns whereas MeSH terms are not.

![meshvstopics](https://cloud.githubusercontent.com/assets/7493331/10407346/80191c60-6e9e-11e5-8b8f-084619698395.JPG)

Actually, they both should be styled better ... more like badges without the "x"'s with a background color that sets them apart from the form background.  We can deal with that later though.

**Comment by saschaben** [comment]
this can be addressed in a general review of badge styling after launch
