### ISSUE TITLE
Add values of session type and publication status to search box for sessions list

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#87]
It seems like we should provide some of the same kinds of filters at the top of the session list that we provide at the top of the course list.  I'm thinking:
* Publication Status
* Session Type
* Has Offerings / No Offerings
* ILM

Thoughts?

**Comment by saschaben** [comment]
Much of this could be mooted by having:
a) sortable column headers, and 
b) adding the values of _publication status_ and _session type_ to the basic search box.
ILM filtering is harder: should get punted to 3.1
