### ISSUE TITLE
provide event detail for ILM

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#883]
ILMs are not currently getting processed correctly for event detail display. We need to add this.

ILMs have the following changes in display:

1: "On [Date value], [time value]" changes to "Due by [Date value], [[time value]]"
> > "Due by October 31, 2015, 5:00pm"
2: Session type displays the same as now, but should be appended with a tag of "__(ILM)__" 
> > This session is "Self-Directed Learning __(ILM)__"
3: The instructor list will typically be empty on ILMs

**Comment by djvoa12** [comment]
- [ ] Calendar event-popover ([PR](https://github.com/ilios/calendar/pull/4))
- [ ] Events page fix
