### ISSUE TITLE
Objective MeSH Terms Don't Save

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#885]
This is related to #484 as well since we need to provide context for adding MeSH terms to objectives. Currently, you can't tell which objective is the one having the objective attached to it.  This example is from a Course Objective - similar situation occurs with Session Objective.

Click "Add New"

![meshbg1](https://cloud.githubusercontent.com/assets/7493331/10470754/650adf52-71c4-11e5-96f4-352ac98482b6.JPG)

The Objective is missing.

![meshbg2](https://cloud.githubusercontent.com/assets/7493331/10470775/8341c24c-71c4-11e5-8cd0-d4888490d395.JPG)

Add two MeSH terms - the search works fine - and click the green confirmation check button to "Save".

![meshbg3](https://cloud.githubusercontent.com/assets/7493331/10470781/89008722-71c4-11e5-803c-6a3919fd5bf9.JPG)

Nothing happens .... in Console the 400 error.

![meshbg4](https://cloud.githubusercontent.com/assets/7493331/10470785/8e1d58a2-71c4-11e5-88a7-07eb8c7308a3.JPG)

**Comment by stopfstedt** [comment]
mesh terms are saving now, this got fixed a week or two ago. see #869.

working on providing more context in picker title "search mesh descriptors for objective X"

**Comment by stopfstedt** [comment]
![selection_020](https://cloud.githubusercontent.com/assets/1410427/10798388/90c5d38a-7d64-11e5-8289-a5505000b189.png)

@dartajax is this better?

**Comment by dartajax** [comment]
That looks great.  So will it be like "Select MeSH Descriptors for Objective "Use your brain as much as possible""?

**Comment by stopfstedt** [comment]
doable, but i'd be concerned about long objective descriptions (containing markup!) polluting the UI. 

![selection_021](https://cloud.githubusercontent.com/assets/1410427/10798959/720672b2-7d67-11e5-92cd-0e709db66cb8.png)

"for Objective" should provide enough context, no?

**Comment by stopfstedt** [comment]
issuing PR on this, sans objective title display.
