### ISSUE TITLE
Course Objective Not Saved Unless Course Header Data is Updated

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#886]
Note:  If you save something (External ID or whatever) and then run through the steps below, you will be able to process the Save event correctly. 

Pull up a Course >> Review the Objective count (23)

![objnosv1](https://cloud.githubusercontent.com/assets/7493331/10471681/35504b04-71cd-11e5-800d-96784bbc8368.JPG)

Click Add New (at the Objective level) to add a new objective as shown below.

![objnosv2](https://cloud.githubusercontent.com/assets/7493331/10471687/3a4ca472-71cd-11e5-89a7-e627748502b6.JPG)

Click Done to call up the save event on the Course Objective.

![objnosv3](https://cloud.githubusercontent.com/assets/7493331/10471688/3ec84e98-71cd-11e5-8f74-954e3af6cbf7.JPG)

Above you can see that now there are 24 Objectives.

Below you can see the objective down at the bottom of the list where it is supposed to be.

![objnosv4](https://cloud.githubusercontent.com/assets/7493331/10471689/453611de-71cd-11e5-9e30-e21866c406cf.JPG)

Refresh the page (F5) -- oops only 23 Objectives appear -- the 24th Objective did not get saved. 

![objnosv5](https://cloud.githubusercontent.com/assets/7493331/10471699/4ad29d06-71cd-11e5-9b46-54c0492d863f.JPG)

**Comment by jrjohnson** [comment]
This is an API issue, I will move it to that side.
