### ISSUE TITLE
Style Text on Courses & Learner Groups Page

### ISSUE THREAD

**Issue by jenzweben** [ilios/frontend#89]
Currently each line item on Course List & Learner Groups pages are #333 - please make them appear as links (#ilios-blue)

**Comment by jrjohnson** [comment]
@jenzweben all text in the line?  Or just the title?

**Comment by jrjohnson** [comment]
![screen shot 2015-02-11 at 1 36 13 pm](https://cloud.githubusercontent.com/assets/349624/6156995/f9bb6776-b1f2-11e4-8642-76ea2bdb2759.png)

**Comment by jrjohnson** [comment]
![screen shot 2015-02-11 at 1 38 00 pm](https://cloud.githubusercontent.com/assets/349624/6157025/4534c8e6-b1f3-11e4-8e57-ebcdb0195183.png)
![screen shot 2015-02-11 at 1 38 20 pm](https://cloud.githubusercontent.com/assets/349624/6157027/4826f9b6-b1f3-11e4-876c-593e7d5d7419.png)

**Comment by jenzweben** [comment]
I think just course title in link blue but the whole row should have hover bg
