### ISSUE TITLE
Unidentified Colored Squares Appear on Calendar

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#892]
This is most easily seen when "All Events" is selected.  I will put a screen shot down below for reference.

The "Mystery Squares" TM are not clickable and there are no mouse-over tool tips with Session offering information because the squares are not associated with any offering I am assuming.  I indicated a bunch of examples of the squares by pointing an arrow at them.

![mysterysquares](https://cloud.githubusercontent.com/assets/7493331/10493763/bd450ef6-7267-11e5-8ff4-6221c42e30bb.JPG)

**Comment by saschaben** [comment]
closing. please see #1066
