### ISSUE TITLE
Small Group Generator Fail

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#901]
https://ilios3-demo.ucsf.edu/courses/773/sessions/22154

Using Prologue >> 15-16 ...

![generator1](https://cloud.githubusercontent.com/assets/7493331/10554399/1c01f2d6-7418-11e5-9803-104605467a0a.JPG)

![generator2](https://cloud.githubusercontent.com/assets/7493331/10554400/21d9f780-7418-11e5-8375-cbac0fd69c7f.JPG)

**Comment by dartajax** [comment]
400's up the wazoo.

**Comment by jrjohnson** [comment]
This is caused by three things:
- We're sending a publishEvent here, but the offering API does not accept it
- We're sending updatedAt which is not allowed
- A blank room is being sent which we do not currently allow
