### ISSUE TITLE
Froala Configuration Issue - The Box is Too Short Initially - Can It Be Made Taller?

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#903]
I understand that we are going to license the product so the red unlicensed badge will disappear; but it still seems that a taller box might be easier to use for data entry - maybe twice as tall as shown in the lower screenshot.

![taller1](https://cloud.githubusercontent.com/assets/7493331/10554577/83d6bdd2-7419-11e5-80a0-3626dd03d0f7.JPG)

How it is ...

![taller2](https://cloud.githubusercontent.com/assets/7493331/10554580/883690dc-7419-11e5-9116-ce9a7b178cbf.JPG)

How it could / should be ...

![taller3](https://cloud.githubusercontent.com/assets/7493331/10554583/8c213f30-7419-11e5-92b9-4d5c1abf62a8.JPG)

**Comment by saschaben** [comment]
The box auto expands as content is put in --- this means that the box is never taking up more space than it needs to on the screen, and also that it always shows the full content that is being typed in. 

closing
