### ISSUE TITLE
Use css grids instead of bourbon neat for layout

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#911]
CSS grids looks like a better overall choice and browser support is landing now and will be mainstream in early 2016.  It looks like the polyfill library is working and will provide support for un-updated browsers and IE 11, but we will want to test with devices we intend to support.
https://github.com/FremyCompany/css-grid-polyfill

For developers this will improve our overall layout quality, the readability and future reliability of our css.
For users we can probably do this fix with no visual change, however it will make it much easier to create a source order that can be easily parsed for screen readers and to create a mobile design usable on smaller devices.

**Comment by thecoolestguy** [comment]
More useful links!

http://gridbyexample.com/
https://drafts.csswg.org/css-grid/
http://igalia.github.io/css-grid-layout/
https://github.com/FremyCompany/css-grid-polyfill

**Comment by saschaben** [comment]
is this still an issue? If not, please close, thx.

**Comment by jrjohnson** [comment]
Yes, but it is probably going to be 12 months before we can use them, I will close for now.
