### ISSUE TITLE
inplace-date component's data interaction need to be fixed

### ISSUE THREAD

**Issue by djvoa12** [ilios/frontend#915]
This bug is applicable for all areas where `inplace-date` component is being used to change a date (via date-picker). If a user chooses `11/2/2015`, the app sends the newly chosen date to the backend as `11/02/2015 midnight PST`. Afterwards, when the user refreshes the page, the date reads `11/1/2015` (`11/01/2015 17:00:00`). This occurs because there is a timezone conflict between frontend/backend. 

This could either be solved from the client-side, or the server-side could make some adjustments.

<img width="906" alt="screen shot 2015-10-21 at 4 14 09 pm" src="https://cloud.githubusercontent.com/assets/7553764/10653018/30843ae2-7810-11e5-8a05-cd225b7f6825.png">

**Comment by saschaben** [comment]
Is this still an issue? if not, please close, thanks.

**Comment by jrjohnson** [comment]
Will resolve in #2212
