### ISSUE TITLE
inplace-select component's backend interaction need to be fixed

### ISSUE THREAD

**Issue by djvoa12** [ilios/frontend#916]
In `session-overview`, a user can change the session type via `inplace-select` component. After submitting the change, if the user refreshes the page, the change is not reflected most of the time.

`PUT` request is sent from the client-side, but the issue may be residing in the server.

Note: Session type may not be the only area that is affected by this issue.

<img width="764" alt="screen shot 2015-10-21 at 4 32 12 pm" src="https://cloud.githubusercontent.com/assets/7553764/10653126/5ed53b52-7811-11e5-9a47-d9ce50e2f35e.png">

<img width="560" alt="screen shot 2015-10-21 at 4 32 54 pm" src="https://cloud.githubusercontent.com/assets/7553764/10653130/686cbd3e-7811-11e5-98b6-b9d25ecee30c.png">

**Comment by saschaben** [comment]
Is this still an issue? if not, please close, thanks.

**Comment by jrjohnson** [comment]
Unable to reproduce.
