### ISSUE TITLE
Publish Session Doesn't Work on Demo

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#917]
This is related loosely to #724.

![sessionpub1](https://cloud.githubusercontent.com/assets/7493331/10653271/b9d81c6c-7812-11e5-887e-1eda06d931fd.JPG)

![sessionpub2](https://cloud.githubusercontent.com/assets/7493331/10653275/bf959be8-7812-11e5-88f5-2e0412abd765.JPG)

![sessionpub3](https://cloud.githubusercontent.com/assets/7493331/10653276/c3ecbe6a-7812-11e5-9c99-9de28197240c.JPG)

Nothing happens when Publish Session is selected.

**Comment by dartajax** [comment]
Here is another look at Session publishing that doesn't work but it looks like the Count of missing items has been fixed (I think this was a while ago actually).

![asis1](https://cloud.githubusercontent.com/assets/7493331/10653382/f7391858-7813-11e5-8eaf-408336e723f4.JPG)

Clicking "Publish As-Is" does not publish the Session.  It doesn't seem to do anything.

**Comment by jrjohnson** [comment]
This was fixed in #888
