### ISSUE TITLE
Instructor group needs loading indicator and better list

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#932]
Attempting to work with a large group like the BMB Instructors in SOM is a mess.  We need to go to the columnar display here and also provide a loading indicator.

**Comment by stopfstedt** [comment]
at first...

![screenshot from 2016-01-14 11 34 09](https://cloud.githubusercontent.com/assets/1410427/12335330/77f6dcdc-bab3-11e5-8a77-3de7978fb893.png)

... but then ..

![screenshot from 2016-01-14 11 34 11](https://cloud.githubusercontent.com/assets/1410427/12335332/7ccb0d64-bab3-11e5-8eb3-50734bfc7494.png)

..  and finally

![screenshot from 2016-01-14 11 34 14](https://cloud.githubusercontent.com/assets/1410427/12335336/802744be-bab3-11e5-8b2f-3a1e19b33c72.png)

**Comment by stopfstedt** [comment]
suggested placement of loading indicator here.

![f](https://cloud.githubusercontent.com/assets/1410427/12335357/b5e09a24-bab3-11e5-9094-b513449ddd2f.png)

**Comment by stopfstedt** [comment]
CSS: use `columnar-list` class on the instructor list element instead.

see `app/templates/components/detail-instructors-list.hbs` for an example.

**Comment by jrjohnson** [comment]
Fixed in #2361
