### ISSUE TITLE
Loading the number of instructors in each group is a time killer

### ISSUE THREAD

**Issue by jrjohnson** [ilios/frontend#933]
Currently on the instructors list we indicate how many users are in each group.  This requires loading all of those user accounts which takes a while.

@saschaben Do we need this count for this list?  I'm assuming yes.  If so we should add a userCount to the API endpoint for instructorgroups that calculates this against the DB which should be much faster.

**Comment by saschaben** [comment]
@jrjohnson that makes sense. I can't say definitively whether we need the count without feedback from the users, but my gut sense says we do indeed need the count on the linstructor group list.

I would think that a userCount on the API endpoint for instructorGroup (and for learnerGroup for that matter) would be a significant benefit for the system.
