### ISSUE TITLE
Small Group Generator Sets Time of Sessions to 12:00AM - 12:00AM on Frontend

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#938]
Pick a session ...

![newbug1](https://cloud.githubusercontent.com/assets/7493331/10739222/74fc14c6-7bd8-11e5-8356-5e71aeb7f686.JPG)

Add offering ...

![newbug2](https://cloud.githubusercontent.com/assets/7493331/10739227/78f027ac-7bd8-11e5-9e61-df45283be507.JPG)

Select Small Groups ...

![newbug3](https://cloud.githubusercontent.com/assets/7493331/10739230/7c8a4b90-7bd8-11e5-9156-b4c010d8efe3.JPG)

Pick Group (ACM)

![newbug4](https://cloud.githubusercontent.com/assets/7493331/10739240/80f8e204-7bd8-11e5-930c-60679e67373b.JPG)
 Create offerings ...

![newbug5](https://cloud.githubusercontent.com/assets/7493331/10739243/87d2a04c-7bd8-11e5-8221-ab33a293bb55.JPG)

Click to edit one of them ... the start end times look fine ... save and close ..

![newbug6](https://cloud.githubusercontent.com/assets/7493331/10739244/8c21b4ee-7bd8-11e5-8fa1-99a04997fa20.JPG)

Now pick a different one to edit -- 12:00AM - 12:00AM issue.

![newbug7](https://cloud.githubusercontent.com/assets/7493331/10739250/8f38b20e-7bd8-11e5-9b12-97e95fa0cf58.JPG)

**Comment by saschaben** [comment]
see also #1034
