### ISSUE TITLE
show more of  MeSH scope notes in picker.

### ISSUE THREAD

**Issue by stopfstedt** [ilios/frontend#939]
based on https://github.com/ilios/frontend/pull/919#issuecomment-150483407:

truncate scope notes in the MeSH picker at the 250 char limit.

**Comment by stopfstedt** [comment]
this will require a modest amount of coding in order to replace the pure CSS solution that's in place currently.

**Comment by saschaben** [comment]
Works for me. Let's deal with this enhancement after the 7th.
