### ISSUE TITLE
Calendar Day View cuts off at 4pm

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#941]
This disallows the view of any activity 5pm or on. Need to add a vertical scroll just as with week view. or make overflow visible. or somethin'.

**Comment by saschaben** [comment]
On second glance....this may be due to needing #839 to get addressed.

**Comment by jrjohnson** [comment]
I think this is probably a bug in the day view CSS since the week seems to work.

**Comment by jrjohnson** [comment]
Fixed by https://github.com/ilios/calendar/pull/7 we will need to release a new version and then update our dependancy.
