### ISSUE TITLE
Froala Text Fields Don't Line Up Very Well After Save (Alignment Issue?)

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#945]
See the screen shots below ...

This is in Learning Materials.

![notes1](https://cloud.githubusercontent.com/assets/7493331/10745964/5d5263d6-7c03-11e5-8bc0-0b4af92b86fc.JPG)

Save the LM.

Retrieve the LM.

Review the alignment.

![notes2](https://cloud.githubusercontent.com/assets/7493331/10745977/8ec4b5a4-7c03-11e5-8cfe-94e9379b8572.JPG)

The same is true with Instructional Notes (another Froala field). See below ...

![notes3](https://cloud.githubusercontent.com/assets/7493331/10746010/e449b434-7c03-11e5-9748-3a86d020e84a.JPG)

Save the record and review the alignment misery.

![notes4](https://cloud.githubusercontent.com/assets/7493331/10746012/ea7588ba-7c03-11e5-923c-030ec2d29252.JPG)

**Comment by jrjohnson** [comment]
Froala is wrapping saved content in a <p> tag which we are not accounting for in out layout.  We probably need to remove top margin from <p> tags in our HTML allowed sections.
