### ISSUE TITLE
course mangager: only include course directors in "course director" search

### ISSUE THREAD

**Issue by stopfstedt** [ilios/frontend#953]
currently, all active users are queried in search, regardless of their role. restrict that.

refs ilios/ilios#1070

**Comment by jrjohnson** [comment]
I'm not sure about this.  Shouldn't it be possible to make anyone a course director?  Maybe what we need to do is add a course director role to anyone selected here.

**Comment by stopfstedt** [comment]
i'd prefer to keep course and user management separated. doing it the way suggested would break the the limitations of course director capabilities - now they are assigning user roles (implicitly) which is the domain of the developer role. but ultimately, that's @saschaben call.

**Comment by stopfstedt** [comment]
this issue got already addressed and resolved via #959.

**Comment by saschaben** [comment]
for the record, I agree here with @stopfstedt: while it would be simple to just assign the role to anyone picked in this context, that isn't the real value use case. We want to be able to scope the role on the users, and provide only those scoped users for selection, keeping user management and course management distinct.
