### ISSUE TITLE
Add idiot checks for COURSE delete actions

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#96]
when deleting a course, a session, or a group: need a "are you sure you wanna do this?" message.

**Comment by jrjohnson** [comment]
@jenzweben please sit with @saschaben and discuss how we want to warn people about this kind of thing.

**Comment by jenzweben** [comment]
![delete-course-confirmation](https://cloud.githubusercontent.com/assets/5023894/6240357/48f634e6-b6c2-11e4-869f-0ca824f695e7.png)

**Comment by jenzweben** [comment]
@saschaben this is what I was thinking - the alert would expand down...

**Comment by saschaben** [comment]
Love it. Let's do it.

**Comment by jrjohnson** [comment]
OMG this is my favorite thing ever!  I'm so happy its not a dialog and it looks GREAT! 

Think about expanding the info to say something like:
There are 116 Sessions with 252 offerings and 1034 assigned students.  Are you SURE you want to delete this course?  It doesn't have to happen, I'm just saying we have access to all those numbers so if we want a more informative warning that might highlight critical info thats completely doable.

Also, fyi, this mock seems to be for deleting a group, but it is against the course list background.

**Comment by saschaben** [comment]
We will need to customize the error messages, for session  course and group. We can discuss.

**Comment by saschaben** [comment]
MESSAGES:

For GROUPS: "Are you sure you want to delete this group, currently attached to _n_ offerings? This action cannot be undone."

For COURSES: "Are you sure you want to delete this course, with _n_ published offerings? This action will remove all sessions and offerings for this course, and cannot be undone."

For SESSIONS: "Are you sure you want to delete this session? This action will remove the session and all its offerings, and cannot be undone."

For OFFERINGS: "Are you sure you want to delete this offering? This action cannot be undone."

For PROGRAM YEAR: "Are you sure you want to delete this Program Year? Doing so will remove the student cohort for this matriculation year, and disassociate all courses from that cohort and its groups. This action cannot be undone."

**Comment by jrjohnson** [comment]
I understand why we have all the 'cannot be undone' language, but since we're not actually deleting anything it really CAN be undone.

**Comment by dartajax** [comment]
We want the user to believe that it cannot be undone so that when we need to undo something, it is a special occasion - not an everyday event.  That's what I believe anyway.

**Comment by saschaben** [comment]
"This cannot be undone" is way better than "we could undo this for you, but it would be a massive PITA and earn you our undying disdain." For a user perspective, anyway. 

It's also much easier to fit onscreen.

**Comment by jrjohnson** [comment]
@saschaben please open separate tickets for each idiot check and close this one.

**Comment by saschaben** [comment]
Modified to specify course; reference on PR to close.
