### ISSUE TITLE
Demo Faculty(x)'s Calendar Not Showing Events Where He/She is an Instructor

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#961]
Events for which Demo Faculty2 (the logged in user) is an Instructor are not showing up in Demo Faculty2's Calendar.  This is on the Dashboard with the Calendar turned off.

I added Demo Faculty2 to be the Instructor on several session offerings but the offerings don't end up appearing on the Dashboard.

![onecourseonly](https://cloud.githubusercontent.com/assets/7493331/10775889/ad8fd416-7cc9-11e5-97cd-6d1c2ac2d6cc.JPG)

Here is a screenshot of Demo Faculty2 as the Instructor of a Session which should be showing up on the Dashboard.

https://ilios3-demo.ucsf.edu/courses/791/sessions/23116

![onecourseonly2](https://cloud.githubusercontent.com/assets/7493331/10775945/3fdc30da-7cca-11e5-8e2e-75853e67f4c7.JPG)

Should not this offering also show up on Demo Faculty2's Calendar on the Dashboard?

**Comment by saschaben** [comment]
@dartajax test this with a non-ILM session and see if you encounter anything similar. I suspect this is due to not handling ILMs effectively, not a more global bug. I hope.

**Comment by saschaben** [comment]
must be published. must be within two weeks.
