### ISSUE TITLE
Delete Button (Trash) Is Too Close To Edit Button on Session Offerings / Events

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#969]
We need to move the Trash icon further away from the Edit button so the user will have an easier time not accidentally click the Trash icon when they want to edit a Session Offering / Event.

See the screen shot below ...

![tooclose](https://cloud.githubusercontent.com/assets/7493331/10828280/c2f6ff92-7e30-11e5-8c4c-6b9b1fe5eb57.JPG)

**Comment by saschaben** [comment]
being addressed by #973
