### ISSUE TITLE
space between `edit` and `remove` should be greater

### ISSUE THREAD

**Issue by djvoa12** [ilios/frontend#973]
Set the `delete` icon's `left-margin` to 5px across the whole app.

<img width="119" alt="screen shot 2015-10-30 at 12 58 43 pm" src="https://cloud.githubusercontent.com/assets/7553764/10857377/fcbbd60a-7f0a-11e5-9455-6fa0b8bd52a3.png">

**Comment by saschaben** [comment]
if the grid allows, we might even want to go 7px
