### ISSUE TITLE
ILM Toggle Fails When Being Switched Off

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#974]
On the netlify version, the toggle just stays in the On position and doesn't turn off.

On demo, I am getting a 500 error.

![toggleerror](https://cloud.githubusercontent.com/assets/7493331/10857990/c99ba652-7f0e-11e5-842f-28f40120fcdb.JPG)

to reproduce ...

* pull up a session
* change the Independent Learning to the Yes position
* realize that you have indeed screwed up and attempt to change it back to the Off position

Either nothing happens (netlify) or you get a cool error (500) on demo.

**Comment by saschaben** [comment]
This issue has been corrected elsewhere.
