### ISSUE TITLE
Calendar Feed Functionality Needed on The Dashboard

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#977]
We need to provide the functionality contained in Ilios 2.4.x for the students to be able to generate and download the URL that they can paste into the mobile devices to set up their calendar feed.

For reference, here is how it looks in 2.4.8 ...

![feed](https://cloud.githubusercontent.com/assets/7493331/10860523/ac02e598-7f26-11e5-809b-6a5eadbdda37.JPG)

I will check the mocks for this as well to see if it has been scoped out for 3.0.

**Comment by jrjohnson** [comment]
Fixed by https://github.com/ilios/calendar/pull/6 we will need to release a new version and then update our dependancy.
