### ISSUE TITLE
Make Column headers in course and session lists sortable

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#98]
For Session, should allow sort by: 
Title	| Type | First Offering  | Status	

For Course, should allow sort by:
Course | School | Level | Start Date | End Date | Status

**Comment by dartajax** [comment]
Also, please ensure the headers still appear when the user scrolls down.

**Comment by jrjohnson** [comment]
Sorting should be 'sticky' during a current session.

**Comment by saschaben** [comment]
refs. #1261, #1262
