### ISSUE TITLE
Fixed Table Headers on Courses and Sessions List

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#99]
If a user has a large result set and scrolls down the screen, the headers will disappear.  Please ensure the headers can remain -- usability issue and request from Valentina.  Also, a great idea.

**Comment by jrjohnson** [comment]
@jenzweben please do no more than 15 minutes of research into fixed table headers.  Hopefully CSS only solution.

**Comment by jenzweben** [comment]
Here are a bunch of examples: http://salzerdesign.com/test/fixedTable.html  not all of them work but...

Here's a codepen example:  http://codepen.io/tjvantoll/pen/JEKIu
