### ISSUE TITLE
Permissions for Instructor Group Create

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#993]
Only users with Developer permissions should be able to create Instructor groups

**Comment by jrjohnson** [comment]
@saschaben should we hide the entire instructor groups menu and all of the info therein? Or just modify the display of the instructor group screen to not allow addition / modification of groups?

**Comment by saschaben** [comment]
unfortunately, we will need to go with option #2, since a non-developer will otherwise have no visibility into the membership of a group. So restriction needs to be at the page-control level, not at the menu level.

**Comment by dartajax** [comment]
Superseded by Permissions Matrix
